# LJ Dev Commerce - Phase 4

# VI. Product ETL

# =========================================================
# SECTION 1 — EXTRACT, SET UP, PROFILE, FINDINGS & DECISIONS
# =========================================================

# 1.1 Setup

This section prepares the notebook environment for the Product ETL process.

The setup includes:

- Importing the required Python libraries.
- Configuring Pandas display options.
- Preparing the notebook environment for the Product ETL workflow.

No dataset is loaded, modified, cleaned, or transformed in this section.

In [2]:
# =========================================================
# 1.1 Setup
# =========================================================

import pandas as pd
import numpy as np

# =========================================================
# Display Configuration
# =========================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)

In [3]:

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

## 1.2 Load and Preserve Product Raw Dataset

Load the raw Product source file and preserve it as the original source dataset.

The raw dataset must not be modified during the ETL process. Any profiling, cleaning, transformation, or validation work will use separate DataFrame copies where appropriate.

In [4]:
# =========================================================
# 1.2 Load and Preserve Product Raw Dataset
# =========================================================

# Define the raw Product dataset path
product_catalog_products_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\03_Product_Catalog\product_catalog_products.csv"
)


# Load the raw source dataset
product_catalog_products_raw = pd.read_csv(
    product_catalog_products_raw_path
)


# Preserve an untouched copy of the original raw dataset
product_catalog_products_raw_original = (
    product_catalog_products_raw.copy(deep=True)
)


print("Product raw dataset loaded successfully.")
print("Rows:", len(product_catalog_products_raw))
print("Columns:", len(product_catalog_products_raw.columns))
print("Path:", product_catalog_products_raw_path)

Product raw dataset loaded successfully.
Rows: 15
Columns: 15
Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\03_Product_Catalog\product_catalog_products.csv

## 1.3 Initial Raw Data Inspection

Perform an initial inspection of the untouched Product raw dataset before profiling.

This step establishes the dataset structure, current pandas data types, missing-value counts, and a sample of the raw records.

No transformations are performed at this stage.

In [5]:
# =========================================================
# 1.3 Initial Raw Data Inspection
# =========================================================

print("Dataset shape:")
print(product_catalog_products_raw.shape)


print("\nColumn names:")
print(product_catalog_products_raw.columns.tolist())


print("\nCurrent pandas data types:")
print(product_catalog_products_raw.dtypes)


print("\nMissing values:")
print(product_catalog_products_raw.isnull().sum())


print("\nSample raw records:")
display(product_catalog_products_raw.head())

Dataset shape:
(15, 15)

Column names:
['ProductCode', 'SKU', 'ProductName', 'Description', 'CategoryCode', 'SupplierCode', 'UnitCost', 'ListPrice', 'WeightKg', 'WarrantyMonths', 'ActiveFlag', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Current pandas data types:
ProductCode        object
SKU                object
ProductName        object
Description        object
CategoryCode       object
SupplierCode       object
UnitCost            int64
ListPrice           int64
WeightKg          float64
WarrantyMonths      int64
ActiveFlag           bool
CreatedOn          object
CreatedByUser      object
ModifiedOn         object
ModifiedByUser     object
dtype: object

Missing values:
ProductCode       0
SKU               0
ProductName       0
Description       0
CategoryCode      0
SupplierCode      0
UnitCost          0
ListPrice         0
WeightKg          0
WarrantyMonths    0
ActiveFlag        0
CreatedOn         0
CreatedByUser     0
ModifiedOn        0
ModifiedByUser    0
dtype: int64

Sample raw records:

  ProductCode      SKU         ProductName                   Description CategoryCode SupplierCode  UnitCost  ListPrice  WeightKg  WarrantyMonths  ActiveFlag   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0       P0001  LAP-001    Dell Inspiron 15       15-inch business laptop       CAT001       SUP001      2100       2499      1.75              24        True  2026-07-01         admin  2026-07-15          admin
1       P0002  LAP-002   Lenovo IdeaPad 5   Everyday productivity laptop       CAT001       SUP002      1800       2199      1.65              24        True  2026-07-01         admin  2026-07-15          admin
2       P0003  LAP-003     ASUS TUF Gaming                 Gaming laptop       CAT001       SUP003      3200       3899      2.20              24        True  2026-07-01         admin  2026-07-15          admin
3       P0004  PHN-001  Samsung Galaxy A55          Mid-range smartphone       CAT002       SUP004      1050       1399      0.21              12        True  2026-07-01         admin  2026-07-15          admin
4       P0005  PHN-002           iPhone 15              Apple smartphone       CAT002       SUP005      2600       2999      0.17              12        True  2026-07-01         admin  2026-07-15          admin

## 1.4 Data Profiling

Profile the untouched raw Product dataset using the reusable `data_profiler_v1` tool.

The profiler is used to identify potential data-quality issues, semantic field types, missing values, duplicates, formatting inconsistencies, and other detectable anomalies before any cleaning or transformation is performed.

Profiling results are treated as findings for investigation. The profiler does not make business decisions or automatically determine the correct transformation.

In [6]:
# =========================================================
# 1.4 Data Profiling
# =========================================================

import sys
import importlib


# Identify the project root
project_root = Path.cwd().parent


# Add the project root to the Python path if needed
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))


# Import and reload the reusable data profiler
from profiler import data_profiler_v1 as profiler

importlib.reload(profiler)


print("Profiler loaded successfully:")
print(profiler.__file__)


print("\nProfiler configuration:")
print(profiler.DEFAULT_CONFIG)

Profiler loaded successfully:
c:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\profiler\data_profiler_v1.py

Profiler configuration:
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

In [7]:
# Run the complete profiler against the untouched raw Product dataset

profile_results = profiler.profile_dataset(
    product_catalog_products_raw
)

print("\nProduct profiling completed successfully.")

print("\nProfiler sections:")
print(list(profile_results.keys()))

Product profiling completed successfully.

Profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

## 1.5 Review Profiling Results

Review the complete Product profiling results before making any transformation decisions.

The automated profiler identifies potential data-quality issues, but the results must be independently reviewed in the context of the Product dataset and LJ Dev Commerce business requirements.

This review examines:

- Automated profiling findings
- Issues requiring independent analyst review
- Potential business-rule decisions
- Issues that may require transformation

No data is modified during this stage.

In [8]:
# =========================================================
# 1.5 Review Profiling Results
# =========================================================

for section_name, section_result in profile_results.items():

    print("\n" + "=" * 70)
    print(section_name.upper())
    print("=" * 70)

    print(section_result)

======================================================================
FIELD_TYPES
======================================================================
ProductCode        identifier
SKU                identifier
ProductName              text
Description              text
CategoryCode       identifier
SupplierCode       identifier
UnitCost              numeric
ListPrice             numeric
WeightKg              numeric
WarrantyMonths        numeric
ActiveFlag            boolean
CreatedOn                date
CreatedByUser     categorical
ModifiedOn               date
ModifiedByUser    categorical
Name: DetectedFieldType, dtype: object

======================================================================
DETECTION_DETAILS
======================================================================
{'ProductCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SKU': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'ProductName': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'Description': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'CategoryCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SupplierCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'UnitCost': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'ListPrice': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'WeightKg': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'WarrantyMonths': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'ActiveFlag': {'DetectedType': 'boolean', 'Confidence': 'High', 'Evidence': 'Native boolean dtype'}, 'CreatedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'CreatedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'ModifiedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'ModifiedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}}

======================================================================
GENERAL
======================================================================
{'rows': 15, 'columns': 15, 'exact_duplicate_rows': 0, 'column_profile':                DataType DetectedFieldType  MissingCount  MissingPercent  UniqueCount  DuplicateValueCount
ProductCode      object        identifier             0             0.0           15                    0
SKU              object        identifier             0             0.0           15                    0
ProductName      object              text             0             0.0           15                    0
Description      object              text             0             0.0           15                    0
CategoryCode     object        identifier             0             0.0            6                    9
SupplierCode     object        identifier             0             0.0            7                    8
UnitCost          int64           numeric             0             0.0           15                    0
ListPrice         int64           numeric             0             0.0           13                    2
WeightKg        float64           numeric             0             0.0           15                    0
WarrantyMonths    int64           numeric             0             0.0            2                   13
ActiveFlag         bool           boolean             0             0.0            1                   14
CreatedOn        object              date             0             0.0            1                   14
CreatedByUser    object       categorical             0             0.0            1                   14
ModifiedOn       object              date             0             0.0            1                   14
ModifiedByUser   object       categorical             0             0.0            1                   14}

======================================================================
TEXT
======================================================================
{'ProductName': {'WhitespaceCount': 1, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 8, 'MaximumLength': 21, 'AverageLength': np.float64(15.73)}, 'Description': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 12, 'MaximumLength': 32, 'AverageLength': np.float64(19.6)}}

======================================================================
CATEGORICAL
======================================================================
{'ActiveFlag': {'UniqueCount': 1, 'MostCommonValue': np.True_, 'MostCommonCount': 15, 'CategoryDistribution': {True: 15}}, 'CreatedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 15, 'CategoryDistribution': {'admin': 15}}, 'ModifiedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 15, 'CategoryDistribution': {'admin': 15}}}

======================================================================
NUMERIC
======================================================================
{'UnitCost': {'ValidNumericCount': 15, 'InvalidNumericCount': 0, 'Minimum': np.float64(120.0), 'Maximum': np.float64(3200.0), 'Mean': np.float64(1409.3333333333333), 'Median': np.float64(1250.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 15, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(-2425.0), 'UpperOutlierBoundary': np.float64(5135.0)}, 'ListPrice': {'ValidNumericCount': 15, 'InvalidNumericCount': 0, 'Minimum': np.float64(179.0), 'Maximum': np.float64(3899.0), 'Mean': np.float64(1727.6666666666667), 'Median': np.float64(1599.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 15, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(-2626.0), 'UpperOutlierBoundary': np.float64(5974.0)}, 'WeightKg': {'ValidNumericCount': 15, 'InvalidNumericCount': 0, 'Minimum': np.float64(0.14), 'Maximum': np.float64(6.2), 'Mean': np.float64(1.2453333333333334), 'Median': np.float64(0.5), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 15, 'RecognizedRepresentations': ['Decimal'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 1, 'LowerOutlierBoundary': np.float64(-2.0374999999999996), 'UpperOutlierBoundary': np.float64(3.9425)}, 'WarrantyMonths': {'ValidNumericCount': 15, 'InvalidNumericCount': 0, 'Minimum': np.float64(12.0), 'Maximum': np.float64(24.0), 'Mean': np.float64(16.8), 'Median': np.float64(12.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 15, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(-6.0), 'UpperOutlierBoundary': np.float64(42.0)}}

======================================================================
DATE
======================================================================
{'CreatedOn': {'ValidDateCount': 15, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-01 00:00:00'), 'MaximumDate': Timestamp('2026-07-01 00:00:00'), 'FutureDateCount': 0}, 'ModifiedOn': {'ValidDateCount': 15, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-15 00:00:00'), 'MaximumDate': Timestamp('2026-07-15 00:00:00'), 'FutureDateCount': 0}}

======================================================================
PATTERNS
======================================================================
{'email': {}, 'phone': {}, 'identifier': {'ProductCode': {'UniqueCount': 15, 'DuplicateCount': 0, 'MissingCount': 0}, 'SKU': {'UniqueCount': 15, 'DuplicateCount': 0, 'MissingCount': 0}, 'CategoryCode': {'UniqueCount': 6, 'DuplicateCount': 9, 'MissingCount': 0}, 'SupplierCode': {'UniqueCount': 7, 'DuplicateCount': 8, 'MissingCount': 0}}}

======================================================================
ISSUES
======================================================================
         Column            IssueType Severity  Count                               Description
0  CategoryCode  DuplicateIdentifier     High      9      Repeated identifier values detected.
1  SupplierCode  DuplicateIdentifier     High      8      Repeated identifier values detected.
2   ProductName           Whitespace      Low      1  Leading or trailing whitespace detected.

======================================================================
CONFIGURATION
======================================================================
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

## 1.6 Review Profiler Issues

Review the issues identified by the automated profiler.

The full profiling output provides a broad assessment of the raw Product dataset. This step focuses specifically on the detected issues so they can be investigated before any transformation decisions are made.

Profiler findings are treated as indicators for review and do not automatically determine the correct transformation.

In [9]:
# =========================================================
# 1.6 Review Profiler Issues
# =========================================================

product_issues = profile_results["issues"]

display(product_issues)

         Column            IssueType Severity  Count                               Description
0  CategoryCode  DuplicateIdentifier     High      9      Repeated identifier values detected.
1  SupplierCode  DuplicateIdentifier     High      8      Repeated identifier values detected.
2   ProductName           Whitespace      Low      1  Leading or trailing whitespace detected.

## 1.7 Independent Analyst Review

Perform a systematic independent analyst review of the untouched raw Product dataset.

This section is the notebook-based version of the Pre-ETL Inspection.

The review goes beyond the automated profiler and checks the Product dataset using independent analyst validation relevant to its business meaning and approved ETL design.

The review covers, where applicable:

- Dataset structure and grain
- Missing and blank values
- Exact duplicate rows
- Primary-key candidates and key uniqueness
- Whitespace in text fields
- Text consistency
- Numeric validity and statistical outlier candidates
- Boolean validity
- Date parsing, datatype, validity, and Created/Modified date consistency
- CategoryCode and SupplierCode relationship values
- Source-to-target datatype compatibility considerations

Automated profiler findings and independent analyst findings are kept conceptually separate.

No data is modified in this section.

In [10]:
# =========================================================
# 1.7 Independent Analyst Review
# =========================================================


# =========================================================
# 1. Dataset Structure and Grain
# =========================================================

print("1. DATASET STRUCTURE AND GRAIN")
print("=" * 80)

print(f"Rows: {product_catalog_products_raw.shape[0]}")
print(f"Columns: {product_catalog_products_raw.shape[1]}")

print("\nWorking assumption:")
print("One row represents one product record.")


# =========================================================
# 2. Missing Values and Blank Values
# =========================================================

print("\n2. MISSING VALUES AND BLANK VALUES")
print("=" * 80)

missing_values = product_catalog_products_raw.isna().sum()

blank_values = pd.Series(
    {
        column: (
            product_catalog_products_raw[column]
            .astype("string")
            .str.strip()
            .eq("")
            .sum()
            if product_catalog_products_raw[column].dtype == "object"
            else 0
        )
        for column in product_catalog_products_raw.columns
    }
)

missing_blank_review = pd.DataFrame({
    "MissingValues": missing_values,
    "BlankValues": blank_values
})

display(missing_blank_review)


# =========================================================
# 3. Exact Duplicate Rows
# =========================================================

print("\n3. EXACT DUPLICATE ROWS")
print("=" * 80)

exact_duplicate_count = product_catalog_products_raw.duplicated().sum()

print(f"Exact duplicate rows: {exact_duplicate_count}")

if exact_duplicate_count > 0:
    display(
        product_catalog_products_raw[
            product_catalog_products_raw.duplicated(keep=False)
        ]
    )


# =========================================================
# 4. Primary Key Candidate and Identifier Uniqueness
# =========================================================

print("\n4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS")
print("=" * 80)

identifier_columns = ["ProductCode", "SKU"]

identifier_review = pd.DataFrame(
    {
        "Column": identifier_columns,
        "NullCount": [
            product_catalog_products_raw[column].isna().sum()
            for column in identifier_columns
        ],
        "BlankCount": [
            product_catalog_products_raw[column]
            .astype("string")
            .str.strip()
            .eq("")
            .sum()
            for column in identifier_columns
        ],
        "DuplicateCount": [
            product_catalog_products_raw[column]
            .duplicated()
            .sum()
            for column in identifier_columns
        ],
        "UniqueValues": [
            product_catalog_products_raw[column]
            .nunique()
            for column in identifier_columns
        ]
    }
)

display(identifier_review)


# =========================================================
# 5. Leading and Trailing Whitespace Review
# =========================================================

print("\n5. LEADING AND TRAILING WHITESPACE REVIEW")
print("=" * 80)

text_columns = product_catalog_products_raw.select_dtypes(
    include="object"
).columns

whitespace_findings = []

for column in text_columns:

    whitespace_mask = (
        product_catalog_products_raw[column]
        .astype("string")
        != product_catalog_products_raw[column]
        .astype("string")
        .str.strip()
    )

    count = whitespace_mask.sum()

    if count > 0:

        whitespace_records = product_catalog_products_raw.loc[
            whitespace_mask,
            ["ProductCode", column]
        ]

        whitespace_findings.append({
            "Column": column,
            "WhitespaceRecordCount": count
        })

        print(f"\nColumn: {column}")
        display(whitespace_records)


if whitespace_findings:

    print("\nWhitespace findings summary:")
    display(pd.DataFrame(whitespace_findings))

else:

    print("No leading or trailing whitespace found.")


# =========================================================
# 6. Numeric Validity Review
# =========================================================

print("\n6. NUMERIC VALIDITY REVIEW")
print("=" * 80)

numeric_columns = [
    "UnitCost",
    "ListPrice",
    "WeightKg",
    "WarrantyMonths"
]

numeric_summary = product_catalog_products_raw[
    numeric_columns
].describe().T

numeric_summary["NegativeCount"] = [
    (product_catalog_products_raw[column] < 0).sum()
    for column in numeric_columns
]

display(numeric_summary)


# =========================================================
# 7. Numeric Outlier Candidate Review
# =========================================================

print("\n7. NUMERIC OUTLIER CANDIDATE REVIEW")
print("=" * 80)

outlier_summary = []

for column in numeric_columns:

    q1 = product_catalog_products_raw[column].quantile(0.25)
    q3 = product_catalog_products_raw[column].quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)

    outlier_mask = (
        (product_catalog_products_raw[column] < lower_bound)
        |
        (product_catalog_products_raw[column] > upper_bound)
    )

    outlier_count = outlier_mask.sum()

    outlier_summary.append({
        "Column": column,
        "LowerBoundary": lower_bound,
        "UpperBoundary": upper_bound,
        "OutlierCandidateCount": outlier_count
    })

    if outlier_count > 0:

        print(f"\nOutlier candidate(s): {column}")

        display(
            product_catalog_products_raw.loc[
                outlier_mask,
                [
                    "ProductCode",
                    "SKU",
                    "ProductName",
                    column
                ]
            ]
        )


print("\nOutlier candidate summary:")
display(pd.DataFrame(outlier_summary))


# =========================================================
# 8. Boolean Validity Review
# =========================================================

print("\n8. BOOLEAN VALIDITY REVIEW")
print("=" * 80)

print("ActiveFlag datatype:")
print(product_catalog_products_raw["ActiveFlag"].dtype)

print("\nActiveFlag values:")
print(
    product_catalog_products_raw["ActiveFlag"]
    .value_counts(dropna=False)
)


# =========================================================
# 9. Date Parsing and Datatype Review
# =========================================================

print("\n9. DATE PARSING AND DATATYPE REVIEW")
print("=" * 80)

date_columns = ["CreatedOn", "ModifiedOn"]

date_review = []

for column in date_columns:

    parsed_dates = pd.to_datetime(
        product_catalog_products_raw[column],
        errors="coerce"
    )

    date_review.append({
        "Column": column,
        "CurrentSourceDtype": str(
            product_catalog_products_raw[column].dtype
        ),
        "InvalidDateCount": parsed_dates.isna().sum(),
        "MinimumDate": parsed_dates.min(),
        "MaximumDate": parsed_dates.max()
    })

display(pd.DataFrame(date_review))


# =========================================================
# 10. CreatedOn and ModifiedOn Date Logic
# =========================================================

print("\n10. CREATED / MODIFIED DATE LOGIC")
print("=" * 80)

created_dates = pd.to_datetime(
    product_catalog_products_raw["CreatedOn"],
    errors="coerce"
)

modified_dates = pd.to_datetime(
    product_catalog_products_raw["ModifiedOn"],
    errors="coerce"
)

date_logic_issues = product_catalog_products_raw[
    modified_dates < created_dates
]

print(
    f"Records where ModifiedOn is earlier than CreatedOn: "
    f"{len(date_logic_issues)}"
)

if not date_logic_issues.empty:

    display(
        date_logic_issues[
            [
                "ProductCode",
                "CreatedOn",
                "ModifiedOn"
            ]
        ]
    )


# =========================================================
# 11. CategoryCode and SupplierCode Relationship Review
# =========================================================

print("\n11. RELATIONSHIP VALUE REVIEW")
print("=" * 80)

for column in ["CategoryCode", "SupplierCode"]:

    print(f"\n{column} frequency:")

    display(
        product_catalog_products_raw[column]
        .value_counts(dropna=False)
        .sort_index()
        .rename("RecordCount")
        .to_frame()
    )


# =========================================================
# 12. Source Datatype Review
# =========================================================

print("\n12. SOURCE DATATYPE REVIEW")
print("=" * 80)

datatype_review = pd.DataFrame({
    "Column": product_catalog_products_raw.columns,
    "SourceDtype": [
        str(product_catalog_products_raw[column].dtype)
        for column in product_catalog_products_raw.columns
    ]
})

display(datatype_review)


# =========================================================
# Independent Analyst Review Complete
# =========================================================

print("\n" + "=" * 80)
print("Independent Analyst Review completed.")
print("No data was modified.")
print("=" * 80)

1. DATASET STRUCTURE AND GRAIN
================================================================================
Rows: 15
Columns: 15

Working assumption:
One row represents one product record.

2. MISSING VALUES AND BLANK VALUES
================================================================================

                MissingValues  BlankValues
ProductCode                 0            0
SKU                         0            0
ProductName                 0            0
Description                 0            0
CategoryCode                0            0
SupplierCode                0            0
UnitCost                    0            0
ListPrice                   0            0
WeightKg                    0            0
WarrantyMonths              0            0
ActiveFlag                  0            0
CreatedOn                   0            0
CreatedByUser               0            0
ModifiedOn                  0            0
ModifiedByUser              0            0

3. EXACT DUPLICATE ROWS
================================================================================
Exact duplicate rows: 0

4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS
================================================================================

        Column  NullCount  BlankCount  DuplicateCount  UniqueValues
0  ProductCode          0           0               0            15
1          SKU          0           0               0            15

5. LEADING AND TRAILING WHITESPACE REVIEW
================================================================================

Column: SKU

  ProductCode        SKU
8       P0009   MON-001

Column: ProductName

  ProductCode         ProductName
1       P0002   Lenovo IdeaPad 5

Whitespace findings summary:

        Column  WhitespaceRecordCount
0          SKU                      1
1  ProductName                      1

6. NUMERIC VALIDITY REVIEW
================================================================================

                count         mean          std     min      25%     50%     75%     max  NegativeCount
UnitCost         15.0  1409.333333  1041.197571  120.00  410.000  1250.0  2300.0  3200.0              0
ListPrice        15.0  1727.666667  1201.206933  179.00  599.000  1599.0  2749.0  3899.0              0
WeightKg         15.0     1.245333     1.634288    0.14    0.205     0.5     1.7     6.2              0
WarrantyMonths   15.0    16.800000     6.085111   12.00   12.000    12.0    24.0    24.0              0

7. NUMERIC OUTLIER CANDIDATE REVIEW
================================================================================

Outlier candidate(s): WeightKg

  ProductCode      SKU      ProductName  WeightKg
9       P0010  MON-002  LG UltraWide 34       6.2

Outlier candidate summary:

           Column  LowerBoundary  UpperBoundary  OutlierCandidateCount
0        UnitCost     -2425.0000      5135.0000                      0
1       ListPrice     -2626.0000      5974.0000                      0
2        WeightKg        -2.0375         3.9425                      1
3  WarrantyMonths        -6.0000        42.0000                      0

8. BOOLEAN VALIDITY REVIEW
================================================================================
ActiveFlag datatype:
bool

ActiveFlag values:
ActiveFlag
True    15
Name: count, dtype: int64

9. DATE PARSING AND DATATYPE REVIEW
================================================================================

       Column CurrentSourceDtype  InvalidDateCount MinimumDate MaximumDate
0   CreatedOn             object                 0  2026-07-01  2026-07-01
1  ModifiedOn             object                 0  2026-07-15  2026-07-15

10. CREATED / MODIFIED DATE LOGIC
================================================================================
Records where ModifiedOn is earlier than CreatedOn: 0

11. RELATIONSHIP VALUE REVIEW
================================================================================

CategoryCode frequency:

              RecordCount
CategoryCode
CAT001                  3
CAT002                  3
CAT003                  2
CAT004                  2
CAT005                  3
CAT006                  2

SupplierCode frequency:

              RecordCount
SupplierCode
SUP001                  2
SUP002                  1
SUP003                  3
SUP004                  3
SUP005                  2
SUP006                  2
SUP007                  2

12. SOURCE DATATYPE REVIEW
================================================================================

            Column SourceDtype
0      ProductCode      object
1              SKU      object
2      ProductName      object
3      Description      object
4     CategoryCode      object
5     SupplierCode      object
6         UnitCost       int64
7        ListPrice       int64
8         WeightKg     float64
9   WarrantyMonths       int64
10      ActiveFlag        bool
11       CreatedOn      object
12   CreatedByUser      object
13      ModifiedOn      object
14  ModifiedByUser      object

================================================================================
Independent Analyst Review completed.
No data was modified.
================================================================================

## 1.8 Findings and Transformation Decisions

Compare the automated profiler findings, the Independent Analyst Review findings, and the approved Product data requirements to formally determine the required treatment for each finding.

Each finding must be classified as one of the following:

- Safe deterministic transformation
- Valid value — retain unchanged
- Expected business behavior
- Requires relationship validation later
- Requires business investigation

No transformation is performed in this section.

The approved decisions from this section will define the transformations applied in Section 2.2.

In [11]:
# =========================================================
# 1.8 Findings and Transformation Decisions
# =========================================================

transformation_decisions = pd.DataFrame([
    
    {
        "Finding": "SKU leading/trailing whitespace",
        "AffectedRecords": 1,
        "Decision": "Transform",
        "ApprovedAction": "Trim leading and trailing whitespace",
        "Reason": "Whitespace is not part of the business identifier value and can affect joins and matching."
    },
    
    {
        "Finding": "ProductName leading/trailing whitespace",
        "AffectedRecords": 1,
        "Decision": "Transform",
        "ApprovedAction": "Trim leading and trailing whitespace",
        "Reason": "Safe deterministic text cleaning with no change to business meaning."
    },
    
    {
        "Finding": "CreatedOn stored as object",
        "AffectedRecords": 15,
        "Decision": "Transform",
        "ApprovedAction": "Convert to datetime",
        "Reason": "Values are valid dates but require proper datatype preparation for the clean dataset and database loading."
    },
    
    {
        "Finding": "ModifiedOn stored as object",
        "AffectedRecords": 15,
        "Decision": "Transform",
        "ApprovedAction": "Convert to datetime",
        "Reason": "Values are valid dates but require proper datatype preparation for the clean dataset and database loading."
    },
    
    {
        "Finding": "WeightKg statistical outlier candidate",
        "AffectedRecords": 1,
        "Decision": "Retain unchanged",
        "ApprovedAction": "No automatic modification",
        "Reason": "Statistical outlier detection does not prove that the product weight is incorrect. The value requires business context."
    },
    
    {
        "Finding": "Repeated CategoryCode values",
        "AffectedRecords": 9,
        "Decision": "Expected business behavior",
        "ApprovedAction": "Retain unchanged",
        "Reason": "Multiple products can belong to the same category. Relationship integrity will be validated later."
    },
    
    {
        "Finding": "Repeated SupplierCode values",
        "AffectedRecords": 8,
        "Decision": "Expected business behavior",
        "ApprovedAction": "Retain unchanged",
        "Reason": "Multiple products can be supplied by the same supplier. Relationship integrity will be validated later."
    },
    
    {
        "Finding": "Exact duplicate rows",
        "AffectedRecords": 0,
        "Decision": "No action required",
        "ApprovedAction": "Retain dataset unchanged",
        "Reason": "No exact duplicate rows were found."
    },
    
    {
        "Finding": "Missing or blank values",
        "AffectedRecords": 0,
        "Decision": "No action required",
        "ApprovedAction": "Retain dataset unchanged",
        "Reason": "No missing or blank values were found."
    },
    
    {
        "Finding": "ProductCode and SKU uniqueness",
        "AffectedRecords": 0,
        "Decision": "Valid",
        "ApprovedAction": "Retain unchanged",
        "Reason": "Both identifiers are unique in the source dataset."
    }
])


print("Product Findings and Transformation Decisions")
print("=" * 120)

display(transformation_decisions)


print("\nDecision Summary")
print("=" * 120)

print(
    transformation_decisions["Decision"]
    .value_counts()
)

Product Findings and Transformation Decisions
========================================================================================================================

                                   Finding  AffectedRecords                    Decision                        ApprovedAction                                                                                                                   Reason
0          SKU leading/trailing whitespace                1                   Transform  Trim leading and trailing whitespace                               Whitespace is not part of the business identifier value and can affect joins and matching.
1  ProductName leading/trailing whitespace                1                   Transform  Trim leading and trailing whitespace                                                     Safe deterministic text cleaning with no change to business meaning.
2               CreatedOn stored as object               15                   Transform                   Convert to datetime               Values are valid dates but require proper datatype preparation for the clean dataset and database loading.
3              ModifiedOn stored as object               15                   Transform                   Convert to datetime               Values are valid dates but require proper datatype preparation for the clean dataset and database loading.
4   WeightKg statistical outlier candidate                1            Retain unchanged             No automatic modification  Statistical outlier detection does not prove that the product weight is incorrect. The value requires business context.
5             Repeated CategoryCode values                9  Expected business behavior                      Retain unchanged                       Multiple products can belong to the same category. Relationship integrity will be validated later.
6             Repeated SupplierCode values                8  Expected business behavior                      Retain unchanged                  Multiple products can be supplied by the same supplier. Relationship integrity will be validated later.
7                     Exact duplicate rows                0          No action required              Retain dataset unchanged                                                                                      No exact duplicate rows were found.
8                  Missing or blank values                0          No action required              Retain dataset unchanged                                                                                   No missing or blank values were found.
9           ProductCode and SKU uniqueness                0                       Valid                      Retain unchanged                                                                       Both identifiers are unique in the source dataset.

Decision Summary
========================================================================================================================
Decision
Transform                     4
Expected business behavior    2
No action required            2
Retain unchanged              1
Valid                         1
Name: count, dtype: int64

# =========================================================
# SECTION 2 — DATA TRANSFORMATION
# =========================================================

## 2.1 Create Clean Working Dataset

Create a separate working copy of the raw Product dataset before applying any approved transformations.

The raw dataset must remain unchanged throughout the ETL process.

All transformations will be applied only to the clean working dataset.

In [14]:
# =========================================================
# 2.1 Create Clean Working Dataset
# =========================================================

product_catalog_products_clean = product_catalog_products_raw.copy()

print("Clean working dataset created successfully.")

print(f"Raw dataset rows:   {product_catalog_products_raw.shape[0]}")
print(f"Clean dataset rows: {product_catalog_products_clean.shape[0]}")

print("\nRaw and clean datasets are separate objects:")

print(
    product_catalog_products_raw is not product_catalog_products_clean
)

Clean working dataset created successfully.
Raw dataset rows:   15
Clean dataset rows: 15

Raw and clean datasets are separate objects:
True

## 2.2 Apply Approved Transformations

Apply only the transformations approved in Section 1.8 to the clean working dataset.

Approved transformations:

- Trim leading and trailing whitespace from SKU.
- Trim leading and trailing whitespace from ProductName.
- Convert CreatedOn to datetime.
- Convert ModifiedOn to datetime.

No other values will be modified.

The WeightKg statistical outlier candidate will be retained unchanged because statistical outlier detection alone does not confirm a data error.

In [15]:
# =========================================================
# 2.2 Apply Approved Transformations
# =========================================================

# ---------------------------------------------------------
# 1. Trim approved text fields
# ---------------------------------------------------------

product_catalog_products_clean["SKU"] = (
    product_catalog_products_clean["SKU"]
    .str.strip()
)

product_catalog_products_clean["ProductName"] = (
    product_catalog_products_clean["ProductName"]
    .str.strip()
)


# ---------------------------------------------------------
# 2. Convert approved date fields
# ---------------------------------------------------------

product_catalog_products_clean["CreatedOn"] = pd.to_datetime(
    product_catalog_products_clean["CreatedOn"],
    errors="raise"
)

product_catalog_products_clean["ModifiedOn"] = pd.to_datetime(
    product_catalog_products_clean["ModifiedOn"],
    errors="raise"
)


# ---------------------------------------------------------
# Transformation Summary
# ---------------------------------------------------------

print("Approved transformations applied successfully.")

print("\nClean dataset datatypes:")
print(
    product_catalog_products_clean[
        ["SKU", "ProductName", "CreatedOn", "ModifiedOn"]
    ].dtypes
)

print("\nWeightKg outlier candidate retained unchanged.")

Approved transformations applied successfully.

Clean dataset datatypes:
SKU                    object
ProductName            object
CreatedOn      datetime64[ns]
ModifiedOn     datetime64[ns]
dtype: object

WeightKg outlier candidate retained unchanged.

# =========================================================
# SECTION 3 — VALIDATE
# =========================================================

## 3.1 Transformation Validation

Validate that every transformation approved in Section 1.8 was successfully applied to the clean Product dataset.

This validation checks:

- SKU whitespace removal
- ProductName whitespace removal
- CreatedOn datetime conversion
- ModifiedOn datetime conversion
- WeightKg outlier candidate retention

Only approved transformations are validated.

No additional data modifications are performed in this section.

In [18]:
# =========================================================
# 3.1 Transformation Validation
# =========================================================

validation_results = []


# ---------------------------------------------------------
# 1. SKU Whitespace Validation
# ---------------------------------------------------------

sku_whitespace_remaining = (
    product_catalog_products_clean["SKU"]
    != product_catalog_products_clean["SKU"].str.strip()
).sum()

validation_results.append({
    "Validation": "SKU whitespace removal",
    "Expected": "0 records with leading/trailing whitespace",
    "Actual": f"{sku_whitespace_remaining} records remaining",
    "Passed": sku_whitespace_remaining == 0
})


# ---------------------------------------------------------
# 2. ProductName Whitespace Validation
# ---------------------------------------------------------

product_name_whitespace_remaining = (
    product_catalog_products_clean["ProductName"]
    != product_catalog_products_clean["ProductName"].str.strip()
).sum()

validation_results.append({
    "Validation": "ProductName whitespace removal",
    "Expected": "0 records with leading/trailing whitespace",
    "Actual": f"{product_name_whitespace_remaining} records remaining",
    "Passed": product_name_whitespace_remaining == 0
})


# ---------------------------------------------------------
# 3. CreatedOn Datetime Validation
# ---------------------------------------------------------

created_on_is_datetime = pd.api.types.is_datetime64_any_dtype(
    product_catalog_products_clean["CreatedOn"]
)

validation_results.append({
    "Validation": "CreatedOn datetime conversion",
    "Expected": "datetime64 datatype",
    "Actual": str(product_catalog_products_clean["CreatedOn"].dtype),
    "Passed": created_on_is_datetime
})


# ---------------------------------------------------------
# 4. ModifiedOn Datetime Validation
# ---------------------------------------------------------

modified_on_is_datetime = pd.api.types.is_datetime64_any_dtype(
    product_catalog_products_clean["ModifiedOn"]
)

validation_results.append({
    "Validation": "ModifiedOn datetime conversion",
    "Expected": "datetime64 datatype",
    "Actual": str(product_catalog_products_clean["ModifiedOn"].dtype),
    "Passed": modified_on_is_datetime
})


# ---------------------------------------------------------
# 5. WeightKg Retention Validation
# ---------------------------------------------------------

raw_p0010_weight = product_catalog_products_raw.loc[
    product_catalog_products_raw["ProductCode"] == "P0010",
    "WeightKg"
].iloc[0]

clean_p0010_weight = product_catalog_products_clean.loc[
    product_catalog_products_clean["ProductCode"] == "P0010",
    "WeightKg"
].iloc[0]

weight_retained = raw_p0010_weight == clean_p0010_weight

validation_results.append({
    "Validation": "WeightKg outlier candidate retention",
    "Expected": f"WeightKg remains {raw_p0010_weight}",
    "Actual": f"WeightKg is {clean_p0010_weight}",
    "Passed": weight_retained
})


# ---------------------------------------------------------
# Transformation Validation Results
# ---------------------------------------------------------

transformation_validation = pd.DataFrame(validation_results)

print("TRANSFORMATION VALIDATION RESULTS")
print("=" * 120)

display(transformation_validation)


# ---------------------------------------------------------
# Overall Result
# ---------------------------------------------------------

overall_validation_passed = transformation_validation["Passed"].all()

print(
    "\nOverall Transformation Validation Passed:",
    overall_validation_passed
)

if not overall_validation_passed:
    raise ValueError(
        "Transformation validation failed. Review the results "
        "before proceeding."
    )

TRANSFORMATION VALIDATION RESULTS
========================================================================================================================

                             Validation                                    Expected               Actual  Passed
0                SKU whitespace removal  0 records with leading/trailing whitespace  0 records remaining    True
1        ProductName whitespace removal  0 records with leading/trailing whitespace  0 records remaining    True
2         CreatedOn datetime conversion                         datetime64 datatype       datetime64[ns]    True
3        ModifiedOn datetime conversion                         datetime64 datatype       datetime64[ns]    True
4  WeightKg outlier candidate retention                        WeightKg remains 6.2      WeightKg is 6.2    True

Overall Transformation Validation Passed: True

## 3.2 Validate Data Preservation

Validate that the approved transformations did not unintentionally alter unaffected Product data.

The validation compares the raw and cleaned datasets while accounting for the approved transformations:

- SKU whitespace removal
- ProductName whitespace removal
- CreatedOn datatype conversion
- ModifiedOn datatype conversion

All other business and audit field values should remain unchanged.

In [19]:
# =========================================================
# 3.2 Validate Data Preservation
# =========================================================

# Columns that should remain completely unchanged
unchanged_columns = [
    "ProductCode",
    "Description",
    "CategoryCode",
    "SupplierCode",
    "UnitCost",
    "ListPrice",
    "WeightKg",
    "WarrantyMonths",
    "ActiveFlag",
    "CreatedByUser",
    "ModifiedByUser"
]

all_columns_match = True

for column in unchanged_columns:

    matches = (
        product_catalog_products_raw[column]
        .astype(str)
        .reset_index(drop=True)
        ==
        product_catalog_products_clean[column]
        .astype(str)
        .reset_index(drop=True)
    ).all()

    print(f"{column}: {matches}")

    if not matches:
        all_columns_match = False


print(
    "\nAll unaffected columns preserved:",
    all_columns_match
)

if not all_columns_match:
    raise ValueError(
        "Data preservation validation failed. "
        "An unaffected column was unexpectedly changed."
    )

ProductCode: True
Description: True
CategoryCode: True
SupplierCode: True
UnitCost: True
ListPrice: True
WeightKg: True
WarrantyMonths: True
ActiveFlag: True
CreatedByUser: True
ModifiedByUser: True

All unaffected columns preserved: True

# =========================================================
# SECTION 4 — CLEAN CSV
# =========================================================

## 4.1 Export Clean Product Dataset

Export the validated `product_catalog_products_clean` DataFrame as the clean Product dataset.

The clean CSV represents the completed data-cleaning stage and preserves the validated Product records before database-ready column mapping begins.

In [20]:
# =========================================================
# 4.1 Export Clean Product Dataset
# =========================================================

from pathlib import Path

clean_product_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\03_Product_Catalog\clean\product_catalog_products_clean.csv"
)

# Create the clean folder if it does not exist
clean_product_path.parent.mkdir(
    parents=True,
    exist_ok=True
)

# Export clean dataset
product_catalog_products_clean.to_csv(
    clean_product_path,
    index=False
)

print("Clean Product CSV exported successfully.")
print("Path:", clean_product_path)
print("Rows exported:", len(product_catalog_products_clean))
print("Columns exported:", len(product_catalog_products_clean.columns))

Clean Product CSV exported successfully.
Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\03_Product_Catalog\clean\product_catalog_products_clean.csv
Rows exported: 15
Columns exported: 15

## 4.2 Verify Exported Clean Product CSV

Reload the exported clean CSV and verify that it matches the validated clean DataFrame.

This confirms that the persisted clean CSV is the official handoff artifact for the next pipeline stage.

In [21]:
# =========================================================
# 4.2 Verify Exported Clean Product CSV
# =========================================================

# Reload the exported clean CSV
product_catalog_products_clean_csv = pd.read_csv(
    clean_product_path,
    parse_dates=["CreatedOn", "ModifiedOn"]
)


# ---------------------------------------------------------
# Basic Export Validation
# ---------------------------------------------------------

print("Clean CSV rows:", len(product_catalog_products_clean_csv))
print("Clean DataFrame rows:", len(product_catalog_products_clean))

print("\nClean CSV columns:", len(product_catalog_products_clean_csv.columns))
print("Clean DataFrame columns:", len(product_catalog_products_clean.columns))


# ---------------------------------------------------------
# Row Count Validation
# ---------------------------------------------------------

row_count_match = (
    len(product_catalog_products_clean_csv)
    == len(product_catalog_products_clean)
)

print("\nRow count matches:", row_count_match)


# ---------------------------------------------------------
# Column Validation
# ---------------------------------------------------------

columns_match = (
    list(product_catalog_products_clean_csv.columns)
    == list(product_catalog_products_clean.columns)
)

print("Column names and order match:", columns_match)


# ---------------------------------------------------------
# Datatype Validation
# ---------------------------------------------------------

print("\nReloaded Clean CSV datatypes:")
print(product_catalog_products_clean_csv.dtypes)


# ---------------------------------------------------------
# Content Validation
# ---------------------------------------------------------

content_match = (
    product_catalog_products_clean
    .reset_index(drop=True)
    .equals(
        product_catalog_products_clean_csv
        .reset_index(drop=True)
    )
)

print("\nClean DataFrame and exported CSV content match:", content_match)


# ---------------------------------------------------------
# Final Validation
# ---------------------------------------------------------

export_validation_passed = (
    row_count_match
    and columns_match
    and content_match
)

print("\n" + "=" * 80)
print("EXPORTED CLEAN CSV VALIDATION PASSED:", export_validation_passed)
print("=" * 80)

if not export_validation_passed:
    raise ValueError(
        "Exported clean CSV validation failed. "
        "Review the results before proceeding."
    )

Clean CSV rows: 15
Clean DataFrame rows: 15

Clean CSV columns: 15
Clean DataFrame columns: 15

Row count matches: True
Column names and order match: True

Reloaded Clean CSV datatypes:
ProductCode               object
SKU                       object
ProductName               object
Description               object
CategoryCode              object
SupplierCode              object
UnitCost                   int64
ListPrice                  int64
WeightKg                 float64
WarrantyMonths             int64
ActiveFlag                  bool
CreatedOn         datetime64[ns]
CreatedByUser             object
ModifiedOn        datetime64[ns]
ModifiedByUser            object
dtype: object

Clean DataFrame and exported CSV content match: True

================================================================================
EXPORTED CLEAN CSV VALIDATION PASSED: True
================================================================================

# =========================================================
# SECTION 5 — Database Ready
# =========================================================

## 5.1 Define Source → Target Mapping

Define the approved source-to-target column mapping based on the

LJ Dev Commerce Product Data Dictionary.

The mapping converts the source column names into the standardized

PostgreSQL target column names.

No data values are modified during this step.

In [13]:
# =========================================================
# 5.1 Define Source → Target Mapping
# =========================================================

product_catalog_column_mapping = {
    "ProductCode": "product_id",
    "SKU": "sku",
    "ProductName": "product_name",
    "Description": "product_description",
    "CategoryCode": "category_id",
    "SupplierCode": "supplier_id",
    "UnitCost": "cost_price",
    "ListPrice": "selling_price",
    "WeightKg": "weight_kg",
    "WarrantyMonths": "warranty_months",
    "ActiveFlag": "is_active",
    "CreatedOn": "created_date",
    "CreatedByUser": "created_by",
    "ModifiedOn": "updated_date",
    "ModifiedByUser": "updated_by"
}

print("Product Catalog Source → Target Mapping")
print("=" * 80)

for source_column, target_column in product_catalog_column_mapping.items():
    print(f"{source_column:<20} → {target_column}")

Product Catalog Source → Target Mapping
================================================================================
ProductCode          → product_id
SKU                  → sku
ProductName          → product_name
Description          → product_description
CategoryCode         → category_id
SupplierCode         → supplier_id
UnitCost             → cost_price
ListPrice            → selling_price
WeightKg             → weight_kg
WarrantyMonths       → warranty_months
ActiveFlag           → is_active
CreatedOn            → created_date
CreatedByUser        → created_by
ModifiedOn           → updated_date
ModifiedByUser       → updated_by

## 5.2 Create Database-Ready Dataset

Create the Product Catalog Database-Ready dataset from the verified

exported Clean CSV.

The approved source-to-target mapping is then applied to convert the

source column names into the PostgreSQL target structure.

The Clean CSV remains unchanged.

No undocumented business-value transformations are applied during this step.

In [14]:
# =========================================================
# 5.2 Create Database-Ready Dataset
# =========================================================

from decimal import Decimal

# Define the verified exported Clean CSV path
product_catalog_clean_path = (
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data"
    r"\03_Product_Catalog\clean\product_catalog_products_clean.csv"
)

# Load the verified exported Clean CSV
product_catalog_products_clean_exported = pd.read_csv(
    product_catalog_clean_path
)

# Convert approved date columns back to datetime
product_catalog_products_clean_exported["CreatedOn"] = pd.to_datetime(
    product_catalog_products_clean_exported["CreatedOn"]
)

product_catalog_products_clean_exported["ModifiedOn"] = pd.to_datetime(
    product_catalog_products_clean_exported["ModifiedOn"]
)

# Create the Database-Ready dataset from the exported Clean CSV
product_catalog_products_db_ready = (
    product_catalog_products_clean_exported
    .rename(columns=product_catalog_column_mapping)
    .copy()
)

# ---------------------------------------------------------
# Prepare Decimal-Compatible Numeric Fields
# ---------------------------------------------------------

decimal_columns = [
    "cost_price",
    "selling_price",
    "weight_kg"
]

for column in decimal_columns:
    product_catalog_products_db_ready[column] = (
        product_catalog_products_db_ready[column]
        .apply(Decimal)
    )

print("Product Catalog Database-Ready Dataset Created Successfully.")
print("=" * 80)

print("\nSource: Verified Exported Clean CSV")

print("\nDatabase-Ready Dataset Shape:")
print(product_catalog_products_db_ready.shape)

print("\nDatabase-Ready Column Names:")
print(product_catalog_products_db_ready.columns.tolist())

print("\nDatabase-Ready Data Types:")
print(product_catalog_products_db_ready.dtypes)

print("\nDatabase-Ready Dataset:")
display(product_catalog_products_db_ready)

Product Catalog Database-Ready Dataset Created Successfully.
================================================================================

Source: Verified Exported Clean CSV

Database-Ready Dataset Shape:
(15, 15)

Database-Ready Column Names:
['product_id', 'sku', 'product_name', 'product_description', 'category_id', 'supplier_id', 'cost_price', 'selling_price', 'weight_kg', 'warranty_months', 'is_active', 'created_date', 'created_by', 'updated_date', 'updated_by']

Database-Ready Data Types:
product_id                     object
sku                            object
product_name                   object
product_description            object
category_id                    object
supplier_id                    object
cost_price                     object
selling_price                  object
weight_kg                      object
warranty_months                 int64
is_active                        bool
created_date           datetime64[ns]
created_by                     object
updated_date           datetime64[ns]
updated_by                     object
dtype: object

Database-Ready Dataset:

   product_id      sku           product_name               product_description category_id supplier_id cost_price selling_price                                                  weight_kg  warranty_months  is_active created_date created_by updated_date updated_by
0       P0001  LAP-001       Dell Inspiron 15           15-inch business laptop      CAT001      SUP001       2100          2499                                                       1.75               24       True   2026-07-01      admin   2026-07-15      admin
1       P0002  LAP-002       Lenovo IdeaPad 5      Everyday productivity laptop      CAT001      SUP002       1800          2199      1.649999999999999911182158029987476766109466552734375               24       True   2026-07-01      admin   2026-07-15      admin
2       P0003  LAP-003        ASUS TUF Gaming                     Gaming laptop      CAT001      SUP003       3200          3899       2.20000000000000017763568394002504646778106689453125               24       True   2026-07-01      admin   2026-07-15      admin
3       P0004  PHN-001     Samsung Galaxy A55              Mid-range smartphone      CAT002      SUP004       1050          1399  0.2099999999999999922284388276239042170345783233642578125               12       True   2026-07-01      admin   2026-07-15      admin
4       P0005  PHN-002              iPhone 15                  Apple smartphone      CAT002      SUP005       2600          2999  0.1700000000000000122124532708767219446599483489990234375               12       True   2026-07-01      admin   2026-07-15      admin
5       P0006  PHN-003         Google Pixel 9                Android smartphone      CAT002      SUP003       2500          2899   0.200000000000000011102230246251565404236316680908203125               12       True   2026-07-01      admin   2026-07-15      admin
6       P0007  TAB-001               iPad Air                      Apple tablet      CAT003      SUP005       2200          2599   0.460000000000000019984014443252817727625370025634765625               12       True   2026-07-01      admin   2026-07-15      admin
7       P0008  TAB-002  Samsung Galaxy Tab S9                    Android tablet      CAT003      SUP004       2400          2899                                                        0.5               12       True   2026-07-01      admin   2026-07-15      admin
8       P0009  MON-001        Dell 24 Monitor          24-inch business monitor      CAT004      SUP001        500           699      3.100000000000000088817841970012523233890533447265625               12       True   2026-07-01      admin   2026-07-15      admin
9       P0010  MON-002        LG UltraWide 34         34-inch ultrawide monitor      CAT004      SUP006       1250          1599       6.20000000000000017763568394002504646778106689453125               24       True   2026-07-01      admin   2026-07-15      admin
10      P0011  ACC-001  Logitech MX Master 3S                    Wireless mouse      CAT005      SUP007        280           399    0.14000000000000001332267629550187848508358001708984375               12       True   2026-07-01      admin   2026-07-15      admin
11      P0012  ACC-002            Keychron K2               Mechanical keyboard      CAT005      SUP007        300           449    0.83999999999999996891375531049561686813831329345703125               12       True   2026-07-01      admin   2026-07-15      admin
12      P0013  ACC-003        Anker USB-C Hub            USB-C connectivity hub      CAT005      SUP004        120           179  0.1499999999999999944488848768742172978818416595458984375               12       True   2026-07-01      admin   2026-07-15      admin
13      P0014  NET-001  TP-Link AX3000 Router                    Wi-Fi 6 router      CAT006      SUP006        320           499     0.6999999999999999555910790149937383830547332763671875               24       True   2026-07-01      admin   2026-07-15      admin
14      P0015  NET-002  Ubiquiti Access Point  Enterprise wireless access point      CAT006      SUP003        520           699   0.409999999999999975575093458246556110680103302001953125               24       True   2026-07-01      admin   2026-07-15      admin

## 5.3 Database-Ready Validation

Validate the Product Catalog Database-Ready DataFrame before

PostgreSQL loading.

This validation confirms that:

* The row count is preserved from the verified Clean CSV.

* All expected target columns are present.

* Target columns are in the approved order.

* The source-to-target mapping is complete.

* No undocumented source columns were lost.

* Required fields do not contain NULL values.

* The primary key is unique and does not contain NULL values.

* The dataset is prepared for PostgreSQL table verification and loading.

In [15]:
# =========================================================
# 5.3 Database-Ready Validation
# =========================================================

print("Product Catalog Database-Ready Validation")
print("=" * 80)

# ---------------------------------------------------------
# 1. Row Count Validation
# ---------------------------------------------------------

print("\n1. Row Count Validation")

clean_csv_row_count = len(product_catalog_products_clean_exported)
database_ready_row_count = len(product_catalog_products_db_ready)

row_count_match = (
    clean_csv_row_count == database_ready_row_count
)

print("Verified Clean CSV rows:", clean_csv_row_count)
print("Database-Ready rows:", database_ready_row_count)
print("Row counts match:", row_count_match)

# ---------------------------------------------------------
# 2. Expected Target Column Validation
# ---------------------------------------------------------

print("\n2. Expected Target Column Validation")

expected_target_columns = list(
    product_catalog_column_mapping.values()
)

actual_target_columns = (
    product_catalog_products_db_ready.columns.tolist()
)

target_columns_match = (
    expected_target_columns == actual_target_columns
)

print("Expected target columns:")
print(expected_target_columns)

print("\nActual Database-Ready columns:")
print(actual_target_columns)

print("\nColumns and order match:",
      target_columns_match)

# ---------------------------------------------------------
# 3. Mapping Completeness Validation
# ---------------------------------------------------------

print("\n3. Mapping Completeness Validation")

source_columns = (
    product_catalog_products_clean_exported.columns.tolist()
)

mapping_source_columns = list(
    product_catalog_column_mapping.keys()
)

mapping_complete = (
    source_columns == mapping_source_columns
)

print("Source columns match mapping definition:",
      mapping_complete)

print("Source columns not mapped:",
      sorted(set(source_columns) - set(mapping_source_columns)))

print("Unexpected mapping source columns:",
      sorted(set(mapping_source_columns) - set(source_columns)))

# ---------------------------------------------------------
# 4. Required Field Validation
# ---------------------------------------------------------

print("\n4. Required Field Validation")

null_counts = (
    product_catalog_products_db_ready.isnull().sum()
)

print(null_counts)

required_fields_valid = (
    null_counts.sum() == 0
)

print("\nRows with NULL required values:",
      null_counts.sum())

print("Required field validation passed:",
      required_fields_valid)

# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

print("\n5. Primary Key Validation")

duplicate_primary_keys = (
    product_catalog_products_db_ready["product_id"]
    .duplicated()
    .sum()
)

null_primary_keys = (
    product_catalog_products_db_ready["product_id"]
    .isnull()
    .sum()
)

primary_key_valid = (
    duplicate_primary_keys == 0
    and null_primary_keys == 0
)

print("Duplicate Primary Keys:",
      duplicate_primary_keys)

print("NULL Primary Keys:",
      null_primary_keys)

print("Primary Key validation passed:",
      primary_key_valid)

# ---------------------------------------------------------
# 6. Overall Database-Ready Validation
# ---------------------------------------------------------

database_ready_validation_passed = (
    row_count_match
    and target_columns_match
    and mapping_complete
    and required_fields_valid
    and primary_key_valid
)

print("\n6. Database-Ready Validation Summary")
print("=" * 80)

print("Database-Ready validation passed:",
      database_ready_validation_passed)

Product Catalog Database-Ready Validation
================================================================================

1. Row Count Validation
Verified Clean CSV rows: 15
Database-Ready rows: 15
Row counts match: True

2. Expected Target Column Validation
Expected target columns:
['product_id', 'sku', 'product_name', 'product_description', 'category_id', 'supplier_id', 'cost_price', 'selling_price', 'weight_kg', 'warranty_months', 'is_active', 'created_date', 'created_by', 'updated_date', 'updated_by']

Actual Database-Ready columns:
['product_id', 'sku', 'product_name', 'product_description', 'category_id', 'supplier_id', 'cost_price', 'selling_price', 'weight_kg', 'warranty_months', 'is_active', 'created_date', 'created_by', 'updated_date', 'updated_by']

Columns and order match: True

3. Mapping Completeness Validation
Source columns match mapping definition: True
Source columns not mapped: []
Unexpected mapping source columns: []

4. Required Field Validation
product_id             0
sku                    0
product_name           0
product_description    0
category_id            0
supplier_id            0
cost_price             0
selling_price          0
weight_kg              0
warranty_months        0
is_active              0
created_date           0
created_by             0
updated_date           0
updated_by             0
dtype: int64

Rows with NULL required values: 0
Required field validation passed: True

5. Primary Key Validation
Duplicate Primary Keys: 0
NULL Primary Keys: 0
Primary Key validation passed: True

6. Database-Ready Validation Summary
================================================================================
Database-Ready validation passed: True

# =========================================================
# SECTION 6 — PostgreSQL
# =========================================================

Connect to PostgreSQL and confirm that the ETL notebook is connected to

the correct database and PostgreSQL environment.

No table changes or data loading are performed in this step.

## 6.1 Connect

Establish a PostgreSQL connection for the Product Catalog ETL

process.

Confirm that:

* The PostgreSQL connection is successful.

* The correct database is connected.

* The correct PostgreSQL user is connected.

* The target schema is available.

No records are inserted during this step.

In [16]:
# =========================================================
# 6.1 Connect to PostgreSQL
# =========================================================

import psycopg2
from getpass import getpass


# ---------------------------------------------------------
# PostgreSQL Connection Configuration
# ---------------------------------------------------------

DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "lj_dev_commerce"
DB_USER = "postgres"

DB_PASSWORD = getpass("Enter PostgreSQL password: ")


# ---------------------------------------------------------
# Connect to PostgreSQL
# ---------------------------------------------------------

try:
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD
    )

    cursor = conn.cursor()

    print("PostgreSQL connection successful.")
    print("Database:", DB_NAME)
    print("Host:", DB_HOST)
    print("Port:", DB_PORT)

except Exception as e:
    print("PostgreSQL connection failed.")
    print("Error:", e)

PostgreSQL connection successful.
Database: lj_dev_commerce
Host: localhost
Port: 5432

## 6.2 Prepare / Create Target Table

Check whether the approved Product Catalog PostgreSQL target table

already exists before creating or modifying anything.

Target:

Schema: commerce

Table: product

The table must not be recreated blindly. Its existence and approved

database design must be confirmed first.

In [17]:
# =========================================================
# 6.2 Prepare / Create Target Table
# =========================================================

target_schema = "commerce"
target_table = "product"

# Check whether the target table already exists
cursor.execute("""
    SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = %s
          AND table_name = %s
    );
""", (target_schema, target_table))

table_exists = cursor.fetchone()[0]

print("Product Catalog Target Table Check")
print("=" * 80)

print("Schema:", target_schema)
print("Table:", target_table)
print("Table exists:", table_exists)

if table_exists:
    print("\nTarget table already exists.")
    print("The table will not be recreated.")
else:
    print("\nTarget table does not exist.")
    print("The approved database design must be used before creating it.")

Product Catalog Target Table Check
================================================================================
Schema: commerce
Table: product
Table exists: True

Target table already exists.
The table will not be recreated.

## 6.2.1 Create Product Catalog Table

The `commerce.product` table does not currently exist.

This section creates the Product Catalog PostgreSQL target table based

on the approved LJ Dev Commerce Product Data Dictionary.

Key design decisions:

- `product_id` is the Primary Key.

- All required Data Dictionary fields use `NOT NULL`.

- `category_id`, `supplier_id`, and `weight_kg` are optional and
  therefore allow `NULL`.

- `category_id` and `supplier_id` are Foreign Keys based on the
  approved Product database relationships.

- `is_active` uses the PostgreSQL `BOOLEAN` datatype.

- `created_date` and `updated_date` use the PostgreSQL `TIMESTAMP`
  datatype.

- `cost_price`, `selling_price`, and `weight_kg` use the PostgreSQL
  `DECIMAL` datatype.

In [32]:
# =========================================================
# 6.2.1 Create Product Catalog Table
# =========================================================

create_product_catalog_table_query = """
CREATE TABLE commerce.product (

    product_id TEXT PRIMARY KEY,

    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    product_description TEXT NOT NULL,

    category_id TEXT,
    supplier_id TEXT,

    cost_price DECIMAL NOT NULL,
    selling_price DECIMAL NOT NULL,

    weight_kg DECIMAL,

    warranty_months INTEGER NOT NULL,

    is_active BOOLEAN NOT NULL,

    created_date TIMESTAMP NOT NULL,
    created_by TEXT NOT NULL,

    updated_date TIMESTAMP NOT NULL,
    updated_by TEXT NOT NULL,

    FOREIGN KEY (category_id)
        REFERENCES commerce.category(category_id),

    FOREIGN KEY (supplier_id)
        REFERENCES commerce.supplier(supplier_id)

);
"""

try:
    cursor.execute(create_product_catalog_table_query)
    conn.commit()

    print("Product Catalog table created successfully.")
    print("Table: commerce.product")

except Exception as e:
    conn.rollback()

    print("Product Catalog table creation failed.")
    print("Error:", e)

Product Catalog table created successfully.
Table: commerce.product

## 6.3 Verify Product Catalog Table Structure

Verify the actual PostgreSQL structure of the

`commerce.product` table after creation.

Confirm:

- Column names

- Column order

- PostgreSQL data types

- NULL / NOT NULL rules

- Default values

The actual PostgreSQL table structure will be reviewed against the

approved Product Catalog Data Dictionary before records are loaded.

In [18]:
# =========================================================
# 6.3 Verify Product Catalog Table Structure
# =========================================================

verify_product_catalog_table_query = """
SELECT
    ordinal_position,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'commerce'
  AND table_name = 'product'
ORDER BY ordinal_position;
"""

try:
    cursor.execute(verify_product_catalog_table_query)

    table_structure = cursor.fetchall()

    print("Product Catalog Table Structure")
    print("=" * 80)

    print(
        f"{'Position':<10}"
        f"{'Column Name':<25}"
        f"{'Data Type':<25}"
        f"{'Nullable':<12}"
        f"{'Default'}"
    )

    print("-" * 100)

    for row in table_structure:
        print(
            f"{row[0]:<10}"
            f"{row[1]:<25}"
            f"{row[2]:<25}"
            f"{row[3]:<12}"
            f"{row[4]}"
        )

except Exception as e:
    print("Product Catalog table structure verification failed.")
    print("Error:", e)

Product Catalog Table Structure
================================================================================
Position  Column Name              Data Type                Nullable    Default
----------------------------------------------------------------------------------------------------
1         product_id               text                     NO          None
2         sku                      text                     NO          None
3         product_name             text                     NO          None
4         product_description      text                     NO          None
5         category_id              text                     YES         None
6         supplier_id              text                     YES         None
7         cost_price               numeric                  NO          None
8         selling_price            numeric                  NO          None
9         weight_kg                numeric                  YES         None
10        warranty_months          integer                  NO          None
11        is_active                boolean                  NO          None
12        created_date             timestamp without time zoneNO          None
13        created_by               text                     NO          None
14        updated_date             timestamp without time zoneNO          None
15        updated_by               text                     NO          None

## 6.4 Verify Keys, Relationships & Load Dependencies

Verify the applicable keys, relationships, and load dependencies before

loading Product Catalog records into PostgreSQL.

Confirm:

- `product_id` is the Primary Key.

- `category_id` references the approved Category parent table.

- `supplier_id` references the approved Supplier parent table.

- Required parent/master records are available before loading Product
  Catalog records.

- The dataset follows the approved project ETL load order.

Only applicable checks are performed for this dataset.

In [19]:
# =========================================================
# 6.4 Verify Keys, Relationships & Load Dependencies
# =========================================================

print("Product Catalog Keys, Relationships & Load Dependency Review")
print("=" * 80)

# ---------------------------------------------------------
# 1. Primary Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'product'
      AND tc.constraint_type = 'PRIMARY KEY';
""")

primary_keys = cursor.fetchall()

print("\n1. Primary Key")
print(primary_keys)

primary_key_valid = (
    len(primary_keys) == 1
    and primary_keys[0][1] == "product_id"
)

print("Primary Key validation passed:", primary_key_valid)


# ---------------------------------------------------------
# 2. Foreign Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name,
        ccu.table_schema AS referenced_schema,
        ccu.table_name AS referenced_table,
        ccu.column_name AS referenced_column
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
        ON ccu.constraint_name = tc.constraint_name
        AND ccu.table_schema = tc.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'product'
      AND tc.constraint_type = 'FOREIGN KEY'
    ORDER BY kcu.column_name;
""")

foreign_keys = cursor.fetchall()

print("\n2. Foreign Keys")
print(foreign_keys)

expected_foreign_key_columns = {
    "category_id",
    "supplier_id"
}

actual_foreign_key_columns = {
    row[1] for row in foreign_keys
}

foreign_keys_valid = (
    actual_foreign_key_columns
    == expected_foreign_key_columns
)

print("Expected Foreign Key columns:",
      expected_foreign_key_columns)

print("Actual Foreign Key columns:",
      actual_foreign_key_columns)

print("Foreign Key validation passed:",
      foreign_keys_valid)


# ---------------------------------------------------------
# 3. Load Dependency Review
# ---------------------------------------------------------

print("\n3. Load Dependency Review")

load_dependency_ready = (
    primary_key_valid
    and foreign_keys_valid
)

print("Primary Key ready:", primary_key_valid)

print("Foreign Key dependencies ready:",
      foreign_keys_valid)


# ---------------------------------------------------------
# 4. Overall Load Dependency Status
# ---------------------------------------------------------

print("\n4. Overall Load Dependency Status")
print("=" * 80)

print("Product Catalog is ready for data loading:",
      load_dependency_ready)

Product Catalog Keys, Relationships & Load Dependency Review
================================================================================

1. Primary Key
[('product_catalog_pkey', 'product_id')]
Primary Key validation passed: True

2. Foreign Keys
[('product_catalog_category_id_fkey', 'category_id', 'commerce', 'category', 'category_id'), ('product_catalog_supplier_id_fkey', 'supplier_id', 'commerce', 'supplier', 'supplier_id')]
Expected Foreign Key columns: {'supplier_id', 'category_id'}
Actual Foreign Key columns: {'supplier_id', 'category_id'}
Foreign Key validation passed: True

3. Load Dependency Review
Primary Key ready: True
Foreign Key dependencies ready: True

4. Overall Load Dependency Status
================================================================================
Product Catalog is ready for data loading: True

## 6.5 Insert Product Catalog Records

Load the validated Product Catalog database-ready dataset into the

verified `commerce.product` PostgreSQL table.

Before inserting records:

- Confirm the target table is currently empty.

- Confirm the database-ready row count.

- Insert only the validated database-ready records.

- Use an explicit column list matching the approved target structure.

- Commit the transaction only after successful insertion.

No transformations are performed during the database loading step.

In [20]:
# =========================================================
# 6.5 Insert Product Catalog Records
# =========================================================

# ---------------------------------------------------------
# 1. Check Current Target Table Row Count
# ---------------------------------------------------------

cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.product;
""")

existing_row_count = cursor.fetchone()[0]

print("Product Catalog Database Load")
print("=" * 80)

print("\n1. Current Target Table Status")
print("Existing rows:", existing_row_count)


# ---------------------------------------------------------
# 2. Confirm Database-Ready Dataset
# ---------------------------------------------------------

source_row_count = len(product_catalog_products_db_ready)

print("\n2. Database-Ready Dataset")
print("Rows ready for loading:", source_row_count)


# ---------------------------------------------------------
# 3. Prevent Accidental Duplicate Load
# ---------------------------------------------------------

if existing_row_count > 0:

    print("\n3. Duplicate Load Protection")
    print("Target table already contains records.")
    print("No records were inserted.")

else:

    # -----------------------------------------------------
    # 4. Prepare Records for PostgreSQL
    # -----------------------------------------------------

    records_to_insert = [
        tuple(row)
        for row in product_catalog_products_db_ready[
            [
                "product_id",
                "sku",
                "product_name",
                "product_description",
                "category_id",
                "supplier_id",
                "cost_price",
                "selling_price",
                "weight_kg",
                "warranty_months",
                "is_active",
                "created_date",
                "created_by",
                "updated_date",
                "updated_by"
            ]
        ].itertuples(index=False, name=None)
    ]


    # -----------------------------------------------------
    # 5. Insert Records
    # -----------------------------------------------------

    insert_product_catalog_query = """
    INSERT INTO commerce.product (
        product_id,
        sku,
        product_name,
        product_description,
        category_id,
        supplier_id,
        cost_price,
        selling_price,
        weight_kg,
        warranty_months,
        is_active,
        created_date,
        created_by,
        updated_date,
        updated_by
    )
    VALUES (
        %s, %s, %s, %s, %s,
        %s, %s, %s, %s, %s,
        %s, %s, %s, %s, %s
    );
    """

    try:
        cursor.executemany(
            insert_product_catalog_query,
            records_to_insert
        )

        conn.commit()

        print("\n3. Insert Result")
        print("Product Catalog records inserted successfully.")
        print("Rows inserted:", len(records_to_insert))

    except Exception as e:
        conn.rollback()

        print("\n3. Insert Result")
        print("Product Catalog record insertion failed.")
        print("Error:", e)

Product Catalog Database Load
================================================================================

1. Current Target Table Status
Existing rows: 0

2. Database-Ready Dataset
Rows ready for loading: 15

3. Insert Result
Product Catalog records inserted successfully.
Rows inserted: 15

## 6.6 Validate Product Catalog Row Count

Compare the number of records in the Database-Ready dataset with the

number of records currently stored in the PostgreSQL

`commerce.product` table.

This confirms that the intended load scope was completed successfully.

No additional integrity checks are performed in this section.

In [21]:
# =========================================================
# 6.6 Validate Product Catalog Row Count
# =========================================================

# Expected row count from the Database-Ready dataset
db_ready_row_count = len(product_catalog_products_db_ready)


# Actual row count from PostgreSQL
cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.product;
""")

postgresql_row_count = cursor.fetchone()[0]


# Validation result
row_count_match = (
    db_ready_row_count == postgresql_row_count
)


print("Product Catalog Row Count Validation")
print("=" * 80)

print("\n1. Database-Ready Dataset Row Count")
print("Rows:", db_ready_row_count)

print("\n2. PostgreSQL Table Row Count")
print("Rows:", postgresql_row_count)

print("\n3. Row Count Validation")
print("Row counts match:", row_count_match)

print("\n4. Validation Summary")
print("=" * 80)

if row_count_match:
    print("Product Catalog row count validation passed.")
else:
    print("Product Catalog row count validation failed.")

Product Catalog Row Count Validation
================================================================================

1. Database-Ready Dataset Row Count
Rows: 15

2. PostgreSQL Table Row Count
Rows: 15

3. Row Count Validation
Row counts match: True

4. Validation Summary
================================================================================
Product Catalog row count validation passed.

## 6.7 Retrieve Product Catalog Records

Retrieve the Product Catalog records directly from PostgreSQL to confirm

that the loaded data is stored correctly.

Review:

- Loaded records

- Column values

- Cost and selling price values

- Weight and warranty values

- Boolean values

- Date values

- Overall record formatting

This step confirms that records can be successfully retrieved from the

PostgreSQL target table.

In [22]:
# =========================================================
# 6.7 Retrieve Product Catalog Records
# =========================================================

retrieve_product_catalog_query = """
SELECT
    product_id,
    sku,
    product_name,
    product_description,
    category_id,
    supplier_id,
    cost_price,
    selling_price,
    weight_kg,
    warranty_months,
    is_active,
    created_date,
    created_by,
    updated_date,
    updated_by
FROM commerce.product
ORDER BY product_id;
"""

try:
    cursor.execute(retrieve_product_catalog_query)

    product_catalog_records = cursor.fetchall()

    print("Product Catalog Records Retrieved from PostgreSQL")
    print("=" * 80)

    print("Records retrieved:", len(product_catalog_records))

    # Retrieve column names from the query result
    column_names = [
        description[0]
        for description in cursor.description
    ]

    # Create a DataFrame for readable review
    product_catalog_postgresql = pd.DataFrame(
        product_catalog_records,
        columns=column_names
    )

    print("\nRetrieved Product Catalog Records:")
    display(product_catalog_postgresql)

except Exception as e:
    print("Product Catalog record retrieval failed.")
    print("Error:", e)

Product Catalog Records Retrieved from PostgreSQL
================================================================================
Records retrieved: 15

Retrieved Product Catalog Records:

   product_id      sku           product_name               product_description category_id supplier_id cost_price selling_price                                                  weight_kg  warranty_months  is_active created_date created_by updated_date updated_by
0       P0001  LAP-001       Dell Inspiron 15           15-inch business laptop      CAT001      SUP001       2100          2499                                                       1.75               24       True   2026-07-01      admin   2026-07-15      admin
1       P0002  LAP-002       Lenovo IdeaPad 5      Everyday productivity laptop      CAT001      SUP002       1800          2199      1.649999999999999911182158029987476766109466552734375               24       True   2026-07-01      admin   2026-07-15      admin
2       P0003  LAP-003        ASUS TUF Gaming                     Gaming laptop      CAT001      SUP003       3200          3899       2.20000000000000017763568394002504646778106689453125               24       True   2026-07-01      admin   2026-07-15      admin
3       P0004  PHN-001     Samsung Galaxy A55              Mid-range smartphone      CAT002      SUP004       1050          1399  0.2099999999999999922284388276239042170345783233642578125               12       True   2026-07-01      admin   2026-07-15      admin
4       P0005  PHN-002              iPhone 15                  Apple smartphone      CAT002      SUP005       2600          2999  0.1700000000000000122124532708767219446599483489990234375               12       True   2026-07-01      admin   2026-07-15      admin
5       P0006  PHN-003         Google Pixel 9                Android smartphone      CAT002      SUP003       2500          2899   0.200000000000000011102230246251565404236316680908203125               12       True   2026-07-01      admin   2026-07-15      admin
6       P0007  TAB-001               iPad Air                      Apple tablet      CAT003      SUP005       2200          2599   0.460000000000000019984014443252817727625370025634765625               12       True   2026-07-01      admin   2026-07-15      admin
7       P0008  TAB-002  Samsung Galaxy Tab S9                    Android tablet      CAT003      SUP004       2400          2899                                                        0.5               12       True   2026-07-01      admin   2026-07-15      admin
8       P0009  MON-001        Dell 24 Monitor          24-inch business monitor      CAT004      SUP001        500           699      3.100000000000000088817841970012523233890533447265625               12       True   2026-07-01      admin   2026-07-15      admin
9       P0010  MON-002        LG UltraWide 34         34-inch ultrawide monitor      CAT004      SUP006       1250          1599       6.20000000000000017763568394002504646778106689453125               24       True   2026-07-01      admin   2026-07-15      admin
10      P0011  ACC-001  Logitech MX Master 3S                    Wireless mouse      CAT005      SUP007        280           399    0.14000000000000001332267629550187848508358001708984375               12       True   2026-07-01      admin   2026-07-15      admin
11      P0012  ACC-002            Keychron K2               Mechanical keyboard      CAT005      SUP007        300           449    0.83999999999999996891375531049561686813831329345703125               12       True   2026-07-01      admin   2026-07-15      admin
12      P0013  ACC-003        Anker USB-C Hub            USB-C connectivity hub      CAT005      SUP004        120           179  0.1499999999999999944488848768742172978818416595458984375               12       True   2026-07-01      admin   2026-07-15      admin
13      P0014  NET-001  TP-Link AX3000 Router                    Wi-Fi 6 router      CAT006      SUP006        320           499     0.6999999999999999555910790149937383830547332763671875               24       True   2026-07-01      admin   2026-07-15      admin
14      P0015  NET-002  Ubiquiti Access Point  Enterprise wireless access point      CAT006      SUP003        520           699   0.409999999999999975575093458246556110680103302001953125               24       True   2026-07-01      admin   2026-07-15      admin

## 6.8 Source → Database Reconciliation

Compare the validated Product Catalog Database-Ready dataset with the

records retrieved directly from PostgreSQL.

Validate:

- Row counts

- Column names

- Column order

- Product IDs

- Record-level values

This confirms that the Database-Ready dataset was loaded into PostgreSQL

without unintended changes.

In [23]:
# =========================================================
# 6.8 Source → Database Reconciliation
# =========================================================

# ---------------------------------------------------------
# 1. Prepare Source Dataset
# ---------------------------------------------------------

product_catalog_source_reconciliation = (
    product_catalog_products_db_ready.copy()
    .sort_values("product_id")
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 2. Prepare PostgreSQL Dataset
# ---------------------------------------------------------

product_catalog_postgresql_reconciliation = (
    product_catalog_postgresql.copy()
    .sort_values("product_id")
    .reset_index(drop=True)
)


print("Product Catalog Source → Database Reconciliation")
print("=" * 80)


# ---------------------------------------------------------
# 3. Row Count Validation
# ---------------------------------------------------------

source_row_count = len(product_catalog_source_reconciliation)

database_row_count = len(
    product_catalog_postgresql_reconciliation
)

row_count_match = (
    source_row_count == database_row_count
)

print("\n1. Row Count Validation")
print("Database-Ready rows:", source_row_count)
print("PostgreSQL rows:", database_row_count)
print("Row counts match:", row_count_match)


# ---------------------------------------------------------
# 4. Column Validation
# ---------------------------------------------------------

source_columns = (
    product_catalog_source_reconciliation.columns.tolist()
)

database_columns = (
    product_catalog_postgresql_reconciliation.columns.tolist()
)

column_match = (
    source_columns == database_columns
)

print("\n2. Column Validation")
print("Columns and order match:", column_match)

if not column_match:
    print("\nDatabase-Ready columns:")
    print(source_columns)

    print("\nPostgreSQL columns:")
    print(database_columns)


# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

source_product_ids = set(
    product_catalog_source_reconciliation["product_id"]
)

database_product_ids = set(
    product_catalog_postgresql_reconciliation["product_id"]
)

primary_key_match = (
    source_product_ids == database_product_ids
)

print("\n3. Product ID Validation")
print("Product IDs match:", primary_key_match)


# ---------------------------------------------------------
# 6. Record-Level Value Validation
# ---------------------------------------------------------

value_match = (
    product_catalog_source_reconciliation.equals(
        product_catalog_postgresql_reconciliation
    )
)

print("\n4. Record-Level Value Validation")
print("All record values match:", value_match)


# ---------------------------------------------------------
# 7. Reconciliation Summary
# ---------------------------------------------------------

reconciliation_passed = (
    row_count_match
    and column_match
    and primary_key_match
    and value_match
)

print("\n5. Source → Database Reconciliation Summary")
print("=" * 80)

print("Source → Database reconciliation passed:",
      reconciliation_passed)

Product Catalog Source → Database Reconciliation
================================================================================

1. Row Count Validation
Database-Ready rows: 15
PostgreSQL rows: 15
Row counts match: True

2. Column Validation
Columns and order match: True

3. Product ID Validation
Product IDs match: True

4. Record-Level Value Validation
All record values match: True

5. Source → Database Reconciliation Summary
================================================================================
Source → Database reconciliation passed: True

## 6.9 Product Catalog Database Integrity Validation

Perform final integrity checks on the loaded

`commerce.product` table.

The checks confirm:

- Primary-key uniqueness

- Required-field integrity

- Duplicate record checks

- Boolean validity

- Product price integrity

- Product weight integrity

- Warranty integrity

- Audit date consistency

These checks provide the final confirmation that the Product Catalog

table is structurally and business-rule compliant after loading.

In [24]:
# =========================================================
# 6.9 Product Catalog Database Integrity Validation
# =========================================================

integrity_query = """
SELECT
    COUNT(*) AS total_rows,

    COUNT(DISTINCT product_id) AS distinct_product_ids,

    COUNT(*) FILTER (
        WHERE product_id IS NULL
    ) AS null_product_ids,

    COUNT(*) FILTER (
        WHERE sku IS NULL
    ) AS null_skus,

    COUNT(*) FILTER (
        WHERE product_name IS NULL
    ) AS null_product_names,

    COUNT(*) FILTER (
        WHERE product_description IS NULL
    ) AS null_product_descriptions,

    COUNT(*) FILTER (
        WHERE cost_price IS NULL
    ) AS null_cost_prices,

    COUNT(*) FILTER (
        WHERE selling_price IS NULL
    ) AS null_selling_prices,

    COUNT(*) FILTER (
        WHERE warranty_months IS NULL
    ) AS null_warranty_months,

    COUNT(*) FILTER (
        WHERE is_active IS NULL
    ) AS null_active_flags,

    COUNT(*) FILTER (
        WHERE created_date IS NULL
    ) AS null_created_dates,

    COUNT(*) FILTER (
        WHERE created_by IS NULL
    ) AS null_created_by,

    COUNT(*) FILTER (
        WHERE updated_date IS NULL
    ) AS null_updated_dates,

    COUNT(*) FILTER (
        WHERE updated_by IS NULL
    ) AS null_updated_by,

    COUNT(*) FILTER (
        WHERE cost_price < 0
    ) AS negative_cost_prices,

    COUNT(*) FILTER (
        WHERE selling_price < 0
    ) AS negative_selling_prices,

    COUNT(*) FILTER (
        WHERE weight_kg < 0
    ) AS negative_weights,

    COUNT(*) FILTER (
        WHERE warranty_months < 0
    ) AS negative_warranty_months,

    COUNT(*) FILTER (
        WHERE updated_date < created_date
    ) AS invalid_audit_date_order

FROM commerce.product;
"""

try:
    cursor.execute(integrity_query)

    integrity_result = cursor.fetchone()

    print("Product Catalog Database Integrity Validation")
    print("=" * 80)

    print("\n1. Primary Key Integrity")
    print("Total rows:", integrity_result[0])
    print("Distinct product IDs:", integrity_result[1])
    print("NULL product IDs:", integrity_result[2])

    print("\n2. Required Field Integrity")
    print("NULL SKUs:", integrity_result[3])
    print("NULL product names:", integrity_result[4])
    print("NULL product descriptions:", integrity_result[5])
    print("NULL cost prices:", integrity_result[6])
    print("NULL selling prices:", integrity_result[7])
    print("NULL warranty months:", integrity_result[8])
    print("NULL active flags:", integrity_result[9])
    print("NULL created dates:", integrity_result[10])
    print("NULL created by:", integrity_result[11])
    print("NULL updated dates:", integrity_result[12])
    print("NULL updated by:", integrity_result[13])

    print("\n3. Product Value Integrity")
    print("Negative cost prices:", integrity_result[14])
    print("Negative selling prices:", integrity_result[15])
    print("Negative weights:", integrity_result[16])
    print("Negative warranty months:", integrity_result[17])

    print("\n4. Audit Date Integrity")
    print(
        "Updated date earlier than created date:",
        integrity_result[18]
    )

    # -----------------------------------------------------
    # Final Validation Result
    # -----------------------------------------------------

    integrity_passed = (
        integrity_result[0] == integrity_result[1]
        and integrity_result[2] == 0
        and integrity_result[3] == 0
        and integrity_result[4] == 0
        and integrity_result[5] == 0
        and integrity_result[6] == 0
        and integrity_result[7] == 0
        and integrity_result[8] == 0
        and integrity_result[9] == 0
        and integrity_result[10] == 0
        and integrity_result[11] == 0
        and integrity_result[12] == 0
        and integrity_result[13] == 0
        and integrity_result[14] == 0
        and integrity_result[15] == 0
        and integrity_result[16] == 0
        and integrity_result[17] == 0
        and integrity_result[18] == 0
    )

    print("\n5. Database Integrity Validation Summary")
    print("=" * 80)

    print(
        "Product Catalog database integrity passed:",
        integrity_passed
    )

except Exception as e:
    print("Product Catalog database integrity validation failed.")
    print("Error:", e)

Product Catalog Database Integrity Validation
================================================================================

1. Primary Key Integrity
Total rows: 15
Distinct product IDs: 15
NULL product IDs: 0

2. Required Field Integrity
NULL SKUs: 0
NULL product names: 0
NULL product descriptions: 0
NULL cost prices: 0
NULL selling prices: 0
NULL warranty months: 0
NULL active flags: 0
NULL created dates: 0
NULL created by: 0
NULL updated dates: 0
NULL updated by: 0

3. Product Value Integrity
Negative cost prices: 0
Negative selling prices: 0
Negative weights: 0
Negative warranty months: 0

4. Audit Date Integrity
Updated date earlier than created date: 0

5. Database Integrity Validation Summary
================================================================================
Product Catalog database integrity passed: True

## 6.10 Close PostgreSQL Connection

Close the PostgreSQL cursor and database connection after all

Product Catalog loading and validation steps are complete.

Confirm that PostgreSQL resources are closed cleanly.

In [26]:
# =========================================================
# 6.10 Close PostgreSQL Connection
# =========================================================

try:
    if cursor is not None and not cursor.closed:
        cursor.close()

    if conn is not None and conn.closed == 0:
        conn.close()

    print("PostgreSQL resources closed successfully.")
    print("Cursor closed:", cursor.closed)
    print("Connection closed:", conn.closed != 0)

except Exception as e:
    print("PostgreSQL resource closure failed.")
    print("Error:", e)

PostgreSQL resources closed successfully.
Cursor closed: True
Connection closed: True