# LJ Dev Commerce - Phase 4

# VII. Sales Order ETL

# =========================================================
# SECTION 1 — EXTRACT, SET UP, PROFILE, FINDINGS & DECISIONS
# =========================================================

# 1.1 Setup

This section prepares the notebook environment for the Sales Order ETL process.

The setup includes:

* Importing the required Python libraries.
* Configuring Pandas display options.
* Preparing the notebook environment for the Sales Order ETL workflow.

No dataset is loaded, modified, cleaned, or transformed in this section.

In [27]:
# =========================================================
# 1.1 Setup
# =========================================================

import pandas as pd
import numpy as np

# =========================================================
# Display Configuration
# =========================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)

In [28]:

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

## 1.2 Load and Preserve Sales Order Raw Datasets

Load the raw Sales Order source files from Shopify, Amazon UAE, and Noon and preserve each as its original source dataset.

The raw datasets must not be modified during the ETL process. Any profiling, cleaning, transformation, consolidation, or validation work will use separate DataFrame copies where appropriate.

For this section, the three source datasets will remain separate. They will not be consolidated or transformed during the loading process.

In [29]:
# =========================================================
# 1.2 Load and Preserve Sales Order Raw Datasets
# =========================================================

# Define the raw Sales Order dataset paths
shopify_orders_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\06_Ecommerce_Shopify\shopify_orders.csv"
)

amazon_orders_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\07_Ecommerce_Amazon_UAE\amazon_orders.csv"
)

noon_orders_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\08_Ecommerce_Noon\noon_orders.csv"
)


# Load the raw source datasets
shopify_orders_raw = pd.read_csv(
    shopify_orders_raw_path
)

amazon_orders_raw = pd.read_csv(
    amazon_orders_raw_path
)

noon_orders_raw = pd.read_csv(
    noon_orders_raw_path
)


# Preserve untouched copies of the original raw datasets
shopify_orders_raw_original = (
    shopify_orders_raw.copy(deep=True)
)

amazon_orders_raw_original = (
    amazon_orders_raw.copy(deep=True)
)

noon_orders_raw_original = (
    noon_orders_raw.copy(deep=True)
)


print("Sales Order raw datasets loaded successfully.")
print("Shopify - Rows:", len(shopify_orders_raw))
print("Shopify - Columns:", len(shopify_orders_raw.columns))
print("Shopify - Path:", shopify_orders_raw_path)

print()

print("Amazon UAE - Rows:", len(amazon_orders_raw))
print("Amazon UAE - Columns:", len(amazon_orders_raw.columns))
print("Amazon UAE - Path:", amazon_orders_raw_path)

print()

print("Noon - Rows:", len(noon_orders_raw))
print("Noon - Columns:", len(noon_orders_raw.columns))
print("Noon - Path:", noon_orders_raw_path)

Sales Order raw datasets loaded successfully.
Shopify - Rows: 7
Shopify - Columns: 16
Shopify - Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\06_Ecommerce_Shopify\shopify_orders.csv

Amazon UAE - Rows: 7
Amazon UAE - Columns: 16
Amazon UAE - Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\07_Ecommerce_Amazon_UAE\amazon_orders.csv

Noon - Rows: 6
Noon - Columns: 16
Noon - Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\08_Ecommerce_Noon\noon_orders.csv

## 1.3 Initial Raw Data Inspection

Perform an initial inspection of the untouched Sales Order raw datasets before profiling.

This step establishes the structure, current pandas data types, missing-value counts, and sample records for each source dataset.

No transformations are performed at this stage.

In [30]:
# =========================================================
# 1.3 Initial Raw Data Inspection
# =========================================================

print("Shopify Sales Order Dataset shape:")
print(shopify_orders_raw.shape)


print("\nShopify Column names:")
print(shopify_orders_raw.columns.tolist())


print("\nShopify Current pandas data types:")
print(shopify_orders_raw.dtypes)


print("\nShopify Missing values:")
print(shopify_orders_raw.isnull().sum())


print("\nShopify Sample raw records:")
display(shopify_orders_raw.head())


print("\n\nAmazon UAE Sales Order Dataset shape:")
print(amazon_orders_raw.shape)


print("\nAmazon UAE Column names:")
print(amazon_orders_raw.columns.tolist())


print("\nAmazon UAE Current pandas data types:")
print(amazon_orders_raw.dtypes)


print("\nAmazon UAE Missing values:")
print(amazon_orders_raw.isnull().sum())


print("\nAmazon UAE Sample raw records:")
display(amazon_orders_raw.head())


print("\n\nNoon Sales Order Dataset shape:")
print(noon_orders_raw.shape)


print("\nNoon Column names:")
print(noon_orders_raw.columns.tolist())


print("\nNoon Current pandas data types:")
print(noon_orders_raw.dtypes)


print("\nNoon Missing values:")
print(noon_orders_raw.isnull().sum())


print("\nNoon Sample raw records:")
display(noon_orders_raw.head())

Shopify Sales Order Dataset shape:
(7, 16)

Shopify Column names:
['SourceSystem', 'SourceOrderID', 'SourceOrderIDInternal', 'CustomerCode', 'CampaignCode', 'OrderDate', 'OrderStatus', 'ShipToAddress', 'BillToAddress', 'PaymentMethod', 'OrderGrossAmount', 'OrderNotes', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Shopify Current pandas data types:
SourceSystem              object
SourceOrderID             object
SourceOrderIDInternal     object
CustomerCode              object
CampaignCode              object
OrderDate                 object
OrderStatus               object
ShipToAddress             object
BillToAddress             object
PaymentMethod             object
OrderGrossAmount           int64
OrderNotes               float64
CreatedOn                 object
CreatedByUser             object
ModifiedOn                object
ModifiedByUser            object
dtype: object

Shopify Missing values:
SourceSystem             0
SourceOrderID            0
SourceOrderIDInternal    0
CustomerCode             0
CampaignCode             2
OrderDate                0
OrderStatus              0
ShipToAddress            0
BillToAddress            0
PaymentMethod            0
OrderGrossAmount         0
OrderNotes               7
CreatedOn                0
CreatedByUser            0
ModifiedOn               0
ModifiedByUser           0
dtype: int64

Shopify Sample raw records:

  SourceSystem  SourceOrderID SourceOrderIDInternal CustomerCode CampaignCode   OrderDate OrderStatus              ShipToAddress              BillToAddress     PaymentMethod  OrderGrossAmount  OrderNotes   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0      Shopify  SHOPIFY-SO001                 SO001         C001       CAM001  2026-07-05   Completed         Al Jafiliya, Dubai         Al Jafiliya, Dubai              Visa              3198         NaN  2026-07-05         admin  2026-07-05          admin
1      Shopify  SHOPIFY-SO002                 SO002         C002       CAM004  2026-07-06   Completed             Makati, Manila             Makati, Manila       Credit Card              2199         NaN  2026-07-06         admin  2026-07-06          admin
2      Shopify  SHOPIFY-SO003                 SO003         C003          NaN  2026-07-07   Completed        Dubai Marina, Dubai        Dubai Marina, Dubai  Cash on Delivery              1399         NaN  2026-07-07         admin  2026-07-07          admin
3      Shopify  SHOPIFY-SO004                 SO004         C004       CAM001  2026-07-08    shipped             Al Nahda, Dubai            Al Nahda, Dubai              Visa              4298         NaN  2026-07-08         admin  2026-07-08          admin
4      Shopify  SHOPIFY-SO005                 SO005         C005       CAM002  2026-07-09   Completed  Abu Dhabi City, Abu Dhabi  Abu Dhabi City, Abu Dhabi        Mastercard              3448         NaN  2026-07-09         admin  2026-07-09          admin

Amazon UAE Sales Order Dataset shape:
(7, 16)

Amazon UAE Column names:
['SourceSystem', 'SourceOrderID', 'SourceOrderIDInternal', 'CustomerCode', 'CampaignCode', 'OrderDate', 'OrderStatus', 'ShipToAddress', 'BillToAddress', 'PaymentMethod', 'OrderGrossAmount', 'OrderNotes', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Amazon UAE Current pandas data types:
SourceSystem              object
SourceOrderID             object
SourceOrderIDInternal     object
CustomerCode              object
CampaignCode              object
OrderDate                 object
OrderStatus               object
ShipToAddress             object
BillToAddress             object
PaymentMethod             object
OrderGrossAmount           int64
OrderNotes               float64
CreatedOn                 object
CreatedByUser             object
ModifiedOn                object
ModifiedByUser            object
dtype: object

Amazon UAE Missing values:
SourceSystem             0
SourceOrderID            0
SourceOrderIDInternal    0
CustomerCode             0
CampaignCode             4
OrderDate                0
OrderStatus              0
ShipToAddress            0
BillToAddress            0
PaymentMethod            0
OrderGrossAmount         0
OrderNotes               7
CreatedOn                0
CreatedByUser            0
ModifiedOn               0
ModifiedByUser           0
dtype: int64

Amazon UAE Sample raw records:

  SourceSystem SourceOrderID SourceOrderIDInternal CustomerCode CampaignCode   OrderDate OrderStatus            ShipToAddress            BillToAddress     PaymentMethod  OrderGrossAmount  OrderNotes   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0   Amazon UAE  AMAZON-SO008                 SO008         C008          NaN  2026-07-12   Completed             Deira, Dubai             Deira, Dubai       Credit Card              1599         NaN  2026-07-12         admin  2026-07-12          admin
1   Amazon UAE  AMAZON-SO009                 SO009         C009       CAM001  2026-07-13   Completed         Al Barsha, Dubai         Al Barsha, Dubai              Visa               399         NaN  2026-07-13         admin  2026-07-13          admin
2   Amazon UAE  AMAZON-SO010                 SO010         C010          NaN  2026-07-14   Cancelled  Khalifa City, Abu Dhabi  Khalifa City, Abu Dhabi       Credit Card               449         NaN  2026-07-14         admin  2026-07-14          admin
3   Amazon UAE  AMAZON-SO011                 SO011         C011       CAM004  2026-07-15   Completed         Bur Dubai, Dubai         Bur Dubai, Dubai  Cash on Delivery               499         NaN  2026-07-15         admin  2026-07-15          admin
4   Amazon UAE  AMAZON-SO012                 SO012         C012          NaN  2026-07-16   Completed        Ajman City, Ajman        Ajman City, Ajman              Visa               699         NaN  2026-07-16         admin  2026-07-16          admin

Noon Sales Order Dataset shape:
(6, 16)

Noon Column names:
['SourceSystem', 'SourceOrderID', 'SourceOrderIDInternal', 'CustomerCode', 'CampaignCode', 'OrderDate', 'OrderStatus', 'ShipToAddress', 'BillToAddress', 'PaymentMethod', 'OrderGrossAmount', 'OrderNotes', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Noon Current pandas data types:
SourceSystem              object
SourceOrderID             object
SourceOrderIDInternal     object
CustomerCode              object
CampaignCode              object
OrderDate                 object
OrderStatus               object
ShipToAddress             object
BillToAddress             object
PaymentMethod             object
OrderGrossAmount           int64
OrderNotes               float64
CreatedOn                 object
CreatedByUser             object
ModifiedOn                object
ModifiedByUser            object
dtype: object

Noon Missing values:
SourceSystem             0
SourceOrderID            0
SourceOrderIDInternal    0
CustomerCode             0
CampaignCode             3
OrderDate                0
OrderStatus              0
ShipToAddress            0
BillToAddress            0
PaymentMethod            0
OrderGrossAmount         0
OrderNotes               6
CreatedOn                0
CreatedByUser            0
ModifiedOn               0
ModifiedByUser           0
dtype: int64

Noon Sample raw records:

  SourceSystem SourceOrderID SourceOrderIDInternal CustomerCode CampaignCode   OrderDate OrderStatus        ShipToAddress        BillToAddress     PaymentMethod  OrderGrossAmount  OrderNotes   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0         Noon    NOON-SO015                 SO015         C015       CAM001  2026-07-19     Shipped        Mirdif, Dubai        Mirdif, Dubai              Visa              3598         NaN  2026-07-19         admin  2026-07-19          admin
1         Noon    NOON-SO016                 SO016         C001          NaN  2026-07-20   Completed   Al Jafiliya, Dubai   Al Jafiliya, Dubai              Visa               699         NaN  2026-07-20         admin  2026-07-20          admin
2         Noon    NOON-SO017                 SO017         C002       CAM004  2026-07-21   Completed       Makati, Manila       Makati, Manila       Credit Card               499         NaN  2026-07-21         admin  2026-07-21          admin
3         Noon    NOON-SO018                 SO018         C003          NaN  2026-07-22   Completed  Dubai Marina, Dubai  Dubai Marina, Dubai        Mastercard              3899         NaN  2026-07-22         admin  2026-07-22          admin
4         Noon    NOON-SO019                 SO019         C004       CAM002  2026-07-23     Pending      Al Nahda, Dubai      Al Nahda, Dubai  Cash on Delivery              2199         NaN  2026-07-23         admin  2026-07-23          admin

## 1.4 Data Profiling

Profile the untouched raw Sales Order datasets using the reusable `data_profiler_v1` tool.

The profiler is used to identify potential data-quality issues, semantic field types, missing values, duplicates, formatting inconsistencies, and other detectable anomalies before any cleaning or transformation is performed.

Each source dataset will be profiled separately before any consolidation takes place.

Profiling results are treated as findings for investigation. The profiler does not make business decisions or automatically determine the correct transformation.

In [31]:
# =========================================================
# 1.4 Data Profiling
# =========================================================

import sys
import importlib


# Identify the project root
project_root = Path.cwd().parent


# Add the project root to the Python path if needed
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))


# Import and reload the reusable data profiler
from profiler import data_profiler_v1 as profiler

importlib.reload(profiler)


print("Profiler loaded successfully:")
print(profiler.__file__)


print("\nProfiler configuration:")
print(profiler.DEFAULT_CONFIG)

Profiler loaded successfully:
c:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\profiler\data_profiler_v1.py

Profiler configuration:
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

In [32]:
# Run the complete profiler against the untouched raw Sales Order datasets

shopify_profile_results = profiler.profile_dataset(
    shopify_orders_raw
)

amazon_profile_results = profiler.profile_dataset(
    amazon_orders_raw
)

noon_profile_results = profiler.profile_dataset(
    noon_orders_raw
)


print("\nSales Order profiling completed successfully.")

print("\nShopify profiler sections:")
print(list(shopify_profile_results.keys()))

print("\nAmazon UAE profiler sections:")
print(list(amazon_profile_results.keys()))

print("\nNoon profiler sections:")
print(list(noon_profile_results.keys()))

Sales Order profiling completed successfully.

Shopify profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

Amazon UAE profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

Noon profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

## 1.5 Review Profiling Results

Review the complete Sales Order profiling results before making any transformation decisions.

The automated profiler identifies potential data-quality issues, but the results must be independently reviewed in the context of the Sales Order datasets and LJ Dev Commerce business requirements.

This review examines:

- Automated profiling findings
- Issues requiring independent analyst review
- Potential business-rule decisions
- Issues that may require transformation

Each source dataset will be reviewed separately before any consolidation takes place.

No data is modified during this stage.

In [33]:
# =========================================================
# 1.5 Review Profiling Results
# =========================================================

print("\n" + "=" * 70)
print("SHOPIFY SALES ORDER PROFILING RESULTS")
print("=" * 70)

for section_name, section_result in shopify_profile_results.items():

    print("\n" + "-" * 70)
    print(section_name.upper())
    print("-" * 70)

    print(section_result)


print("\n\n" + "=" * 70)
print("AMAZON UAE SALES ORDER PROFILING RESULTS")
print("=" * 70)

for section_name, section_result in amazon_profile_results.items():

    print("\n" + "-" * 70)
    print(section_name.upper())
    print("-" * 70)

    print(section_result)


print("\n\n" + "=" * 70)
print("NOON SALES ORDER PROFILING RESULTS")
print("=" * 70)

for section_name, section_result in noon_profile_results.items():

    print("\n" + "-" * 70)
    print(section_name.upper())
    print("-" * 70)

    print(section_result)

======================================================================
SHOPIFY SALES ORDER PROFILING RESULTS
======================================================================

----------------------------------------------------------------------
FIELD_TYPES
----------------------------------------------------------------------
SourceSystem             categorical
SourceOrderID             identifier
SourceOrderIDInternal     identifier
CustomerCode              identifier
CampaignCode              identifier
OrderDate                       date
OrderStatus                     text
ShipToAddress                   text
BillToAddress                   text
PaymentMethod                   text
OrderGrossAmount             numeric
OrderNotes                      text
CreatedOn                       date
CreatedByUser            categorical
ModifiedOn                      date
ModifiedByUser           categorical
Name: DetectedFieldType, dtype: object

----------------------------------------------------------------------
DETECTION_DETAILS
----------------------------------------------------------------------
{'SourceSystem': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'SourceOrderID': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SourceOrderIDInternal': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'CustomerCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'CampaignCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'OrderDate': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'OrderStatus': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'ShipToAddress': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'BillToAddress': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'PaymentMethod': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'OrderGrossAmount': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'OrderNotes': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No non-empty values available'}, 'CreatedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'CreatedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'ModifiedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'ModifiedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}}

----------------------------------------------------------------------
GENERAL
----------------------------------------------------------------------
{'rows': 7, 'columns': 16, 'exact_duplicate_rows': 0, 'column_profile':                       DataType DetectedFieldType  MissingCount  MissingPercent  UniqueCount  DuplicateValueCount
SourceSystem            object       categorical             0            0.00            1                    6
SourceOrderID           object        identifier             0            0.00            7                    0
SourceOrderIDInternal   object        identifier             0            0.00            7                    0
CustomerCode            object        identifier             0            0.00            7                    0
CampaignCode            object        identifier             2           28.57            3                    3
OrderDate               object              date             0            0.00            7                    0
OrderStatus             object              text             0            0.00            3                    4
ShipToAddress           object              text             0            0.00            7                    0
BillToAddress           object              text             0            0.00            7                    0
PaymentMethod           object              text             0            0.00            4                    3
OrderGrossAmount         int64           numeric             0            0.00            7                    0
OrderNotes             float64              text             7          100.00            0                    6
CreatedOn               object              date             0            0.00            7                    0
CreatedByUser           object       categorical             0            0.00            1                    6
ModifiedOn              object              date             0            0.00            7                    0
ModifiedByUser          object       categorical             0            0.00            1                    6}

----------------------------------------------------------------------
TEXT
----------------------------------------------------------------------
{'OrderStatus': {'WhitespaceCount': 1, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 7, 'MaximumLength': 9, 'AverageLength': np.float64(8.43)}, 'ShipToAddress': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 14, 'MaximumLength': 25, 'AverageLength': np.float64(18.14)}, 'BillToAddress': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 14, 'MaximumLength': 25, 'AverageLength': np.float64(18.14)}, 'PaymentMethod': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 4, 'MaximumLength': 16, 'AverageLength': np.float64(9.29)}, 'OrderNotes': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 0, 'MaximumLength': 0, 'AverageLength': 0}}

----------------------------------------------------------------------
CATEGORICAL
----------------------------------------------------------------------
{'SourceSystem': {'UniqueCount': 1, 'MostCommonValue': 'Shopify', 'MostCommonCount': 7, 'CategoryDistribution': {'Shopify': 7}}, 'CreatedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 7, 'CategoryDistribution': {'admin': 7}}, 'ModifiedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 7, 'CategoryDistribution': {'admin': 7}}}

----------------------------------------------------------------------
NUMERIC
----------------------------------------------------------------------
{'OrderGrossAmount': {'ValidNumericCount': 7, 'InvalidNumericCount': 0, 'Minimum': np.float64(699.0), 'Maximum': np.float64(4298.0), 'Mean': np.float64(2642.5714285714284), 'Median': np.float64(3198.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 7, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(-531.25), 'UpperOutlierBoundary': np.float64(5682.75)}}

----------------------------------------------------------------------
DATE
----------------------------------------------------------------------
{'OrderDate': {'ValidDateCount': 7, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-05 00:00:00'), 'MaximumDate': Timestamp('2026-07-11 00:00:00'), 'FutureDateCount': 0}, 'CreatedOn': {'ValidDateCount': 7, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-05 00:00:00'), 'MaximumDate': Timestamp('2026-07-11 00:00:00'), 'FutureDateCount': 0}, 'ModifiedOn': {'ValidDateCount': 7, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-05 00:00:00'), 'MaximumDate': Timestamp('2026-07-11 00:00:00'), 'FutureDateCount': 0}}

----------------------------------------------------------------------
PATTERNS
----------------------------------------------------------------------
{'email': {}, 'phone': {}, 'identifier': {'SourceOrderID': {'UniqueCount': 7, 'DuplicateCount': 0, 'MissingCount': 0}, 'SourceOrderIDInternal': {'UniqueCount': 7, 'DuplicateCount': 0, 'MissingCount': 0}, 'CustomerCode': {'UniqueCount': 7, 'DuplicateCount': 0, 'MissingCount': 0}, 'CampaignCode': {'UniqueCount': 3, 'DuplicateCount': 2, 'MissingCount': 2}}}

----------------------------------------------------------------------
ISSUES
----------------------------------------------------------------------
         Column            IssueType Severity  Count                               Description
0  CampaignCode        MissingValues     High      2                  Missing values detected.
1  CampaignCode  DuplicateIdentifier     High      2      Repeated identifier values detected.
2  CampaignCode    MissingIdentifier     High      2       Missing identifier values detected.
3    OrderNotes        MissingValues   Medium      7                  Missing values detected.
4   OrderStatus           Whitespace      Low      1  Leading or trailing whitespace detected.

----------------------------------------------------------------------
CONFIGURATION
----------------------------------------------------------------------
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}


======================================================================
AMAZON UAE SALES ORDER PROFILING RESULTS
======================================================================

----------------------------------------------------------------------
FIELD_TYPES
----------------------------------------------------------------------
SourceSystem             categorical
SourceOrderID             identifier
SourceOrderIDInternal     identifier
CustomerCode              identifier
CampaignCode              identifier
OrderDate                       date
OrderStatus                     text
ShipToAddress                   text
BillToAddress                   text
PaymentMethod                   text
OrderGrossAmount             numeric
OrderNotes                      text
CreatedOn                       date
CreatedByUser            categorical
ModifiedOn                      date
ModifiedByUser           categorical
Name: DetectedFieldType, dtype: object

----------------------------------------------------------------------
DETECTION_DETAILS
----------------------------------------------------------------------
{'SourceSystem': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'SourceOrderID': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SourceOrderIDInternal': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'CustomerCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'CampaignCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'OrderDate': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'OrderStatus': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'ShipToAddress': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'BillToAddress': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'PaymentMethod': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'OrderGrossAmount': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'OrderNotes': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No non-empty values available'}, 'CreatedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'CreatedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'ModifiedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'ModifiedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}}

----------------------------------------------------------------------
GENERAL
----------------------------------------------------------------------
{'rows': 7, 'columns': 16, 'exact_duplicate_rows': 0, 'column_profile':                       DataType DetectedFieldType  MissingCount  MissingPercent  UniqueCount  DuplicateValueCount
SourceSystem            object       categorical             0            0.00            1                    6
SourceOrderID           object        identifier             0            0.00            7                    0
SourceOrderIDInternal   object        identifier             0            0.00            7                    0
CustomerCode            object        identifier             0            0.00            7                    0
CampaignCode            object        identifier             4           57.14            3                    3
OrderDate               object              date             0            0.00            7                    0
OrderStatus             object              text             0            0.00            2                    5
ShipToAddress           object              text             0            0.00            7                    0
BillToAddress           object              text             0            0.00            7                    0
PaymentMethod           object              text             0            0.00            4                    3
OrderGrossAmount         int64           numeric             0            0.00            7                    0
OrderNotes             float64              text             7          100.00            0                    6
CreatedOn               object              date             0            0.00            7                    0
CreatedByUser           object       categorical             0            0.00            1                    6
ModifiedOn              object              date             0            0.00            7                    0
ModifiedByUser          object       categorical             0            0.00            1                    6}

----------------------------------------------------------------------
TEXT
----------------------------------------------------------------------
{'OrderStatus': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 9, 'MaximumLength': 9, 'AverageLength': np.float64(9.0)}, 'ShipToAddress': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 12, 'MaximumLength': 23, 'AverageLength': np.float64(17.0)}, 'BillToAddress': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 12, 'MaximumLength': 23, 'AverageLength': np.float64(17.0)}, 'PaymentMethod': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 4, 'MaximumLength': 16, 'AverageLength': np.float64(10.29)}, 'OrderNotes': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 0, 'MaximumLength': 0, 'AverageLength': 0}}

----------------------------------------------------------------------
CATEGORICAL
----------------------------------------------------------------------
{'SourceSystem': {'UniqueCount': 1, 'MostCommonValue': 'Amazon UAE', 'MostCommonCount': 7, 'CategoryDistribution': {'Amazon UAE': 7}}, 'CreatedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 7, 'CategoryDistribution': {'admin': 7}}, 'ModifiedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 7, 'CategoryDistribution': {'admin': 7}}}

----------------------------------------------------------------------
NUMERIC
----------------------------------------------------------------------
{'OrderGrossAmount': {'ValidNumericCount': 7, 'InvalidNumericCount': 0, 'Minimum': np.float64(179.0), 'Maximum': np.float64(3298.0), 'Mean': np.float64(1017.4285714285714), 'Median': np.float64(499.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 7, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 1, 'LowerOutlierBoundary': np.float64(-663.5), 'UpperOutlierBoundary': np.float64(2236.5)}}

----------------------------------------------------------------------
DATE
----------------------------------------------------------------------
{'OrderDate': {'ValidDateCount': 7, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-12 00:00:00'), 'MaximumDate': Timestamp('2026-07-18 00:00:00'), 'FutureDateCount': 0}, 'CreatedOn': {'ValidDateCount': 7, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-12 00:00:00'), 'MaximumDate': Timestamp('2026-07-18 00:00:00'), 'FutureDateCount': 0}, 'ModifiedOn': {'ValidDateCount': 7, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-12 00:00:00'), 'MaximumDate': Timestamp('2026-07-18 00:00:00'), 'FutureDateCount': 0}}

----------------------------------------------------------------------
PATTERNS
----------------------------------------------------------------------
{'email': {}, 'phone': {}, 'identifier': {'SourceOrderID': {'UniqueCount': 7, 'DuplicateCount': 0, 'MissingCount': 0}, 'SourceOrderIDInternal': {'UniqueCount': 7, 'DuplicateCount': 0, 'MissingCount': 0}, 'CustomerCode': {'UniqueCount': 7, 'DuplicateCount': 0, 'MissingCount': 0}, 'CampaignCode': {'UniqueCount': 3, 'DuplicateCount': 0, 'MissingCount': 4}}}

----------------------------------------------------------------------
ISSUES
----------------------------------------------------------------------
         Column          IssueType Severity  Count                          Description
0  CampaignCode      MissingValues     High      4             Missing values detected.
1  CampaignCode  MissingIdentifier     High      4  Missing identifier values detected.
2    OrderNotes      MissingValues   Medium      7             Missing values detected.

----------------------------------------------------------------------
CONFIGURATION
----------------------------------------------------------------------
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}



## 1.6 Review Profiler Issues

Review the issues identified by the automated profiler across the Shopify, Amazon UAE, and Noon Sales Order datasets.

The full profiling output provides a broad assessment of each raw Sales Order dataset. This step focuses specifically on the detected issues so they can be investigated before any transformation decisions are made.

Profiler findings are treated as indicators for review and do not automatically determine the correct transformation.

Each source dataset will be reviewed separately, and identified issues will be evaluated against the Sales Order Data Dictionary and LJ Dev Commerce business requirements.

In [34]:
# =========================================================
# 1.6 Review Profiler Issues
# =========================================================

shopify_issues = shopify_profile_results["issues"]
amazon_issues = amazon_profile_results["issues"]
noon_issues = noon_profile_results["issues"]


print("\n" + "=" * 70)
print("SHOPIFY SALES ORDER PROFILER ISSUES")
print("=" * 70)

display(shopify_issues)


print("\n" + "=" * 70)
print("AMAZON UAE SALES ORDER PROFILER ISSUES")
print("=" * 70)

display(amazon_issues)


print("\n" + "=" * 70)
print("NOON SALES ORDER PROFILER ISSUES")
print("=" * 70)

display(noon_issues)

======================================================================
SHOPIFY SALES ORDER PROFILER ISSUES
======================================================================

         Column            IssueType Severity  Count                               Description
0  CampaignCode        MissingValues     High      2                  Missing values detected.
1  CampaignCode  DuplicateIdentifier     High      2      Repeated identifier values detected.
2  CampaignCode    MissingIdentifier     High      2       Missing identifier values detected.
3    OrderNotes        MissingValues   Medium      7                  Missing values detected.
4   OrderStatus           Whitespace      Low      1  Leading or trailing whitespace detected.

======================================================================
AMAZON UAE SALES ORDER PROFILER ISSUES
======================================================================

         Column          IssueType Severity  Count                          Description
0  CampaignCode      MissingValues     High      4             Missing values detected.
1  CampaignCode  MissingIdentifier     High      4  Missing identifier values detected.
2    OrderNotes      MissingValues   Medium      7             Missing values detected.

======================================================================
NOON SALES ORDER PROFILER ISSUES
======================================================================

         Column          IssueType Severity  Count                          Description
0  CampaignCode      MissingValues     High      3             Missing values detected.
1  CampaignCode  MissingIdentifier     High      3  Missing identifier values detected.
2    OrderNotes      MissingValues   Medium      6             Missing values detected.

## 1.7 Independent Analyst Review

Perform a systematic independent analyst review of the untouched raw Sales Order datasets.

This section is the notebook-based version of the Pre-ETL Inspection.

The review goes beyond the automated profiler and checks each Sales Order source dataset using independent analyst validation relevant to its business meaning and approved ETL design.

The review covers, where applicable:

- Dataset structure and grain
- Missing and blank values
- Exact duplicate rows
- Primary-key candidates and key uniqueness
- Cross-source key uniqueness and collision checks
- Whitespace in text fields
- Text consistency
- Numeric validity and statistical outlier candidates
- Date parsing, datatype, validity, and Created/Modified date consistency
- CustomerCode and CampaignCode relationship values
- Source-to-target datatype compatibility considerations
- Cross-source structural consistency

Automated profiler findings and independent analyst findings are kept conceptually separate.

Each source dataset is reviewed independently before consolidation.

No data is modified in this section.

In [35]:
# =========================================================
# 1.7 Independent Analyst Review
# =========================================================


# =========================================================
# 1. Dataset Structure and Grain
# =========================================================

print("1. DATASET STRUCTURE AND GRAIN")
print("=" * 80)

sales_order_sources = {
    "Shopify": shopify_orders_raw,
    "Amazon UAE": amazon_orders_raw,
    "Noon": noon_orders_raw
}

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    print(f"Rows: {source_df.shape[0]}")
    print(f"Columns: {source_df.shape[1]}")

    print("\nWorking assumption:")
    print("One row represents one customer order / sales order header.")


# =========================================================
# 2. Missing Values and Blank Values
# =========================================================

print("\n\n2. MISSING VALUES AND BLANK VALUES")
print("=" * 80)

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    missing_values = source_df.isna().sum()

    blank_values = pd.Series(
        {
            column: (
                source_df[column]
                .astype("string")
                .str.strip()
                .eq("")
                .sum()
                if source_df[column].dtype == "object"
                else 0
            )
            for column in source_df.columns
        }
    )

    missing_blank_review = pd.DataFrame({
        "MissingValues": missing_values,
        "BlankValues": blank_values
    })

    display(missing_blank_review)


# =========================================================
# 3. Exact Duplicate Rows
# =========================================================

print("\n\n3. EXACT DUPLICATE ROWS")
print("=" * 80)

for source_name, source_df in sales_order_sources.items():

    exact_duplicate_count = source_df.duplicated().sum()

    print(
        f"{source_name} - Exact duplicate rows: "
        f"{exact_duplicate_count}"
    )

    if exact_duplicate_count > 0:

        display(
            source_df[
                source_df.duplicated(keep=False)
            ]
        )


# =========================================================
# 4. Primary Key Candidate and Identifier Uniqueness
# =========================================================

print("\n\n4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS")
print("=" * 80)

identifier_columns = [
    "SourceOrderID",
    "SourceOrderIDInternal",
    "CustomerCode",
    "CampaignCode"
]

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    identifier_review = pd.DataFrame(
        {
            "Column": identifier_columns,
            "NullCount": [
                source_df[column].isna().sum()
                for column in identifier_columns
            ],
            "BlankCount": [
                source_df[column]
                .astype("string")
                .str.strip()
                .eq("")
                .sum()
                for column in identifier_columns
            ],
            "DuplicateCount": [
                source_df[column]
                .duplicated()
                .sum()
                for column in identifier_columns
            ],
            "UniqueValues": [
                source_df[column]
                .nunique()
                for column in identifier_columns
            ]
        }
    )

    display(identifier_review)


# =========================================================
# 5. Cross-Source Order Identifier Collision Review
# =========================================================

print("\n\n5. CROSS-SOURCE ORDER IDENTIFIER COLLISION REVIEW")
print("=" * 80)

cross_source_ids = pd.concat(
    [
        shopify_orders_raw[
            ["SourceSystem", "SourceOrderID", "SourceOrderIDInternal"]
        ],
        amazon_orders_raw[
            ["SourceSystem", "SourceOrderID", "SourceOrderIDInternal"]
        ],
        noon_orders_raw[
            ["SourceSystem", "SourceOrderID", "SourceOrderIDInternal"]
        ]
    ],
    ignore_index=True
)

print("Total consolidated source-order records:")
print(len(cross_source_ids))

print("\nUnique SourceOrderIDInternal values:")
print(cross_source_ids["SourceOrderIDInternal"].nunique())

cross_source_internal_duplicates = (
    cross_source_ids[
        cross_source_ids["SourceOrderIDInternal"].duplicated(
            keep=False
        )
    ]
    .sort_values("SourceOrderIDInternal")
)

print(
    "\nCross-source SourceOrderIDInternal collisions: "
    f"{len(cross_source_internal_duplicates)}"
)

if not cross_source_internal_duplicates.empty:

    display(cross_source_internal_duplicates)


# =========================================================
# 6. Leading and Trailing Whitespace Review
# =========================================================

print("\n\n6. LEADING AND TRAILING WHITESPACE REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    text_columns = source_df.select_dtypes(
        include="object"
    ).columns

    whitespace_findings = []

    for column in text_columns:

        whitespace_mask = (
            source_df[column]
            .astype("string")
            != source_df[column]
            .astype("string")
            .str.strip()
        )

        count = whitespace_mask.sum()

        if count > 0:

            whitespace_records = source_df.loc[
                whitespace_mask,
                ["SourceOrderID", column]
            ]

            whitespace_findings.append({
                "Column": column,
                "WhitespaceRecordCount": count
            })

            print(f"\nColumn: {column}")
            display(whitespace_records)

    if whitespace_findings:

        print("\nWhitespace findings summary:")
        display(pd.DataFrame(whitespace_findings))

    else:

        print("No leading or trailing whitespace found.")


# =========================================================
# 7. Text Consistency Review
# =========================================================

print("\n\n7. TEXT CONSISTENCY REVIEW")
print("=" * 80)

text_consistency_columns = [
    "SourceSystem",
    "OrderStatus",
    "PaymentMethod"
]

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    for column in text_consistency_columns:

        print(f"\n{column} values:")

        display(
            source_df[column]
            .value_counts(dropna=False)
            .sort_index()
            .rename("RecordCount")
            .to_frame()
        )


# =========================================================
# 8. Numeric Validity Review
# =========================================================

print("\n\n8. NUMERIC VALIDITY REVIEW")
print("=" * 80)

numeric_columns = [
    "OrderGrossAmount"
]

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    numeric_summary = source_df[
        numeric_columns
    ].describe().T

    numeric_summary["NegativeCount"] = [
        (source_df[column] < 0).sum()
        for column in numeric_columns
    ]

    numeric_summary["ZeroCount"] = [
        (source_df[column] == 0).sum()
        for column in numeric_columns
    ]

    numeric_summary["PositiveCount"] = [
        (source_df[column] > 0).sum()
        for column in numeric_columns
    ]

    display(numeric_summary)


# =========================================================
# 9. Numeric Outlier Candidate Review
# =========================================================

print("\n\n9. NUMERIC OUTLIER CANDIDATE REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    outlier_summary = []

    for column in numeric_columns:

        q1 = source_df[column].quantile(0.25)
        q3 = source_df[column].quantile(0.75)

        iqr = q3 - q1

        lower_bound = q1 - (1.5 * iqr)
        upper_bound = q3 + (1.5 * iqr)

        outlier_mask = (
            (source_df[column] < lower_bound)
            |
            (source_df[column] > upper_bound)
        )

        outlier_count = outlier_mask.sum()

        outlier_summary.append({
            "Column": column,
            "LowerBoundary": lower_bound,
            "UpperBoundary": upper_bound,
            "OutlierCandidateCount": outlier_count
        })

        if outlier_count > 0:

            print(f"\nOutlier candidate(s): {column}")

            display(
                source_df.loc[
                    outlier_mask,
                    [
                        "SourceOrderID",
                        "SourceOrderIDInternal",
                        "CustomerCode",
                        column
                    ]
                ]
            )

    print("\nOutlier candidate summary:")
    display(pd.DataFrame(outlier_summary))


# =========================================================
# 10. Date Parsing and Datatype Review
# =========================================================

print("\n\n10. DATE PARSING AND DATATYPE REVIEW")
print("=" * 80)

date_columns = [
    "OrderDate",
    "CreatedOn",
    "ModifiedOn"
]

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    date_review = []

    for column in date_columns:

        parsed_dates = pd.to_datetime(
            source_df[column],
            errors="coerce"
        )

        date_review.append({
            "Column": column,
            "CurrentSourceDtype": str(
                source_df[column].dtype
            ),
            "InvalidDateCount": parsed_dates.isna().sum(),
            "MinimumDate": parsed_dates.min(),
            "MaximumDate": parsed_dates.max()
        })

    display(pd.DataFrame(date_review))


# =========================================================
# 11. CreatedOn / ModifiedOn and OrderDate Logic
# =========================================================

print("\n\n11. DATE LOGIC REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    order_dates = pd.to_datetime(
        source_df["OrderDate"],
        errors="coerce"
    )

    created_dates = pd.to_datetime(
        source_df["CreatedOn"],
        errors="coerce"
    )

    modified_dates = pd.to_datetime(
        source_df["ModifiedOn"],
        errors="coerce"
    )

    modified_before_created = source_df[
        modified_dates < created_dates
    ]

    created_before_order = source_df[
        created_dates < order_dates
    ]

    modified_before_order = source_df[
        modified_dates < order_dates
    ]

    print(
        "Records where ModifiedOn is earlier than CreatedOn: "
        f"{len(modified_before_created)}"
    )

    print(
        "Records where CreatedOn is earlier than OrderDate: "
        f"{len(created_before_order)}"
    )

    print(
        "Records where ModifiedOn is earlier than OrderDate: "
        f"{len(modified_before_order)}"
    )

    if not modified_before_created.empty:

        print("\nModifiedOn earlier than CreatedOn:")

        display(
            modified_before_created[
                [
                    "SourceOrderID",
                    "OrderDate",
                    "CreatedOn",
                    "ModifiedOn"
                ]
            ]
        )


# =========================================================
# 12. CustomerCode and CampaignCode Relationship Review
# =========================================================

print("\n\n12. RELATIONSHIP VALUE REVIEW")
print("=" * 80)

relationship_columns = [
    "CustomerCode",
    "CampaignCode"
]

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    for column in relationship_columns:

        print(f"\n{column} frequency:")

        display(
            source_df[column]
            .value_counts(dropna=False)
            .sort_index()
            .rename("RecordCount")
            .to_frame()
        )


# =========================================================
# 13. Sales Order and Campaign Date Relationship Review
# =========================================================

print("\n\n13. SALES ORDER AND CAMPAIGN DATE RELATIONSHIP REVIEW")
print("=" * 80)

print(
    "Review Sales Order records where OrderDate occurs before "
    "the associated Campaign StartDate."
)

# ---------------------------------------------------------
# Load Marketing Campaign raw dataset
# ---------------------------------------------------------

marketing_campaign_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\05_Marketing\marketing_campaign_master.csv"
)

marketing_campaign_raw = pd.read_csv(
    marketing_campaign_raw_path
)

# ---------------------------------------------------------
# Combine Sales Order raw datasets
# ---------------------------------------------------------

sales_order_campaign_review = pd.concat(
    [
        shopify_orders_raw,
        amazon_orders_raw,
        noon_orders_raw
    ],
    ignore_index=True
)

# ---------------------------------------------------------
# Convert dates for comparison
# ---------------------------------------------------------

sales_order_campaign_review["OrderDate_Parsed"] = pd.to_datetime(
    sales_order_campaign_review["OrderDate"],
    errors="coerce"
)

marketing_campaign_raw_review = (
    marketing_campaign_raw.copy(deep=True)
)

marketing_campaign_raw_review["StartDate_Parsed"] = pd.to_datetime(
    marketing_campaign_raw_review["StartDate"],
    errors="coerce"
)

# ---------------------------------------------------------
# Match Sales Orders to Marketing Campaigns
# ---------------------------------------------------------

campaign_date_review = sales_order_campaign_review.merge(
    marketing_campaign_raw_review[
        [
            "CampaignCode",
            "StartDate_Parsed"
        ]
    ],
    on="CampaignCode",
    how="left"
)

# ---------------------------------------------------------
# Identify campaign date exceptions
# ---------------------------------------------------------

campaign_date_exception_mask = (
    campaign_date_review["CampaignCode"].notna()
    &
    campaign_date_review["OrderDate_Parsed"].notna()
    &
    campaign_date_review["StartDate_Parsed"].notna()
    &
    (
        campaign_date_review["OrderDate_Parsed"]
        < campaign_date_review["StartDate_Parsed"]
    )
)

campaign_date_exceptions = campaign_date_review.loc[
    campaign_date_exception_mask,
    [
        "SourceSystem",
        "SourceOrderID",
        "SourceOrderIDInternal",
        "CustomerCode",
        "CampaignCode",
        "OrderDate",
        "StartDate_Parsed"
    ]
].copy()

print(
    "Sales Order records with OrderDate before Campaign StartDate:",
    len(campaign_date_exceptions)
)

if not campaign_date_exceptions.empty:

    display(campaign_date_exceptions)

else:

    print("No campaign date relationship exceptions found.")


# =========================================================
# 14. Source Datatype Review
# =========================================================

print("\n\n14. SOURCE DATATYPE REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    datatype_review = pd.DataFrame({
        "Column": source_df.columns,
        "SourceDtype": [
            str(source_df[column].dtype)
            for column in source_df.columns
        ]
    })

    display(datatype_review)


# =========================================================
# 15. Cross-Source Structural Consistency Review
# =========================================================

print("\n\n15. CROSS-SOURCE STRUCTURAL CONSISTENCY REVIEW")
print("=" * 80)

source_structure_review = pd.DataFrame(
    {
        "Source": list(sales_order_sources.keys()),
        "Rows": [
            source_df.shape[0]
            for source_df in sales_order_sources.values()
        ],
        "Columns": [
            source_df.shape[1]
            for source_df in sales_order_sources.values()
        ],
        "ColumnOrderMatchesShopify": [
            list(source_df.columns)
            == list(shopify_orders_raw.columns)
            for source_df in sales_order_sources.values()
        ]
    }
)

display(source_structure_review)

print("\nExpected Sales Order source columns:")
print(shopify_orders_raw.columns.tolist())


# =========================================================
# Independent Analyst Review Complete
# =========================================================

print("\n" + "=" * 80)
print("Independent Analyst Review completed.")
print("No data was modified.")
print("=" * 80)

1. DATASET STRUCTURE AND GRAIN
================================================================================

Shopify
--------------------------------------------------------------------------------
Rows: 7
Columns: 16

Working assumption:
One row represents one customer order / sales order header.

Amazon UAE
--------------------------------------------------------------------------------
Rows: 7
Columns: 16

Working assumption:
One row represents one customer order / sales order header.

Noon
--------------------------------------------------------------------------------
Rows: 6
Columns: 16

Working assumption:
One row represents one customer order / sales order header.


2. MISSING VALUES AND BLANK VALUES
================================================================================

Shopify
--------------------------------------------------------------------------------

                       MissingValues  BlankValues
SourceSystem                       0            0
SourceOrderID                      0            0
SourceOrderIDInternal              0            0
CustomerCode                       0            0
CampaignCode                       2            0
OrderDate                          0            0
OrderStatus                        0            0
ShipToAddress                      0            0
BillToAddress                      0            0
PaymentMethod                      0            0
OrderGrossAmount                   0            0
OrderNotes                         7            0
CreatedOn                          0            0
CreatedByUser                      0            0
ModifiedOn                         0            0
ModifiedByUser                     0            0

Amazon UAE
--------------------------------------------------------------------------------

                       MissingValues  BlankValues
SourceSystem                       0            0
SourceOrderID                      0            0
SourceOrderIDInternal              0            0
CustomerCode                       0            0
CampaignCode                       4            0
OrderDate                          0            0
OrderStatus                        0            0
ShipToAddress                      0            0
BillToAddress                      0            0
PaymentMethod                      0            0
OrderGrossAmount                   0            0
OrderNotes                         7            0
CreatedOn                          0            0
CreatedByUser                      0            0
ModifiedOn                         0            0
ModifiedByUser                     0            0

Noon
--------------------------------------------------------------------------------

                       MissingValues  BlankValues
SourceSystem                       0            0
SourceOrderID                      0            0
SourceOrderIDInternal              0            0
CustomerCode                       0            0
CampaignCode                       3            0
OrderDate                          0            0
OrderStatus                        0            0
ShipToAddress                      0            0
BillToAddress                      0            0
PaymentMethod                      0            0
OrderGrossAmount                   0            0
OrderNotes                         6            0
CreatedOn                          0            0
CreatedByUser                      0            0
ModifiedOn                         0            0
ModifiedByUser                     0            0

3. EXACT DUPLICATE ROWS
================================================================================
Shopify - Exact duplicate rows: 0
Amazon UAE - Exact duplicate rows: 0
Noon - Exact duplicate rows: 0


4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS
================================================================================

Shopify
--------------------------------------------------------------------------------

                  Column  NullCount  BlankCount  DuplicateCount  UniqueValues
0          SourceOrderID          0           0               0             7
1  SourceOrderIDInternal          0           0               0             7
2           CustomerCode          0           0               0             7
3           CampaignCode          2           0               3             3

Amazon UAE
--------------------------------------------------------------------------------

                  Column  NullCount  BlankCount  DuplicateCount  UniqueValues
0          SourceOrderID          0           0               0             7
1  SourceOrderIDInternal          0           0               0             7
2           CustomerCode          0           0               0             7
3           CampaignCode          4           0               3             3

Noon
--------------------------------------------------------------------------------

                  Column  NullCount  BlankCount  DuplicateCount  UniqueValues
0          SourceOrderID          0           0               0             6
1  SourceOrderIDInternal          0           0               0             6
2           CustomerCode          0           0               0             6
3           CampaignCode          3           0               2             3

5. CROSS-SOURCE ORDER IDENTIFIER COLLISION REVIEW
================================================================================
Total consolidated source-order records:
20

Unique SourceOrderIDInternal values:
20

Cross-source SourceOrderIDInternal collisions: 0


6. LEADING AND TRAILING WHITESPACE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

Column: OrderStatus

   SourceOrderID OrderStatus
3  SHOPIFY-SO004    shipped

Whitespace findings summary:

        Column  WhitespaceRecordCount
0  OrderStatus                      1

Amazon UAE
--------------------------------------------------------------------------------
No leading or trailing whitespace found.

Noon
--------------------------------------------------------------------------------
No leading or trailing whitespace found.


7. TEXT CONSISTENCY REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

SourceSystem values:

              RecordCount
SourceSystem
Shopify                 7

OrderStatus values:

             RecordCount
OrderStatus
 shipped               1
Completed              5
Pending                1

PaymentMethod values:

                  RecordCount
PaymentMethod
Cash on Delivery            2
Credit Card                 1
Mastercard                  1
Visa                        3

Amazon UAE
--------------------------------------------------------------------------------

SourceSystem values:

              RecordCount
SourceSystem
Amazon UAE              7

OrderStatus values:

             RecordCount
OrderStatus
Cancelled              1
Completed              6

PaymentMethod values:

                  RecordCount
PaymentMethod
Cash on Delivery            2
Credit Card                 2
Mastercard                  1
Visa                        2

Noon
--------------------------------------------------------------------------------

SourceSystem values:

              RecordCount
SourceSystem
Noon                    6

OrderStatus values:

             RecordCount
OrderStatus
Completed              4
Pending                1
Shipped                1

PaymentMethod values:

                  RecordCount
PaymentMethod
Cash on Delivery            1
Credit Card                 1
Mastercard                  1
Visa                        3

8. NUMERIC VALIDITY REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

                  count         mean          std    min     25%     50%     75%     max  NegativeCount  ZeroCount  PositiveCount
OrderGrossAmount    7.0  2642.571429  1264.639455  699.0  1799.0  3198.0  3352.5  4298.0              0          0              7

Amazon UAE
--------------------------------------------------------------------------------

                  count         mean          std    min    25%    50%     75%     max  NegativeCount  ZeroCount  PositiveCount
OrderGrossAmount    7.0  1017.428571  1104.379442  179.0  424.0  499.0  1149.0  3298.0              0          0              7

Noon
--------------------------------------------------------------------------------

                  count         mean          std    min    25%     50%      75%     max  NegativeCount  ZeroCount  PositiveCount
OrderGrossAmount    6.0  2082.166667  1432.850364  499.0  924.0  1899.0  3248.25  3899.0              0          0              6

9. NUMERIC OUTLIER CANDIDATE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

Outlier candidate summary:

             Column  LowerBoundary  UpperBoundary  OutlierCandidateCount
0  OrderGrossAmount        -531.25        5682.75                      0

Amazon UAE
--------------------------------------------------------------------------------

Outlier candidate(s): OrderGrossAmount

  SourceOrderID SourceOrderIDInternal CustomerCode  OrderGrossAmount
5  AMAZON-SO013                 SO013         C013              3298

Outlier candidate summary:

             Column  LowerBoundary  UpperBoundary  OutlierCandidateCount
0  OrderGrossAmount         -663.5         2236.5                      1

Noon
--------------------------------------------------------------------------------

Outlier candidate summary:

             Column  LowerBoundary  UpperBoundary  OutlierCandidateCount
0  OrderGrossAmount      -2562.375       6734.625                      0

10. DATE PARSING AND DATATYPE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

       Column CurrentSourceDtype  InvalidDateCount MinimumDate MaximumDate
0   OrderDate             object                 0  2026-07-05  2026-07-11
1   CreatedOn             object                 0  2026-07-05  2026-07-11
2  ModifiedOn             object                 0  2026-07-05  2026-07-11

Amazon UAE
--------------------------------------------------------------------------------

       Column CurrentSourceDtype  InvalidDateCount MinimumDate MaximumDate
0   OrderDate             object                 0  2026-07-12  2026-07-18
1   CreatedOn             object                 0  2026-07-12  2026-07-18
2  ModifiedOn             object                 0  2026-07-12  2026-07-18

Noon
--------------------------------------------------------------------------------

       Column CurrentSourceDtype  InvalidDateCount MinimumDate MaximumDate
0   OrderDate             object                 0  2026-07-19  2026-07-24
1   CreatedOn             object                 0  2026-07-19  2026-07-24
2  ModifiedOn             object                 0  2026-07-19  2026-07-24

11. DATE LOGIC REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------
Records where ModifiedOn is earlier than CreatedOn: 0
Records where CreatedOn is earlier than OrderDate: 0
Records where ModifiedOn is earlier than OrderDate: 0

Amazon UAE
--------------------------------------------------------------------------------
Records where ModifiedOn is earlier than CreatedOn: 0
Records where CreatedOn is earlier than OrderDate: 0
Records where ModifiedOn is earlier than OrderDate: 0

Noon
--------------------------------------------------------------------------------
Records where ModifiedOn is earlier than CreatedOn: 0
Records where CreatedOn is earlier than OrderDate: 0
Records where ModifiedOn is earlier than OrderDate: 0


12. RELATIONSHIP VALUE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

CustomerCode frequency:

              RecordCount
CustomerCode
C001                    1
C002                    1
C003                    1
C004                    1
C005                    1
C006                    1
C007                    1

CampaignCode frequency:

              RecordCount
CampaignCode
CAM001                  2
CAM002                  2
CAM004                  1
NaN                     2

Amazon UAE
--------------------------------------------------------------------------------

CustomerCode frequency:

              RecordCount
CustomerCode
C008                    1
C009                    1
C010                    1
C011                    1
C012                    1
C013                    1
C014                    1

CampaignCode frequency:

              RecordCount
CampaignCode
CAM001                  1
CAM002                  1
CAM004                  1
NaN                     4

Noon
--------------------------------------------------------------------------------

CustomerCode frequency:

              RecordCount
CustomerCode
C001                    1
C002                    1
C003                    1
C004                    1
C005                    1
C015                    1

CampaignCode frequency:

              RecordCount
CampaignCode
CAM001                  1
CAM002                  1
CAM004                  1
NaN                     3

13. SALES ORDER AND CAMPAIGN DATE RELATIONSHIP REVIEW
================================================================================
Review Sales Order records where OrderDate occurs before the associated Campaign StartDate.
Sales Order records with OrderDate before Campaign StartDate: 2

  SourceSystem  SourceOrderID SourceOrderIDInternal CustomerCode CampaignCode   OrderDate StartDate_Parsed
4      Shopify  SHOPIFY-SO005                 SO005         C005       CAM002  2026-07-09       2026-07-15
6      Shopify  SHOPIFY-SO007                 SO007         C007       CAM002  2026-07-11       2026-07-15

14. SOURCE DATATYPE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

                   Column SourceDtype
0            SourceSystem      object
1           SourceOrderID      object
2   SourceOrderIDInternal      object
3            CustomerCode      object
4            CampaignCode      object
5               OrderDate      object
6             OrderStatus      object
7           ShipToAddress      object
8           BillToAddress      object
9           PaymentMethod      object
10       OrderGrossAmount       int64
11             OrderNotes     float64
12              CreatedOn      object
13          CreatedByUser      object
14             ModifiedOn      object
15         ModifiedByUser      object

Amazon UAE
--------------------------------------------------------------------------------

                   Column SourceDtype
0            SourceSystem      object
1           SourceOrderID      object
2   SourceOrderIDInternal      object
3            CustomerCode      object
4            CampaignCode      object
5               OrderDate      object
6             OrderStatus      object
7           ShipToAddress      object
8           BillToAddress      object
9           PaymentMethod      object
10       OrderGrossAmount       int64
11             OrderNotes     float64
12              CreatedOn      object
13          CreatedByUser      object
14             ModifiedOn      object
15         ModifiedByUser      object

Noon
--------------------------------------------------------------------------------

                   Column SourceDtype
0            SourceSystem      object
1           SourceOrderID      object
2   SourceOrderIDInternal      object
3            CustomerCode      object
4            CampaignCode      object
5               OrderDate      object
6             OrderStatus      object
7           ShipToAddress      object
8           BillToAddress      object
9           PaymentMethod      object
10       OrderGrossAmount       int64
11             OrderNotes     float64
12              CreatedOn      object
13          CreatedByUser      object
14             ModifiedOn      object
15         ModifiedByUser      object

15. CROSS-SOURCE STRUCTURAL CONSISTENCY REVIEW
================================================================================

       Source  Rows  Columns  ColumnOrderMatchesShopify
0     Shopify     7       16                       True
1  Amazon UAE     7       16                       True
2        Noon     6       16                       True

Expected Sales Order source columns:
['SourceSystem', 'SourceOrderID', 'SourceOrderIDInternal', 'CustomerCode', 'CampaignCode', 'OrderDate', 'OrderStatus', 'ShipToAddress', 'BillToAddress', 'PaymentMethod', 'OrderGrossAmount', 'OrderNotes', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

================================================================================
Independent Analyst Review completed.
No data was modified.
================================================================================

## 1.8 Findings and Transformation Decisions

Compare the automated profiler findings, the Independent Analyst Review findings, and the approved Sales Order data requirements to formally determine the required treatment for each finding.

Each finding must be classified as one of the following:

- Safe deterministic transformation
- Valid value — retain unchanged
- Expected business behavior
- Requires relationship validation later
- Requires business investigation

No transformation is performed in this section.

For OrderStatus, the approved canonical business values are:

- Completed
- Pending
- Shipped
- Cancelled

Equivalent source representations are standardized to these canonical values during Section 2.2. This is a controlled business-value standardization, not an arbitrary data correction.

The approved decisions from this section will define the transformations applied in Section 2.2.

In [36]:
# =========================================================
# 1.8 Findings and Transformation Decisions
# =========================================================

transformation_decisions = pd.DataFrame([
    
    {
        "Finding": "SourceOrderIDInternal uniqueness and completeness",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": "Map SourceOrderIDInternal to sales_order_id without modification",
        "Reason": "The identifier is unique and non-null across all three Sales Order sources and corresponds to the approved Sales Order primary-key design."
    },
    
    {
        "Finding": "SourceOrderID source-specific identifiers",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": "Retain unchanged in the working dataset for source lineage and reconciliation",
        "Reason": "Source-specific order identifiers provide source-system traceability and reconciliation capability. They must not be modified during ETL."
    },
    
    {
        "Finding": "OrderStatus leading/trailing whitespace",
        "AffectedRecords": 1,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": "Trim leading and trailing whitespace",
        "Reason": "Whitespace is not part of the business status value and can create inconsistent status values during filtering, grouping, and reporting."
    },
    
    {
        "Finding": "OrderStatus capitalization/canonicalization",
        "AffectedRecords": 20,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": "Trim leading/trailing whitespace and standardize known OrderStatus values to the approved canonical values: Completed, Pending, Shipped, and Cancelled",
        "Reason": "OrderStatus is a controlled business classification. Standardizing equivalent values such as 'shipped' and 'Shipped' prevents duplicate status categories during filtering, grouping, reporting, and downstream BI analysis."
    },
    
    {
        "Finding": "OrderDate stored as object",
        "AffectedRecords": 20,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": "Convert to datetime",
        "Reason": "The source values are valid and parseable dates but require the target Datetime-compatible datatype."
    },
    
    {
        "Finding": "CreatedOn stored as object",
        "AffectedRecords": 20,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": "Convert to datetime",
        "Reason": "The audit date values are valid and require proper datatype preparation for the clean dataset and database loading."
    },
    
    {
        "Finding": "ModifiedOn stored as object",
        "AffectedRecords": 20,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": "Convert to datetime",
        "Reason": "The audit date values are valid and require proper datatype preparation for the clean dataset and database loading."
    },
    
    {
        "Finding": "OrderGrossAmount numeric and positive",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": "Retain source business values unchanged; convert only to the target Decimal-compatible datatype",
        "Reason": "All Sales Order amounts are numeric and positive. No evidence supports changing the business values. Datatype conversion is a technical preparation step, not a business-value correction."
    },
    
    {
        "Finding": "Amazon SO013 statistical outlier candidate",
        "AffectedRecords": 1,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": "No automatic modification",
        "Reason": "Statistical outlier detection does not prove that the order amount is incorrect. The source value must be preserved unless business evidence establishes an error."
    },
    
    {
        "Finding": "CampaignCode NULL values",
        "AffectedRecords": 9,
        "Decision": "Expected business behavior",
        "ApprovedAction": "Retain NULL values",
        "Reason": "Campaign association is optional in the Sales Order design. An order does not require a campaign."
    },
    
    {
        "Finding": "OrderNotes NULL values",
        "AffectedRecords": 20,
        "Decision": "Expected business behavior",
        "ApprovedAction": "Retain NULL values",
        "Reason": "Notes is an optional Sales Order field and no business requirement requires every order to contain notes."
    },
    
    {
        "Finding": "CustomerCode relationship values",
        "AffectedRecords": 20,
        "Decision": "Requires relationship validation later",
        "ApprovedAction": "Retain CustomerCode values unchanged and validate against commerce.customer",
        "Reason": "CustomerCode is required as a Sales Order relationship and the completed Customer table must be used to confirm foreign-key readiness."
    },
    
    {
        "Finding": "CampaignCode relationship values",
        "AffectedRecords": 11,
        "Decision": "Requires relationship validation later",
        "ApprovedAction": "Retain populated CampaignCode values unchanged and validate against the Marketing Campaign table",
        "Reason": "CampaignCode is an optional foreign-key relationship and must be validated against the completed Marketing Campaign dataset."
    },
    
    {
        "Finding": "SO005 and SO007 occur before CAM002 StartDate",
        "AffectedRecords": 2,
        "Decision": "Requires business investigation",
        "ApprovedAction": "Retain the source order dates and CAM002 relationships unchanged; carry the temporal exception forward for validation and reporting",
        "Reason": "The cross-dataset relationship identifies a business-rule exception. There is insufficient evidence to determine whether this represents pre-launch activity, early campaign attribution, a historical campaign-date change, or a synthetic-data inconsistency. The source values must therefore not be invented or silently corrected."
    },
    
    {
        "Finding": "SO007 Sales Order total differs from successful payment amount",
        "AffectedRecords": 1,
        "Decision": "Requires business investigation",
        "ApprovedAction": "Retain Sales Order, Sales Order Item, and Payment source values unchanged; carry the reconciliation exception forward for validation and reporting",
        "Reason": "SO007 totals AED 3,257 while PAY008 records AED 3,078, producing an unexplained AED 179 difference. The difference matches one P0013 item, but the available data does not establish that it is a discount, fee, refund, partial payment, or other adjustment. No business value should therefore be invented or silently corrected."
    },
    
    {
        "Finding": "Shipping and billing addresses are identical",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": "Retain both address values unchanged",
        "Reason": "Identical shipping and billing addresses are not prohibited by the Sales Order business requirements and are not sufficient evidence of an error."
    },
    
    {
        "Finding": "Exact duplicate rows",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": "Retain dataset unchanged",
        "Reason": "No exact duplicate Sales Order rows were identified."
    },
    
    {
        "Finding": "Cross-source structural consistency",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": "Proceed with controlled consolidation of the three validated source datasets",
        "Reason": "Shopify, Amazon UAE, and Noon contain the same approved 16-column source structure, supporting consolidation after source-specific validation."
    }
])


print("Sales Order Findings and Transformation Decisions")
print("=" * 120)

display(transformation_decisions)


print("\nDecision Summary")
print("=" * 120)

print(
    transformation_decisions["Decision"].value_counts()
)

Sales Order Findings and Transformation Decisions
========================================================================================================================

                                                           Finding  AffectedRecords                                Decision                                                                                                                                          ApprovedAction                                                                                                                                                                                                                                                                                                                                   Reason
0                SourceOrderIDInternal uniqueness and completeness               20          Valid value — retain unchanged                                                                                        Map SourceOrderIDInternal to sales_order_id without modification                                                                                                                                                                                               The identifier is unique and non-null across all three Sales Order sources and corresponds to the approved Sales Order primary-key design.
1                        SourceOrderID source-specific identifiers               20          Valid value — retain unchanged                                                                           Retain unchanged in the working dataset for source lineage and reconciliation                                                                                                                                                                                                Source-specific order identifiers provide source-system traceability and reconciliation capability. They must not be modified during ETL.
2                          OrderStatus leading/trailing whitespace                1       Safe deterministic transformation                                                                                                                    Trim leading and trailing whitespace                                                                                                                                                                                                 Whitespace is not part of the business status value and can create inconsistent status values during filtering, grouping, and reporting.
3                      OrderStatus capitalization/canonicalization               20       Safe deterministic transformation  Trim leading/trailing whitespace and standardize known OrderStatus values to the approved canonical values: Completed, Pending, Shipped, and Cancelled                                                                                                             OrderStatus is a controlled business classification. Standardizing equivalent values such as 'shipped' and 'Shipped' prevents duplicate status categories during filtering, grouping, reporting, and downstream BI analysis.
4                                       OrderDate stored as object               20       Safe deterministic transformation                                                                                                                                     Convert to datetime                                                                                                                                                                                                                                     The source values are valid and parseable dates but require the target Datetime-compatible datatype.
5                                       CreatedOn stored as object               20       Safe deterministic transformation                                                                                                                                     Convert to datetime                                                                                                                                                                                                                      The audit date values are valid and require proper datatype preparation for the clean dataset and database loading.
6                                      ModifiedOn stored as object               20       Safe deterministic transformation                                                                                                                                     Convert to datetime                                                                                                                                                                                                                      The audit date values are valid and require proper datatype preparation for the clean dataset and database loading.
7                            OrderGrossAmount numeric and positive               20          Valid value — retain unchanged                                                         Retain source business values unchanged; convert only to the target Decimal-compatible datatype                                                                                                                                               All Sales Order amounts are numeric and positive. No evidence supports changing the business values. Datatype conversion is a technical preparation step, not a business-value correction.
8                       Amazon SO013 statistical outlier candidate                1          Valid value — retain unchanged                                                                                                                               No automatic modification                                                                                                                                                                       Statistical outlier detection does not prove that the order amount is incorrect. The source value must be preserved unless business evidence establishes an error.
9                                         CampaignCode NULL values                9              Expected business behavior                                                                                                                                      Retain NULL values                                                                                                                                                                                                                                        Campaign association is optional in the Sales Order design. An order does not require a campaign.
10                                          OrderNotes NULL values               20              Expected business behavior                                                                                                                                      Retain NULL values                                                                                                                                                                                                                                Notes is an optional Sales Order field and no business requirement requires every order to contain notes.
11                                CustomerCode relationship values               20  Requires relationship validation later                                                                             Retain CustomerCode values unchanged and validate against commerce.customer                                                                                                                                                                                                   CustomerCode is required as a Sales Order relationship and the completed Customer table must be used to confirm foreign-key readiness.
12                                CampaignCode relationship values               11  Requires relationship validation later                                                        Retain populated CampaignCode values unchanged and validate against the Marketing Campaign table                                                                                                                                                                                                             CampaignCode is an optional foreign-key relationship and must be validated against the completed Marketing Campaign dataset.
13                   SO005 and SO007 occur before CAM002 StartDate                2         Requires business investigation                     Retain the source order dates and CAM002 relationships unchanged; carry the temporal exception forward for validation and reporting  The cross-dataset relationship identifies a business-rule exception. There is insufficient evidence to determine whether this represents pre-launch activity, early campaign attribution, a historical campaign-date change, or a synthetic-data inconsistency. The source values must therefore not be invented or silently corrected.
14  SO007 Sales Order total differs from successful payment amount                1         Requires business investigation      Retain Sales Order, Sales Order Item, and Payment source values unchanged; carry the reconciliation exception forward for validation and reporting     SO007 totals AED 3,257 while PAY008 records AED 3,078, producing an unexplained AED 179 difference. The difference matches one P0013 item, but the available data does not establish that it is a discount, fee, refund, partial payment, or other adjustment. No business value should therefore be invented or silently corrected.
15                    Shipping and billing addresses are identical               20          Valid value — retain unchanged                                                                                                                    Retain both address values unchanged                                                                                                                                                                                        Identical shipping and billing addresses are not prohibited by the Sales Order business requirements and are not sufficient evidence of an error.
16                                            Exact duplicate rows                0          Valid value — retain unchanged                                                                                                                                Retain dataset unchanged                                                                                                                                                                                                                                                                                     No exact duplicate Sales Order rows were identified.
17                             Cross-source structural consistency               20          Valid value — retain unchanged                                                                            Proceed with controlled consolidation of the three validated source datasets                                                                                                                                                                                           Shopify, Amazon UAE, and Noon contain the same approved 16-column source structure, supporting consolidation after source-specific validation.

Decision Summary
========================================================================================================================
Decision
Valid value — retain unchanged            7
Safe deterministic transformation         5
Expected business behavior                2
Requires relationship validation later    2
Requires business investigation           2
Name: count, dtype: int64

# =========================================================
# SECTION 2 — DATA TRANSFORMATION
# =========================================================

## 2.1 Create Clean Working Datasets

Create separate working copies of the raw Sales Order datasets from Shopify, Amazon UAE, and Noon before applying any approved transformations.

The raw datasets must remain unchanged throughout the ETL process.

All transformations will be applied only to the clean working datasets.

The three source datasets will remain separate during this step. Controlled consolidation will occur only after the approved source-specific transformations have been applied and validated.

In [37]:
# =========================================================
# 2.1 Create Clean Working Dataset
# =========================================================

shopify_orders_clean = shopify_orders_raw.copy()

amazon_orders_clean = amazon_orders_raw.copy()

noon_orders_clean = noon_orders_raw.copy()


print("Clean working datasets created successfully.")

print(f"\nShopify raw rows:   {shopify_orders_raw.shape[0]}")
print(f"Shopify clean rows: {shopify_orders_clean.shape[0]}")

print(f"\nAmazon raw rows:   {amazon_orders_raw.shape[0]}")
print(f"Amazon clean rows: {amazon_orders_clean.shape[0]}")

print(f"\nNoon raw rows:   {noon_orders_raw.shape[0]}")
print(f"Noon clean rows: {noon_orders_clean.shape[0]}")


print("\nRaw and clean datasets are separate objects:")

print(
    "Shopify:",
    shopify_orders_raw is not shopify_orders_clean
)

print(
    "Amazon UAE:",
    amazon_orders_raw is not amazon_orders_clean
)

print(
    "Noon:",
    noon_orders_raw is not noon_orders_clean
)

Clean working datasets created successfully.

Shopify raw rows:   7
Shopify clean rows: 7

Amazon raw rows:   7
Amazon clean rows: 7

Noon raw rows:   6
Noon clean rows: 6

Raw and clean datasets are separate objects:
Shopify: True
Amazon UAE: True
Noon: True

## 2.2 Apply Approved Transformations

Apply only the transformations approved in Section 1.8 to the clean working Sales Order datasets.

Approved transformations:

- Trim leading and trailing whitespace from OrderStatus.
- Standardize known OrderStatus values to the approved canonical values: Completed, Pending, Shipped, and Cancelled.
- Convert OrderDate to datetime.
- Convert CreatedOn to datetime.
- Convert ModifiedOn to datetime.

The OrderStatus standardization is deterministic and ensures equivalent source values are represented consistently for filtering, grouping, reporting, and downstream BI analysis.

No other business values will be modified.

The Amazon SO013 statistical outlier candidate will be retained unchanged because statistical outlier detection alone does not confirm a data error.

The SO005 and SO007 CAM002 temporal exceptions will be retained unchanged because there is insufficient evidence to determine the correct business value.

The SO007 Sales Order total and payment discrepancy will also be retained unchanged because the available data does not establish the reason for the AED 179 difference.

The three source datasets will remain separate during this transformation step.

In [38]:
# =========================================================
# 2.2 Apply Approved Transformations
# =========================================================

# ---------------------------------------------------------
# 1. Standardize approved OrderStatus values
# ---------------------------------------------------------

status_standardization = {
    "completed": "Completed",
    "pending": "Pending",
    "shipped": "Shipped",
    "cancelled": "Cancelled"
}

for df in [
    shopify_orders_clean,
    amazon_orders_clean,
    noon_orders_clean
]:
    df["OrderStatus"] = (
        df["OrderStatus"]
        .str.strip()
        .str.lower()
        .replace(status_standardization)
    )


# ---------------------------------------------------------
# 2. Convert approved date fields
# ---------------------------------------------------------

for df in [
    shopify_orders_clean,
    amazon_orders_clean,
    noon_orders_clean
]:
    df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors="raise")
    df["CreatedOn"] = pd.to_datetime(df["CreatedOn"], errors="raise")
    df["ModifiedOn"] = pd.to_datetime(df["ModifiedOn"], errors="raise")


# ---------------------------------------------------------
# 3. Confirm approved OrderStatus values only
# ---------------------------------------------------------

approved_order_statuses = {
    "Completed",
    "Pending",
    "Shipped",
    "Cancelled"
}

for source_name, df in [
    ("Shopify", shopify_orders_clean),
    ("Amazon UAE", amazon_orders_clean),
    ("Noon", noon_orders_clean)
]:
    unexpected_statuses = sorted(
        set(df["OrderStatus"].dropna()) - approved_order_statuses
    )

    if unexpected_statuses:
        raise ValueError(
            f"{source_name} contains unexpected OrderStatus values "
            f"after standardization: {unexpected_statuses}"
        )


print("Sales Order approved transformations applied successfully.")

Sales Order approved transformations applied successfully.

# =========================================================
# SECTION 3 — VALIDATE
# =========================================================

## 3.1 Transformation Validation

Validate that every transformation approved in Section 1.8 was successfully applied to the clean Sales Order datasets.

This validation checks:

- OrderStatus whitespace removal and canonicalization
- OrderDate datetime conversion
- CreatedOn datetime conversion
- ModifiedOn datetime conversion
- Amazon SO013 outlier candidate retention
- SO005 and SO007 CAM002 temporal exception retention
- SO007 payment reconciliation exception retention

Only approved transformations and approved source-value retention decisions are validated.

No additional data modifications are performed in this section.

In [39]:
# =========================================================
# 3.1 Transformation Validation
# =========================================================

validation_results = []


# ---------------------------------------------------------
# 1. OrderStatus Whitespace Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_orders_clean),
    ("Amazon UAE", amazon_orders_clean),
    ("Noon", noon_orders_clean)
]:

    order_status_whitespace_remaining = (
        df["OrderStatus"]
        != df["OrderStatus"].str.strip()
    ).sum()

    validation_results.append({
        "Validation": f"{source_name} OrderStatus whitespace removal",
        "Expected": "0 records with leading/trailing whitespace",
        "Actual": f"{order_status_whitespace_remaining} records remaining",
        "Passed": order_status_whitespace_remaining == 0
    })


# ---------------------------------------------------------
# 2. OrderStatus Canonicalization Validation
# ---------------------------------------------------------

approved_order_statuses = {
    "Completed",
    "Pending",
    "Shipped",
    "Cancelled"
}

for source_name, df in [
    ("Shopify", shopify_orders_clean),
    ("Amazon UAE", amazon_orders_clean),
    ("Noon", noon_orders_clean)
]:

    unexpected_statuses = sorted(
        set(df["OrderStatus"].dropna()) - approved_order_statuses
    )

    validation_results.append({
        "Validation": f"{source_name} OrderStatus canonicalization",
        "Expected": "Only Completed, Pending, Shipped, and Cancelled",
        "Actual": (
            "All values canonical"
            if not unexpected_statuses
            else f"Unexpected values: {unexpected_statuses}"
        ),
        "Passed": len(unexpected_statuses) == 0
    })


# ---------------------------------------------------------
# 3. OrderStatus Source-to-Clean Value Validation
# ---------------------------------------------------------

for source_name, raw_df, clean_df in [
    ("Shopify", shopify_orders_raw, shopify_orders_clean),
    ("Amazon UAE", amazon_orders_raw, amazon_orders_clean),
    ("Noon", noon_orders_raw, noon_orders_clean)
]:

    expected_statuses = (
        raw_df["OrderStatus"]
        .str.strip()
        .str.lower()
        .replace(status_standardization)
    )

    status_values_match = (
        expected_statuses.reset_index(drop=True)
        == clean_df["OrderStatus"].reset_index(drop=True)
    ).all()

    validation_results.append({
        "Validation": f"{source_name} OrderStatus source-to-clean mapping",
        "Expected": "Trimmed source statuses map to approved canonical values",
        "Actual": f"Mapping matches: {status_values_match}",
        "Passed": status_values_match
    })


# ---------------------------------------------------------
# 4. OrderDate Datetime Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_orders_clean),
    ("Amazon UAE", amazon_orders_clean),
    ("Noon", noon_orders_clean)
]:

    order_date_is_datetime = pd.api.types.is_datetime64_any_dtype(
        df["OrderDate"]
    )

    validation_results.append({
        "Validation": f"{source_name} OrderDate datetime conversion",
        "Expected": "datetime64 datatype",
        "Actual": str(df["OrderDate"].dtype),
        "Passed": order_date_is_datetime
    })


# ---------------------------------------------------------
# 5. CreatedOn Datetime Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_orders_clean),
    ("Amazon UAE", amazon_orders_clean),
    ("Noon", noon_orders_clean)
]:

    created_on_is_datetime = pd.api.types.is_datetime64_any_dtype(
        df["CreatedOn"]
    )

    validation_results.append({
        "Validation": f"{source_name} CreatedOn datetime conversion",
        "Expected": "datetime64 datatype",
        "Actual": str(df["CreatedOn"].dtype),
        "Passed": created_on_is_datetime
    })


# ---------------------------------------------------------
# 6. ModifiedOn Datetime Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_orders_clean),
    ("Amazon UAE", amazon_orders_clean),
    ("Noon", noon_orders_clean)
]:

    modified_on_is_datetime = pd.api.types.is_datetime64_any_dtype(
        df["ModifiedOn"]
    )

    validation_results.append({
        "Validation": f"{source_name} ModifiedOn datetime conversion",
        "Expected": "datetime64 datatype",
        "Actual": str(df["ModifiedOn"].dtype),
        "Passed": modified_on_is_datetime
    })


# ---------------------------------------------------------
# 7. Amazon SO013 Outlier Retention Validation
# ---------------------------------------------------------

raw_so013_amount = amazon_orders_raw.loc[
    amazon_orders_raw["SourceOrderIDInternal"] == "SO013",
    "OrderGrossAmount"
].iloc[0]

clean_so013_amount = amazon_orders_clean.loc[
    amazon_orders_clean["SourceOrderIDInternal"] == "SO013",
    "OrderGrossAmount"
].iloc[0]

so013_retained = raw_so013_amount == clean_so013_amount

validation_results.append({
    "Validation": "Amazon SO013 outlier candidate retention",
    "Expected": f"OrderGrossAmount remains {raw_so013_amount}",
    "Actual": f"OrderGrossAmount is {clean_so013_amount}",
    "Passed": so013_retained
})


# ---------------------------------------------------------
# 8. SO005 CAM002 Temporal Exception Retention
# ---------------------------------------------------------

raw_so005 = shopify_orders_raw.loc[
    shopify_orders_raw["SourceOrderIDInternal"] == "SO005"
].iloc[0]

clean_so005 = shopify_orders_clean.loc[
    shopify_orders_clean["SourceOrderIDInternal"] == "SO005"
].iloc[0]

raw_so005_order_date = pd.to_datetime(
    raw_so005["OrderDate"],
    errors="raise"
)

so005_date_retained = (
    raw_so005_order_date == clean_so005["OrderDate"]
)

so005_campaign_retained = (
    raw_so005["CampaignCode"] == clean_so005["CampaignCode"]
)

validation_results.append({
    "Validation": "SO005 CAM002 temporal exception retention",
    "Expected": "OrderDate and CampaignCode remain unchanged",
    "Actual": (
        f"OrderDate unchanged: {so005_date_retained}; "
        f"CampaignCode unchanged: {so005_campaign_retained}"
    ),
    "Passed": (
        so005_date_retained
        and so005_campaign_retained
    )
})


# ---------------------------------------------------------
# 9. SO007 CAM002 Temporal Exception Retention
# ---------------------------------------------------------

raw_so007 = shopify_orders_raw.loc[
    shopify_orders_raw["SourceOrderIDInternal"] == "SO007"
].iloc[0]

clean_so007 = shopify_orders_clean.loc[
    shopify_orders_clean["SourceOrderIDInternal"] == "SO007"
].iloc[0]

raw_so007_order_date = pd.to_datetime(
    raw_so007["OrderDate"],
    errors="raise"
)

so007_date_retained = (
    raw_so007_order_date == clean_so007["OrderDate"]
)

so007_campaign_retained = (
    raw_so007["CampaignCode"] == clean_so007["CampaignCode"]
)

validation_results.append({
    "Validation": "SO007 CAM002 temporal exception retention",
    "Expected": "OrderDate and CampaignCode remain unchanged",
    "Actual": (
        f"OrderDate unchanged: {so007_date_retained}; "
        f"CampaignCode unchanged: {so007_campaign_retained}"
    ),
    "Passed": (
        so007_date_retained
        and so007_campaign_retained
    )
})


# ---------------------------------------------------------
# 10. SO007 Payment Reconciliation Exception Retention
# ---------------------------------------------------------

raw_so007_total = shopify_orders_raw.loc[
    shopify_orders_raw["SourceOrderIDInternal"] == "SO007",
    "OrderGrossAmount"
].iloc[0]

clean_so007_total = shopify_orders_clean.loc[
    shopify_orders_clean["SourceOrderIDInternal"] == "SO007",
    "OrderGrossAmount"
].iloc[0]

so007_total_retained = (
    raw_so007_total == clean_so007_total
)

validation_results.append({
    "Validation": "SO007 payment reconciliation exception retention",
    "Expected": f"OrderGrossAmount remains {raw_so007_total}",
    "Actual": f"OrderGrossAmount is {clean_so007_total}",
    "Passed": so007_total_retained
})


# ---------------------------------------------------------
# Transformation Validation Results
# ---------------------------------------------------------

transformation_validation = pd.DataFrame(
    validation_results
)

print("TRANSFORMATION VALIDATION RESULTS")
print("=" * 120)

display(transformation_validation)


# ---------------------------------------------------------
# Overall Result
# ---------------------------------------------------------

overall_validation_passed = (
    transformation_validation["Passed"].all()
)

print(
    "\nOverall Transformation Validation Passed:",
    overall_validation_passed
)

if not overall_validation_passed:
    raise ValueError(
        "Transformation validation failed. Review the results "
        "before proceeding."
    )

TRANSFORMATION VALIDATION RESULTS
========================================================================================================================

                                          Validation                                                  Expected                                                   Actual  Passed
0             Shopify OrderStatus whitespace removal                0 records with leading/trailing whitespace                                      0 records remaining    True
1          Amazon UAE OrderStatus whitespace removal                0 records with leading/trailing whitespace                                      0 records remaining    True
2                Noon OrderStatus whitespace removal                0 records with leading/trailing whitespace                                      0 records remaining    True
3               Shopify OrderStatus canonicalization           Only Completed, Pending, Shipped, and Cancelled                                     All values canonical    True
4            Amazon UAE OrderStatus canonicalization           Only Completed, Pending, Shipped, and Cancelled                                     All values canonical    True
5                  Noon OrderStatus canonicalization           Only Completed, Pending, Shipped, and Cancelled                                     All values canonical    True
6        Shopify OrderStatus source-to-clean mapping  Trimmed source statuses map to approved canonical values                                    Mapping matches: True    True
7     Amazon UAE OrderStatus source-to-clean mapping  Trimmed source statuses map to approved canonical values                                    Mapping matches: True    True
8           Noon OrderStatus source-to-clean mapping  Trimmed source statuses map to approved canonical values                                    Mapping matches: True    True
9              Shopify OrderDate datetime conversion                                       datetime64 datatype                                           datetime64[ns]    True
10          Amazon UAE OrderDate datetime conversion                                       datetime64 datatype                                           datetime64[ns]    True
11                Noon OrderDate datetime conversion                                       datetime64 datatype                                           datetime64[ns]    True
12             Shopify CreatedOn datetime conversion                                       datetime64 datatype                                           datetime64[ns]    True
13          Amazon UAE CreatedOn datetime conversion                                       datetime64 datatype                                           datetime64[ns]    True
14                Noon CreatedOn datetime conversion                                       datetime64 datatype                                           datetime64[ns]    True
15            Shopify ModifiedOn datetime conversion                                       datetime64 datatype                                           datetime64[ns]    True
16         Amazon UAE ModifiedOn datetime conversion                                       datetime64 datatype                                           datetime64[ns]    True
17               Noon ModifiedOn datetime conversion                                       datetime64 datatype                                           datetime64[ns]    True
18          Amazon SO013 outlier candidate retention                             OrderGrossAmount remains 3298                                 OrderGrossAmount is 3298    True
19         SO005 CAM002 temporal exception retention               OrderDate and CampaignCode remain unchanged  OrderDate unchanged: True; CampaignCode unchanged: True    True
20         SO007 CAM002 temporal exception retention               OrderDate and CampaignCode remain unchanged  OrderDate unchanged: True; CampaignCode unchanged: True    True
21  SO007 payment reconciliation exception retention                             OrderGrossAmount remains 3257                                 OrderGrossAmount is 3257    True

Overall Transformation Validation Passed: True

## 3.2 Validate Data Preservation

Validate that the approved transformations did not unintentionally alter unaffected Sales Order data.

The validation compares the raw and cleaned datasets while accounting for the approved transformations:

- OrderStatus whitespace removal and canonicalization
- OrderDate datatype conversion
- CreatedOn datatype conversion
- ModifiedOn datatype conversion

All other business and audit field values should remain unchanged.

Each source dataset will be validated separately.

In [40]:
# =========================================================
# 3.2 Validate Data Preservation
# =========================================================

# Columns that should remain completely unchanged after accounting for approved transformations
unchanged_columns = [
    "SourceSystem",
    "SourceOrderID",
    "SourceOrderIDInternal",
    "CustomerCode",
    "CampaignCode",
    "ShipToAddress",
    "BillToAddress",
    "PaymentMethod",
    "OrderGrossAmount",
    "OrderNotes",
    "CreatedByUser",
    "ModifiedByUser"
]


all_datasets_match = True


# =========================================================
# Shopify
# =========================================================

print("=" * 70)
print("SHOPIFY SALES ORDER DATA PRESERVATION")
print("=" * 70)

for column in unchanged_columns:

    matches = (
        shopify_orders_raw[column]
        .astype(str)
        .reset_index(drop=True)
        ==
        shopify_orders_clean[column]
        .astype(str)
        .reset_index(drop=True)
    ).all()

    print(f"{column}: {matches}")

    if not matches:
        all_datasets_match = False


# =========================================================
# Amazon UAE
# =========================================================

print("\n" + "=" * 70)
print("AMAZON UAE SALES ORDER DATA PRESERVATION")
print("=" * 70)

for column in unchanged_columns:

    matches = (
        amazon_orders_raw[column]
        .astype(str)
        .reset_index(drop=True)
        ==
        amazon_orders_clean[column]
        .astype(str)
        .reset_index(drop=True)
    ).all()

    print(f"{column}: {matches}")

    if not matches:
        all_datasets_match = False


# =========================================================
# Noon
# =========================================================

print("\n" + "=" * 70)
print("NOON SALES ORDER DATA PRESERVATION")
print("=" * 70)

for column in unchanged_columns:

    matches = (
        noon_orders_raw[column]
        .astype(str)
        .reset_index(drop=True)
        ==
        noon_orders_clean[column]
        .astype(str)
        .reset_index(drop=True)
    ).all()

    print(f"{column}: {matches}")

    if not matches:
        all_datasets_match = False


# =========================================================
# Final Validation
# =========================================================

print(
    "\nAll unaffected Sales Order columns preserved:",
    all_datasets_match
)

if not all_datasets_match:
    raise ValueError(
        "Data preservation validation failed. "
        "An unaffected Sales Order column was unexpectedly changed."
    )

======================================================================
SHOPIFY SALES ORDER DATA PRESERVATION
======================================================================
SourceSystem: True
SourceOrderID: True
SourceOrderIDInternal: True
CustomerCode: True
CampaignCode: True
ShipToAddress: True
BillToAddress: True
PaymentMethod: True
OrderGrossAmount: True
OrderNotes: True
CreatedByUser: True
ModifiedByUser: True

======================================================================
AMAZON UAE SALES ORDER DATA PRESERVATION
======================================================================
SourceSystem: True
SourceOrderID: True
SourceOrderIDInternal: True
CustomerCode: True
CampaignCode: True
ShipToAddress: True
BillToAddress: True
PaymentMethod: True
OrderGrossAmount: True
OrderNotes: True
CreatedByUser: True
ModifiedByUser: True

======================================================================
NOON SALES ORDER DATA PRESERVATION
======================================================================
SourceSystem: True
SourceOrderID: True
SourceOrderIDInternal: True
CustomerCode: True
CampaignCode: True
ShipToAddress: True
BillToAddress: True
PaymentMethod: True
OrderGrossAmount: True
OrderNotes: True
CreatedByUser: True
ModifiedByUser: True

All unaffected Sales Order columns preserved: True

# =========================================================
# SECTION 4 — CLEAN CSV
# =========================================================

## 4.1 Consolidate Validated Sales Order Datasets

Consolidate the validated Clean DataFrames from Shopify, Amazon UAE,
and Noon into one consolidated Sales Order Clean DataFrame.

Consolidation is performed only after each source dataset has completed
its transformation and data preservation validation.

The source-specific Clean DataFrames must not be modified during
consolidation.

The consolidated dataset must:

- Combine the validated records from all three source systems.
- Preserve the approved column structure.
- Preserve source-system lineage.
- Preserve SourceOrderID and SourceOrderIDInternal.
- Preserve approved business values and NULL values.
- Not generate or resequence Sales Order identifiers.
- Not correct or modify source-specific business exceptions.
- Not introduce unexpected columns.

The result will be one consolidated Clean DataFrame representing the
validated Sales Order records from all source systems.

In [41]:
# =========================================================
# 4.1 Consolidate Validated Sales Order Datasets
# =========================================================

# ---------------------------------------------------------
# 1. Define the expected consolidated column structure
# ---------------------------------------------------------

sales_order_clean_columns = [
    "SourceSystem",
    "SourceOrderID",
    "SourceOrderIDInternal",
    "CustomerCode",
    "CampaignCode",
    "OrderDate",
    "OrderStatus",
    "ShipToAddress",
    "BillToAddress",
    "PaymentMethod",
    "OrderGrossAmount",
    "OrderNotes",
    "CreatedOn",
    "CreatedByUser",
    "ModifiedOn",
    "ModifiedByUser"
]


# ---------------------------------------------------------
# 2. Validate column compatibility before consolidation
# ---------------------------------------------------------

shopify_columns_match = (
    shopify_orders_clean.columns.tolist()
    == sales_order_clean_columns
)

amazon_columns_match = (
    amazon_orders_clean.columns.tolist()
    == sales_order_clean_columns
)

noon_columns_match = (
    noon_orders_clean.columns.tolist()
    == sales_order_clean_columns
)

print("Column structure validation:")
print("Shopify:", shopify_columns_match)
print("Amazon UAE:", amazon_columns_match)
print("Noon:", noon_columns_match)


if not all([
    shopify_columns_match,
    amazon_columns_match,
    noon_columns_match
]):
    raise ValueError(
        "Consolidation stopped. "
        "One or more source datasets do not have the expected "
        "Sales Order column structure."
    )


# ---------------------------------------------------------
# 3. Record validated source row counts
# ---------------------------------------------------------

shopify_clean_row_count = shopify_orders_clean.shape[0]
amazon_clean_row_count = amazon_orders_clean.shape[0]
noon_clean_row_count = noon_orders_clean.shape[0]

expected_consolidated_row_count = (
    shopify_clean_row_count
    + amazon_clean_row_count
    + noon_clean_row_count
)

print("\nValidated source row counts:")
print("Shopify:", shopify_clean_row_count)
print("Amazon UAE:", amazon_clean_row_count)
print("Noon:", noon_clean_row_count)

print(
    "\nExpected consolidated row count:",
    expected_consolidated_row_count
)


# ---------------------------------------------------------
# 4. Consolidate validated Clean DataFrames
# ---------------------------------------------------------

sales_order_clean = pd.concat(
    [
        shopify_orders_clean,
        amazon_orders_clean,
        noon_orders_clean
    ],
    axis=0,
    ignore_index=True
)


# ---------------------------------------------------------
# 5. Confirm consolidated structure and row count
# ---------------------------------------------------------

print("\nConsolidated Sales Order dataset created.")

print("Consolidated shape:")
print(sales_order_clean.shape)

print("\nConsolidated columns:")
print(sales_order_clean.columns.tolist())

print(
    "\nActual consolidated row count:",
    sales_order_clean.shape[0]
)

print(
    "Expected consolidated row count:",
    expected_consolidated_row_count
)


# ---------------------------------------------------------
# 6. Validate consolidated row count
# ---------------------------------------------------------

if sales_order_clean.shape[0] != expected_consolidated_row_count:
    raise ValueError(
        "Consolidation validation failed. "
        "The consolidated row count does not match the "
        "sum of the validated source datasets."
    )


# ---------------------------------------------------------
# 7. Confirm source-system distribution
# ---------------------------------------------------------

print("\nRecords by source system:")
print(
    sales_order_clean["SourceSystem"]
    .value_counts()
)


# ---------------------------------------------------------
# 8. Confirm source lineage fields are populated
# ---------------------------------------------------------

print("\nSource lineage validation:")

print(
    "SourceSystem nulls:",
    sales_order_clean["SourceSystem"].isnull().sum()
)

print(
    "SourceOrderID nulls:",
    sales_order_clean["SourceOrderID"].isnull().sum()
)

print(
    "SourceOrderIDInternal nulls:",
    sales_order_clean["SourceOrderIDInternal"].isnull().sum()
)


# ---------------------------------------------------------
# 9. Final consolidation validation
# ---------------------------------------------------------

consolidation_passed = (
    sales_order_clean.shape[0]
    == expected_consolidated_row_count
    and sales_order_clean.columns.tolist()
    == sales_order_clean_columns
    and sales_order_clean["SourceSystem"].notna().all()
    and sales_order_clean["SourceOrderID"].notna().all()
    and sales_order_clean["SourceOrderIDInternal"].notna().all()
)

print(
    "\nConsolidation Validation Passed:",
    consolidation_passed
)

if not consolidation_passed:
    raise ValueError(
        "Sales Order consolidation validation failed."
    )

Column structure validation:
Shopify: True
Amazon UAE: True
Noon: True

Validated source row counts:
Shopify: 7
Amazon UAE: 7
Noon: 6

Expected consolidated row count: 20

Consolidated Sales Order dataset created.
Consolidated shape:
(20, 16)

Consolidated columns:
['SourceSystem', 'SourceOrderID', 'SourceOrderIDInternal', 'CustomerCode', 'CampaignCode', 'OrderDate', 'OrderStatus', 'ShipToAddress', 'BillToAddress', 'PaymentMethod', 'OrderGrossAmount', 'OrderNotes', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Actual consolidated row count: 20
Expected consolidated row count: 20

Records by source system:
SourceSystem
Shopify       7
Amazon UAE    7
Noon          6
Name: count, dtype: int64

Source lineage validation:
SourceSystem nulls: 0
SourceOrderID nulls: 0
SourceOrderIDInternal nulls: 0

Consolidation Validation Passed: True

## 4.2 Export Consolidated Clean Sales Order Dataset

Export the validated consolidated `sales_order_clean` DataFrame as the
clean Sales Order dataset.

The clean CSV represents the completed data-cleaning and consolidation
stage and preserves the validated Sales Order records from Shopify,
Amazon UAE, and Noon before database-ready column mapping begins.

In [42]:
# =========================================================
# 4.2 Export Consolidated Clean Sales Order Dataset
# =========================================================

from pathlib import Path

clean_sales_order_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\12_Commerce_Consolidated\Sales_Order\clean"
    r"\sales_order_clean.csv"
)

# Create the clean folder if it does not exist
clean_sales_order_path.parent.mkdir(
    parents=True,
    exist_ok=True
)

# Export consolidated clean dataset
sales_order_clean.to_csv(
    clean_sales_order_path,
    index=False
)

print("Consolidated Clean Sales Order CSV exported successfully.")
print("Path:", clean_sales_order_path)
print("Rows exported:", len(sales_order_clean))
print("Columns exported:", len(sales_order_clean.columns))

Consolidated Clean Sales Order CSV exported successfully.
Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\12_Commerce_Consolidated\Sales_Order\clean\sales_order_clean.csv
Rows exported: 20
Columns exported: 16

## 4.3 Verify Exported Clean Sales Order CSV

Reload the exported consolidated Clean Sales Order CSV and verify that
it matches the validated consolidated `sales_order_clean` DataFrame.

This confirms that the persisted consolidated Clean CSV is the official
handoff artifact for the next pipeline stage.

The verification must confirm:

- Row count
- Column names and order
- Reloaded datatypes
- Data content

The exported CSV must represent the same validated records produced
during the controlled consolidation stage.

In [43]:
# =========================================================
# 4.3 Verify Exported Clean Sales Order CSV
# =========================================================

# Reload the exported consolidated clean CSV
sales_order_clean_csv = pd.read_csv(
    clean_sales_order_path,
    parse_dates=[
        "OrderDate",
        "CreatedOn",
        "ModifiedOn"
    ]
)


# ---------------------------------------------------------
# Basic Export Validation
# ---------------------------------------------------------

print(
    "Clean CSV rows:",
    len(sales_order_clean_csv)
)

print(
    "Clean DataFrame rows:",
    len(sales_order_clean)
)

print(
    "\nClean CSV columns:",
    len(sales_order_clean_csv.columns)
)

print(
    "Clean DataFrame columns:",
    len(sales_order_clean.columns)
)


# ---------------------------------------------------------
# Row Count Validation
# ---------------------------------------------------------

row_count_match = (
    len(sales_order_clean_csv)
    == len(sales_order_clean)
)

print(
    "\nRow count matches:",
    row_count_match
)


# ---------------------------------------------------------
# Column Validation
# ---------------------------------------------------------

columns_match = (
    list(sales_order_clean_csv.columns)
    == list(sales_order_clean.columns)
)

print(
    "Column names and order match:",
    columns_match
)


# ---------------------------------------------------------
# Datatype Validation
# ---------------------------------------------------------

print("\nReloaded Clean CSV datatypes:")
print(sales_order_clean_csv.dtypes)


# ---------------------------------------------------------
# Content Validation
# ---------------------------------------------------------

content_match = (
    sales_order_clean
    .reset_index(drop=True)
    .equals(
        sales_order_clean_csv
        .reset_index(drop=True)
    )
)

print(
    "\nClean DataFrame and exported CSV content match:",
    content_match
)


# ---------------------------------------------------------
# Final Validation
# ---------------------------------------------------------

export_validation_passed = (
    row_count_match
    and columns_match
    and content_match
)

print(
    "\n" + "=" * 80
)

print(
    "EXPORTED CLEAN CSV VALIDATION PASSED:",
    export_validation_passed
)

print(
    "=" * 80
)


if not export_validation_passed:
    raise ValueError(
        "Exported consolidated clean CSV validation failed. "
        "Review the results before proceeding."
    )

Clean CSV rows: 20
Clean DataFrame rows: 20

Clean CSV columns: 16
Clean DataFrame columns: 16

Row count matches: True
Column names and order match: True

Reloaded Clean CSV datatypes:
SourceSystem                     object
SourceOrderID                    object
SourceOrderIDInternal            object
CustomerCode                     object
CampaignCode                     object
OrderDate                datetime64[ns]
OrderStatus                      object
ShipToAddress                    object
BillToAddress                    object
PaymentMethod                    object
OrderGrossAmount                  int64
OrderNotes                      float64
CreatedOn                datetime64[ns]
CreatedByUser                    object
ModifiedOn               datetime64[ns]
ModifiedByUser                   object
dtype: object

Clean DataFrame and exported CSV content match: True

================================================================================
EXPORTED CLEAN CSV VALIDATION PASSED: True
================================================================================

# =========================================================
# SECTION 5 — DATABASE READY
# =========================================================

## 5.1 Define Source → Target Mapping

Define the approved source-to-target column mapping based on the
LJ Dev Commerce Sales Order Data Dictionary.

The mapping converts the consolidated Clean Sales Order column names
into the standardized PostgreSQL target column names.

No data values are modified during this step.

In [44]:
# =========================================================
# 5.1 Define Source → Target Mapping
# =========================================================

sales_order_column_mapping = {
    "SourceOrderIDInternal": "sales_order_id",
    "CustomerCode": "customer_id",
    "CampaignCode": "campaign_id",
    "OrderDate": "order_date",
    "OrderStatus": "order_status",
    "ShipToAddress": "shipping_address",
    "BillToAddress": "billing_address",
    "PaymentMethod": "payment_method",
    "OrderGrossAmount": "order_total",
    "OrderNotes": "notes",
    "CreatedOn": "created_date",
    "CreatedByUser": "created_by",
    "ModifiedOn": "updated_date",
    "ModifiedByUser": "updated_by"
}

print("Sales Order Source → Target Mapping")
print("=" * 80)

for source_column, target_column in sales_order_column_mapping.items():
    print(f"{source_column:<25} → {target_column}")

Sales Order Source → Target Mapping
================================================================================
SourceOrderIDInternal     → sales_order_id
CustomerCode              → customer_id
CampaignCode              → campaign_id
OrderDate                 → order_date
OrderStatus               → order_status
ShipToAddress             → shipping_address
BillToAddress             → billing_address
PaymentMethod             → payment_method
OrderGrossAmount          → order_total
OrderNotes                → notes
CreatedOn                 → created_date
CreatedByUser             → created_by
ModifiedOn                → updated_date
ModifiedByUser            → updated_by

## 5.2 Create Database-Ready Dataset

Create the Sales Order Database-Ready dataset from the verified
exported consolidated Clean CSV.

The approved source-to-target mapping is then applied to convert the
source column names into the PostgreSQL target structure.

The Clean CSV remains unchanged.

No undocumented business-value transformations are applied during
this step.

Source-system lineage fields that are not part of the current
PostgreSQL target structure remain available in the verified Clean CSV
for source traceability and reconciliation.

In [74]:
# =========================================================
# 5.2 Create Database-Ready Dataset
# =========================================================

from decimal import Decimal

# Define the verified exported consolidated Clean CSV path
sales_order_clean_path = (
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data"
    r"\12_Commerce_Consolidated\Sales_Order\clean"
    r"\sales_order_clean.csv"
)

# Load the verified exported consolidated Clean CSV
sales_order_clean_exported = pd.read_csv(
    sales_order_clean_path
)

# Convert approved date columns back to datetime
sales_order_clean_exported["OrderDate"] = pd.to_datetime(
    sales_order_clean_exported["OrderDate"]
)

sales_order_clean_exported["CreatedOn"] = pd.to_datetime(
    sales_order_clean_exported["CreatedOn"]
)

sales_order_clean_exported["ModifiedOn"] = pd.to_datetime(
    sales_order_clean_exported["ModifiedOn"]
)

# Select only the approved source columns that map
# to the PostgreSQL Sales Order target structure
sales_order_db_ready = (
    sales_order_clean_exported[
        list(sales_order_column_mapping.keys())
    ]
    .rename(columns=sales_order_column_mapping)
    .copy()
)

# ---------------------------------------------------------
# Convert Approved Nullable Fields to SQL NULL-Compatible
# Python None Values
# ---------------------------------------------------------

nullable_columns = [
    "campaign_id",
    "shipping_address",
    "notes"
]

for column in nullable_columns:
    sales_order_db_ready[column] = (
        sales_order_db_ready[column]
        .astype(object)
        .where(
            sales_order_db_ready[column].notna(),
            None
        )
    )

# ---------------------------------------------------------
# Prepare Decimal-Compatible Order Total
# ---------------------------------------------------------

sales_order_db_ready["order_total"] = (
    sales_order_db_ready["order_total"]
    .apply(Decimal)
)

print("Sales Order Database-Ready Dataset Created Successfully.")
print("=" * 80)

print("\nSource: Verified Exported Consolidated Clean CSV")

print("\nDatabase-Ready Dataset Shape:")
print(sales_order_db_ready.shape)

print("\nDatabase-Ready Column Names:")
print(sales_order_db_ready.columns.tolist())

print("\nDatabase-Ready Data Types:")
print(sales_order_db_ready.dtypes)

print("\nDatabase-Ready Missing Values:")
print(sales_order_db_ready.isnull().sum())

print("\nDatabase-Ready Dataset:")
display(sales_order_db_ready)

Sales Order Database-Ready Dataset Created Successfully.
================================================================================

Source: Verified Exported Consolidated Clean CSV

Database-Ready Dataset Shape:
(20, 14)

Database-Ready Column Names:
['sales_order_id', 'customer_id', 'campaign_id', 'order_date', 'order_status', 'shipping_address', 'billing_address', 'payment_method', 'order_total', 'notes', 'created_date', 'created_by', 'updated_date', 'updated_by']

Database-Ready Data Types:
sales_order_id              object
customer_id                 object
campaign_id                 object
order_date          datetime64[ns]
order_status                object
shipping_address            object
billing_address             object
payment_method              object
order_total                 object
notes                       object
created_date        datetime64[ns]
created_by                  object
updated_date        datetime64[ns]
updated_by                  object
dtype: object

Database-Ready Missing Values:
sales_order_id       0
customer_id          0
campaign_id          9
order_date           0
order_status         0
shipping_address     0
billing_address      0
payment_method       0
order_total          0
notes               20
created_date         0
created_by           0
updated_date         0
updated_by           0
dtype: int64

Database-Ready Dataset:

   sales_order_id customer_id campaign_id order_date order_status           shipping_address            billing_address    payment_method order_total notes created_date created_by updated_date updated_by
0           SO001        C001      CAM001 2026-07-05    Completed         Al Jafiliya, Dubai         Al Jafiliya, Dubai              Visa        3198  None   2026-07-05      admin   2026-07-05      admin
1           SO002        C002      CAM004 2026-07-06    Completed             Makati, Manila             Makati, Manila       Credit Card        2199  None   2026-07-06      admin   2026-07-06      admin
2           SO003        C003        None 2026-07-07    Completed        Dubai Marina, Dubai        Dubai Marina, Dubai  Cash on Delivery        1399  None   2026-07-07      admin   2026-07-07      admin
3           SO004        C004      CAM001 2026-07-08      Shipped            Al Nahda, Dubai            Al Nahda, Dubai              Visa        4298  None   2026-07-08      admin   2026-07-08      admin
4           SO005        C005      CAM002 2026-07-09    Completed  Abu Dhabi City, Abu Dhabi  Abu Dhabi City, Abu Dhabi        Mastercard        3448  None   2026-07-09      admin   2026-07-09      admin
5           SO006        C006        None 2026-07-10      Pending            Jumeirah, Dubai            Jumeirah, Dubai  Cash on Delivery         699  None   2026-07-10      admin   2026-07-10      admin
6           SO007        C007      CAM002 2026-07-11    Completed      Sharjah City, Sharjah      Sharjah City, Sharjah              Visa        3257  None   2026-07-11      admin   2026-07-11      admin
7           SO008        C008        None 2026-07-12    Completed               Deira, Dubai               Deira, Dubai       Credit Card        1599  None   2026-07-12      admin   2026-07-12      admin
8           SO009        C009      CAM001 2026-07-13    Completed           Al Barsha, Dubai           Al Barsha, Dubai              Visa         399  None   2026-07-13      admin   2026-07-13      admin
9           SO010        C010        None 2026-07-14    Cancelled    Khalifa City, Abu Dhabi    Khalifa City, Abu Dhabi       Credit Card         449  None   2026-07-14      admin   2026-07-14      admin
10          SO011        C011      CAM004 2026-07-15    Completed           Bur Dubai, Dubai           Bur Dubai, Dubai  Cash on Delivery         499  None   2026-07-15      admin   2026-07-15      admin
11          SO012        C012        None 2026-07-16    Completed          Ajman City, Ajman          Ajman City, Ajman              Visa         699  None   2026-07-16      admin   2026-07-16      admin
12          SO013        C013      CAM002 2026-07-17    Completed        Business Bay, Dubai        Business Bay, Dubai        Mastercard        3298  None   2026-07-17      admin   2026-07-17      admin
13          SO014        C014        None 2026-07-18    Completed           Al Qusais, Dubai           Al Qusais, Dubai  Cash on Delivery         179  None   2026-07-18      admin   2026-07-18      admin
14          SO015        C015      CAM001 2026-07-19      Shipped              Mirdif, Dubai              Mirdif, Dubai              Visa        3598  None   2026-07-19      admin   2026-07-19      admin
15          SO016        C001        None 2026-07-20    Completed         Al Jafiliya, Dubai         Al Jafiliya, Dubai              Visa         699  None   2026-07-20      admin   2026-07-20      admin
16          SO017        C002      CAM004 2026-07-21    Completed             Makati, Manila             Makati, Manila       Credit Card         499  None   2026-07-21      admin   2026-07-21      admin
17          SO018        C003        None 2026-07-22    Completed        Dubai Marina, Dubai        Dubai Marina, Dubai        Mastercard        3899  None   2026-07-22      admin   2026-07-22      admin
18          SO019        C004      CAM002 2026-07-23      Pending            Al Nahda, Dubai            Al Nahda, Dubai  Cash on Delivery        2199  None   2026-07-23      admin   2026-07-23      admin
19          SO020        C005        None 2026-07-24    Completed  Abu Dhabi City, Abu Dhabi  Abu Dhabi City, Abu Dhabi              Visa        1599  None   2026-07-24      admin   2026-07-24      admin

## 5.3 Database-Ready Validation

Validate the Sales Order Database-Ready DataFrame before

PostgreSQL loading.

This validation confirms that:

* The row count is preserved from the verified Clean CSV.
* All expected target columns are present.
* Target columns are in the approved order.
* The source-to-target mapping is complete.
* No undocumented source columns were lost.
* Required fields do not contain NULL values.
* The primary key is unique and does not contain NULL values.
* The dataset is prepared for PostgreSQL table verification and loading.

In [75]:
# =========================================================
# 5.3 Database-Ready Validation
# =========================================================

print("Sales Order Database-Ready Validation")
print("=" * 80)


# ---------------------------------------------------------
# 1. Row Count Validation
# ---------------------------------------------------------

print("\n1. Row Count Validation")

clean_csv_row_count = len(
    sales_order_clean_exported
)

database_ready_row_count = len(
    sales_order_db_ready
)

row_count_match = (
    clean_csv_row_count
    == database_ready_row_count
)

print(
    "Verified Clean CSV rows:",
    clean_csv_row_count
)

print(
    "Database-Ready rows:",
    database_ready_row_count
)

print(
    "Row counts match:",
    row_count_match
)


# ---------------------------------------------------------
# 2. Expected Target Column Validation
# ---------------------------------------------------------

print("\n2. Expected Target Column Validation")

expected_target_columns = list(
    sales_order_column_mapping.values()
)

actual_target_columns = (
    sales_order_db_ready.columns.tolist()
)

target_columns_match = (
    expected_target_columns
    == actual_target_columns
)

print("Expected target columns:")
print(expected_target_columns)

print("\nActual Database-Ready columns:")
print(actual_target_columns)

print(
    "\nColumns and order match:",
    target_columns_match
)


# ---------------------------------------------------------
# 3. Mapping Completeness Validation
# ---------------------------------------------------------

print("\n3. Mapping Completeness Validation")

source_columns = (
    sales_order_clean_exported.columns.tolist()
)

mapping_source_columns = list(
    sales_order_column_mapping.keys()
)

# These lineage columns intentionally remain in the
# Clean CSV but are not mapped to the current target table.
expected_unmapped_source_columns = [
    "SourceSystem",
    "SourceOrderID"
]

mapped_source_columns_present = (
    set(mapping_source_columns).issubset(
        set(source_columns)
    )
)

actual_unmapped_source_columns = (
    sorted(
        set(source_columns)
        - set(mapping_source_columns)
    )
)

unmapped_source_columns_expected = (
    actual_unmapped_source_columns
    == sorted(
        expected_unmapped_source_columns
    )
)

unexpected_mapping_source_columns = (
    sorted(
        set(mapping_source_columns)
        - set(source_columns)
    )
)

mapping_complete = (
    mapped_source_columns_present
    and unmapped_source_columns_expected
    and len(
        unexpected_mapping_source_columns
    ) == 0
)

print(
    "Mapped source columns are present:",
    mapped_source_columns_present
)

print(
    "Expected unmapped lineage columns:",
    expected_unmapped_source_columns
)

print(
    "Actual unmapped source columns:",
    actual_unmapped_source_columns
)

print(
    "Lineage exclusions are as expected:",
    unmapped_source_columns_expected
)

print(
    "Unexpected mapping source columns:",
    unexpected_mapping_source_columns
)

print(
    "Source-to-target mapping complete:",
    mapping_complete
)


# ---------------------------------------------------------
# 4. Required Field Validation
# ---------------------------------------------------------

print("\n4. Required Field Validation")

required_sales_order_fields = [
    "sales_order_id",
    "customer_id",
    "order_date",
    "order_status",
    "billing_address",
    "payment_method",
    "order_total",
    "created_date",
    "created_by",
    "updated_date",
    "updated_by"
]

null_counts = (
    sales_order_db_ready[
        required_sales_order_fields
    ].isnull().sum()
)

print(null_counts)

required_fields_valid = (
    null_counts.sum() == 0
)

print(
    "\nRows with NULL required values:",
    null_counts.sum()
)

print(
    "Required field validation passed:",
    required_fields_valid
)


# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

print("\n5. Primary Key Validation")

duplicate_primary_keys = (
    sales_order_db_ready[
        "sales_order_id"
    ]
    .duplicated()
    .sum()
)

null_primary_keys = (
    sales_order_db_ready[
        "sales_order_id"
    ]
    .isnull()
    .sum()
)

primary_key_valid = (
    duplicate_primary_keys == 0
    and null_primary_keys == 0
)

print(
    "Duplicate Primary Keys:",
    duplicate_primary_keys
)

print(
    "NULL Primary Keys:",
    null_primary_keys
)

print(
    "Primary Key validation passed:",
    primary_key_valid
)


# ---------------------------------------------------------
# 6. Overall Database-Ready Validation
# ---------------------------------------------------------

database_ready_validation_passed = (
    row_count_match
    and target_columns_match
    and mapping_complete
    and required_fields_valid
    and primary_key_valid
)

print("\n6. Database-Ready Validation Summary")
print("=" * 80)

print(
    "Database-Ready validation passed:",
    database_ready_validation_passed
)

Sales Order Database-Ready Validation
================================================================================

1. Row Count Validation
Verified Clean CSV rows: 20
Database-Ready rows: 20
Row counts match: True

2. Expected Target Column Validation
Expected target columns:
['sales_order_id', 'customer_id', 'campaign_id', 'order_date', 'order_status', 'shipping_address', 'billing_address', 'payment_method', 'order_total', 'notes', 'created_date', 'created_by', 'updated_date', 'updated_by']

Actual Database-Ready columns:
['sales_order_id', 'customer_id', 'campaign_id', 'order_date', 'order_status', 'shipping_address', 'billing_address', 'payment_method', 'order_total', 'notes', 'created_date', 'created_by', 'updated_date', 'updated_by']

Columns and order match: True

3. Mapping Completeness Validation
Mapped source columns are present: True
Expected unmapped lineage columns: ['SourceSystem', 'SourceOrderID']
Actual unmapped source columns: ['SourceOrderID', 'SourceSystem']
Lineage exclusions are as expected: True
Unexpected mapping source columns: []
Source-to-target mapping complete: True

4. Required Field Validation
sales_order_id     0
customer_id        0
order_date         0
order_status       0
billing_address    0
payment_method     0
order_total        0
created_date       0
created_by         0
updated_date       0
updated_by         0
dtype: int64

Rows with NULL required values: 0
Required field validation passed: True

5. Primary Key Validation
Duplicate Primary Keys: 0
NULL Primary Keys: 0
Primary Key validation passed: True

6. Database-Ready Validation Summary
================================================================================
Database-Ready validation passed: True

# =========================================================
# 6.1 Connect to PostgreSQL
# =========================================================

import psycopg2
from getpass import getpass


# ---------------------------------------------------------
# PostgreSQL Connection Configuration
# ---------------------------------------------------------

DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "lj_dev_commerce"
DB_USER = "postgres"

DB_PASSWORD = getpass("Enter PostgreSQL password: ")


# ---------------------------------------------------------
# Connect to PostgreSQL
# ---------------------------------------------------------

try:
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD
    )

    cursor = conn.cursor()

    print("PostgreSQL connection successful.")
    print("Database:", DB_NAME)
    print("Host:", DB_HOST)
    print("Port:", DB_PORT)

except Exception as e:
    print("PostgreSQL connection failed.")
    print("Error:", e)

# =========================================================
# SECTION 6 — PostgreSQL
# =========================================================

Connect to PostgreSQL and confirm that the ETL notebook is connected to

the correct database and PostgreSQL environment.

No table changes or data loading are performed in this step.

## 6.1 Connect

Establish a PostgreSQL connection for the Sales Order ETL

process.

Confirm that:

* The PostgreSQL connection is successful.

* The correct database is connected.

* The correct PostgreSQL user is connected.

* The target schema is available.

No records are inserted during this step.

In [48]:
# =========================================================
# 6.1 Connect to PostgreSQL
# =========================================================

import psycopg2
from getpass import getpass


# ---------------------------------------------------------
# PostgreSQL Connection Configuration
# ---------------------------------------------------------

DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "lj_dev_commerce"
DB_USER = "postgres"

DB_PASSWORD = getpass("Enter PostgreSQL password: ")


# ---------------------------------------------------------
# Connect to PostgreSQL
# ---------------------------------------------------------

try:
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD
    )

    cursor = conn.cursor()

    print("PostgreSQL connection successful.")
    print("Database:", DB_NAME)
    print("Host:", DB_HOST)
    print("Port:", DB_PORT)

except Exception as e:
    print("PostgreSQL connection failed.")
    print("Error:", e)

PostgreSQL connection successful.
Database: lj_dev_commerce
Host: localhost
Port: 5432

## 6.2 Prepare / Create Target Table

Check whether the approved Sales Order PostgreSQL target table

already exists before creating or modifying anything.

Target:

Schema: commerce

Table: sales_order

The table must not be recreated blindly. Its existence and approved

database design must be confirmed first.

In [49]:
# =========================================================
# 6.2 Prepare / Create Target Table
# =========================================================

target_schema = "commerce"
target_table = "sales_order"

# Check whether the target table already exists
cursor.execute("""
    SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = %s
          AND table_name = %s
    );
""", (target_schema, target_table))

table_exists = cursor.fetchone()[0]

print("Sales Order Target Table Check")
print("=" * 80)

print("Schema:", target_schema)
print("Table:", target_table)
print("Table exists:", table_exists)

if table_exists:
    print("\nTarget table already exists.")
    print("The table will not be recreated.")
else:
    print("\nTarget table does not exist.")
    print("The approved database design must be used before creating it.")

Sales Order Target Table Check
================================================================================
Schema: commerce
Table: sales_order
Table exists: False

Target table does not exist.
The approved database design must be used before creating it.

## 6.2.1 Create Sales Order Table

The `commerce.sales_order` table does not currently exist.

This section creates the Sales Order PostgreSQL target table based

on the approved LJ Dev Commerce Sales Order Data Dictionary.

Key design decisions:

- `sales_order_id` is the Primary Key.

- All required Data Dictionary fields use `NOT NULL`.

- `campaign_id`, `shipping_address`, and `notes` are optional and

  therefore allow `NULL`.

- `customer_id` and `campaign_id` are Foreign Keys based on the

  approved Sales Order database relationships.

- `order_date`, `created_date`, and `updated_date` use the PostgreSQL

  `TIMESTAMP` datatype.

- `order_total` uses the PostgreSQL `DECIMAL` datatype.

In [50]:
# =========================================================
# 6.2.1 Create Sales Order Table
# =========================================================

create_sales_order_table_query = """
CREATE TABLE commerce.sales_order (

    sales_order_id TEXT PRIMARY KEY,

    customer_id TEXT NOT NULL,
    campaign_id TEXT,

    order_date TIMESTAMP NOT NULL,
    order_status TEXT NOT NULL,

    shipping_address TEXT,
    billing_address TEXT NOT NULL,

    payment_method TEXT NOT NULL,
    order_total DECIMAL NOT NULL,

    notes TEXT,

    created_date TIMESTAMP NOT NULL,
    created_by TEXT NOT NULL,

    updated_date TIMESTAMP NOT NULL,
    updated_by TEXT NOT NULL,

    FOREIGN KEY (customer_id)
        REFERENCES commerce.customer(customer_id),

    FOREIGN KEY (campaign_id)
        REFERENCES commerce.marketing_campaign(campaign_id)

);
"""

try:
    cursor.execute(create_sales_order_table_query)
    conn.commit()

    print("Sales Order table created successfully.")
    print("Table: commerce.sales_order")

except Exception as e:
    conn.rollback()

    print("Sales Order table creation failed.")
    print("Error:", e)

Sales Order table created successfully.
Table: commerce.sales_order

## 6.3 Verify Sales Order Table Structure

Verify the actual PostgreSQL structure of the

`commerce.sales_order` table after creation.

Confirm:

- Column names

- Column order

- PostgreSQL data types

- NULL / NOT NULL rules

- Default values

The actual PostgreSQL table structure will be reviewed against the

approved Sales Order Data Dictionary before records are loaded.

In [51]:
# =========================================================
# 6.3 Verify Sales Order Table Structure
# =========================================================

verify_sales_order_table_query = """
SELECT
    ordinal_position,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'commerce'
  AND table_name = 'sales_order'
ORDER BY ordinal_position;
"""

try:
    cursor.execute(verify_sales_order_table_query)

    table_structure = cursor.fetchall()

    print("Sales Order Table Structure")
    print("=" * 80)

    print(
        f"{'Position':<10}"
        f"{'Column Name':<25}"
        f"{'Data Type':<25}"
        f"{'Nullable':<12}"
        f"{'Default'}"
    )

    print("-" * 100)

    for row in table_structure:
        print(
            f"{row[0]:<10}"
            f"{row[1]:<25}"
            f"{row[2]:<25}"
            f"{row[3]:<12}"
            f"{row[4]}"
        )

except Exception as e:
    print("Sales Order table structure verification failed.")
    print("Error:", e)

Sales Order Table Structure
================================================================================
Position  Column Name              Data Type                Nullable    Default
----------------------------------------------------------------------------------------------------
1         sales_order_id           text                     NO          None
2         customer_id              text                     NO          None
3         campaign_id              text                     YES         None
4         order_date               timestamp without time zoneNO          None
5         order_status             text                     NO          None
6         shipping_address         text                     YES         None
7         billing_address          text                     NO          None
8         payment_method           text                     NO          None
9         order_total              numeric                  NO          None
10        notes                    text                     YES         None
11        created_date             timestamp without time zoneNO          None
12        created_by               text                     NO          None
13        updated_date             timestamp without time zoneNO          None
14        updated_by               text                     NO          None

## 6.4 Verify Keys, Relationships & Load Dependencies

Verify the applicable keys, relationships, and load dependencies before

loading Sales Order records into PostgreSQL.

Confirm:

- `sales_order_id` is the Primary Key.

- `customer_id` references the approved Customer parent table.

- `campaign_id` references the approved Marketing Campaign parent table.

- Required parent/master records are available before loading Sales Order

  records.

- The dataset follows the approved project ETL load order.

Only applicable checks are performed for this dataset.

In [53]:
# =========================================================
# 6.4 Verify Keys, Relationships & Load Dependencies
# =========================================================

print("Sales Order Keys, Relationships & Load Dependency Review")
print("=" * 80)

# ---------------------------------------------------------
# 1. Primary Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'sales_order'
      AND tc.constraint_type = 'PRIMARY KEY';
""")

primary_keys = cursor.fetchall()

print("\n1. Primary Key")
print(primary_keys)

primary_key_valid = (
    len(primary_keys) == 1
    and primary_keys[0][1] == "sales_order_id"
)

print("Primary Key validation passed:", primary_key_valid)


# ---------------------------------------------------------
# 2. Foreign Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name,
        ccu.table_schema AS referenced_schema,
        ccu.table_name AS referenced_table,
        ccu.column_name AS referenced_column
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
        ON ccu.constraint_name = tc.constraint_name
        AND ccu.table_schema = tc.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'sales_order'
      AND tc.constraint_type = 'FOREIGN KEY'
    ORDER BY kcu.column_name;
""")

foreign_keys = cursor.fetchall()

print("\n2. Foreign Keys")
print(foreign_keys)

expected_foreign_key_columns = {
    "customer_id",
    "campaign_id"
}

actual_foreign_key_columns = {
    row[1] for row in foreign_keys
}

foreign_keys_valid = (
    actual_foreign_key_columns
    == expected_foreign_key_columns
)

print("Expected Foreign Key columns:",
      expected_foreign_key_columns)

print("Actual Foreign Key columns:",
      actual_foreign_key_columns)

print("Foreign Key validation passed:",
      foreign_keys_valid)


# ---------------------------------------------------------
# 3. Load Dependency Review
# ---------------------------------------------------------

print("\n3. Load Dependency Review")

load_dependency_ready = (
    primary_key_valid
    and foreign_keys_valid
)

print("Primary Key ready:", primary_key_valid)

print("Foreign Key dependencies ready:",
      foreign_keys_valid)


# ---------------------------------------------------------
# 4. Overall Load Dependency Status
# ---------------------------------------------------------

print("\n4. Overall Load Dependency Status")
print("=" * 80)

print("Sales Order is ready for data loading:",
      load_dependency_ready)

Sales Order Keys, Relationships & Load Dependency Review
================================================================================

1. Primary Key
[('sales_order_pkey', 'sales_order_id')]
Primary Key validation passed: True

2. Foreign Keys
[('sales_order_campaign_id_fkey', 'campaign_id', 'commerce', 'marketing_campaign', 'campaign_id'), ('sales_order_customer_id_fkey', 'customer_id', 'commerce', 'customer', 'customer_id')]
Expected Foreign Key columns: {'customer_id', 'campaign_id'}
Actual Foreign Key columns: {'customer_id', 'campaign_id'}
Foreign Key validation passed: True

3. Load Dependency Review
Primary Key ready: True
Foreign Key dependencies ready: True

4. Overall Load Dependency Status
================================================================================
Sales Order is ready for data loading: True

## 6.5 Insert Sales Order Records

Load the validated Sales Order database-ready dataset into the

verified `commerce.sales_order` PostgreSQL table.

Before inserting records:

- Confirm the target table is currently empty.

- Confirm the database-ready row count.

- Insert only the validated database-ready records.

- Use an explicit column list matching the approved target structure.

- Commit the transaction only after successful insertion.

No transformations are performed during the database loading step.

In [78]:
# =========================================================
# 6.5 Insert Sales Order Records
# =========================================================

print("Sales Order Record Loading")
print("=" * 80)


# ---------------------------------------------------------
# 1. Confirm Target Table Is Empty
# ---------------------------------------------------------

cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.sales_order;
""")

existing_record_count = cursor.fetchone()[0]

print("\n1. Target Table Record Count")
print("Existing records:", existing_record_count)

target_table_empty = (
    existing_record_count == 0
)

print("Target table is empty:", target_table_empty)


# ---------------------------------------------------------
# 2. Confirm Database-Ready Row Count
# ---------------------------------------------------------

db_ready_row_count = len(
    sales_order_db_ready
)

print("\n2. Database-Ready Row Count")
print("Database-ready records:", db_ready_row_count)


# ---------------------------------------------------------
# 3. Insert Validated Database-Ready Records
# ---------------------------------------------------------

insert_sales_order_query = """
INSERT INTO commerce.sales_order (
    sales_order_id,
    customer_id,
    campaign_id,
    order_date,
    order_status,
    shipping_address,
    billing_address,
    payment_method,
    order_total,
    notes,
    created_date,
    created_by,
    updated_date,
    updated_by
)
VALUES (
    %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s
);
"""

try:

    if not target_table_empty:
        raise ValueError(
            "Target table is not empty. "
            "Insertion stopped to prevent accidental duplicate loading."
        )

    records_to_insert = [
        tuple(row)
        for row in sales_order_db_ready.itertuples(
            index=False,
            name=None
        )
    ]

    if len(records_to_insert) != db_ready_row_count:
        raise ValueError(
            "Database-ready record count changed before insertion."
        )

    cursor.executemany(
        insert_sales_order_query,
        records_to_insert
    )

    conn.commit()

    print("\n3. Insert Result")
    print(
        "Sales Order records inserted:",
        len(records_to_insert)
    )
    print("Transaction committed successfully.")

except Exception as e:

    conn.rollback()

    print("\nSales Order record insertion failed.")
    print("Transaction rolled back.")
    print("Error:", e)

Sales Order Record Loading
================================================================================

1. Target Table Record Count
Existing records: 0
Target table is empty: True

2. Database-Ready Row Count
Database-ready records: 20

3. Insert Result
Sales Order records inserted: 20
Transaction committed successfully.

## 6.6 Validate Sales Order Row Count

Compare the number of records in the Database-Ready dataset with the

number of records currently stored in the PostgreSQL

`commerce.sales_order` table.

This confirms that the intended load scope was completed successfully.

No additional integrity checks are performed in this section.

In [79]:
# =========================================================
# 6.6 Validate Sales Order Row Count
# =========================================================

# Expected row count from the Database-Ready dataset
db_ready_row_count = len(sales_order_db_ready)


# Actual row count from PostgreSQL
cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.sales_order;
""")

postgresql_row_count = cursor.fetchone()[0]


# Validation result
row_count_match = (
    db_ready_row_count == postgresql_row_count
)


print("Sales Order Row Count Validation")
print("=" * 80)

print("\n1. Database-Ready Dataset Row Count")
print("Rows:", db_ready_row_count)

print("\n2. PostgreSQL Table Row Count")
print("Rows:", postgresql_row_count)

print("\n3. Row Count Validation")
print("Row counts match:", row_count_match)

print("\n4. Validation Summary")
print("=" * 80)

if row_count_match:
    print("Sales Order row count validation passed.")
else:
    print("Sales Order row count validation failed.")

Sales Order Row Count Validation
================================================================================

1. Database-Ready Dataset Row Count
Rows: 20

2. PostgreSQL Table Row Count
Rows: 20

3. Row Count Validation
Row counts match: True

4. Validation Summary
================================================================================
Sales Order row count validation passed.

## 6.7 Retrieve Sales Order Records

Retrieve the Sales Order records directly from PostgreSQL to confirm

that the loaded data is stored correctly.

Review:

- Loaded records

- Column values

- Order status values

- Order total values

- Payment method values

- Customer and campaign reference values

- Date and timestamp values

- Optional NULL values

- Overall record formatting

This step confirms that records can be successfully retrieved from the

PostgreSQL target table.

In [80]:
# =========================================================
# 6.7 Retrieve Sales Order Records
# =========================================================

retrieve_sales_order_query = """
SELECT
    sales_order_id,
    customer_id,
    campaign_id,
    order_date,
    order_status,
    shipping_address,
    billing_address,
    payment_method,
    order_total,
    notes,
    created_date,
    created_by,
    updated_date,
    updated_by
FROM commerce.sales_order
ORDER BY sales_order_id;
"""

try:
    cursor.execute(retrieve_sales_order_query)

    sales_order_records = cursor.fetchall()

    print("Sales Order Records Retrieved from PostgreSQL")
    print("=" * 80)

    print("Records retrieved:", len(sales_order_records))

    # Retrieve column names from the query result
    column_names = [
        description[0]
        for description in cursor.description
    ]

    # Create a DataFrame for readable review
    sales_order_postgresql = pd.DataFrame(
        sales_order_records,
        columns=column_names
    )

    print("\nRetrieved Sales Order Records:")
    display(sales_order_postgresql)

except Exception as e:
    print("Sales Order record retrieval failed.")
    print("Error:", e)

Sales Order Records Retrieved from PostgreSQL
================================================================================
Records retrieved: 20

Retrieved Sales Order Records:

   sales_order_id customer_id campaign_id order_date order_status           shipping_address            billing_address    payment_method order_total notes created_date created_by updated_date updated_by
0           SO001        C001      CAM001 2026-07-05    Completed         Al Jafiliya, Dubai         Al Jafiliya, Dubai              Visa        3198  None   2026-07-05      admin   2026-07-05      admin
1           SO002        C002      CAM004 2026-07-06    Completed             Makati, Manila             Makati, Manila       Credit Card        2199  None   2026-07-06      admin   2026-07-06      admin
2           SO003        C003        None 2026-07-07    Completed        Dubai Marina, Dubai        Dubai Marina, Dubai  Cash on Delivery        1399  None   2026-07-07      admin   2026-07-07      admin
3           SO004        C004      CAM001 2026-07-08      Shipped            Al Nahda, Dubai            Al Nahda, Dubai              Visa        4298  None   2026-07-08      admin   2026-07-08      admin
4           SO005        C005      CAM002 2026-07-09    Completed  Abu Dhabi City, Abu Dhabi  Abu Dhabi City, Abu Dhabi        Mastercard        3448  None   2026-07-09      admin   2026-07-09      admin
5           SO006        C006        None 2026-07-10      Pending            Jumeirah, Dubai            Jumeirah, Dubai  Cash on Delivery         699  None   2026-07-10      admin   2026-07-10      admin
6           SO007        C007      CAM002 2026-07-11    Completed      Sharjah City, Sharjah      Sharjah City, Sharjah              Visa        3257  None   2026-07-11      admin   2026-07-11      admin
7           SO008        C008        None 2026-07-12    Completed               Deira, Dubai               Deira, Dubai       Credit Card        1599  None   2026-07-12      admin   2026-07-12      admin
8           SO009        C009      CAM001 2026-07-13    Completed           Al Barsha, Dubai           Al Barsha, Dubai              Visa         399  None   2026-07-13      admin   2026-07-13      admin
9           SO010        C010        None 2026-07-14    Cancelled    Khalifa City, Abu Dhabi    Khalifa City, Abu Dhabi       Credit Card         449  None   2026-07-14      admin   2026-07-14      admin
10          SO011        C011      CAM004 2026-07-15    Completed           Bur Dubai, Dubai           Bur Dubai, Dubai  Cash on Delivery         499  None   2026-07-15      admin   2026-07-15      admin
11          SO012        C012        None 2026-07-16    Completed          Ajman City, Ajman          Ajman City, Ajman              Visa         699  None   2026-07-16      admin   2026-07-16      admin
12          SO013        C013      CAM002 2026-07-17    Completed        Business Bay, Dubai        Business Bay, Dubai        Mastercard        3298  None   2026-07-17      admin   2026-07-17      admin
13          SO014        C014        None 2026-07-18    Completed           Al Qusais, Dubai           Al Qusais, Dubai  Cash on Delivery         179  None   2026-07-18      admin   2026-07-18      admin
14          SO015        C015      CAM001 2026-07-19      Shipped              Mirdif, Dubai              Mirdif, Dubai              Visa        3598  None   2026-07-19      admin   2026-07-19      admin
15          SO016        C001        None 2026-07-20    Completed         Al Jafiliya, Dubai         Al Jafiliya, Dubai              Visa         699  None   2026-07-20      admin   2026-07-20      admin
16          SO017        C002      CAM004 2026-07-21    Completed             Makati, Manila             Makati, Manila       Credit Card         499  None   2026-07-21      admin   2026-07-21      admin
17          SO018        C003        None 2026-07-22    Completed        Dubai Marina, Dubai        Dubai Marina, Dubai        Mastercard        3899  None   2026-07-22      admin   2026-07-22      admin
18          SO019        C004      CAM002 2026-07-23      Pending            Al Nahda, Dubai            Al Nahda, Dubai  Cash on Delivery        2199  None   2026-07-23      admin   2026-07-23      admin
19          SO020        C005        None 2026-07-24    Completed  Abu Dhabi City, Abu Dhabi  Abu Dhabi City, Abu Dhabi              Visa        1599  None   2026-07-24      admin   2026-07-24      admin

## 6.8 Source → Database Reconciliation

Compare the validated Sales Order Database-Ready dataset with the

records retrieved directly from PostgreSQL.

Validate:

- Row counts

- Column names

- Column order

- Sales Order IDs

- Record-level values

This confirms that the Database-Ready dataset was loaded into PostgreSQL

without unintended changes.

In [81]:
# =========================================================
# 6.8 Source → Database Reconciliation
# =========================================================

# ---------------------------------------------------------
# 1. Prepare Source Dataset
# ---------------------------------------------------------

sales_order_source_reconciliation = (
    sales_order_db_ready.copy()
    .sort_values("sales_order_id")
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 2. Prepare PostgreSQL Dataset
# ---------------------------------------------------------

sales_order_postgresql_reconciliation = (
    sales_order_postgresql.copy()
    .sort_values("sales_order_id")
    .reset_index(drop=True)
)


print("Sales Order Source → Database Reconciliation")
print("=" * 80)


# ---------------------------------------------------------
# 3. Row Count Validation
# ---------------------------------------------------------

source_row_count = len(
    sales_order_source_reconciliation
)

database_row_count = len(
    sales_order_postgresql_reconciliation
)

row_count_match = (
    source_row_count == database_row_count
)

print("\n1. Row Count Validation")
print("Database-Ready rows:", source_row_count)
print("PostgreSQL rows:", database_row_count)
print("Row counts match:", row_count_match)


# ---------------------------------------------------------
# 4. Column Validation
# ---------------------------------------------------------

source_columns = (
    sales_order_source_reconciliation.columns.tolist()
)

database_columns = (
    sales_order_postgresql_reconciliation.columns.tolist()
)

column_match = (
    source_columns == database_columns
)

print("\n2. Column Validation")
print("Columns and order match:", column_match)

if not column_match:
    print("\nDatabase-Ready columns:")
    print(source_columns)

    print("\nPostgreSQL columns:")
    print(database_columns)


# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

source_sales_order_ids = set(
    sales_order_source_reconciliation["sales_order_id"]
)

database_sales_order_ids = set(
    sales_order_postgresql_reconciliation["sales_order_id"]
)

primary_key_match = (
    source_sales_order_ids == database_sales_order_ids
)

print("\n3. Sales Order ID Validation")
print("Sales Order IDs match:", primary_key_match)


# ---------------------------------------------------------
# 6. Record-Level Value Validation
# ---------------------------------------------------------

value_match = (
    sales_order_source_reconciliation.equals(
        sales_order_postgresql_reconciliation
    )
)

print("\n4. Record-Level Value Validation")
print("All record values match:", value_match)


# ---------------------------------------------------------
# 7. Reconciliation Summary
# ---------------------------------------------------------

reconciliation_passed = (
    row_count_match
    and column_match
    and primary_key_match
    and value_match
)

print("\n5. Source → Database Reconciliation Summary")
print("=" * 80)

print(
    "Source → Database reconciliation passed:",
    reconciliation_passed
)

Sales Order Source → Database Reconciliation
================================================================================

1. Row Count Validation
Database-Ready rows: 20
PostgreSQL rows: 20
Row counts match: True

2. Column Validation
Columns and order match: True

3. Sales Order ID Validation
Sales Order IDs match: True

4. Record-Level Value Validation
All record values match: True

5. Source → Database Reconciliation Summary
================================================================================
Source → Database reconciliation passed: True

## 6.9 Sales Order Database Integrity Validation

Perform final integrity checks on the loaded

`commerce.sales_order` table.

The checks confirm:

- Primary-key uniqueness

- Required-field integrity

- Duplicate record checks

- Order status validity

- Order total integrity

- Audit date consistency

These checks provide the final confirmation that the Sales Order

table is structurally and business-rule compliant after loading.

In [82]:
# =========================================================
# 6.9 Sales Order Database Integrity Validation
# =========================================================

integrity_query = """
SELECT
    COUNT(*) AS total_rows,

    COUNT(DISTINCT sales_order_id) AS distinct_sales_order_ids,

    COUNT(*) FILTER (
        WHERE sales_order_id IS NULL
    ) AS null_sales_order_ids,

    COUNT(*) FILTER (
        WHERE customer_id IS NULL
    ) AS null_customer_ids,

    COUNT(*) FILTER (
        WHERE order_date IS NULL
    ) AS null_order_dates,

    COUNT(*) FILTER (
        WHERE order_status IS NULL
    ) AS null_order_statuses,

    COUNT(*) FILTER (
        WHERE billing_address IS NULL
    ) AS null_billing_addresses,

    COUNT(*) FILTER (
        WHERE payment_method IS NULL
    ) AS null_payment_methods,

    COUNT(*) FILTER (
        WHERE order_total IS NULL
    ) AS null_order_totals,

    COUNT(*) FILTER (
        WHERE created_date IS NULL
    ) AS null_created_dates,

    COUNT(*) FILTER (
        WHERE created_by IS NULL
    ) AS null_created_by,

    COUNT(*) FILTER (
        WHERE updated_date IS NULL
    ) AS null_updated_dates,

    COUNT(*) FILTER (
        WHERE updated_by IS NULL
    ) AS null_updated_by,

    COUNT(*) FILTER (
        WHERE order_status NOT IN (
            'Completed',
            'Pending',
            'Shipped',
            'Cancelled'
        )
    ) AS invalid_order_statuses,

    COUNT(*) FILTER (
        WHERE order_total <= 0
    ) AS invalid_order_totals,

    COUNT(*) FILTER (
        WHERE updated_date < created_date
    ) AS invalid_audit_date_order

FROM commerce.sales_order;
"""

try:
    cursor.execute(integrity_query)

    integrity_result = cursor.fetchone()

    print("Sales Order Database Integrity Validation")
    print("=" * 80)

    print("\n1. Primary Key Integrity")
    print("Total rows:", integrity_result[0])
    print("Distinct sales order IDs:", integrity_result[1])
    print("NULL sales order IDs:", integrity_result[2])

    print("\n2. Required Field Integrity")
    print("NULL customer IDs:", integrity_result[3])
    print("NULL order dates:", integrity_result[4])
    print("NULL order statuses:", integrity_result[5])
    print("NULL billing addresses:", integrity_result[6])
    print("NULL payment methods:", integrity_result[7])
    print("NULL order totals:", integrity_result[8])
    print("NULL created dates:", integrity_result[9])
    print("NULL created by:", integrity_result[10])
    print("NULL updated dates:", integrity_result[11])
    print("NULL updated by:", integrity_result[12])

    print("\n3. Sales Order Value Integrity")
    print("Invalid order statuses:", integrity_result[13])
    print("Invalid order totals:", integrity_result[14])

    print("\n4. Audit Date Integrity")
    print(
        "Updated date earlier than created date:",
        integrity_result[15]
    )

    # -----------------------------------------------------
    # Final Validation Result
    # -----------------------------------------------------

    integrity_passed = (
        integrity_result[0] == integrity_result[1]
        and integrity_result[2] == 0
        and integrity_result[3] == 0
        and integrity_result[4] == 0
        and integrity_result[5] == 0
        and integrity_result[6] == 0
        and integrity_result[7] == 0
        and integrity_result[8] == 0
        and integrity_result[9] == 0
        and integrity_result[10] == 0
        and integrity_result[11] == 0
        and integrity_result[12] == 0
        and integrity_result[13] == 0
        and integrity_result[14] == 0
        and integrity_result[15] == 0
    )

    print("\n5. Database Integrity Validation Summary")
    print("=" * 80)

    print(
        "Sales Order database integrity passed:",
        integrity_passed
    )

except Exception as e:
    print("Sales Order database integrity validation failed.")
    print("Error:", e)

Sales Order Database Integrity Validation
================================================================================

1. Primary Key Integrity
Total rows: 20
Distinct sales order IDs: 20
NULL sales order IDs: 0

2. Required Field Integrity
NULL customer IDs: 0
NULL order dates: 0
NULL order statuses: 0
NULL billing addresses: 0
NULL payment methods: 0
NULL order totals: 0
NULL created dates: 0
NULL created by: 0
NULL updated dates: 0
NULL updated by: 0

3. Sales Order Value Integrity
Invalid order statuses: 0
Invalid order totals: 0

4. Audit Date Integrity
Updated date earlier than created date: 0

5. Database Integrity Validation Summary
================================================================================
Sales Order database integrity passed: True

## 6.10 Close PostgreSQL Connection

Close the PostgreSQL cursor and database connection after all

Sales Order loading and validation steps are complete.

Confirm that PostgreSQL resources are closed cleanly.

In [83]:
# =========================================================
# 6.10 Close PostgreSQL Connection
# =========================================================

try:
    if cursor is not None and not cursor.closed:
        cursor.close()

    if conn is not None and conn.closed == 0:
        conn.close()

    print("PostgreSQL resources closed successfully.")
    print("Cursor closed:", cursor.closed)
    print("Connection closed:", conn.closed != 0)

except Exception as e:
    print("PostgreSQL resource closure failed.")
    print("Error:", e)

PostgreSQL resources closed successfully.
Cursor closed: True
Connection closed: True