# LJ Dev Commerce - Phase 4

# VIII. Sales Order Item ETL

# =========================================================
# SECTION 1 — EXTRACT, SET UP, PROFILE, FINDINGS & DECISIONS
# =========================================================

# 1.1 Setup

This section prepares the notebook environment for the Sales Order Item ETL process.

The setup includes:

* Importing the required Python libraries.
* Configuring Pandas display options.
* Preparing the notebook environment for the Sales Order Item ETL workflow.

No dataset is loaded, modified, cleaned, or transformed in this section.

In [1]:
# =========================================================
# 1.1 Setup
# =========================================================

import pandas as pd
import numpy as np

# =========================================================
# Display Configuration
# =========================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)

In [3]:

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

## 1.2 Load and Preserve Sales Order Item Raw Datasets

Load the raw Sales Order Item source files from Shopify, Amazon UAE, and Noon and preserve each as its original source dataset.

The raw datasets must not be modified during the ETL process. Any profiling, cleaning, transformation, consolidation, or validation work will use separate DataFrame copies where appropriate.

For this section, the three source datasets will remain separate. They will not be consolidated or transformed during the loading process.

In [4]:
# =========================================================
# 1.2 Load and Preserve Sales Order Item Raw Datasets
# =========================================================

# Define the raw Sales Order Item dataset paths
shopify_order_items_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\06_Ecommerce_Shopify\shopify_order_items.csv"
)

amazon_order_items_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\07_Ecommerce_Amazon_UAE\amazon_order_items.csv"
)

noon_order_items_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\08_Ecommerce_Noon\noon_order_items.csv"
)


# Load the raw source datasets
shopify_order_items_raw = pd.read_csv(
    shopify_order_items_raw_path
)

amazon_order_items_raw = pd.read_csv(
    amazon_order_items_raw_path
)

noon_order_items_raw = pd.read_csv(
    noon_order_items_raw_path
)


# Preserve untouched copies of the original raw datasets
shopify_order_items_raw_original = (
    shopify_order_items_raw.copy(deep=True)
)

amazon_order_items_raw_original = (
    amazon_order_items_raw.copy(deep=True)
)

noon_order_items_raw_original = (
    noon_order_items_raw.copy(deep=True)
)


print("Sales Order Item raw datasets loaded successfully.")
print("Shopify - Rows:", len(shopify_order_items_raw))
print("Shopify - Columns:", len(shopify_order_items_raw.columns))
print("Shopify - Path:", shopify_order_items_raw_path)

print()

print("Amazon UAE - Rows:", len(amazon_order_items_raw))
print("Amazon UAE - Columns:", len(amazon_order_items_raw.columns))
print("Amazon UAE - Path:", amazon_order_items_raw_path)

print()

print("Noon - Rows:", len(noon_order_items_raw))
print("Noon - Columns:", len(noon_order_items_raw.columns))
print("Noon - Path:", noon_order_items_raw_path)

Sales Order Item raw datasets loaded successfully.
Shopify - Rows: 11
Shopify - Columns: 13
Shopify - Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\06_Ecommerce_Shopify\shopify_order_items.csv

Amazon UAE - Rows: 8
Amazon UAE - Columns: 13
Amazon UAE - Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\07_Ecommerce_Amazon_UAE\amazon_order_items.csv

Noon - Rows: 7
Noon - Columns: 13
Noon - Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\08_Ecommerce_Noon\noon_order_items.csv

## 1.3 Initial Raw Data Inspection

Perform an initial inspection of the untouched Sales Order Item raw datasets before profiling.

This step establishes the structure, current pandas data types, missing-value counts, and sample records for each source dataset.

No transformations are performed at this stage.

In [5]:
# =========================================================
# 1.3 Initial Raw Data Inspection
# =========================================================

print("Shopify Sales Order Item Dataset shape:")
print(shopify_order_items_raw.shape)


print("\nShopify Column names:")
print(shopify_order_items_raw.columns.tolist())


print("\nShopify Current pandas data types:")
print(shopify_order_items_raw.dtypes)


print("\nShopify Missing values:")
print(shopify_order_items_raw.isnull().sum())


print("\nShopify Sample raw records:")
display(shopify_order_items_raw.head())


print("\n\nAmazon UAE Sales Order Item Dataset shape:")
print(amazon_order_items_raw.shape)


print("\nAmazon UAE Column names:")
print(amazon_order_items_raw.columns.tolist())


print("\nAmazon UAE Current pandas data types:")
print(amazon_order_items_raw.dtypes)


print("\nAmazon UAE Missing values:")
print(amazon_order_items_raw.isnull().sum())


print("\nAmazon UAE Sample raw records:")
display(amazon_order_items_raw.head())


print("\n\nNoon Sales Order Item Dataset shape:")
print(noon_order_items_raw.shape)


print("\nNoon Column names:")
print(noon_order_items_raw.columns.tolist())


print("\nNoon Current pandas data types:")
print(noon_order_items_raw.dtypes)


print("\nNoon Missing values:")
print(noon_order_items_raw.isnull().sum())


print("\nNoon Sample raw records:")
display(noon_order_items_raw.head())

Shopify Sales Order Item Dataset shape:
(11, 13)

Shopify Column names:
['SourceSystem', 'SourceOrderID', 'SourceLineID', 'SourceOrderIDInternal', 'ProductCode', 'Qty', 'UnitPrice', 'DiscountAmount', 'LineAmount', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Shopify Current pandas data types:
SourceSystem             object
SourceOrderID            object
SourceLineID             object
SourceOrderIDInternal    object
ProductCode              object
Qty                       int64
UnitPrice                 int64
DiscountAmount            int64
LineAmount                int64
CreatedOn                object
CreatedByUser            object
ModifiedOn               object
ModifiedByUser           object
dtype: object

Shopify Missing values:
SourceSystem             0
SourceOrderID            0
SourceLineID             0
SourceOrderIDInternal    0
ProductCode              0
Qty                      0
UnitPrice                0
DiscountAmount           0
LineAmount               0
CreatedOn                0
CreatedByUser            0
ModifiedOn               0
ModifiedByUser           0
dtype: int64

Shopify Sample raw records:

  SourceSystem  SourceOrderID SourceLineID SourceOrderIDInternal ProductCode  Qty  UnitPrice  DiscountAmount  LineAmount   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0      Shopify  SHOPIFY-SO001       SOI001                 SO001       P0001    1       2499               0        2499  2026-07-01         admin  2026-07-24          admin
1      Shopify  SHOPIFY-SO002       SOI002                 SO002       P0002    1       2199               0        2199  2026-07-01         admin  2026-07-24          admin
2      Shopify  SHOPIFY-SO003       SOI003                 SO003       P0004    1       1399               0        1399  2026-07-01         admin  2026-07-24          admin
3      Shopify  SHOPIFY-SO004       SOI004                 SO004       P0003    1       3899               0        3899  2026-07-01         admin  2026-07-24          admin
4      Shopify  SHOPIFY-SO005       SOI005                 SO005       P0005    1       2999               0        2999  2026-07-01         admin  2026-07-24          admin

Amazon UAE Sales Order Item Dataset shape:
(8, 13)

Amazon UAE Column names:
['SourceSystem', 'SourceOrderID', 'SourceLineID', 'SourceOrderIDInternal', 'ProductCode', 'Qty', 'UnitPrice', 'DiscountAmount', 'LineAmount', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Amazon UAE Current pandas data types:
SourceSystem             object
SourceOrderID            object
SourceLineID             object
SourceOrderIDInternal    object
ProductCode              object
Qty                       int64
UnitPrice                 int64
DiscountAmount            int64
LineAmount                int64
CreatedOn                object
CreatedByUser            object
ModifiedOn               object
ModifiedByUser           object
dtype: object

Amazon UAE Missing values:
SourceSystem             0
SourceOrderID            0
SourceLineID             0
SourceOrderIDInternal    0
ProductCode              0
Qty                      0
UnitPrice                0
DiscountAmount           0
LineAmount               0
CreatedOn                0
CreatedByUser            0
ModifiedOn               0
ModifiedByUser           0
dtype: int64

Amazon UAE Sample raw records:

  SourceSystem SourceOrderID SourceLineID SourceOrderIDInternal ProductCode  Qty  UnitPrice  DiscountAmount  LineAmount   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0   Amazon UAE  AMAZON-SO008       SOI008                 SO008       P0010    1       1599               0        1599  2026-07-01         admin  2026-07-24          admin
1   Amazon UAE  AMAZON-SO009       SOI009                 SO009       P0011    1        399               0         399  2026-07-01         admin  2026-07-24          admin
2   Amazon UAE  AMAZON-SO010       SOI010                 SO010       P0012    1        449               0         449  2026-07-01         admin  2026-07-24          admin
3   Amazon UAE  AMAZON-SO011       SOI011                 SO011       P0014    1        499               0         499  2026-07-01         admin  2026-07-24          admin
4   Amazon UAE  AMAZON-SO012       SOI012                 SO012       P0015    1        699               0         699  2026-07-01         admin  2026-07-24          admin

Noon Sales Order Item Dataset shape:
(7, 13)

Noon Column names:
['SourceSystem', 'SourceOrderID', 'SourceLineID', 'SourceOrderIDInternal', 'ProductCode', 'Qty', 'UnitPrice', 'DiscountAmount', 'LineAmount', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Noon Current pandas data types:
SourceSystem             object
SourceOrderID            object
SourceLineID             object
SourceOrderIDInternal    object
ProductCode              object
Qty                       int64
UnitPrice                 int64
DiscountAmount            int64
LineAmount                int64
CreatedOn                object
CreatedByUser            object
ModifiedOn               object
ModifiedByUser           object
dtype: object

Noon Missing values:
SourceSystem             0
SourceOrderID            0
SourceLineID             0
SourceOrderIDInternal    0
ProductCode              0
Qty                      0
UnitPrice                0
DiscountAmount           0
LineAmount               0
CreatedOn                0
CreatedByUser            0
ModifiedOn               0
ModifiedByUser           0
dtype: int64

Noon Sample raw records:

  SourceSystem SourceOrderID SourceLineID SourceOrderIDInternal ProductCode  Qty  UnitPrice  DiscountAmount  LineAmount   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0         Noon    NOON-SO015       SOI015                 SO015       P0008    1       2899               0        2899  2026-07-01         admin  2026-07-24          admin
1         Noon    NOON-SO016       SOI016                 SO016       P0009    1        699               0         699  2026-07-01         admin  2026-07-24          admin
2         Noon    NOON-SO017       SOI017                 SO017       P0014    1        499               0         499  2026-07-01         admin  2026-07-24          admin
3         Noon    NOON-SO018       SOI018                 SO018       P0003    1       3899               0        3899  2026-07-01         admin  2026-07-24          admin
4         Noon    NOON-SO019       SOI019                 SO019       P0002    1       2199               0        2199  2026-07-01         admin  2026-07-24          admin

## 1.4 Data Profiling

Profile the untouched raw Sales Order Item datasets using the reusable `data_profiler_v1` tool.

The profiler is used to identify potential data-quality issues, semantic field types, missing values, duplicates, formatting inconsistencies, and other detectable anomalies before any cleaning or transformation is performed.

Each source dataset will be profiled separately before any consolidation takes place.

Profiling results are treated as findings for investigation. The profiler does not make business decisions or automatically determine the correct transformation.

In [6]:
# =========================================================
# 1.4 Data Profiling
# =========================================================

import sys
import importlib


# Identify the project root
project_root = Path.cwd().parent


# Add the project root to the Python path if needed
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))


# Import and reload the reusable data profiler
from profiler import data_profiler_v1 as profiler

importlib.reload(profiler)


print("Profiler loaded successfully:")
print(profiler.__file__)


print("\nProfiler configuration:")
print(profiler.DEFAULT_CONFIG)

Profiler loaded successfully:
c:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\profiler\data_profiler_v1.py

Profiler configuration:
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

In [7]:
# Run the complete profiler against the untouched raw Sales Order Item datasets

shopify_profile_results = profiler.profile_dataset(
    shopify_order_items_raw
)

amazon_profile_results = profiler.profile_dataset(
    amazon_order_items_raw
)

noon_profile_results = profiler.profile_dataset(
    noon_order_items_raw
)


print("\nSales Order Item profiling completed successfully.")

print("\nShopify profiler sections:")
print(list(shopify_profile_results.keys()))

print("\nAmazon UAE profiler sections:")
print(list(amazon_profile_results.keys()))

print("\nNoon profiler sections:")
print(list(noon_profile_results.keys()))

Sales Order Item profiling completed successfully.

Shopify profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

Amazon UAE profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

Noon profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

## 1.5 Review Profiling Results

Review the complete Sales Order Item profiling results before making any transformation decisions.

The automated profiler identifies potential data-quality issues, but the results must be independently reviewed in the context of the Sales Order Item datasets and LJ Dev Commerce business requirements.

This review examines:

- Automated profiling findings

- Issues requiring independent analyst review

- Potential business-rule decisions

- Issues that may require transformation

Each source dataset will be reviewed separately before any consolidation takes place.

No data is modified during this stage.

In [8]:
# =========================================================
# 1.5 Review Profiling Results
# =========================================================

print("\n" + "=" * 70)
print("SHOPIFY SALES ORDER ITEM PROFILING RESULTS")
print("=" * 70)

for section_name, section_result in shopify_profile_results.items():

    print("\n" + "-" * 70)
    print(section_name.upper())
    print("-" * 70)

    print(section_result)


print("\n\n" + "=" * 70)
print("AMAZON UAE SALES ORDER ITEM PROFILING RESULTS")
print("=" * 70)

for section_name, section_result in amazon_profile_results.items():

    print("\n" + "-" * 70)
    print(section_name.upper())
    print("-" * 70)

    print(section_result)


print("\n\n" + "=" * 70)
print("NOON SALES ORDER ITEM PROFILING RESULTS")
print("=" * 70)

for section_name, section_result in noon_profile_results.items():

    print("\n" + "-" * 70)
    print(section_name.upper())
    print("-" * 70)

    print(section_result)

======================================================================
SHOPIFY SALES ORDER ITEM PROFILING RESULTS
======================================================================

----------------------------------------------------------------------
FIELD_TYPES
----------------------------------------------------------------------
SourceSystem             categorical
SourceOrderID             identifier
SourceLineID              identifier
SourceOrderIDInternal     identifier
ProductCode               identifier
Qty                          numeric
UnitPrice                    numeric
DiscountAmount               numeric
LineAmount                   numeric
CreatedOn                       date
CreatedByUser            categorical
ModifiedOn                      date
ModifiedByUser           categorical
Name: DetectedFieldType, dtype: object

----------------------------------------------------------------------
DETECTION_DETAILS
----------------------------------------------------------------------
{'SourceSystem': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'SourceOrderID': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SourceLineID': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SourceOrderIDInternal': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'ProductCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'Qty': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'UnitPrice': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'DiscountAmount': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'LineAmount': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'CreatedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'CreatedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'ModifiedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'ModifiedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}}

----------------------------------------------------------------------
GENERAL
----------------------------------------------------------------------
{'rows': 11, 'columns': 13, 'exact_duplicate_rows': 0, 'column_profile':                       DataType DetectedFieldType  MissingCount  MissingPercent  UniqueCount  DuplicateValueCount
SourceSystem            object       categorical             0             0.0            1                   10
SourceOrderID           object        identifier             0             0.0            7                    4
SourceLineID            object        identifier             0             0.0           11                    0
SourceOrderIDInternal   object        identifier             0             0.0            7                    4
ProductCode             object        identifier             0             0.0           10                    1
Qty                      int64           numeric             0             0.0            2                    9
UnitPrice                int64           numeric             0             0.0           10                    1
DiscountAmount           int64           numeric             0             0.0            2                    9
LineAmount               int64           numeric             0             0.0           10                    1
CreatedOn               object              date             0             0.0            1                   10
CreatedByUser           object       categorical             0             0.0            1                   10
ModifiedOn              object              date             0             0.0            1                   10
ModifiedByUser          object       categorical             0             0.0            1                   10}

----------------------------------------------------------------------
TEXT
----------------------------------------------------------------------
{}

----------------------------------------------------------------------
CATEGORICAL
----------------------------------------------------------------------
{'SourceSystem': {'UniqueCount': 1, 'MostCommonValue': 'Shopify', 'MostCommonCount': 11, 'CategoryDistribution': {'Shopify': 11}}, 'CreatedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 11, 'CategoryDistribution': {'admin': 11}}, 'ModifiedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 11, 'CategoryDistribution': {'admin': 11}}}

----------------------------------------------------------------------
NUMERIC
----------------------------------------------------------------------
{'Qty': {'ValidNumericCount': 11, 'InvalidNumericCount': 0, 'Minimum': np.float64(1.0), 'Maximum': np.float64(2.0), 'Mean': np.float64(1.1818181818181819), 'Median': np.float64(1.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 11, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 2, 'LowerOutlierBoundary': np.float64(1.0), 'UpperOutlierBoundary': np.float64(1.0)}, 'UnitPrice': {'ValidNumericCount': 11, 'InvalidNumericCount': 0, 'Minimum': np.float64(179.0), 'Maximum': np.float64(3899.0), 'Mean': np.float64(1638.090909090909), 'Median': np.float64(1399.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 11, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(-2988.5), 'UpperOutlierBoundary': np.float64(6111.5)}, 'DiscountAmount': {'ValidNumericCount': 11, 'InvalidNumericCount': 0, 'Minimum': np.float64(0.0), 'Maximum': np.float64(99.0), 'Mean': np.float64(9.0), 'Median': np.float64(0.0), 'ZeroCount': 10, 'NegativeCount': 0, 'PositiveCount': 1, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 1, 'LowerOutlierBoundary': np.float64(0.0), 'UpperOutlierBoundary': np.float64(0.0)}, 'LineAmount': {'ValidNumericCount': 11, 'InvalidNumericCount': 0, 'Minimum': np.float64(358.0), 'Maximum': np.float64(3899.0), 'Mean': np.float64(1681.6363636363637), 'Median': np.float64(1399.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 11, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(-2613.5), 'UpperOutlierBoundary': np.float64(5886.5)}}

----------------------------------------------------------------------
DATE
----------------------------------------------------------------------
{'CreatedOn': {'ValidDateCount': 11, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-01 00:00:00'), 'MaximumDate': Timestamp('2026-07-01 00:00:00'), 'FutureDateCount': 0}, 'ModifiedOn': {'ValidDateCount': 11, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-24 00:00:00'), 'MaximumDate': Timestamp('2026-07-24 00:00:00'), 'FutureDateCount': 0}}

----------------------------------------------------------------------
PATTERNS
----------------------------------------------------------------------
{'email': {}, 'phone': {}, 'identifier': {'SourceOrderID': {'UniqueCount': 7, 'DuplicateCount': 4, 'MissingCount': 0}, 'SourceLineID': {'UniqueCount': 11, 'DuplicateCount': 0, 'MissingCount': 0}, 'SourceOrderIDInternal': {'UniqueCount': 7, 'DuplicateCount': 4, 'MissingCount': 0}, 'ProductCode': {'UniqueCount': 10, 'DuplicateCount': 1, 'MissingCount': 0}}}

----------------------------------------------------------------------
ISSUES
----------------------------------------------------------------------
                  Column            IssueType Severity  Count                           Description
0            ProductCode  DuplicateIdentifier     High      1  Repeated identifier values detected.
1          SourceOrderID  DuplicateIdentifier     High      4  Repeated identifier values detected.
2  SourceOrderIDInternal  DuplicateIdentifier     High      4  Repeated identifier values detected.

----------------------------------------------------------------------
CONFIGURATION
----------------------------------------------------------------------
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}


======================================================================
AMAZON UAE SALES ORDER ITEM PROFILING RESULTS
======================================================================

----------------------------------------------------------------------
FIELD_TYPES
----------------------------------------------------------------------
SourceSystem             categorical
SourceOrderID             identifier
SourceLineID              identifier
SourceOrderIDInternal     identifier
ProductCode               identifier
Qty                          numeric
UnitPrice                    numeric
DiscountAmount               numeric
LineAmount                   numeric
CreatedOn                       date
CreatedByUser            categorical
ModifiedOn                      date
ModifiedByUser           categorical
Name: DetectedFieldType, dtype: object

----------------------------------------------------------------------
DETECTION_DETAILS
----------------------------------------------------------------------
{'SourceSystem': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'SourceOrderID': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SourceLineID': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SourceOrderIDInternal': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'ProductCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'Qty': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'UnitPrice': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'DiscountAmount': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'LineAmount': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'CreatedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'CreatedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'ModifiedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'ModifiedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}}

----------------------------------------------------------------------
GENERAL
----------------------------------------------------------------------
{'rows': 8, 'columns': 13, 'exact_duplicate_rows': 0, 'column_profile':                       DataType DetectedFieldType  MissingCount  MissingPercent  UniqueCount  DuplicateValueCount
SourceSystem            object       categorical             0             0.0            1                    7
SourceOrderID           object        identifier             0             0.0            7                    1
SourceLineID            object        identifier             0             0.0            8                    0
SourceOrderIDInternal   object        identifier             0             0.0            7                    1
ProductCode             object        identifier             0             0.0            8                    0
Qty                      int64           numeric             0             0.0            1                    7
UnitPrice                int64           numeric             0             0.0            7                    1
DiscountAmount           int64           numeric             0             0.0            1                    7
LineAmount               int64           numeric             0             0.0            7                    1
CreatedOn               object              date             0             0.0            1                    7
CreatedByUser           object       categorical             0             0.0            1                    7
ModifiedOn              object              date             0             0.0            1                    7
ModifiedByUser          object       categorical             0             0.0            1                    7}

----------------------------------------------------------------------
TEXT
----------------------------------------------------------------------
{}

----------------------------------------------------------------------
CATEGORICAL
----------------------------------------------------------------------
{'SourceSystem': {'UniqueCount': 1, 'MostCommonValue': 'Amazon UAE', 'MostCommonCount': 8, 'CategoryDistribution': {'Amazon UAE': 8}}, 'CreatedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 8, 'CategoryDistribution': {'admin': 8}}, 'ModifiedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 8, 'CategoryDistribution': {'admin': 8}}}

----------------------------------------------------------------------
NUMERIC
----------------------------------------------------------------------
{'Qty': {'ValidNumericCount': 8, 'InvalidNumericCount': 0, 'Minimum': np.float64(1.0), 'Maximum': np.float64(1.0), 'Mean': np.float64(1.0), 'Median': np.float64(1.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 8, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(1.0), 'UpperOutlierBoundary': np.float64(1.0)}, 'UnitPrice': {'ValidNumericCount': 8, 'InvalidNumericCount': 0, 'Minimum': np.float64(179.0), 'Maximum': np.float64(2599.0), 'Mean': np.float64(890.25), 'Median': np.float64(599.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 8, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 1, 'LowerOutlierBoundary': np.float64(-294.75), 'UpperOutlierBoundary': np.float64(1655.25)}, 'DiscountAmount': {'ValidNumericCount': 8, 'InvalidNumericCount': 0, 'Minimum': np.float64(0.0), 'Maximum': np.float64(0.0), 'Mean': np.float64(0.0), 'Median': np.float64(0.0), 'ZeroCount': 8, 'NegativeCount': 0, 'PositiveCount': 0, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(0.0), 'UpperOutlierBoundary': np.float64(0.0)}, 'LineAmount': {'ValidNumericCount': 8, 'InvalidNumericCount': 0, 'Minimum': np.float64(179.0), 'Maximum': np.float64(2599.0), 'Mean': np.float64(890.25), 'Median': np.float64(599.0), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 8, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 1, 'LowerOutlierBoundary': np.float64(-294.75), 'UpperOutlierBoundary': np.float64(1655.25)}}

----------------------------------------------------------------------
DATE
----------------------------------------------------------------------
{'CreatedOn': {'ValidDateCount': 8, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-01 00:00:00'), 'MaximumDate': Timestamp('2026-07-01 00:00:00'), 'FutureDateCount': 0}, 'ModifiedOn': {'ValidDateCount': 8, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-24 00:00:00'), 'MaximumDate': Timestamp('2026-07-24 00:00:00'), 'FutureDateCount': 0}}

----------------------------------------------------------------------
PATTERNS
----------------------------------------------------------------------
{'email': {}, 'phone': {}, 'identifier': {'SourceOrderID': {'UniqueCount': 7, 'DuplicateCount': 1, 'MissingCount': 0}, 'SourceLineID': {'UniqueCount': 8, 'DuplicateCount': 0, 'MissingCount': 0}, 'SourceOrderIDInternal': {'UniqueCount': 7, 'DuplicateCount': 1, 'MissingCount': 0}, 'ProductCode': {'UniqueCount': 8, 'DuplicateCount': 0, 'MissingCount': 0}}}

----------------------------------------------------------------------
ISSUES
----------------------------------------------------------------------
                  Column            IssueType Severity  Count                           Description
0          SourceOrderID  DuplicateIdentifier     High      1  Repeated identifier values detected.
1  SourceOrderIDInternal  DuplicateIdentifier     High      1  Repeated identifier values detected.

----------------------------------------------------------------------
CONFIGURATION
----------------------------------------------------------------------
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}


======================================================================
NOON SALES ORDER ITEM PROFILING RESULTS
======================================================================

----------------------------------------------------------------------
FIELD_TYPES
----------------------------------------------------------------------
SourceSystem             categorical
SourceOrderID             identifier
SourceLineID              identifier
SourceOrderIDInternal     identifier
ProductCode               identifier
Qty                          numeric
UnitPrice                    numeric
DiscountAmount               numeric
LineAmount                   numeric
CreatedOn                       date
CreatedByUser            categorical
ModifiedOn                      date
ModifiedByUser           categorical
Name: DetectedFieldType, dtype: object

----------------------------------------------------------------------
DETECTION_DETAILS
----------------------------------------------------------------------

## 1.6 Review Profiler Issues

Review the issues identified by the automated profiler across the Shopify, Amazon UAE, and Noon Sales Order Item datasets.

The full profiling output provides a broad assessment of each raw Sales Order Item dataset. This step focuses specifically on the detected issues so they can be investigated before any transformation decisions are made.

Profiler findings are treated as indicators for review and do not automatically determine the correct transformation.

Each source dataset will be reviewed separately, and identified issues will be evaluated against the Sales Order Item Data Dictionary and LJ Dev Commerce business requirements.

In [9]:
# =========================================================
# 1.6 Review Profiler Issues
# =========================================================

shopify_issues = shopify_profile_results["issues"]
amazon_issues = amazon_profile_results["issues"]
noon_issues = noon_profile_results["issues"]


print("\n" + "=" * 70)
print("SHOPIFY SALES ORDER ITEM PROFILER ISSUES")
print("=" * 70)

display(shopify_issues)


print("\n" + "=" * 70)
print("AMAZON UAE SALES ORDER ITEM PROFILER ISSUES")
print("=" * 70)

display(amazon_issues)


print("\n" + "=" * 70)
print("NOON SALES ORDER ITEM PROFILER ISSUES")
print("=" * 70)

display(noon_issues)

======================================================================
SHOPIFY SALES ORDER ITEM PROFILER ISSUES
======================================================================

                  Column            IssueType Severity  Count                           Description
0            ProductCode  DuplicateIdentifier     High      1  Repeated identifier values detected.
1          SourceOrderID  DuplicateIdentifier     High      4  Repeated identifier values detected.
2  SourceOrderIDInternal  DuplicateIdentifier     High      4  Repeated identifier values detected.

======================================================================
AMAZON UAE SALES ORDER ITEM PROFILER ISSUES
======================================================================

                  Column            IssueType Severity  Count                           Description
0          SourceOrderID  DuplicateIdentifier     High      1  Repeated identifier values detected.
1  SourceOrderIDInternal  DuplicateIdentifier     High      1  Repeated identifier values detected.

======================================================================
NOON SALES ORDER ITEM PROFILER ISSUES
======================================================================

                  Column            IssueType Severity  Count                           Description
0          SourceOrderID  DuplicateIdentifier     High      1  Repeated identifier values detected.
1  SourceOrderIDInternal  DuplicateIdentifier     High      1  Repeated identifier values detected.

## 1.7 Independent Analyst Review

Perform a systematic independent analyst review of the untouched raw Sales Order Item datasets.

This section is the notebook-based version of the Pre-ETL Inspection.

The review goes beyond the automated profiler and checks each Sales Order Item source dataset using independent analyst validation relevant to its business meaning and approved ETL design.

The review covers, where applicable:

- Dataset structure and grain

- Missing and blank values

- Exact duplicate rows

- Primary-key candidates and key uniqueness

- Parent order relationship and order-line consistency

- Cross-source key uniqueness and collision checks

- Whitespace in text fields

- Text consistency

- Numeric validity and statistical outlier candidates

- Quantity and amount business-rule consistency

- Date parsing, datatype, validity, and Created/Modified date consistency

- ProductCode relationship values

- Source-to-target datatype compatibility considerations

- Cross-source structural consistency

Automated profiler findings and independent analyst findings are kept conceptually separate.

Each source dataset is reviewed independently before consolidation.

No data is modified in this section.

In [10]:
# =========================================================
# 1.7 Independent Analyst Review
# =========================================================


# =========================================================
# 1. Dataset Structure and Grain
# =========================================================

print("1. DATASET STRUCTURE AND GRAIN")
print("=" * 80)

sales_order_item_sources = {
    "Shopify": shopify_order_items_raw,
    "Amazon UAE": amazon_order_items_raw,
    "Noon": noon_order_items_raw
}


for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    print(f"Rows: {source_df.shape[0]}")
    print(f"Columns: {source_df.shape[1]}")

    print("\nWorking assumption:")
    print("One row represents one product/order line within a sales order.")


# =========================================================
# 2. Missing Values and Blank Values
# =========================================================

print("\n\n2. MISSING VALUES AND BLANK VALUES")
print("=" * 80)

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    missing_values = source_df.isna().sum()

    blank_values = pd.Series(
        {
            column: (
                source_df[column]
                .astype("string")
                .str.strip()
                .eq("")
                .sum()
                if source_df[column].dtype == "object"
                else 0
            )
            for column in source_df.columns
        }
    )

    missing_blank_review = pd.DataFrame({
        "MissingValues": missing_values,
        "BlankValues": blank_values
    })

    display(missing_blank_review)


# =========================================================
# 3. Exact Duplicate Rows
# =========================================================

print("\n\n3. EXACT DUPLICATE ROWS")
print("=" * 80)

for source_name, source_df in sales_order_item_sources.items():

    exact_duplicate_count = source_df.duplicated().sum()

    print(
        f"{source_name} - Exact duplicate rows: "
        f"{exact_duplicate_count}"
    )

    if exact_duplicate_count > 0:

        display(
            source_df[
                source_df.duplicated(keep=False)
            ]
        )


# =========================================================
# 4. Primary Key Candidate and Identifier Uniqueness
# =========================================================

print("\n\n4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS")
print("=" * 80)

identifier_columns = [
    "SourceLineID",
    "SourceOrderID",
    "SourceOrderIDInternal",
    "ProductCode"
]

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    identifier_review = pd.DataFrame(
        {
            "Column": identifier_columns,

            "NullCount": [
                source_df[column].isna().sum()
                for column in identifier_columns
            ],

            "BlankCount": [
                source_df[column]
                .astype("string")
                .str.strip()
                .eq("")
                .sum()
                for column in identifier_columns
            ],

            "DuplicateCount": [
                source_df[column].duplicated().sum()
                for column in identifier_columns
            ],

            "UniqueValues": [
                source_df[column].nunique()
                for column in identifier_columns
            ]
        }
    )

    display(identifier_review)


# =========================================================
# 5. Cross-Source Identifier Collision Review
# =========================================================

print("\n\n5. CROSS-SOURCE IDENTIFIER COLLISION REVIEW")
print("=" * 80)

cross_source_line_ids = pd.concat(
    [
        shopify_order_items_raw[
            ["SourceSystem", "SourceLineID"]
        ],

        amazon_order_items_raw[
            ["SourceSystem", "SourceLineID"]
        ],

        noon_order_items_raw[
            ["SourceSystem", "SourceLineID"]
        ]
    ],
    ignore_index=True
)


print("Total consolidated Sales Order Item records:")
print(len(cross_source_line_ids))

print("\nUnique SourceLineID values:")
print(cross_source_line_ids["SourceLineID"].nunique())


cross_source_line_duplicates = (
    cross_source_line_ids[
        cross_source_line_ids["SourceLineID"].duplicated(
            keep=False
        )
    ]
    .sort_values("SourceLineID")
)


print(
    "\nCross-source SourceLineID collisions: "
    f"{len(cross_source_line_duplicates)}"
)

if not cross_source_line_duplicates.empty:

    display(cross_source_line_duplicates)


# =========================================================
# 6. Parent Order / Order-Line Relationship Review
# =========================================================

print("\n\n6. PARENT ORDER / ORDER-LINE RELATIONSHIP REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    order_line_review = pd.DataFrame({
        "SourceOrderID": source_df["SourceOrderID"],
        "SourceOrderIDInternal": source_df["SourceOrderIDInternal"],
        "SourceLineID": source_df["SourceLineID"]
    })

    print("Distinct parent orders:")
    print(source_df["SourceOrderID"].nunique())

    print("Distinct order-line IDs:")
    print(source_df["SourceLineID"].nunique())

    print("Orders containing multiple line items:")

    multi_line_orders = (
        source_df
        .groupby("SourceOrderID")
        .size()
        .reset_index(name="LineItemCount")
    )

    multi_line_orders = multi_line_orders[
        multi_line_orders["LineItemCount"] > 1
    ]

    display(multi_line_orders)


# =========================================================
# 7. Leading and Trailing Whitespace Review
# =========================================================

print("\n\n7. LEADING AND TRAILING WHITESPACE REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    text_columns = source_df.select_dtypes(
        include="object"
    ).columns

    whitespace_findings = []

    for column in text_columns:

        whitespace_mask = (
            source_df[column].astype("string")
            != source_df[column].astype("string").str.strip()
        )

        count = whitespace_mask.sum()

        if count > 0:

            whitespace_records = source_df.loc[
                whitespace_mask,
                ["SourceLineID", column]
            ]

            whitespace_findings.append({
                "Column": column,
                "WhitespaceRecordCount": count
            })

            print(f"\nColumn: {column}")
            display(whitespace_records)

    if whitespace_findings:

        print("\nWhitespace findings summary:")
        display(pd.DataFrame(whitespace_findings))

    else:

        print("No leading or trailing whitespace found.")


# =========================================================
# 8. Text Consistency Review
# =========================================================

print("\n\n8. TEXT CONSISTENCY REVIEW")
print("=" * 80)

text_consistency_columns = [
    "SourceSystem",
    "ProductCode",
    "CreatedByUser",
    "ModifiedByUser"
]

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    for column in text_consistency_columns:

        print(f"\n{column} values:")

        display(
            source_df[column]
            .value_counts(dropna=False)
            .sort_index()
            .rename("RecordCount")
            .to_frame()
        )


# =========================================================
# 9. Numeric Validity Review
# =========================================================

print("\n\n9. NUMERIC VALIDITY REVIEW")
print("=" * 80)

numeric_columns = [
    "Qty",
    "UnitPrice",
    "DiscountAmount",
    "LineAmount"
]

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    numeric_summary = source_df[
        numeric_columns
    ].describe().T

    numeric_summary["NegativeCount"] = [
        (source_df[column] < 0).sum()
        for column in numeric_columns
    ]

    numeric_summary["ZeroCount"] = [
        (source_df[column] == 0).sum()
        for column in numeric_columns
    ]

    numeric_summary["PositiveCount"] = [
        (source_df[column] > 0).sum()
        for column in numeric_columns
    ]

    display(numeric_summary)


# =========================================================
# 10. Numeric Outlier Candidate Review
# =========================================================

print("\n\n10. NUMERIC OUTLIER CANDIDATE REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    outlier_summary = []

    for column in numeric_columns:

        q1 = source_df[column].quantile(0.25)
        q3 = source_df[column].quantile(0.75)

        iqr = q3 - q1

        lower_bound = q1 - (1.5 * iqr)
        upper_bound = q3 + (1.5 * iqr)

        outlier_mask = (
            (source_df[column] < lower_bound)
            |
            (source_df[column] > upper_bound)
        )

        outlier_count = outlier_mask.sum()

        outlier_summary.append({
            "Column": column,
            "LowerBoundary": lower_bound,
            "UpperBoundary": upper_bound,
            "OutlierCandidateCount": outlier_count
        })

        if outlier_count > 0:

            print(f"\nOutlier candidate(s): {column}")

            display(
                source_df.loc[
                    outlier_mask,
                    [
                        "SourceOrderID",
                        "SourceOrderIDInternal",
                        "SourceLineID",
                        "ProductCode",
                        column
                    ]
                ]
            )

    print("\nOutlier candidate summary:")
    display(pd.DataFrame(outlier_summary))


# =========================================================
# 11. Quantity and Amount Business Rule Review
# =========================================================

print("\n\n11. QUANTITY AND AMOUNT BUSINESS RULE REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    invalid_quantity = source_df[
        source_df["Qty"] <= 0
    ]

    invalid_discount = source_df[
        source_df["DiscountAmount"] > (
            source_df["Qty"] * source_df["UnitPrice"]
        )
    ]

    calculated_line_amount = (
        source_df["Qty"] * source_df["UnitPrice"]
        - source_df["DiscountAmount"]
    )

    amount_mismatch = source_df[
        calculated_line_amount != source_df["LineAmount"]
    ]

    print(
        "Records where Qty <= 0:",
        len(invalid_quantity)
    )

    print(
        "Records where DiscountAmount exceeds gross line value:",
        len(invalid_discount)
    )

    print(
        "Records where LineAmount does not equal "
        "(Qty × UnitPrice) - DiscountAmount:",
        len(amount_mismatch)
    )

    if not invalid_quantity.empty:

        print("\nInvalid quantity records:")
        display(invalid_quantity)

    if not invalid_discount.empty:

        print("\nInvalid discount records:")
        display(invalid_discount)

    if not amount_mismatch.empty:

        print("\nLine amount mismatch records:")

        mismatch_review = source_df.loc[
            amount_mismatch.index,
            [
                "SourceOrderID",
                "SourceLineID",
                "ProductCode",
                "Qty",
                "UnitPrice",
                "DiscountAmount",
                "LineAmount"
            ]
        ].copy()

        mismatch_review["CalculatedLineAmount"] = (
            calculated_line_amount.loc[
                amount_mismatch.index
            ]
        )

        display(mismatch_review)


# =========================================================
# 12. Date Parsing and Datatype Review
# =========================================================

print("\n\n12. DATE PARSING AND DATATYPE REVIEW")
print("=" * 80)

date_columns = [
    "CreatedOn",
    "ModifiedOn"
]

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    date_review = []

    for column in date_columns:

        parsed_dates = pd.to_datetime(
            source_df[column],
            errors="coerce"
        )

        date_review.append({
            "Column": column,
            "CurrentSourceDtype": str(
                source_df[column].dtype
            ),
            "InvalidDateCount": parsed_dates.isna().sum(),
            "MinimumDate": parsed_dates.min(),
            "MaximumDate": parsed_dates.max()
        })

    display(pd.DataFrame(date_review))


# =========================================================
# 13. CreatedOn / ModifiedOn Date Logic
# =========================================================

print("\n\n13. CREATEDON / MODIFIEDON DATE LOGIC REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    created_dates = pd.to_datetime(
        source_df["CreatedOn"],
        errors="coerce"
    )

    modified_dates = pd.to_datetime(
        source_df["ModifiedOn"],
        errors="coerce"
    )

    modified_before_created = source_df[
        modified_dates < created_dates
    ]

    print(
        "Records where ModifiedOn is earlier than CreatedOn: "
        f"{len(modified_before_created)}"
    )

    if not modified_before_created.empty:

        print("\nModifiedOn earlier than CreatedOn:")

        display(
            modified_before_created[
                [
                    "SourceOrderID",
                    "SourceLineID",
                    "CreatedOn",
                    "ModifiedOn"
                ]
            ]
        )


# =========================================================
# 14. ProductCode Relationship Value Review
# =========================================================

print("\n\n14. PRODUCTCODE RELATIONSHIP VALUE REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    print("\nProductCode frequency:")

    display(
        source_df["ProductCode"]
        .value_counts(dropna=False)
        .sort_index()
        .rename("RecordCount")
        .to_frame()
    )


# =========================================================
# 15. Source Datatype Review
# =========================================================

print("\n\n15. SOURCE DATATYPE REVIEW")
print("=" * 80)

for source_name, source_df in sales_order_item_sources.items():

    print(f"\n{source_name}")
    print("-" * 80)

    datatype_review = pd.DataFrame({
        "Column": source_df.columns,
        "SourceDtype": [
            str(source_df[column].dtype)
            for column in source_df.columns
        ]
    })

    display(datatype_review)


# =========================================================
# 16. Cross-Source Structural Consistency Review
# =========================================================

print("\n\n16. CROSS-SOURCE STRUCTURAL CONSISTENCY REVIEW")
print("=" * 80)

source_structure_review = pd.DataFrame(
    {
        "Source": list(sales_order_item_sources.keys()),

        "Rows": [
            source_df.shape[0]
            for source_df in sales_order_item_sources.values()
        ],

        "Columns": [
            source_df.shape[1]
            for source_df in sales_order_item_sources.values()
        ],

        "ColumnOrderMatchesShopify": [
            list(source_df.columns)
            == list(shopify_order_items_raw.columns)
            for source_df in sales_order_item_sources.values()
        ]
    }
)

display(source_structure_review)

print("\nExpected Sales Order Item source columns:")
print(shopify_order_items_raw.columns.tolist())


# =========================================================
# Independent Analyst Review Complete
# =========================================================

print("\n" + "=" * 80)
print("Independent Analyst Review completed.")
print("No data was modified.")
print("=" * 80)

1. DATASET STRUCTURE AND GRAIN
================================================================================

Shopify
--------------------------------------------------------------------------------
Rows: 11
Columns: 13

Working assumption:
One row represents one product/order line within a sales order.

Amazon UAE
--------------------------------------------------------------------------------
Rows: 8
Columns: 13

Working assumption:
One row represents one product/order line within a sales order.

Noon
--------------------------------------------------------------------------------
Rows: 7
Columns: 13

Working assumption:
One row represents one product/order line within a sales order.


2. MISSING VALUES AND BLANK VALUES
================================================================================

Shopify
--------------------------------------------------------------------------------

                       MissingValues  BlankValues
SourceSystem                       0            0
SourceOrderID                      0            0
SourceLineID                       0            0
SourceOrderIDInternal              0            0
ProductCode                        0            0
Qty                                0            0
UnitPrice                          0            0
DiscountAmount                     0            0
LineAmount                         0            0
CreatedOn                          0            0
CreatedByUser                      0            0
ModifiedOn                         0            0
ModifiedByUser                     0            0

Amazon UAE
--------------------------------------------------------------------------------

                       MissingValues  BlankValues
SourceSystem                       0            0
SourceOrderID                      0            0
SourceLineID                       0            0
SourceOrderIDInternal              0            0
ProductCode                        0            0
Qty                                0            0
UnitPrice                          0            0
DiscountAmount                     0            0
LineAmount                         0            0
CreatedOn                          0            0
CreatedByUser                      0            0
ModifiedOn                         0            0
ModifiedByUser                     0            0

Noon
--------------------------------------------------------------------------------

                       MissingValues  BlankValues
SourceSystem                       0            0
SourceOrderID                      0            0
SourceLineID                       0            0
SourceOrderIDInternal              0            0
ProductCode                        0            0
Qty                                0            0
UnitPrice                          0            0
DiscountAmount                     0            0
LineAmount                         0            0
CreatedOn                          0            0
CreatedByUser                      0            0
ModifiedOn                         0            0
ModifiedByUser                     0            0

3. EXACT DUPLICATE ROWS
================================================================================
Shopify - Exact duplicate rows: 0
Amazon UAE - Exact duplicate rows: 0
Noon - Exact duplicate rows: 0


4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS
================================================================================

Shopify
--------------------------------------------------------------------------------

                  Column  NullCount  BlankCount  DuplicateCount  UniqueValues
0           SourceLineID          0           0               0            11
1          SourceOrderID          0           0               4             7
2  SourceOrderIDInternal          0           0               4             7
3            ProductCode          0           0               1            10

Amazon UAE
--------------------------------------------------------------------------------

                  Column  NullCount  BlankCount  DuplicateCount  UniqueValues
0           SourceLineID          0           0               0             8
1          SourceOrderID          0           0               1             7
2  SourceOrderIDInternal          0           0               1             7
3            ProductCode          0           0               0             8

Noon
--------------------------------------------------------------------------------

                  Column  NullCount  BlankCount  DuplicateCount  UniqueValues
0           SourceLineID          0           0               0             7
1          SourceOrderID          0           0               1             6
2  SourceOrderIDInternal          0           0               1             6
3            ProductCode          0           0               0             7

5. CROSS-SOURCE IDENTIFIER COLLISION REVIEW
================================================================================
Total consolidated Sales Order Item records:
26

Unique SourceLineID values:
26

Cross-source SourceLineID collisions: 0


6. PARENT ORDER / ORDER-LINE RELATIONSHIP REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------
Distinct parent orders:
7
Distinct order-line IDs:
11
Orders containing multiple line items:

   SourceOrderID  LineItemCount
0  SHOPIFY-SO001              2
3  SHOPIFY-SO004              2
4  SHOPIFY-SO005              2
6  SHOPIFY-SO007              2

Amazon UAE
--------------------------------------------------------------------------------
Distinct parent orders:
7
Distinct order-line IDs:
8
Orders containing multiple line items:

  SourceOrderID  LineItemCount
5  AMAZON-SO013              2

Noon
--------------------------------------------------------------------------------
Distinct parent orders:
6
Distinct order-line IDs:
7
Orders containing multiple line items:

  SourceOrderID  LineItemCount
0    NOON-SO015              2

7. LEADING AND TRAILING WHITESPACE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------
No leading or trailing whitespace found.

Amazon UAE
--------------------------------------------------------------------------------
No leading or trailing whitespace found.

Noon
--------------------------------------------------------------------------------
No leading or trailing whitespace found.


8. TEXT CONSISTENCY REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

SourceSystem values:

              RecordCount
SourceSystem
Shopify                11

ProductCode values:

             RecordCount
ProductCode
P0001                  1
P0002                  1
P0003                  1
P0004                  1
P0005                  1
P0008                  1
P0009                  1
P0011                  2
P0012                  1
P0013                  1

CreatedByUser values:

               RecordCount
CreatedByUser
admin                   11

ModifiedByUser values:

                RecordCount
ModifiedByUser
admin                    11

Amazon UAE
--------------------------------------------------------------------------------

SourceSystem values:

              RecordCount
SourceSystem
Amazon UAE              8

ProductCode values:

             RecordCount
ProductCode
P0007                  1
P0009                  1
P0010                  1
P0011                  1
P0012                  1
P0013                  1
P0014                  1
P0015                  1

CreatedByUser values:

               RecordCount
CreatedByUser
admin                    8

ModifiedByUser values:

                RecordCount
ModifiedByUser
admin                     8

Noon
--------------------------------------------------------------------------------

SourceSystem values:

              RecordCount
SourceSystem
Noon                    7

ProductCode values:

             RecordCount
ProductCode
P0002                  1
P0003                  1
P0008                  1
P0009                  1
P0010                  1
P0014                  1
P0015                  1

CreatedByUser values:

               RecordCount
CreatedByUser
admin                    7

ModifiedByUser values:

                RecordCount
ModifiedByUser
admin                     7

9. NUMERIC VALIDITY REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

                count         mean          std    min    25%     50%     75%     max  NegativeCount  ZeroCount  PositiveCount
Qty              11.0     1.181818     0.404520    1.0    1.0     1.0     1.0     2.0              0          0             11
UnitPrice        11.0  1638.090909  1310.041637  179.0  424.0  1399.0  2699.0  3899.0              0          0             11
DiscountAmount   11.0     9.000000    29.849623    0.0    0.0     0.0     0.0    99.0              0         10              1
LineAmount       11.0  1681.636364  1264.810837  358.0  574.0  1399.0  2699.0  3899.0              0          0             11

Amazon UAE
--------------------------------------------------------------------------------

                count    mean        std    min    25%    50%    75%     max  NegativeCount  ZeroCount  PositiveCount
Qty               8.0    1.00    0.00000    1.0    1.0    1.0    1.0     1.0              0          0              8
UnitPrice         8.0  890.25  809.78723  179.0  436.5  599.0  924.0  2599.0              0          0              8
DiscountAmount    8.0    0.00    0.00000    0.0    0.0    0.0    0.0     0.0              0          8              0
LineAmount        8.0  890.25  809.78723  179.0  436.5  599.0  924.0  2599.0              0          0              8

Noon
--------------------------------------------------------------------------------

                count         mean          std    min    25%     50%     75%     max  NegativeCount  ZeroCount  PositiveCount
Qty               7.0     1.000000     0.000000    1.0    1.0     1.0     1.0     1.0              0          0              7
UnitPrice         7.0  1784.714286  1286.375491  499.0  699.0  1599.0  2549.0  3899.0              0          0              7
DiscountAmount    7.0     0.000000     0.000000    0.0    0.0     0.0     0.0     0.0              0          7              0
LineAmount        7.0  1784.714286  1286.375491  499.0  699.0  1599.0  2549.0  3899.0              0          0              7

10. NUMERIC OUTLIER CANDIDATE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

Outlier candidate(s): Qty

    SourceOrderID SourceOrderIDInternal SourceLineID ProductCode  Qty
7   SHOPIFY-SO001                 SO001       SOI021       P0011    2
10  SHOPIFY-SO007                 SO007       SOI024       P0013    2

Outlier candidate(s): DiscountAmount

   SourceOrderID SourceOrderIDInternal SourceLineID ProductCode  DiscountAmount
7  SHOPIFY-SO001                 SO001       SOI021       P0011              99

Outlier candidate summary:

           Column  LowerBoundary  UpperBoundary  OutlierCandidateCount
0             Qty            1.0            1.0                      2
1       UnitPrice        -2988.5         6111.5                      0
2  DiscountAmount            0.0            0.0                      1
3      LineAmount        -2613.5         5886.5                      0

Amazon UAE
--------------------------------------------------------------------------------

Outlier candidate(s): UnitPrice

  SourceOrderID SourceOrderIDInternal SourceLineID ProductCode  UnitPrice
5  AMAZON-SO013                 SO013       SOI013       P0007       2599

Outlier candidate(s): LineAmount

  SourceOrderID SourceOrderIDInternal SourceLineID ProductCode  LineAmount
5  AMAZON-SO013                 SO013       SOI013       P0007        2599

Outlier candidate summary:

           Column  LowerBoundary  UpperBoundary  OutlierCandidateCount
0             Qty           1.00           1.00                      0
1       UnitPrice        -294.75        1655.25                      1
2  DiscountAmount           0.00           0.00                      0
3      LineAmount        -294.75        1655.25                      1

Noon
--------------------------------------------------------------------------------

Outlier candidate summary:

           Column  LowerBoundary  UpperBoundary  OutlierCandidateCount
0             Qty            1.0            1.0                      0
1       UnitPrice        -2076.0         5324.0                      0
2  DiscountAmount            0.0            0.0                      0
3      LineAmount        -2076.0         5324.0                      0

11. QUANTITY AND AMOUNT BUSINESS RULE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------
Records where Qty <= 0: 0
Records where DiscountAmount exceeds gross line value: 0
Records where LineAmount does not equal (Qty × UnitPrice) - DiscountAmount: 0

Amazon UAE
--------------------------------------------------------------------------------
Records where Qty <= 0: 0
Records where DiscountAmount exceeds gross line value: 0
Records where LineAmount does not equal (Qty × UnitPrice) - DiscountAmount: 0

Noon
--------------------------------------------------------------------------------
Records where Qty <= 0: 0
Records where DiscountAmount exceeds gross line value: 0
Records where LineAmount does not equal (Qty × UnitPrice) - DiscountAmount: 0


12. DATE PARSING AND DATATYPE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

       Column CurrentSourceDtype  InvalidDateCount MinimumDate MaximumDate
0   CreatedOn             object                 0  2026-07-01  2026-07-01
1  ModifiedOn             object                 0  2026-07-24  2026-07-24

Amazon UAE
--------------------------------------------------------------------------------

       Column CurrentSourceDtype  InvalidDateCount MinimumDate MaximumDate
0   CreatedOn             object                 0  2026-07-01  2026-07-01
1  ModifiedOn             object                 0  2026-07-24  2026-07-24

Noon
--------------------------------------------------------------------------------

       Column CurrentSourceDtype  InvalidDateCount MinimumDate MaximumDate
0   CreatedOn             object                 0  2026-07-01  2026-07-01
1  ModifiedOn             object                 0  2026-07-24  2026-07-24

13. CREATEDON / MODIFIEDON DATE LOGIC REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------
Records where ModifiedOn is earlier than CreatedOn: 0

Amazon UAE
--------------------------------------------------------------------------------
Records where ModifiedOn is earlier than CreatedOn: 0

Noon
--------------------------------------------------------------------------------
Records where ModifiedOn is earlier than CreatedOn: 0


14. PRODUCTCODE RELATIONSHIP VALUE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

ProductCode frequency:

             RecordCount
ProductCode
P0001                  1
P0002                  1
P0003                  1
P0004                  1
P0005                  1
P0008                  1
P0009                  1
P0011                  2
P0012                  1
P0013                  1

Amazon UAE
--------------------------------------------------------------------------------

ProductCode frequency:

             RecordCount
ProductCode
P0007                  1
P0009                  1
P0010                  1
P0011                  1
P0012                  1
P0013                  1
P0014                  1
P0015                  1

Noon
--------------------------------------------------------------------------------

ProductCode frequency:

             RecordCount
ProductCode
P0002                  1
P0003                  1
P0008                  1
P0009                  1
P0010                  1
P0014                  1
P0015                  1

15. SOURCE DATATYPE REVIEW
================================================================================

Shopify
--------------------------------------------------------------------------------

                   Column SourceDtype
0            SourceSystem      object
1           SourceOrderID      object
2            SourceLineID      object
3   SourceOrderIDInternal      object
4             ProductCode      object
5                     Qty       int64
6               UnitPrice       int64
7          DiscountAmount       int64
8              LineAmount       int64
9               CreatedOn      object
10          CreatedByUser      object
11             ModifiedOn      object
12         ModifiedByUser      object

Amazon UAE
--------------------------------------------------------------------------------

                   Column SourceDtype
0            SourceSystem      object
1           SourceOrderID      object
2            SourceLineID      object
3   SourceOrderIDInternal      object
4             ProductCode      object
5                     Qty       int64
6               UnitPrice       int64
7          DiscountAmount       int64
8              LineAmount       int64
9               CreatedOn      object
10          CreatedByUser      object
11             ModifiedOn      object
12         ModifiedByUser      object

Noon
--------------------------------------------------------------------------------

                   Column SourceDtype
0            SourceSystem      object
1           SourceOrderID      object
2            SourceLineID      object
3   SourceOrderIDInternal      object
4             ProductCode      object
5                     Qty       int64
6               UnitPrice       int64
7          DiscountAmount       int64
8              LineAmount       int64
9               CreatedOn      object
10          CreatedByUser      object
11             ModifiedOn      object
12         ModifiedByUser      object

16. CROSS-SOURCE STRUCTURAL CONSISTENCY REVIEW
================================================================================

       Source  Rows  Columns  ColumnOrderMatchesShopify
0     Shopify    11       13                       True
1  Amazon UAE     8       13                       True
2        Noon     7       13                       True

Expected Sales Order Item source columns:
['SourceSystem', 'SourceOrderID', 'SourceLineID', 'SourceOrderIDInternal', 'ProductCode', 'Qty', 'UnitPrice', 'DiscountAmount', 'LineAmount', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

================================================================================
Independent Analyst Review completed.
No data was modified.
================================================================================

## 1.8 Findings and Transformation Decisions

Compare the automated profiler findings, the Independent Analyst Review findings, and the approved Sales Order Item data requirements to formally determine the required treatment for each finding.

Each finding must be classified as one of the following:

- Safe deterministic transformation

- Valid value — retain unchanged

- Expected business behavior

- Requires relationship validation later

- Requires business investigation

No transformation is performed in this section.

For Sales Order Item, the approved business rules include:

- Each row represents one product/order line within a sales order.
- One sales order may contain multiple sales order items.
- `SourceLineID` represents the source line-level identifier and must remain unique.
- Quantity must be greater than zero.
- Unit price, discount amount, and line amount must be preserved as transaction values.
- `LineAmount` must equal `(Qty × UnitPrice) - DiscountAmount`.
- Historical unit price values must be preserved.
- Product relationships will be validated against the Product master during the appropriate validation stage.
- Sales Order relationships will be validated against the Sales Order header during the appropriate validation stage.

The approved decisions from this section will define the transformations applied in Section 2.2.

In [11]:
# =========================================================
# 1.8 Findings and Transformation Decisions
# =========================================================

transformation_decisions = pd.DataFrame([
    
    {
        "Finding": "SourceLineID uniqueness and completeness",
        "AffectedRecords": 26,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain SourceLineID unchanged as the source line-level identifier "
            "for Sales Order Item lineage and reconciliation"
        ),
        "Reason": (
            "SourceLineID is non-null and unique across all three Sales Order Item "
            "sources, making it the strongest source line-level identifier."
        )
    },
    
    {
        "Finding": "SourceOrderID repeated across multiple line items",
        "AffectedRecords": 7,
        "Decision": "Expected business behavior",
        "ApprovedAction": (
            "Retain SourceOrderID unchanged and use it to maintain the "
            "Sales Order → Sales Order Item parent-child relationship"
        ),
        "Reason": (
            "A sales order may contain multiple products, so SourceOrderID "
            "is expected to repeat across its line items. It must not be "
            "treated as a duplicate-record condition."
        )
    },
    
    {
        "Finding": "SourceOrderIDInternal repeated across multiple line items",
        "AffectedRecords": 7,
        "Decision": "Expected business behavior",
        "ApprovedAction": (
            "Retain SourceOrderIDInternal unchanged as the source internal "
            "parent-order identifier"
        ),
        "Reason": (
            "The internal order identifier represents the parent sales order "
            "and may legitimately repeat across multiple Sales Order Item records."
        )
    },
    
    {
        "Finding": "ProductCode repeated across line items",
        "AffectedRecords": 1,
        "Decision": "Expected business behavior",
        "ApprovedAction": (
            "Retain ProductCode values unchanged"
        ),
        "Reason": (
            "The same product may legitimately occur on multiple order lines "
            "across different sales orders. A repeated ProductCode does not "
            "represent a duplicate Sales Order Item record."
        )
    },
    
    {
        "Finding": "No exact duplicate Sales Order Item rows",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain the dataset unchanged with respect to exact duplicates"
        ),
        "Reason": (
            "No exact duplicate rows were identified in Shopify, Amazon UAE, "
            "or Noon."
        )
    },
    
    {
        "Finding": "No missing or blank values",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "No missing-value or blank-value treatment is required"
        ),
        "Reason": (
            "All Sales Order Item source fields contain populated values "
            "with no NULL or blank-string findings."
        )
    },
    
    {
        "Finding": "No leading or trailing whitespace",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "No text trimming is required based on the independent review"
        ),
        "Reason": (
            "No leading or trailing whitespace was identified in the "
            "Sales Order Item source datasets."
        )
    },
    
    {
        "Finding": "SourceSystem values are consistent with source files",
        "AffectedRecords": 26,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain SourceSystem values unchanged for source lineage"
        ),
        "Reason": (
            "The source-system values correctly identify Shopify, Amazon UAE, "
            "and Noon records and provide required source traceability."
        )
    },
    
    {
        "Finding": "Quantity values greater than zero",
        "AffectedRecords": 26,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain Qty values unchanged"
        ),
        "Reason": (
            "All observed quantities comply with the approved Sales Order Item "
            "business rule requiring quantity greater than zero."
        )
    },
    
    {
        "Finding": "UnitPrice values are non-negative",
        "AffectedRecords": 26,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain UnitPrice business values unchanged; convert only to the "
            "target Decimal-compatible datatype"
        ),
        "Reason": (
            "All observed unit prices are valid positive transaction values. "
            "No evidence supports changing the business values."
        )
    },
    
    {
        "Finding": "DiscountAmount values are non-negative and do not exceed gross line value",
        "AffectedRecords": 26,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain DiscountAmount values unchanged; convert only to the "
            "target Decimal-compatible datatype"
        ),
        "Reason": (
            "All observed discount amounts are valid and none exceeds "
            "Qty × UnitPrice. The valid Shopify discounted line must be "
            "preserved as a legitimate transaction."
        )
    },
    
    {
        "Finding": "LineAmount arithmetic validation",
        "AffectedRecords": 26,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain LineAmount values unchanged; convert only to the "
            "target Decimal-compatible datatype"
        ),
        "Reason": (
            "All records satisfy the approved calculation "
            "(Qty × UnitPrice) - DiscountAmount = LineAmount."
        )
    },
    
    {
        "Finding": "Profiler numeric outlier candidates",
        "AffectedRecords": 4,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Do not automatically modify or remove statistical outlier candidates"
        ),
        "Reason": (
            "Profiler outlier detection is statistical and does not establish "
            "that a transaction value is erroneous. No business evidence "
            "supports changing the identified values."
        )
    },
    
    {
        "Finding": "CreatedOn stored as object",
        "AffectedRecords": 26,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": (
            "Convert CreatedOn to datetime during transformation"
        ),
        "Reason": (
            "All source CreatedOn values are valid and parseable dates. "
            "The target Sales Order Item design requires a Datetime-compatible "
            "field."
        )
    },
    
    {
        "Finding": "ModifiedOn stored as object",
        "AffectedRecords": 26,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": (
            "Convert ModifiedOn to datetime during transformation"
        ),
        "Reason": (
            "All source ModifiedOn values are valid and parseable dates. "
            "The target Sales Order Item design requires a Datetime-compatible "
            "field."
        )
    },
    
    {
        "Finding": "UnitPrice source datatype",
        "AffectedRecords": 26,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": (
            "Convert UnitPrice to Decimal-compatible values for the "
            "database-ready dataset"
        ),
        "Reason": (
            "UnitPrice is a monetary field and the approved target data "
            "dictionary requires a Decimal-compatible representation."
        )
    },
    
    {
        "Finding": "DiscountAmount source datatype",
        "AffectedRecords": 26,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": (
            "Convert DiscountAmount to Decimal-compatible values for the "
            "database-ready dataset"
        ),
        "Reason": (
            "DiscountAmount is a monetary field and requires a "
            "Decimal-compatible representation for database loading."
        )
    },
    
    {
        "Finding": "LineAmount source datatype",
        "AffectedRecords": 26,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": (
            "Convert LineAmount to Decimal-compatible values for the "
            "database-ready dataset"
        ),
        "Reason": (
            "LineAmount is a monetary field and requires a "
            "Decimal-compatible representation for database loading."
        )
    },
    
    {
        "Finding": "ProductCode relationship to Product",
        "AffectedRecords": 26,
        "Decision": "Requires relationship validation later",
        "ApprovedAction": (
            "Retain ProductCode values unchanged and validate the corresponding "
            "Product relationship against commerce.product"
        ),
        "Reason": (
            "ProductCode represents the Sales Order Item → Product relationship. "
            "Foreign-key readiness must be confirmed during the appropriate "
            "relationship validation stage."
        )
    },
    
    {
        "Finding": "SourceOrderID relationship to Sales Order",
        "AffectedRecords": 26,
        "Decision": "Requires relationship validation later",
        "ApprovedAction": (
            "Retain SourceOrderID values unchanged and validate the corresponding "
            "Sales Order relationship against commerce.sales_order"
        ),
        "Reason": (
            "Each Sales Order Item must belong to a valid Sales Order. "
            "The relationship must be validated against the completed "
            "Sales Order table before database loading."
        )
    },
    
    {
        "Finding": "SourceLineID cross-source collision review",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain SourceLineID values unchanged"
        ),
        "Reason": (
            "No cross-source SourceLineID collisions were identified across "
            "Shopify, Amazon UAE, and Noon."
        )
    },
    
    {
        "Finding": "CreatedOn / ModifiedOn date logic",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain source audit dates and convert only to the required "
            "datetime datatype"
        ),
        "Reason": (
            "No Sales Order Item record has ModifiedOn earlier than CreatedOn."
        )
    },
    
    {
        "Finding": "Cross-source structural consistency",
        "AffectedRecords": 26,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Proceed with controlled consolidation of the three validated "
            "Sales Order Item source datasets"
        ),
        "Reason": (
            "Shopify, Amazon UAE, and Noon contain the same approved "
            "13-column Sales Order Item source structure, supporting "
            "controlled consolidation after source-specific validation."
        )
    }
])


print("Sales Order Item Findings and Transformation Decisions")
print("=" * 120)

display(transformation_decisions)


print("\nDecision Summary")
print("=" * 120)

print(
    transformation_decisions["Decision"].value_counts()
)

Sales Order Item Findings and Transformation Decisions
========================================================================================================================

                                                                      Finding  AffectedRecords                                Decision                                                                                                              ApprovedAction                                                                                                                                                                         Reason
0                                    SourceLineID uniqueness and completeness               26          Valid value — retain unchanged           Retain SourceLineID unchanged as the source line-level identifier for Sales Order Item lineage and reconciliation                                           SourceLineID is non-null and unique across all three Sales Order Item sources, making it the strongest source line-level identifier.
1                           SourceOrderID repeated across multiple line items                7              Expected business behavior          Retain SourceOrderID unchanged and use it to maintain the Sales Order → Sales Order Item parent-child relationship             A sales order may contain multiple products, so SourceOrderID is expected to repeat across its line items. It must not be treated as a duplicate-record condition.
2                   SourceOrderIDInternal repeated across multiple line items                7              Expected business behavior                                       Retain SourceOrderIDInternal unchanged as the source internal parent-order identifier                                          The internal order identifier represents the parent sales order and may legitimately repeat across multiple Sales Order Item records.
3                                      ProductCode repeated across line items                1              Expected business behavior                                                                                         Retain ProductCode values unchanged  The same product may legitimately occur on multiple order lines across different sales orders. A repeated ProductCode does not represent a duplicate Sales Order Item record.
4                                    No exact duplicate Sales Order Item rows                0          Valid value — retain unchanged                                                               Retain the dataset unchanged with respect to exact duplicates                                                                                                       No exact duplicate rows were identified in Shopify, Amazon UAE, or Noon.
5                                                  No missing or blank values                0          Valid value — retain unchanged                                                                       No missing-value or blank-value treatment is required                                                                             All Sales Order Item source fields contain populated values with no NULL or blank-string findings.
6                                           No leading or trailing whitespace                0          Valid value — retain unchanged                                                                No text trimming is required based on the independent review                                                                                      No leading or trailing whitespace was identified in the Sales Order Item source datasets.
7                        SourceSystem values are consistent with source files               26          Valid value — retain unchanged                                                                     Retain SourceSystem values unchanged for source lineage                                                    The source-system values correctly identify Shopify, Amazon UAE, and Noon records and provide required source traceability.
8                                           Quantity values greater than zero               26          Valid value — retain unchanged                                                                                                 Retain Qty values unchanged                                                          All observed quantities comply with the approved Sales Order Item business rule requiring quantity greater than zero.
9                                           UnitPrice values are non-negative               26          Valid value — retain unchanged                          Retain UnitPrice business values unchanged; convert only to the target Decimal-compatible datatype                                                             All observed unit prices are valid positive transaction values. No evidence supports changing the business values.
10  DiscountAmount values are non-negative and do not exceed gross line value               26          Valid value — retain unchanged                              Retain DiscountAmount values unchanged; convert only to the target Decimal-compatible datatype                     All observed discount amounts are valid and none exceeds Qty × UnitPrice. The valid Shopify discounted line must be preserved as a legitimate transaction.
11                                           LineAmount arithmetic validation               26          Valid value — retain unchanged                                  Retain LineAmount values unchanged; convert only to the target Decimal-compatible datatype                                                                                  All records satisfy the approved calculation (Qty × UnitPrice) - DiscountAmount = LineAmount.
12                                        Profiler numeric outlier candidates                4          Valid value — retain unchanged                                                        Do not automatically modify or remove statistical outlier candidates          Profiler outlier detection is statistical and does not establish that a transaction value is erroneous. No business evidence supports changing the identified values.
13                                                 CreatedOn stored as object               26       Safe deterministic transformation                                                                         Convert CreatedOn to datetime during transformation                                            All source CreatedOn values are valid and parseable dates. The target Sales Order Item design requires a Datetime-compatible field.
14                                                ModifiedOn stored as object               26       Safe deterministic transformation                                                                        Convert ModifiedOn to datetime during transformation                                           All source ModifiedOn values are valid and parseable dates. The target Sales Order Item design requires a Datetime-compatible field.
15                                                  UnitPrice source datatype               26       Safe deterministic transformation                                               Convert UnitPrice to Decimal-compatible values for the database-ready dataset                                                            UnitPrice is a monetary field and the approved target data dictionary requires a Decimal-compatible representation.
16                                             DiscountAmount source datatype               26       Safe deterministic transformation                                          Convert DiscountAmount to Decimal-compatible values for the database-ready dataset                                                                      DiscountAmount is a monetary field and requires a Decimal-compatible representation for database loading.
17                                                 LineAmount source datatype               26       Safe deterministic transformation                                              Convert LineAmount to Decimal-compatible values for the database-ready dataset                                                                          LineAmount is a monetary field and requires a Decimal-compatible representation for database loading.
18                                        ProductCode relationship to Product               26  Requires relationship validation later            Retain ProductCode values unchanged and validate the corresponding Product relationship against commerce.product              ProductCode represents the Sales Order Item → Product relationship. Foreign-key readiness must be confirmed during the appropriate relationship validation stage.
19                                  SourceOrderID relationship to Sales Order               26  Requires relationship validation later  Retain SourceOrderID values unchanged and validate the corresponding Sales Order relationship against commerce.sales_order                  Each Sales Order Item must belong to a valid Sales Order. The relationship must be validated against the completed Sales Order table before database loading.
20                                 SourceLineID cross-source collision review                0          Valid value — retain unchanged                                                                                        Retain SourceLineID values unchanged                                                                                  No cross-source SourceLineID collisions were identified across Shopify, Amazon UAE, and Noon.
21                                          CreatedOn / ModifiedOn date logic                0          Valid value — retain unchanged                                                Retain source audit dates and convert only to the required datetime datatype                                                                                                              No Sales Order Item record has ModifiedOn earlier than CreatedOn.
22                                        Cross-source structural consistency               26          Valid value — retain unchanged                               Proceed with controlled consolidation of the three validated Sales Order Item source datasets     Shopify, Amazon UAE, and Noon contain the same approved 13-column Sales Order Item source structure, supporting controlled consolidation after source-specific validation.

Decision Summary
========================================================================================================================
Decision
Valid value — retain unchanged            13
Safe deterministic transformation          5
Expected business behavior                 3
Requires relationship validation later     2
Name: count, dtype: int64

# =========================================================
# SECTION 2 — DATA TRANSFORMATION
# =========================================================

## 2.1 Create Clean Working Datasets

Create separate working copies of the raw Sales Order Item datasets from Shopify, Amazon UAE, and Noon before applying any approved transformations.

The raw datasets must remain unchanged throughout the ETL process.

All transformations will be applied only to the clean working datasets.

The three source datasets will remain separate during this step. Controlled consolidation will occur only after the approved source-specific transformations have been applied and validated.

In [12]:
# =========================================================
# 2.1 Create Clean Working Dataset
# =========================================================

shopify_order_items_clean = shopify_order_items_raw.copy()

amazon_order_items_clean = amazon_order_items_raw.copy()

noon_order_items_clean = noon_order_items_raw.copy()


print("Clean working datasets created successfully.")

print(f"\nShopify raw rows:   {shopify_order_items_raw.shape[0]}")
print(f"Shopify clean rows: {shopify_order_items_clean.shape[0]}")

print(f"\nAmazon raw rows:   {amazon_order_items_raw.shape[0]}")
print(f"Amazon clean rows: {amazon_order_items_clean.shape[0]}")

print(f"\nNoon raw rows:   {noon_order_items_raw.shape[0]}")
print(f"Noon clean rows: {noon_order_items_clean.shape[0]}")


print("\nRaw and clean datasets are separate objects:")

print(
    "Shopify:",
    shopify_order_items_raw is not shopify_order_items_clean
)

print(
    "Amazon UAE:",
    amazon_order_items_raw is not amazon_order_items_clean
)

print(
    "Noon:",
    noon_order_items_raw is not noon_order_items_clean
)

Clean working datasets created successfully.

Shopify raw rows:   11
Shopify clean rows: 11

Amazon raw rows:   8
Amazon clean rows: 8

Noon raw rows:   7
Noon clean rows: 7

Raw and clean datasets are separate objects:
Shopify: True
Amazon UAE: True
Noon: True

## 2.2 Apply Approved Transformations

Apply only the transformations approved in Section 1.8 to the clean working Sales Order Item datasets.

Approved transformations:

- Convert CreatedOn to datetime.

- Convert ModifiedOn to datetime.

- Convert UnitPrice to Decimal-compatible values.

- Convert DiscountAmount to Decimal-compatible values.

- Convert LineAmount to Decimal-compatible values.

The datetime and monetary datatype transformations are deterministic and prepare the source values for the approved Sales Order Item target structure and downstream database loading.

No other business values will be modified.

The SourceOrderID repeated values, SourceOrderIDInternal repeated values, and ProductCode repeated values will be retained unchanged because they represent expected parent-order and product relationships rather than duplicate Sales Order Item records.

The profiler numeric outlier candidates will be retained unchanged because statistical outlier detection alone does not confirm a data error.

The three source datasets will remain separate during this transformation step.

In [13]:
# =========================================================
# 2.2 Apply Approved Transformations
# =========================================================

# ---------------------------------------------------------
# 1. Convert approved date fields
# ---------------------------------------------------------

for df in [
    shopify_order_items_clean,
    amazon_order_items_clean,
    noon_order_items_clean
]:
    df["CreatedOn"] = pd.to_datetime(
        df["CreatedOn"],
        errors="raise"
    )

    df["ModifiedOn"] = pd.to_datetime(
        df["ModifiedOn"],
        errors="raise"
    )


# ---------------------------------------------------------
# 2. Convert approved monetary fields to Decimal-compatible values
# ---------------------------------------------------------

from decimal import Decimal

for df in [
    shopify_order_items_clean,
    amazon_order_items_clean,
    noon_order_items_clean
]:
    df["UnitPrice"] = df["UnitPrice"].apply(Decimal)
    df["DiscountAmount"] = df["DiscountAmount"].apply(Decimal)
    df["LineAmount"] = df["LineAmount"].apply(Decimal)


print("Sales Order Item approved transformations applied successfully.")

Sales Order Item approved transformations applied successfully.

## 3.1 Transformation Validation

Validate that every transformation approved in Section 1.8 was successfully applied to the clean Sales Order Item datasets.

This validation checks:

- CreatedOn datetime conversion

- ModifiedOn datetime conversion

- UnitPrice Decimal-compatible conversion

- DiscountAmount Decimal-compatible conversion

- LineAmount Decimal-compatible conversion

- Quantity and monetary business values remain unchanged

- LineAmount calculation remains valid after transformation

- Profiler numeric outlier candidates remain unchanged

Only approved transformations and approved source-value retention decisions are validated.

No additional data modifications are performed in this section.

In [14]:
# =========================================================
# 3.1 Transformation Validation
# =========================================================

validation_results = []


# ---------------------------------------------------------
# 1. CreatedOn Datetime Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_order_items_clean),
    ("Amazon UAE", amazon_order_items_clean),
    ("Noon", noon_order_items_clean)
]:

    created_on_is_datetime = pd.api.types.is_datetime64_any_dtype(
        df["CreatedOn"]
    )

    validation_results.append({
        "Validation": f"{source_name} CreatedOn datetime conversion",
        "Expected": "datetime64 datatype",
        "Actual": str(df["CreatedOn"].dtype),
        "Passed": created_on_is_datetime
    })


# ---------------------------------------------------------
# 2. ModifiedOn Datetime Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_order_items_clean),
    ("Amazon UAE", amazon_order_items_clean),
    ("Noon", noon_order_items_clean)
]:

    modified_on_is_datetime = pd.api.types.is_datetime64_any_dtype(
        df["ModifiedOn"]
    )

    validation_results.append({
        "Validation": f"{source_name} ModifiedOn datetime conversion",
        "Expected": "datetime64 datatype",
        "Actual": str(df["ModifiedOn"].dtype),
        "Passed": modified_on_is_datetime
    })


# ---------------------------------------------------------
# 3. UnitPrice Decimal Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_order_items_clean),
    ("Amazon UAE", amazon_order_items_clean),
    ("Noon", noon_order_items_clean)
]:

    unit_price_is_decimal = df["UnitPrice"].apply(
        lambda value: isinstance(value, Decimal)
    ).all()

    validation_results.append({
        "Validation": f"{source_name} UnitPrice Decimal conversion",
        "Expected": "All values are Decimal-compatible",
        "Actual": (
            "All values are Decimal"
            if unit_price_is_decimal
            else "One or more values are not Decimal"
        ),
        "Passed": unit_price_is_decimal
    })


# ---------------------------------------------------------
# 4. DiscountAmount Decimal Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_order_items_clean),
    ("Amazon UAE", amazon_order_items_clean),
    ("Noon", noon_order_items_clean)
]:

    discount_amount_is_decimal = df["DiscountAmount"].apply(
        lambda value: isinstance(value, Decimal)
    ).all()

    validation_results.append({
        "Validation": f"{source_name} DiscountAmount Decimal conversion",
        "Expected": "All values are Decimal-compatible",
        "Actual": (
            "All values are Decimal"
            if discount_amount_is_decimal
            else "One or more values are not Decimal"
        ),
        "Passed": discount_amount_is_decimal
    })


# ---------------------------------------------------------
# 5. LineAmount Decimal Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_order_items_clean),
    ("Amazon UAE", amazon_order_items_clean),
    ("Noon", noon_order_items_clean)
]:

    line_amount_is_decimal = df["LineAmount"].apply(
        lambda value: isinstance(value, Decimal)
    ).all()

    validation_results.append({
        "Validation": f"{source_name} LineAmount Decimal conversion",
        "Expected": "All values are Decimal-compatible",
        "Actual": (
            "All values are Decimal"
            if line_amount_is_decimal
            else "One or more values are not Decimal"
        ),
        "Passed": line_amount_is_decimal
    })


# ---------------------------------------------------------
# 6. Quantity and Monetary Business Value Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_order_items_clean),
    ("Amazon UAE", amazon_order_items_clean),
    ("Noon", noon_order_items_clean)
]:

    invalid_quantity_count = (
        df["Qty"] <= 0
    ).sum()

    invalid_discount_count = (
        df["DiscountAmount"]
        > (
            df["Qty"].apply(Decimal)
            * df["UnitPrice"]
        )
    ).sum()

    validation_results.append({
        "Validation": f"{source_name} quantity and monetary business values",
        "Expected": (
            "Qty > 0 and DiscountAmount does not exceed "
            "gross line value"
        ),
        "Actual": (
            f"Qty <= 0: {invalid_quantity_count}; "
            f"Discount exceeds gross line value: "
            f"{invalid_discount_count}"
        ),
        "Passed": (
            invalid_quantity_count == 0
            and invalid_discount_count == 0
        )
    })


# ---------------------------------------------------------
# 7. LineAmount Calculation Validation
# ---------------------------------------------------------

for source_name, df in [
    ("Shopify", shopify_order_items_clean),
    ("Amazon UAE", amazon_order_items_clean),
    ("Noon", noon_order_items_clean)
]:

    calculated_line_amount = (
        df["Qty"].apply(Decimal)
        * df["UnitPrice"]
        - df["DiscountAmount"]
    )

    line_amount_mismatch_count = (
        calculated_line_amount
        != df["LineAmount"]
    ).sum()

    validation_results.append({
        "Validation": f"{source_name} LineAmount calculation",
        "Expected": (
            "LineAmount equals "
            "(Qty × UnitPrice) - DiscountAmount"
        ),
        "Actual": (
            f"{line_amount_mismatch_count} calculation mismatches"
        ),
        "Passed": line_amount_mismatch_count == 0
    })


# ---------------------------------------------------------
# 8. Profiler Outlier Candidate Retention Validation
# ---------------------------------------------------------

for source_name, raw_df, clean_df in [
    ("Shopify", shopify_order_items_raw, shopify_order_items_clean),
    ("Amazon UAE", amazon_order_items_raw, amazon_order_items_clean),
    ("Noon", noon_order_items_raw, noon_order_items_clean)
]:

    source_line_ids = raw_df["SourceLineID"].tolist()

    retained_line_ids = clean_df["SourceLineID"].tolist()

    line_ids_retained = (
        source_line_ids == retained_line_ids
    )

    validation_results.append({
        "Validation": (
            f"{source_name} profiler outlier candidate "
            "retention"
        ),
        "Expected": (
            "Source records and identified outlier candidates "
            "remain retained"
        ),
        "Actual": (
            "Source line records retained unchanged"
            if line_ids_retained
            else "Source line records changed or removed"
        ),
        "Passed": line_ids_retained
    })


# ---------------------------------------------------------
# Transformation Validation Results
# ---------------------------------------------------------

transformation_validation = pd.DataFrame(
    validation_results
)

print("TRANSFORMATION VALIDATION RESULTS")
print("=" * 120)

display(transformation_validation)


# ---------------------------------------------------------
# Overall Result
# ---------------------------------------------------------

overall_validation_passed = (
    transformation_validation["Passed"].all()
)

print(
    "\nOverall Transformation Validation Passed:",
    overall_validation_passed
)

if not overall_validation_passed:
    raise ValueError(
        "Transformation validation failed. Review the results "
        "before proceeding."
    )

TRANSFORMATION VALIDATION RESULTS
========================================================================================================================

                                          Validation                                                          Expected                                             Actual  Passed
0              Shopify CreatedOn datetime conversion                                               datetime64 datatype                                     datetime64[ns]    True
1           Amazon UAE CreatedOn datetime conversion                                               datetime64 datatype                                     datetime64[ns]    True
2                 Noon CreatedOn datetime conversion                                               datetime64 datatype                                     datetime64[ns]    True
3             Shopify ModifiedOn datetime conversion                                               datetime64 datatype                                     datetime64[ns]    True
4          Amazon UAE ModifiedOn datetime conversion                                               datetime64 datatype                                     datetime64[ns]    True
5                Noon ModifiedOn datetime conversion                                               datetime64 datatype                                     datetime64[ns]    True
6               Shopify UnitPrice Decimal conversion                                 All values are Decimal-compatible                             All values are Decimal    True
7            Amazon UAE UnitPrice Decimal conversion                                 All values are Decimal-compatible                             All values are Decimal    True
8                  Noon UnitPrice Decimal conversion                                 All values are Decimal-compatible                             All values are Decimal    True
9          Shopify DiscountAmount Decimal conversion                                 All values are Decimal-compatible                             All values are Decimal    True
10      Amazon UAE DiscountAmount Decimal conversion                                 All values are Decimal-compatible                             All values are Decimal    True
11            Noon DiscountAmount Decimal conversion                                 All values are Decimal-compatible                             All values are Decimal    True
12             Shopify LineAmount Decimal conversion                                 All values are Decimal-compatible                             All values are Decimal    True
13          Amazon UAE LineAmount Decimal conversion                                 All values are Decimal-compatible                             All values are Decimal    True
14                Noon LineAmount Decimal conversion                                 All values are Decimal-compatible                             All values are Decimal    True
15     Shopify quantity and monetary business values       Qty > 0 and DiscountAmount does not exceed gross line value  Qty <= 0: 0; Discount exceeds gross line value: 0    True
16  Amazon UAE quantity and monetary business values       Qty > 0 and DiscountAmount does not exceed gross line value  Qty <= 0: 0; Discount exceeds gross line value: 0    True
17        Noon quantity and monetary business values       Qty > 0 and DiscountAmount does not exceed gross line value  Qty <= 0: 0; Discount exceeds gross line value: 0    True
18                    Shopify LineAmount calculation              LineAmount equals (Qty × UnitPrice) - DiscountAmount                           0 calculation mismatches    True
19                 Amazon UAE LineAmount calculation              LineAmount equals (Qty × UnitPrice) - DiscountAmount                           0 calculation mismatches    True
20                       Noon LineAmount calculation              LineAmount equals (Qty × UnitPrice) - DiscountAmount                           0 calculation mismatches    True
21      Shopify profiler outlier candidate retention  Source records and identified outlier candidates remain retained             Source line records retained unchanged    True
22   Amazon UAE profiler outlier candidate retention  Source records and identified outlier candidates remain retained             Source line records retained unchanged    True
23         Noon profiler outlier candidate retention  Source records and identified outlier candidates remain retained             Source line records retained unchanged    True

Overall Transformation Validation Passed: True

## 3.2 Validate Data Preservation

Validate that the approved transformations did not unintentionally alter unaffected Sales Order Item data.

The validation compares the raw and cleaned datasets while accounting for the approved transformations:

- CreatedOn datatype conversion

- ModifiedOn datatype conversion

- UnitPrice datatype conversion

- DiscountAmount datatype conversion

- LineAmount datatype conversion

All other business and audit field values should remain unchanged.

Each source dataset will be validated separately.

In [15]:
# =========================================================
# 3.2 Validate Data Preservation
# =========================================================

# Columns that should remain completely unchanged after
# accounting for approved transformations
unchanged_columns = [
    "SourceSystem",
    "SourceOrderID",
    "SourceLineID",
    "SourceOrderIDInternal",
    "ProductCode",
    "Qty",
    "CreatedByUser",
    "ModifiedByUser"
]


all_datasets_match = True


# =========================================================
# Shopify
# =========================================================

print("=" * 70)
print("SHOPIFY SALES ORDER ITEM DATA PRESERVATION")
print("=" * 70)

for column in unchanged_columns:

    matches = (
        shopify_order_items_raw[column]
        .astype(str)
        .reset_index(drop=True)
        ==
        shopify_order_items_clean[column]
        .astype(str)
        .reset_index(drop=True)
    ).all()

    print(f"{column}: {matches}")

    if not matches:
        all_datasets_match = False


# =========================================================
# Amazon UAE
# =========================================================

print("\n" + "=" * 70)
print("AMAZON UAE SALES ORDER ITEM DATA PRESERVATION")
print("=" * 70)

for column in unchanged_columns:

    matches = (
        amazon_order_items_raw[column]
        .astype(str)
        .reset_index(drop=True)
        ==
        amazon_order_items_clean[column]
        .astype(str)
        .reset_index(drop=True)
    ).all()

    print(f"{column}: {matches}")

    if not matches:
        all_datasets_match = False


# =========================================================
# Noon
# =========================================================

print("\n" + "=" * 70)
print("NOON SALES ORDER ITEM DATA PRESERVATION")
print("=" * 70)

for column in unchanged_columns:

    matches = (
        noon_order_items_raw[column]
        .astype(str)
        .reset_index(drop=True)
        ==
        noon_order_items_clean[column]
        .astype(str)
        .reset_index(drop=True)
    ).all()

    print(f"{column}: {matches}")

    if not matches:
        all_datasets_match = False


# =========================================================
# Final Validation
# =========================================================

print(
    "\nAll unaffected Sales Order Item columns preserved:",
    all_datasets_match
)

if not all_datasets_match:
    raise ValueError(
        "Data preservation validation failed. "
        "An unaffected Sales Order Item column was unexpectedly changed."
    )

======================================================================
SHOPIFY SALES ORDER ITEM DATA PRESERVATION
======================================================================
SourceSystem: True
SourceOrderID: True
SourceLineID: True
SourceOrderIDInternal: True
ProductCode: True
Qty: True
CreatedByUser: True
ModifiedByUser: True

======================================================================
AMAZON UAE SALES ORDER ITEM DATA PRESERVATION
======================================================================
SourceSystem: True
SourceOrderID: True
SourceLineID: True
SourceOrderIDInternal: True
ProductCode: True
Qty: True
CreatedByUser: True
ModifiedByUser: True

======================================================================
NOON SALES ORDER ITEM DATA PRESERVATION
======================================================================
SourceSystem: True
SourceOrderID: True
SourceLineID: True
SourceOrderIDInternal: True
ProductCode: True
Qty: True
CreatedByUser: True
ModifiedByUser: True

All unaffected Sales Order Item columns preserved: True

# =========================================================
# SECTION 4 — CLEAN CSV
# =========================================================

## 4.1 Consolidate Validated Sales Order Item Datasets

Consolidate the validated Clean DataFrames from Shopify, Amazon UAE,
and Noon into one consolidated Sales Order Item Clean DataFrame.

Consolidation is performed only after each source dataset has completed
its transformation and data preservation validation.

The source-specific Clean DataFrames must not be modified during
consolidation.

The consolidated dataset must:

- Combine the validated records from all three source systems.

- Preserve the approved column structure.

- Preserve source-system lineage.

- Preserve SourceOrderID, SourceLineID, and SourceOrderIDInternal.

- Preserve approved business values and NULL values.

- Not generate or resequence Sales Order Item identifiers.

- Not correct or modify source-specific business exceptions.

- Not introduce unexpected columns.

The result will be one consolidated Clean DataFrame representing the
validated Sales Order Item records from all source systems.

In [16]:
# =========================================================
# 4.1 Consolidate Validated Sales Order Item Datasets
# =========================================================

# ---------------------------------------------------------
# 1. Define the expected consolidated column structure
# ---------------------------------------------------------

sales_order_item_clean_columns = [
    "SourceSystem",
    "SourceOrderID",
    "SourceLineID",
    "SourceOrderIDInternal",
    "ProductCode",
    "Qty",
    "UnitPrice",
    "DiscountAmount",
    "LineAmount",
    "CreatedOn",
    "CreatedByUser",
    "ModifiedOn",
    "ModifiedByUser"
]


# ---------------------------------------------------------
# 2. Validate column compatibility before consolidation
# ---------------------------------------------------------

shopify_columns_match = (
    shopify_order_items_clean.columns.tolist()
    == sales_order_item_clean_columns
)

amazon_columns_match = (
    amazon_order_items_clean.columns.tolist()
    == sales_order_item_clean_columns
)

noon_columns_match = (
    noon_order_items_clean.columns.tolist()
    == sales_order_item_clean_columns
)

print("Column structure validation:")
print("Shopify:", shopify_columns_match)
print("Amazon UAE:", amazon_columns_match)
print("Noon:", noon_columns_match)


if not all([
    shopify_columns_match,
    amazon_columns_match,
    noon_columns_match
]):
    raise ValueError(
        "Consolidation stopped. "
        "One or more source datasets do not have the expected "
        "Sales Order Item column structure."
    )


# ---------------------------------------------------------
# 3. Record validated source row counts
# ---------------------------------------------------------

shopify_clean_row_count = shopify_order_items_clean.shape[0]
amazon_clean_row_count = amazon_order_items_clean.shape[0]
noon_clean_row_count = noon_order_items_clean.shape[0]

expected_consolidated_row_count = (
    shopify_clean_row_count
    + amazon_clean_row_count
    + noon_clean_row_count
)

print("\nValidated source row counts:")
print("Shopify:", shopify_clean_row_count)
print("Amazon UAE:", amazon_clean_row_count)
print("Noon:", noon_clean_row_count)

print(
    "\nExpected consolidated row count:",
    expected_consolidated_row_count
)


# ---------------------------------------------------------
# 4. Consolidate validated Clean DataFrames
# ---------------------------------------------------------

sales_order_item_clean = pd.concat(
    [
        shopify_order_items_clean,
        amazon_order_items_clean,
        noon_order_items_clean
    ],
    axis=0,
    ignore_index=True
)


# ---------------------------------------------------------
# 5. Confirm consolidated structure and row count
# ---------------------------------------------------------

print("\nConsolidated Sales Order Item dataset created.")

print("Consolidated shape:")
print(sales_order_item_clean.shape)

print("\nConsolidated columns:")
print(sales_order_item_clean.columns.tolist())

print(
    "\nActual consolidated row count:",
    sales_order_item_clean.shape[0]
)

print(
    "Expected consolidated row count:",
    expected_consolidated_row_count
)


# ---------------------------------------------------------
# 6. Validate consolidated row count
# ---------------------------------------------------------

if sales_order_item_clean.shape[0] != expected_consolidated_row_count:
    raise ValueError(
        "Consolidation validation failed. "
        "The consolidated row count does not match the "
        "sum of the validated source datasets."
    )


# ---------------------------------------------------------
# 7. Confirm source-system distribution
# ---------------------------------------------------------

print("\nRecords by source system:")
print(
    sales_order_item_clean["SourceSystem"]
    .value_counts()
)


# ---------------------------------------------------------
# 8. Confirm source lineage fields are populated
# ---------------------------------------------------------

print("\nSource lineage validation:")

print(
    "SourceSystem nulls:",
    sales_order_item_clean["SourceSystem"].isnull().sum()
)

print(
    "SourceOrderID nulls:",
    sales_order_item_clean["SourceOrderID"].isnull().sum()
)

print(
    "SourceLineID nulls:",
    sales_order_item_clean["SourceLineID"].isnull().sum()
)

print(
    "SourceOrderIDInternal nulls:",
    sales_order_item_clean["SourceOrderIDInternal"].isnull().sum()
)


# ---------------------------------------------------------
# 9. Final consolidation validation
# ---------------------------------------------------------

consolidation_passed = (
    sales_order_item_clean.shape[0]
    == expected_consolidated_row_count
    and sales_order_item_clean.columns.tolist()
    == sales_order_item_clean_columns
    and sales_order_item_clean["SourceSystem"].notna().all()
    and sales_order_item_clean["SourceOrderID"].notna().all()
    and sales_order_item_clean["SourceLineID"].notna().all()
    and sales_order_item_clean["SourceOrderIDInternal"].notna().all()
)

print(
    "\nConsolidation Validation Passed:",
    consolidation_passed
)

if not consolidation_passed:
    raise ValueError(
        "Sales Order Item consolidation validation failed."
    )

Column structure validation:
Shopify: True
Amazon UAE: True
Noon: True

Validated source row counts:
Shopify: 11
Amazon UAE: 8
Noon: 7

Expected consolidated row count: 26

Consolidated Sales Order Item dataset created.
Consolidated shape:
(26, 13)

Consolidated columns:
['SourceSystem', 'SourceOrderID', 'SourceLineID', 'SourceOrderIDInternal', 'ProductCode', 'Qty', 'UnitPrice', 'DiscountAmount', 'LineAmount', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Actual consolidated row count: 26
Expected consolidated row count: 26

Records by source system:
SourceSystem
Shopify       11
Amazon UAE     8
Noon           7
Name: count, dtype: int64

Source lineage validation:
SourceSystem nulls: 0
SourceOrderID nulls: 0
SourceLineID nulls: 0
SourceOrderIDInternal nulls: 0

Consolidation Validation Passed: True

## 4.2 Export Consolidated Clean Sales Order Item Dataset

Export the validated consolidated `sales_order_item_clean` DataFrame as the

clean Sales Order Item dataset.

The clean CSV represents the completed data-cleaning and consolidation

stage and preserves the validated Sales Order Item records from Shopify,

Amazon UAE, and Noon before database-ready column mapping begins.

In [17]:
# =========================================================
# 4.2 Export Consolidated Clean Sales Order Item Dataset
# =========================================================

from pathlib import Path

clean_sales_order_item_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\12_Commerce_Consolidated\Sales_Order_Item\clean"
    r"\sales_order_item_clean.csv"
)

# Create the clean folder if it does not exist
clean_sales_order_item_path.parent.mkdir(
    parents=True,
    exist_ok=True
)

# Export consolidated clean dataset
sales_order_item_clean.to_csv(
    clean_sales_order_item_path,
    index=False
)

print("Consolidated Clean Sales Order Item CSV exported successfully.")
print("Path:", clean_sales_order_item_path)
print("Rows exported:", len(sales_order_item_clean))
print("Columns exported:", len(sales_order_item_clean.columns))

Consolidated Clean Sales Order Item CSV exported successfully.
Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\12_Commerce_Consolidated\Sales_Order_Item\clean\sales_order_item_clean.csv
Rows exported: 26
Columns exported: 13

## 4.3 Verify Exported Clean Sales Order Item CSV

Reload the exported consolidated Clean Sales Order Item CSV and verify that

it matches the validated consolidated `sales_order_item_clean` DataFrame.

This confirms that the persisted consolidated Clean CSV is the official

handoff artifact for the next pipeline stage.

The verification must confirm:

- Row count

- Column names and order

- Reloaded datatypes

- Data content

The exported CSV must represent the same validated records produced

during the controlled consolidation stage.

In [19]:
# =========================================================
# 4.3 Verify Exported Clean Sales Order Item CSV
# =========================================================

from decimal import Decimal


# ---------------------------------------------------------
# Reload the exported consolidated clean CSV
# ---------------------------------------------------------

sales_order_item_clean_csv = pd.read_csv(
    clean_sales_order_item_path,
    parse_dates=[
        "CreatedOn",
        "ModifiedOn"
    ]
)


# ---------------------------------------------------------
# Basic Export Validation
# ---------------------------------------------------------

print(
    "Clean CSV rows:",
    len(sales_order_item_clean_csv)
)

print(
    "Clean DataFrame rows:",
    len(sales_order_item_clean)
)

print(
    "\nClean CSV columns:",
    len(sales_order_item_clean_csv.columns)
)

print(
    "Clean DataFrame columns:",
    len(sales_order_item_clean.columns)
)


# ---------------------------------------------------------
# Row Count Validation
# ---------------------------------------------------------

row_count_match = (
    len(sales_order_item_clean_csv)
    == len(sales_order_item_clean)
)

print(
    "\nRow count matches:",
    row_count_match
)


# ---------------------------------------------------------
# Column Validation
# ---------------------------------------------------------

columns_match = (
    list(sales_order_item_clean_csv.columns)
    == list(sales_order_item_clean.columns)
)

print(
    "Column names and order match:",
    columns_match
)


# ---------------------------------------------------------
# Datatype Validation
# ---------------------------------------------------------

print("\nReloaded Clean CSV datatypes:")
print(sales_order_item_clean_csv.dtypes)


# ---------------------------------------------------------
# Content Validation
# ---------------------------------------------------------
# CSV does not preserve Python Decimal as a native datatype.
# Therefore, monetary columns are normalized to Decimal
# before comparing the exported CSV with the clean DataFrame.
# This validates value preservation rather than Python
# in-memory datatype preservation.
# ---------------------------------------------------------

comparison_columns = list(
    sales_order_item_clean.columns
)

clean_for_comparison = (
    sales_order_item_clean[
        comparison_columns
    ]
    .reset_index(drop=True)
    .copy()
)

csv_for_comparison = (
    sales_order_item_clean_csv[
        comparison_columns
    ]
    .reset_index(drop=True)
    .copy()
)


# ---------------------------------------------------------
# Normalize Monetary Columns for CSV Round-Trip Comparison
# ---------------------------------------------------------

monetary_columns = [
    "UnitPrice",
    "DiscountAmount",
    "LineAmount"
]

for column in monetary_columns:
    
    clean_for_comparison[column] = (
        clean_for_comparison[column]
        .apply(Decimal)
    )
    
    csv_for_comparison[column] = (
        csv_for_comparison[column]
        .apply(Decimal)
    )


# ---------------------------------------------------------
# Compare Content
# ---------------------------------------------------------

content_match = (
    clean_for_comparison
    .equals(
        csv_for_comparison
    )
)

print(
    "\nClean DataFrame and exported CSV content match:",
    content_match
)


# ---------------------------------------------------------
# Final Validation
# ---------------------------------------------------------

export_validation_passed = (
    row_count_match
    and columns_match
    and content_match
)

print(
    "\n" + "=" * 80
)

print(
    "EXPORTED CLEAN CSV VALIDATION PASSED:",
    export_validation_passed
)

print(
    "=" * 80
)


if not export_validation_passed:
    raise ValueError(
        "Exported consolidated clean CSV validation failed. "
        "Review the results before proceeding."
    )

Clean CSV rows: 26
Clean DataFrame rows: 26

Clean CSV columns: 13
Clean DataFrame columns: 13

Row count matches: True
Column names and order match: True

Reloaded Clean CSV datatypes:
SourceSystem                     object
SourceOrderID                    object
SourceLineID                     object
SourceOrderIDInternal            object
ProductCode                      object
Qty                               int64
UnitPrice                         int64
DiscountAmount                    int64
LineAmount                        int64
CreatedOn                datetime64[ns]
CreatedByUser                    object
ModifiedOn               datetime64[ns]
ModifiedByUser                   object
dtype: object

Clean DataFrame and exported CSV content match: True

================================================================================
EXPORTED CLEAN CSV VALIDATION PASSED: True
================================================================================

# =========================================================

# SECTION 5 — DATABASE READY

# =========================================================

## 5.1 Define Source → Target Mapping

Define the approved source-to-target column mapping based on the

LJ Dev Commerce Sales Order Item Data Dictionary.

The mapping converts the consolidated Clean Sales Order Item column names

into the standardized PostgreSQL target column names.

No data values are modified during this step.

In [20]:
# =========================================================
# 5.1 Define Source → Target Mapping
# =========================================================

sales_order_item_column_mapping = {
    "SourceOrderIDInternal": "sales_order_id",
    "SourceLineID": "sales_order_item_id",
    "ProductCode": "product_id",
    "Qty": "quantity",
    "UnitPrice": "unit_price",
    "DiscountAmount": "discount_amount",
    "LineAmount": "line_total",
    "CreatedOn": "created_date",
    "CreatedByUser": "created_by",
    "ModifiedOn": "updated_date",
    "ModifiedByUser": "updated_by"
}

print("Sales Order Item Source → Target Mapping")
print("=" * 80)

for source_column, target_column in sales_order_item_column_mapping.items():
    print(f"{source_column:<25} → {target_column}")

Sales Order Item Source → Target Mapping
================================================================================
SourceOrderIDInternal     → sales_order_id
SourceLineID              → sales_order_item_id
ProductCode               → product_id
Qty                       → quantity
UnitPrice                 → unit_price
DiscountAmount            → discount_amount
LineAmount                → line_total
CreatedOn                 → created_date
CreatedByUser             → created_by
ModifiedOn                → updated_date
ModifiedByUser            → updated_by

## 5.2 Create Database-Ready Dataset

Create the Sales Order Item Database-Ready dataset from the verified

exported consolidated Clean CSV.

The approved source-to-target mapping is then applied to convert the

source column names into the PostgreSQL target structure.

The Clean CSV remains unchanged.

No undocumented business-value transformations are applied during

this step.

Source-system lineage fields that are not part of the current

PostgreSQL target structure remain available in the verified Clean CSV

for source traceability and reconciliation.

In [21]:
# =========================================================
# 5.2 Create Database-Ready Dataset
# =========================================================

from decimal import Decimal

# Define the verified exported consolidated Clean CSV path
sales_order_item_clean_path = (
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data"
    r"\12_Commerce_Consolidated\Sales_Order_Item\clean"
    r"\sales_order_item_clean.csv"
)

# Load the verified exported consolidated Clean CSV
sales_order_item_clean_exported = pd.read_csv(
    sales_order_item_clean_path
)

# Convert approved date columns back to datetime
sales_order_item_clean_exported["CreatedOn"] = pd.to_datetime(
    sales_order_item_clean_exported["CreatedOn"]
)

sales_order_item_clean_exported["ModifiedOn"] = pd.to_datetime(
    sales_order_item_clean_exported["ModifiedOn"]
)

# Select only the approved source columns that map
# to the PostgreSQL Sales Order Item target structure
sales_order_item_db_ready = (
    sales_order_item_clean_exported[
        list(sales_order_item_column_mapping.keys())
    ]
    .rename(columns=sales_order_item_column_mapping)
    .copy()
)

# ---------------------------------------------------------
# Prepare Approved Monetary Fields as Decimal
# ---------------------------------------------------------

monetary_columns = [
    "unit_price",
    "discount_amount",
    "line_total"
]

for column in monetary_columns:
    sales_order_item_db_ready[column] = (
        sales_order_item_db_ready[column]
        .apply(Decimal)
    )

print("Sales Order Item Database-Ready Dataset Created Successfully.")
print("=" * 80)

print("\nSource: Verified Exported Consolidated Clean CSV")

print("\nDatabase-Ready Dataset Shape:")
print(sales_order_item_db_ready.shape)

print("\nDatabase-Ready Column Names:")
print(sales_order_item_db_ready.columns.tolist())

print("\nDatabase-Ready Data Types:")
print(sales_order_item_db_ready.dtypes)

print("\nDatabase-Ready Missing Values:")
print(sales_order_item_db_ready.isnull().sum())

print("\nDatabase-Ready Dataset:")
display(sales_order_item_db_ready)

Sales Order Item Database-Ready Dataset Created Successfully.
================================================================================

Source: Verified Exported Consolidated Clean CSV

Database-Ready Dataset Shape:
(26, 11)

Database-Ready Column Names:
['sales_order_id', 'sales_order_item_id', 'product_id', 'quantity', 'unit_price', 'discount_amount', 'line_total', 'created_date', 'created_by', 'updated_date', 'updated_by']

Database-Ready Data Types:
sales_order_id                 object
sales_order_item_id            object
product_id                     object
quantity                        int64
unit_price                     object
discount_amount                object
line_total                     object
created_date           datetime64[ns]
created_by                     object
updated_date           datetime64[ns]
updated_by                     object
dtype: object

Database-Ready Missing Values:
sales_order_id         0
sales_order_item_id    0
product_id             0
quantity               0
unit_price             0
discount_amount        0
line_total             0
created_date           0
created_by             0
updated_date           0
updated_by             0
dtype: int64

Database-Ready Dataset:

   sales_order_id sales_order_item_id product_id  quantity unit_price discount_amount line_total created_date created_by updated_date updated_by
0           SO001              SOI001      P0001         1       2499               0       2499   2026-07-01      admin   2026-07-24      admin
1           SO002              SOI002      P0002         1       2199               0       2199   2026-07-01      admin   2026-07-24      admin
2           SO003              SOI003      P0004         1       1399               0       1399   2026-07-01      admin   2026-07-24      admin
3           SO004              SOI004      P0003         1       3899               0       3899   2026-07-01      admin   2026-07-24      admin
4           SO005              SOI005      P0005         1       2999               0       2999   2026-07-01      admin   2026-07-24      admin
5           SO006              SOI006      P0009         1        699               0        699   2026-07-01      admin   2026-07-24      admin
6           SO007              SOI007      P0008         1       2899               0       2899   2026-07-01      admin   2026-07-24      admin
7           SO001              SOI021      P0011         2        399              99        699   2026-07-01      admin   2026-07-24      admin
8           SO004              SOI022      P0011         1        399               0        399   2026-07-01      admin   2026-07-24      admin
9           SO005              SOI023      P0012         1        449               0        449   2026-07-01      admin   2026-07-24      admin
10          SO007              SOI024      P0013         2        179               0        358   2026-07-01      admin   2026-07-24      admin
11          SO008              SOI008      P0010         1       1599               0       1599   2026-07-01      admin   2026-07-24      admin
12          SO009              SOI009      P0011         1        399               0        399   2026-07-01      admin   2026-07-24      admin
13          SO010              SOI010      P0012         1        449               0        449   2026-07-01      admin   2026-07-24      admin
14          SO011              SOI011      P0014         1        499               0        499   2026-07-01      admin   2026-07-24      admin
15          SO012              SOI012      P0015         1        699               0        699   2026-07-01      admin   2026-07-24      admin
16          SO013              SOI013      P0007         1       2599               0       2599   2026-07-01      admin   2026-07-24      admin
17          SO014              SOI014      P0013         1        179               0        179   2026-07-01      admin   2026-07-24      admin
18          SO013              SOI025      P0009         1        699               0        699   2026-07-01      admin   2026-07-24      admin
19          SO015              SOI015      P0008         1       2899               0       2899   2026-07-01      admin   2026-07-24      admin
20          SO016              SOI016      P0009         1        699               0        699   2026-07-01      admin   2026-07-24      admin
21          SO017              SOI017      P0014         1        499               0        499   2026-07-01      admin   2026-07-24      admin
22          SO018              SOI018      P0003         1       3899               0       3899   2026-07-01      admin   2026-07-24      admin
23          SO019              SOI019      P0002         1       2199               0       2199   2026-07-01      admin   2026-07-24      admin
24          SO020              SOI020      P0010         1       1599               0       1599   2026-07-01      admin   2026-07-24      admin
25          SO015              SOI026      P0015         1        699               0        699   2026-07-01      admin   2026-07-24      admin

## 5.3 Database-Ready Validation

Validate the Sales Order Item Database-Ready DataFrame before

PostgreSQL loading.

This validation confirms that:

* The row count is preserved from the verified Clean CSV.

* All expected target columns are present.

* Target columns are in the approved order.

* The source-to-target mapping is complete.

* No undocumented source columns were lost.

* Required fields do not contain NULL values.

* The primary key is unique and does not contain NULL values.

* The dataset is prepared for PostgreSQL table verification and loading.

In [22]:
# =========================================================
# 5.3 Database-Ready Validation
# =========================================================

print("Sales Order Item Database-Ready Validation")
print("=" * 80)


# ---------------------------------------------------------
# 1. Row Count Validation
# ---------------------------------------------------------

print("\n1. Row Count Validation")

clean_csv_row_count = len(
    sales_order_item_clean_exported
)

database_ready_row_count = len(
    sales_order_item_db_ready
)

row_count_match = (
    clean_csv_row_count
    == database_ready_row_count
)

print(
    "Verified Clean CSV rows:",
    clean_csv_row_count
)

print(
    "Database-Ready rows:",
    database_ready_row_count
)

print(
    "Row counts match:",
    row_count_match
)


# ---------------------------------------------------------
# 2. Expected Target Column Validation
# ---------------------------------------------------------

print("\n2. Expected Target Column Validation")

expected_target_columns = list(
    sales_order_item_column_mapping.values()
)

actual_target_columns = (
    sales_order_item_db_ready.columns.tolist()
)

target_columns_match = (
    expected_target_columns
    == actual_target_columns
)

print("Expected target columns:")
print(expected_target_columns)

print("\nActual Database-Ready columns:")
print(actual_target_columns)

print(
    "\nColumns and order match:",
    target_columns_match
)


# ---------------------------------------------------------
# 3. Mapping Completeness Validation
# ---------------------------------------------------------

print("\n3. Mapping Completeness Validation")

source_columns = (
    sales_order_item_clean_exported.columns.tolist()
)

mapping_source_columns = list(
    sales_order_item_column_mapping.keys()
)

# These lineage columns intentionally remain in the
# Clean CSV but are not mapped to the current target table.
expected_unmapped_source_columns = [
    "SourceSystem",
    "SourceOrderID"
]

mapped_source_columns_present = (
    set(mapping_source_columns).issubset(
        set(source_columns)
    )
)

actual_unmapped_source_columns = (
    sorted(
        set(source_columns)
        - set(mapping_source_columns)
    )
)

unmapped_source_columns_expected = (
    actual_unmapped_source_columns
    == sorted(
        expected_unmapped_source_columns
    )
)

unexpected_mapping_source_columns = (
    sorted(
        set(mapping_source_columns)
        - set(source_columns)
    )
)

mapping_complete = (
    mapped_source_columns_present
    and unmapped_source_columns_expected
    and len(
        unexpected_mapping_source_columns
    ) == 0
)

print(
    "Mapped source columns are present:",
    mapped_source_columns_present
)

print(
    "Expected unmapped lineage columns:",
    expected_unmapped_source_columns
)

print(
    "Actual unmapped source columns:",
    actual_unmapped_source_columns
)

print(
    "Lineage exclusions are as expected:",
    unmapped_source_columns_expected
)

print(
    "Unexpected mapping source columns:",
    unexpected_mapping_source_columns
)

print(
    "Source-to-target mapping complete:",
    mapping_complete
)


# ---------------------------------------------------------
# 4. Required Field Validation
# ---------------------------------------------------------

print("\n4. Required Field Validation")

required_sales_order_item_fields = [
    "sales_order_item_id",
    "sales_order_id",
    "product_id",
    "quantity",
    "unit_price",
    "discount_amount",
    "line_total",
    "created_date",
    "created_by",
    "updated_date",
    "updated_by"
]

null_counts = (
    sales_order_item_db_ready[
        required_sales_order_item_fields
    ].isnull().sum()
)

print(null_counts)

required_fields_valid = (
    null_counts.sum() == 0
)

print(
    "\nRows with NULL required values:",
    null_counts.sum()
)

print(
    "Required field validation passed:",
    required_fields_valid
)


# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

print("\n5. Primary Key Validation")

duplicate_primary_keys = (
    sales_order_item_db_ready[
        "sales_order_item_id"
    ]
    .duplicated()
    .sum()
)

null_primary_keys = (
    sales_order_item_db_ready[
        "sales_order_item_id"
    ]
    .isnull()
    .sum()
)

primary_key_valid = (
    duplicate_primary_keys == 0
    and null_primary_keys == 0
)

print(
    "Duplicate Primary Keys:",
    duplicate_primary_keys
)

print(
    "NULL Primary Keys:",
    null_primary_keys
)

print(
    "Primary Key validation passed:",
    primary_key_valid
)


# ---------------------------------------------------------
# 6. Overall Database-Ready Validation
# ---------------------------------------------------------

database_ready_validation_passed = (
    row_count_match
    and target_columns_match
    and mapping_complete
    and required_fields_valid
    and primary_key_valid
)

print("\n6. Database-Ready Validation Summary")
print("=" * 80)

print(
    "Database-Ready validation passed:",
    database_ready_validation_passed
)

Sales Order Item Database-Ready Validation
================================================================================

1. Row Count Validation
Verified Clean CSV rows: 26
Database-Ready rows: 26
Row counts match: True

2. Expected Target Column Validation
Expected target columns:
['sales_order_id', 'sales_order_item_id', 'product_id', 'quantity', 'unit_price', 'discount_amount', 'line_total', 'created_date', 'created_by', 'updated_date', 'updated_by']

Actual Database-Ready columns:
['sales_order_id', 'sales_order_item_id', 'product_id', 'quantity', 'unit_price', 'discount_amount', 'line_total', 'created_date', 'created_by', 'updated_date', 'updated_by']

Columns and order match: True

3. Mapping Completeness Validation
Mapped source columns are present: True
Expected unmapped lineage columns: ['SourceSystem', 'SourceOrderID']
Actual unmapped source columns: ['SourceOrderID', 'SourceSystem']
Lineage exclusions are as expected: True
Unexpected mapping source columns: []
Source-to-target mapping complete: True

4. Required Field Validation
sales_order_item_id    0
sales_order_id         0
product_id             0
quantity               0
unit_price             0
discount_amount        0
line_total             0
created_date           0
created_by             0
updated_date           0
updated_by             0
dtype: int64

Rows with NULL required values: 0
Required field validation passed: True

5. Primary Key Validation
Duplicate Primary Keys: 0
NULL Primary Keys: 0
Primary Key validation passed: True

6. Database-Ready Validation Summary
================================================================================
Database-Ready validation passed: True

# =========================================================

# SECTION 6 — PostgreSQL

# =========================================================

Connect to PostgreSQL and confirm that the ETL notebook is connected to

the correct database and PostgreSQL environment.

No table changes or data loading are performed in this step.

## 6.1 Connect

Establish a PostgreSQL connection for the Sales Order Item ETL

process.

Confirm that:

* The PostgreSQL connection is successful.

* The correct database is connected.

* The correct PostgreSQL user is connected.

* The target schema is available.

No records are inserted during this step.

In [23]:
# =========================================================
# 6.1 Connect to PostgreSQL
# =========================================================

import psycopg2
from getpass import getpass


# ---------------------------------------------------------
# PostgreSQL Connection Configuration
# ---------------------------------------------------------

DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "lj_dev_commerce"
DB_USER = "postgres"

DB_PASSWORD = getpass("Enter PostgreSQL password: ")


# ---------------------------------------------------------
# Connect to PostgreSQL
# ---------------------------------------------------------

try:
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD
    )

    cursor = conn.cursor()

    print("PostgreSQL connection successful.")
    print("Database:", DB_NAME)
    print("Host:", DB_HOST)
    print("Port:", DB_PORT)

except Exception as e:
    print("PostgreSQL connection failed.")
    print("Error:", e)

PostgreSQL connection successful.
Database: lj_dev_commerce
Host: localhost
Port: 5432

## 6.2 Prepare / Create Target Table

Check whether the approved Sales Order Item PostgreSQL target table

already exists before creating or modifying anything.

Target:

Schema: commerce

Table: sales_order_item

The table must not be recreated blindly. Its existence and approved

database design must be confirmed first.

In [24]:
# =========================================================
# 6.2 Prepare / Create Target Table
# =========================================================

target_schema = "commerce"
target_table = "sales_order_item"

# Check whether the target table already exists
cursor.execute("""
    SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = %s
          AND table_name = %s
    );
""", (target_schema, target_table))

table_exists = cursor.fetchone()[0]

print("Sales Order Item Target Table Check")
print("=" * 80)

print("Schema:", target_schema)
print("Table:", target_table)
print("Table exists:", table_exists)

if table_exists:
    print("\nTarget table already exists.")
    print("The table will not be recreated.")
else:
    print("\nTarget table does not exist.")
    print("The approved database design must be used before creating it.")

Sales Order Item Target Table Check
================================================================================
Schema: commerce
Table: sales_order_item
Table exists: False

Target table does not exist.
The approved database design must be used before creating it.

## 6.2.1 Create Sales Order Item Table

The `commerce.sales_order_item` table does not currently exist.

This section creates the Sales Order Item PostgreSQL target table based

on the approved LJ Dev Commerce Sales Order Item Data Dictionary.

Key design decisions:

- `sales_order_item_id` is the Primary Key.

- All required Data Dictionary fields use `NOT NULL`.

- `sales_order_id` and `product_id` are Foreign Keys based on the

  approved Sales Order Item database relationships.

- `created_date` and `updated_date` use the PostgreSQL

  `TIMESTAMP` datatype.

- `unit_price`, `discount_amount`, and `line_total` use the PostgreSQL

  `DECIMAL` datatype.

In [25]:
# =========================================================
# 6.2.1 Create Sales Order Item Table
# =========================================================

create_sales_order_item_table_query = """
CREATE TABLE commerce.sales_order_item (

    sales_order_item_id TEXT PRIMARY KEY,

    sales_order_id TEXT NOT NULL,
    product_id TEXT NOT NULL,

    quantity INTEGER NOT NULL,

    unit_price DECIMAL NOT NULL,
    discount_amount DECIMAL NOT NULL,
    line_total DECIMAL NOT NULL,

    created_date TIMESTAMP NOT NULL,
    created_by TEXT NOT NULL,

    updated_date TIMESTAMP NOT NULL,
    updated_by TEXT NOT NULL,

    FOREIGN KEY (sales_order_id)
        REFERENCES commerce.sales_order(sales_order_id),

    FOREIGN KEY (product_id)
        REFERENCES commerce.product(product_id)

);
"""

try:
    cursor.execute(create_sales_order_item_table_query)
    conn.commit()

    print("Sales Order Item table created successfully.")
    print("Table: commerce.sales_order_item")

except Exception as e:
    conn.rollback()

    print("Sales Order Item table creation failed.")
    print("Error:", e)

Sales Order Item table created successfully.
Table: commerce.sales_order_item

## 6.3 Verify Sales Order Item Table Structure

Verify the actual PostgreSQL structure of the

`commerce.sales_order_item` table after creation.

Confirm:

- Column names

- Column order

- PostgreSQL data types

- NULL / NOT NULL rules

- Default values

The actual PostgreSQL table structure will be reviewed against the

approved Sales Order Item Data Dictionary before records are loaded.

In [26]:
# =========================================================
# 6.3 Verify Sales Order Item Table Structure
# =========================================================

verify_sales_order_item_table_query = """
SELECT
    ordinal_position,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'commerce'
  AND table_name = 'sales_order_item'
ORDER BY ordinal_position;
"""

try:
    cursor.execute(verify_sales_order_item_table_query)

    table_structure = cursor.fetchall()

    print("Sales Order Item Table Structure")
    print("=" * 80)

    print(
        f"{'Position':<10}"
        f"{'Column Name':<25}"
        f"{'Data Type':<25}"
        f"{'Nullable':<12}"
        f"{'Default'}"
    )

    print("-" * 100)

    for row in table_structure:
        print(
            f"{row[0]:<10}"
            f"{row[1]:<25}"
            f"{row[2]:<25}"
            f"{row[3]:<12}"
            f"{row[4]}"
        )

except Exception as e:
    print("Sales Order Item table structure verification failed.")
    print("Error:", e)

Sales Order Item Table Structure
================================================================================
Position  Column Name              Data Type                Nullable    Default
----------------------------------------------------------------------------------------------------
1         sales_order_item_id      text                     NO          None
2         sales_order_id           text                     NO          None
3         product_id               text                     NO          None
4         quantity                 integer                  NO          None
5         unit_price               numeric                  NO          None
6         discount_amount          numeric                  NO          None
7         line_total               numeric                  NO          None
8         created_date             timestamp without time zoneNO          None
9         created_by               text                     NO          None
10        updated_date             timestamp without time zoneNO          None
11        updated_by               text                     NO          None

## 6.4 Verify Keys, Relationships & Load Dependencies

Verify the applicable keys, relationships, and load dependencies before

loading Sales Order Item records into PostgreSQL.

Confirm:

- `sales_order_item_id` is the Primary Key.

- `sales_order_id` references the approved Sales Order parent table.

- `product_id` references the approved Product parent table.

- Required parent/master records are available before loading Sales Order Item

  records.

- The dataset follows the approved project ETL load order.

Only applicable checks are performed for this dataset.

In [27]:
# =========================================================
# 6.4 Verify Keys, Relationships & Load Dependencies
# =========================================================

print("Sales Order Item Keys, Relationships & Load Dependency Review")
print("=" * 80)

# ---------------------------------------------------------
# 1. Primary Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'sales_order_item'
      AND tc.constraint_type = 'PRIMARY KEY';
""")

primary_keys = cursor.fetchall()

print("\n1. Primary Key")
print(primary_keys)

primary_key_valid = (
    len(primary_keys) == 1
    and primary_keys[0][1] == "sales_order_item_id"
)

print("Primary Key validation passed:", primary_key_valid)


# ---------------------------------------------------------
# 2. Foreign Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name,
        ccu.table_schema AS referenced_schema,
        ccu.table_name AS referenced_table,
        ccu.column_name AS referenced_column
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
        ON ccu.constraint_name = tc.constraint_name
        AND ccu.table_schema = tc.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'sales_order_item'
      AND tc.constraint_type = 'FOREIGN KEY'
    ORDER BY kcu.column_name;
""")

foreign_keys = cursor.fetchall()

print("\n2. Foreign Keys")
print(foreign_keys)

expected_foreign_key_columns = {
    "sales_order_id",
    "product_id"
}

actual_foreign_key_columns = {
    row[1] for row in foreign_keys
}

foreign_keys_valid = (
    actual_foreign_key_columns
    == expected_foreign_key_columns
)

print(
    "Expected Foreign Key columns:",
    expected_foreign_key_columns
)

print(
    "Actual Foreign Key columns:",
    actual_foreign_key_columns
)

print(
    "Foreign Key validation passed:",
    foreign_keys_valid
)


# ---------------------------------------------------------
# 3. Load Dependency Review
# ---------------------------------------------------------

print("\n3. Load Dependency Review")

load_dependency_ready = (
    primary_key_valid
    and foreign_keys_valid
)

print(
    "Primary Key ready:",
    primary_key_valid
)

print(
    "Foreign Key dependencies ready:",
    foreign_keys_valid
)


# ---------------------------------------------------------
# 4. Overall Load Dependency Status
# ---------------------------------------------------------

print("\n4. Overall Load Dependency Status")
print("=" * 80)

print(
    "Sales Order Item is ready for data loading:",
    load_dependency_ready
)

Sales Order Item Keys, Relationships & Load Dependency Review
================================================================================

1. Primary Key
[('sales_order_item_pkey', 'sales_order_item_id')]
Primary Key validation passed: True

2. Foreign Keys
[('sales_order_item_product_id_fkey', 'product_id', 'commerce', 'product', 'product_id'), ('sales_order_item_sales_order_id_fkey', 'sales_order_id', 'commerce', 'sales_order', 'sales_order_id')]
Expected Foreign Key columns: {'product_id', 'sales_order_id'}
Actual Foreign Key columns: {'product_id', 'sales_order_id'}
Foreign Key validation passed: True

3. Load Dependency Review
Primary Key ready: True
Foreign Key dependencies ready: True

4. Overall Load Dependency Status
================================================================================
Sales Order Item is ready for data loading: True

## 6.5 Insert Sales Order Item Records

Load the validated Sales Order Item database-ready dataset into the

verified `commerce.sales_order_item` PostgreSQL table.

Before inserting records:

- Confirm the target table is currently empty.

- Confirm the database-ready row count.

- Insert only the validated database-ready records.

- Use an explicit column list matching the approved target structure.

- Commit the transaction only after successful insertion.

No transformations are performed during the database loading step.

In [28]:
# =========================================================
# 6.5 Insert Sales Order Item Records
# =========================================================

print("Sales Order Item Record Loading")
print("=" * 80)


# ---------------------------------------------------------
# 1. Confirm Target Table Is Empty
# ---------------------------------------------------------

cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.sales_order_item;
""")

existing_record_count = cursor.fetchone()[0]

print("\n1. Target Table Record Count")
print("Existing records:", existing_record_count)

target_table_empty = (
    existing_record_count == 0
)

print("Target table is empty:", target_table_empty)


# ---------------------------------------------------------
# 2. Confirm Database-Ready Row Count
# ---------------------------------------------------------

db_ready_row_count = len(
    sales_order_item_db_ready
)

print("\n2. Database-Ready Row Count")
print("Database-ready records:", db_ready_row_count)


# ---------------------------------------------------------
# 3. Insert Validated Database-Ready Records
# ---------------------------------------------------------

insert_sales_order_item_query = """
INSERT INTO commerce.sales_order_item (
    sales_order_id,
    sales_order_item_id,
    product_id,
    quantity,
    unit_price,
    discount_amount,
    line_total,
    created_date,
    created_by,
    updated_date,
    updated_by
)
VALUES (
    %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s
);
"""

try:

    if not target_table_empty:
        raise ValueError(
            "Target table is not empty. "
            "Insertion stopped to prevent accidental duplicate loading."
        )

    records_to_insert = [
        tuple(row)
        for row in sales_order_item_db_ready.itertuples(
            index=False,
            name=None
        )
    ]

    if len(records_to_insert) != db_ready_row_count:
        raise ValueError(
            "Database-ready record count changed before insertion."
        )

    cursor.executemany(
        insert_sales_order_item_query,
        records_to_insert
    )

    conn.commit()

    print("\n3. Insert Result")
    print(
        "Sales Order Item records inserted:",
        len(records_to_insert)
    )
    print("Transaction committed successfully.")

except Exception as e:

    conn.rollback()

    print("\nSales Order Item record insertion failed.")
    print("Transaction rolled back.")
    print("Error:", e)

Sales Order Item Record Loading
================================================================================

1. Target Table Record Count
Existing records: 0
Target table is empty: True

2. Database-Ready Row Count
Database-ready records: 26

3. Insert Result
Sales Order Item records inserted: 26
Transaction committed successfully.

## 6.6 Validate Sales Order Item Row Count

Compare the number of records in the Database-Ready dataset with the

number of records currently stored in the PostgreSQL

`commerce.sales_order_item` table.

This confirms that the intended load scope was completed successfully.

No additional integrity checks are performed in this section.

In [29]:
# =========================================================
# 6.6 Validate Sales Order Item Row Count
# =========================================================

# Expected row count from the Database-Ready dataset
db_ready_row_count = len(sales_order_item_db_ready)


# Actual row count from PostgreSQL
cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.sales_order_item;
""")

postgresql_row_count = cursor.fetchone()[0]


# Validation result
row_count_match = (
    db_ready_row_count == postgresql_row_count
)


print("Sales Order Item Row Count Validation")
print("=" * 80)

print("\n1. Database-Ready Dataset Row Count")
print("Rows:", db_ready_row_count)

print("\n2. PostgreSQL Table Row Count")
print("Rows:", postgresql_row_count)

print("\n3. Row Count Validation")
print("Row counts match:", row_count_match)

print("\n4. Validation Summary")
print("=" * 80)

if row_count_match:
    print("Sales Order Item row count validation passed.")
else:
    print("Sales Order Item row count validation failed.")

Sales Order Item Row Count Validation
================================================================================

1. Database-Ready Dataset Row Count
Rows: 26

2. PostgreSQL Table Row Count
Rows: 26

3. Row Count Validation
Row counts match: True

4. Validation Summary
================================================================================
Sales Order Item row count validation passed.

## 6.7 Retrieve Sales Order Item Records

Retrieve the Sales Order Item records directly from PostgreSQL to confirm

that the loaded data is stored correctly.

Review:

- Loaded records

- Column values

- Quantity values

- Unit price, discount amount, and line total values

- Sales Order and Product reference values

- Date and timestamp values

- Overall record formatting

This step confirms that records can be successfully retrieved from the

PostgreSQL target table.

In [30]:
# =========================================================
# 6.7 Retrieve Sales Order Item Records
# =========================================================

retrieve_sales_order_item_query = """
SELECT
    sales_order_id,
    sales_order_item_id,
    product_id,
    quantity,
    unit_price,
    discount_amount,
    line_total,
    created_date,
    created_by,
    updated_date,
    updated_by
FROM commerce.sales_order_item
ORDER BY sales_order_item_id;
"""

try:
    cursor.execute(retrieve_sales_order_item_query)

    sales_order_item_records = cursor.fetchall()

    print("Sales Order Item Records Retrieved from PostgreSQL")
    print("=" * 80)

    print("Records retrieved:", len(sales_order_item_records))

    # Retrieve column names from the query result
    column_names = [
        description[0]
        for description in cursor.description
    ]

    # Create a DataFrame for readable review
    sales_order_item_postgresql = pd.DataFrame(
        sales_order_item_records,
        columns=column_names
    )

    print("\nRetrieved Sales Order Item Records:")
    display(sales_order_item_postgresql)

except Exception as e:
    print("Sales Order Item record retrieval failed.")
    print("Error:", e)

Sales Order Item Records Retrieved from PostgreSQL
================================================================================
Records retrieved: 26

Retrieved Sales Order Item Records:

   sales_order_id sales_order_item_id product_id  quantity unit_price discount_amount line_total created_date created_by updated_date updated_by
0           SO001              SOI001      P0001         1       2499               0       2499   2026-07-01      admin   2026-07-24      admin
1           SO002              SOI002      P0002         1       2199               0       2199   2026-07-01      admin   2026-07-24      admin
2           SO003              SOI003      P0004         1       1399               0       1399   2026-07-01      admin   2026-07-24      admin
3           SO004              SOI004      P0003         1       3899               0       3899   2026-07-01      admin   2026-07-24      admin
4           SO005              SOI005      P0005         1       2999               0       2999   2026-07-01      admin   2026-07-24      admin
5           SO006              SOI006      P0009         1        699               0        699   2026-07-01      admin   2026-07-24      admin
6           SO007              SOI007      P0008         1       2899               0       2899   2026-07-01      admin   2026-07-24      admin
7           SO008              SOI008      P0010         1       1599               0       1599   2026-07-01      admin   2026-07-24      admin
8           SO009              SOI009      P0011         1        399               0        399   2026-07-01      admin   2026-07-24      admin
9           SO010              SOI010      P0012         1        449               0        449   2026-07-01      admin   2026-07-24      admin
10          SO011              SOI011      P0014         1        499               0        499   2026-07-01      admin   2026-07-24      admin
11          SO012              SOI012      P0015         1        699               0        699   2026-07-01      admin   2026-07-24      admin
12          SO013              SOI013      P0007         1       2599               0       2599   2026-07-01      admin   2026-07-24      admin
13          SO014              SOI014      P0013         1        179               0        179   2026-07-01      admin   2026-07-24      admin
14          SO015              SOI015      P0008         1       2899               0       2899   2026-07-01      admin   2026-07-24      admin
15          SO016              SOI016      P0009         1        699               0        699   2026-07-01      admin   2026-07-24      admin
16          SO017              SOI017      P0014         1        499               0        499   2026-07-01      admin   2026-07-24      admin
17          SO018              SOI018      P0003         1       3899               0       3899   2026-07-01      admin   2026-07-24      admin
18          SO019              SOI019      P0002         1       2199               0       2199   2026-07-01      admin   2026-07-24      admin
19          SO020              SOI020      P0010         1       1599               0       1599   2026-07-01      admin   2026-07-24      admin
20          SO001              SOI021      P0011         2        399              99        699   2026-07-01      admin   2026-07-24      admin
21          SO004              SOI022      P0011         1        399               0        399   2026-07-01      admin   2026-07-24      admin
22          SO005              SOI023      P0012         1        449               0        449   2026-07-01      admin   2026-07-24      admin
23          SO007              SOI024      P0013         2        179               0        358   2026-07-01      admin   2026-07-24      admin
24          SO013              SOI025      P0009         1        699               0        699   2026-07-01      admin   2026-07-24      admin
25          SO015              SOI026      P0015         1        699               0        699   2026-07-01      admin   2026-07-24      admin

## 6.8 Source → Database Reconciliation

Compare the validated Sales Order Item Database-Ready dataset with the

records retrieved directly from PostgreSQL.

Validate:

- Row counts

- Column names

- Column order

- Sales Order Item IDs

- Record-level values

This confirms that the Database-Ready dataset was loaded into PostgreSQL

without unintended changes.

In [31]:
# =========================================================
# 6.8 Source → Database Reconciliation
# =========================================================

# ---------------------------------------------------------
# 1. Prepare Source Dataset
# ---------------------------------------------------------

sales_order_item_source_reconciliation = (
    sales_order_item_db_ready.copy()
    .sort_values("sales_order_item_id")
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 2. Prepare PostgreSQL Dataset
# ---------------------------------------------------------

sales_order_item_postgresql_reconciliation = (
    sales_order_item_postgresql.copy()
    .sort_values("sales_order_item_id")
    .reset_index(drop=True)
)


print("Sales Order Item Source → Database Reconciliation")
print("=" * 80)


# ---------------------------------------------------------
# 3. Row Count Validation
# ---------------------------------------------------------

source_row_count = len(
    sales_order_item_source_reconciliation
)

database_row_count = len(
    sales_order_item_postgresql_reconciliation
)

row_count_match = (
    source_row_count == database_row_count
)

print("\n1. Row Count Validation")
print("Database-Ready rows:", source_row_count)
print("PostgreSQL rows:", database_row_count)
print("Row counts match:", row_count_match)


# ---------------------------------------------------------
# 4. Column Validation
# ---------------------------------------------------------

source_columns = (
    sales_order_item_source_reconciliation.columns.tolist()
)

database_columns = (
    sales_order_item_postgresql_reconciliation.columns.tolist()
)

column_match = (
    source_columns == database_columns
)

print("\n2. Column Validation")
print("Columns and order match:", column_match)

if not column_match:
    print("\nDatabase-Ready columns:")
    print(source_columns)

    print("\nPostgreSQL columns:")
    print(database_columns)


# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

source_sales_order_item_ids = set(
    sales_order_item_source_reconciliation[
        "sales_order_item_id"
    ]
)

database_sales_order_item_ids = set(
    sales_order_item_postgresql_reconciliation[
        "sales_order_item_id"
    ]
)

primary_key_match = (
    source_sales_order_item_ids
    == database_sales_order_item_ids
)

print("\n3. Sales Order Item ID Validation")
print(
    "Sales Order Item IDs match:",
    primary_key_match
)


# ---------------------------------------------------------
# 6. Record-Level Value Validation
# ---------------------------------------------------------

value_match = (
    sales_order_item_source_reconciliation.equals(
        sales_order_item_postgresql_reconciliation
    )
)

print("\n4. Record-Level Value Validation")
print("All record values match:", value_match)


# ---------------------------------------------------------
# 7. Reconciliation Summary
# ---------------------------------------------------------

reconciliation_passed = (
    row_count_match
    and column_match
    and primary_key_match
    and value_match
)

print("\n5. Source → Database Reconciliation Summary")
print("=" * 80)

print(
    "Source → Database reconciliation passed:",
    reconciliation_passed
)

Sales Order Item Source → Database Reconciliation
================================================================================

1. Row Count Validation
Database-Ready rows: 26
PostgreSQL rows: 26
Row counts match: True

2. Column Validation
Columns and order match: True

3. Sales Order Item ID Validation
Sales Order Item IDs match: True

4. Record-Level Value Validation
All record values match: True

5. Source → Database Reconciliation Summary
================================================================================
Source → Database reconciliation passed: True

## 6.9 Sales Order Item Database Integrity Validation

Perform final integrity checks on the loaded

`commerce.sales_order_item` table.

The checks confirm:

- Primary-key uniqueness

- Required-field integrity

- Duplicate record checks

- Quantity validity

- Line amount integrity

- Audit date consistency

These checks provide the final confirmation that the Sales Order Item

table is structurally and business-rule compliant after loading.

In [32]:
# =========================================================
# 6.9 Sales Order Item Database Integrity Validation
# =========================================================

integrity_query = """
SELECT
    COUNT(*) AS total_rows,

    COUNT(DISTINCT sales_order_item_id) AS distinct_sales_order_item_ids,

    COUNT(*) FILTER (
        WHERE sales_order_item_id IS NULL
    ) AS null_sales_order_item_ids,

    COUNT(*) FILTER (
        WHERE sales_order_id IS NULL
    ) AS null_sales_order_ids,

    COUNT(*) FILTER (
        WHERE product_id IS NULL
    ) AS null_product_ids,

    COUNT(*) FILTER (
        WHERE quantity IS NULL
    ) AS null_quantities,

    COUNT(*) FILTER (
        WHERE unit_price IS NULL
    ) AS null_unit_prices,

    COUNT(*) FILTER (
        WHERE discount_amount IS NULL
    ) AS null_discount_amounts,

    COUNT(*) FILTER (
        WHERE line_total IS NULL
    ) AS null_line_totals,

    COUNT(*) FILTER (
        WHERE created_date IS NULL
    ) AS null_created_dates,

    COUNT(*) FILTER (
        WHERE created_by IS NULL
    ) AS null_created_by,

    COUNT(*) FILTER (
        WHERE updated_date IS NULL
    ) AS null_updated_dates,

    COUNT(*) FILTER (
        WHERE updated_by IS NULL
    ) AS null_updated_by,

    COUNT(*) FILTER (
        WHERE quantity <= 0
    ) AS invalid_quantities,

    COUNT(*) FILTER (
        WHERE unit_price < 0
    ) AS invalid_unit_prices,

    COUNT(*) FILTER (
        WHERE discount_amount < 0
        OR discount_amount > (quantity * unit_price)
    ) AS invalid_discount_amounts,

    COUNT(*) FILTER (
        WHERE line_total != (
            quantity * unit_price
            - discount_amount
        )
    ) AS invalid_line_totals,

    COUNT(*) FILTER (
        WHERE updated_date < created_date
    ) AS invalid_audit_date_order

FROM commerce.sales_order_item;
"""

try:
    cursor.execute(integrity_query)

    integrity_result = cursor.fetchone()

    print("Sales Order Item Database Integrity Validation")
    print("=" * 80)

    print("\n1. Primary Key Integrity")
    print("Total rows:", integrity_result[0])
    print(
        "Distinct sales order item IDs:",
        integrity_result[1]
    )
    print(
        "NULL sales order item IDs:",
        integrity_result[2]
    )

    print("\n2. Required Field Integrity")
    print("NULL sales order IDs:", integrity_result[3])
    print("NULL product IDs:", integrity_result[4])
    print("NULL quantities:", integrity_result[5])
    print("NULL unit prices:", integrity_result[6])
    print("NULL discount amounts:", integrity_result[7])
    print("NULL line totals:", integrity_result[8])
    print("NULL created dates:", integrity_result[9])
    print("NULL created by:", integrity_result[10])
    print("NULL updated dates:", integrity_result[11])
    print("NULL updated by:", integrity_result[12])

    print("\n3. Sales Order Item Value Integrity")
    print("Invalid quantities:", integrity_result[13])
    print("Invalid unit prices:", integrity_result[14])
    print(
        "Invalid discount amounts:",
        integrity_result[15]
    )
    print("Invalid line totals:", integrity_result[16])

    print("\n4. Audit Date Integrity")
    print(
        "Updated date earlier than created date:",
        integrity_result[17]
    )

    # -----------------------------------------------------
    # Final Validation Result
    # -----------------------------------------------------

    integrity_passed = (
        integrity_result[0] == integrity_result[1]
        and integrity_result[2] == 0
        and integrity_result[3] == 0
        and integrity_result[4] == 0
        and integrity_result[5] == 0
        and integrity_result[6] == 0
        and integrity_result[7] == 0
        and integrity_result[8] == 0
        and integrity_result[9] == 0
        and integrity_result[10] == 0
        and integrity_result[11] == 0
        and integrity_result[12] == 0
        and integrity_result[13] == 0
        and integrity_result[14] == 0
        and integrity_result[15] == 0
        and integrity_result[16] == 0
        and integrity_result[17] == 0
    )

    print("\n5. Database Integrity Validation Summary")
    print("=" * 80)

    print(
        "Sales Order Item database integrity passed:",
        integrity_passed
    )

except Exception as e:
    print(
        "Sales Order Item database integrity validation failed."
    )
    print("Error:", e)

Sales Order Item Database Integrity Validation
================================================================================

1. Primary Key Integrity
Total rows: 26
Distinct sales order item IDs: 26
NULL sales order item IDs: 0

2. Required Field Integrity
NULL sales order IDs: 0
NULL product IDs: 0
NULL quantities: 0
NULL unit prices: 0
NULL discount amounts: 0
NULL line totals: 0
NULL created dates: 0
NULL created by: 0
NULL updated dates: 0
NULL updated by: 0

3. Sales Order Item Value Integrity
Invalid quantities: 0
Invalid unit prices: 0
Invalid discount amounts: 0
Invalid line totals: 0

4. Audit Date Integrity
Updated date earlier than created date: 0

5. Database Integrity Validation Summary
================================================================================
Sales Order Item database integrity passed: True

## 6.10 Close PostgreSQL Connection

Close the PostgreSQL cursor and database connection after all

Sales Order Item loading and validation steps are complete.

Confirm that PostgreSQL resources are closed cleanly.

In [33]:
# =========================================================
# 6.10 Close PostgreSQL Connection
# =========================================================

try:
    if cursor is not None and not cursor.closed:
        cursor.close()

    if conn is not None and conn.closed == 0:
        conn.close()

    print("PostgreSQL resources closed successfully.")
    print("Cursor closed:", cursor.closed)
    print("Connection closed:", conn.closed != 0)

except Exception as e:
    print("PostgreSQL resource closure failed.")
    print("Error:", e)

PostgreSQL resources closed successfully.
Cursor closed: True
Connection closed: True