# LJ Dev Commerce - Phase 4

# IX. Payment ETL

# =========================================================
# SECTION 1 — EXTRACT, SET UP, PROFILE, FINDINGS & DECISIONS
# =========================================================

# 1.1 Setup

This section prepares the notebook environment for the Payment ETL process.

The setup includes:

* Importing the required Python libraries.

* Configuring Pandas display options.

* Preparing the notebook environment for the Payment ETL workflow.

No dataset is loaded, modified, cleaned, or transformed in this section.

In [1]:
# =========================================================
# 1.1 Setup
# =========================================================

import pandas as pd
import numpy as np

# =========================================================
# Display Configuration
# =========================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)

In [2]:

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

## 1.2 Load and Preserve Payment Raw Dataset

Load the raw Payment source file from Zoho Books and preserve it as the original source dataset.

The raw dataset must not be modified during the ETL process. Any profiling, cleaning, transformation, or validation work will use separate DataFrame copies where appropriate.

For this section, the Payment source dataset will remain as a single raw dataset. It will not be transformed or modified during the loading process.

In [3]:
# =========================================================
# 1.2 Load and Preserve Payment Raw Dataset
# =========================================================

# Define the raw Payment dataset path
zoho_books_customer_payments_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\09_Zoho_Books\zoho_books_customer_payments.csv"
)


# Load the raw source dataset
zoho_books_customer_payments_raw = pd.read_csv(
    zoho_books_customer_payments_raw_path
)


# Preserve an untouched copy of the original raw dataset
zoho_books_customer_payments_raw_original = (
    zoho_books_customer_payments_raw.copy(deep=True)
)


print("Payment raw dataset loaded successfully.")
print(
    "Rows:",
    len(zoho_books_customer_payments_raw)
)
print(
    "Columns:",
    len(zoho_books_customer_payments_raw.columns)
)
print(
    "Path:",
    zoho_books_customer_payments_raw_path
)

Payment raw dataset loaded successfully.
Rows: 20
Columns: 12
Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\09_Zoho_Books\zoho_books_customer_payments.csv

## 1.3 Initial Raw Data Inspection

Perform an initial inspection of the untouched Payment raw dataset before profiling.

This step establishes the structure, current pandas data types, missing-value counts, and sample records for the Payment raw dataset.

No transformations are performed at this stage.

In [4]:
# =========================================================
# 1.3 Initial Raw Data Inspection
# =========================================================

print("Payment Dataset shape:")
print(zoho_books_customer_payments_raw.shape)


print("\nPayment Column names:")
print(zoho_books_customer_payments_raw.columns.tolist())


print("\nPayment Current pandas data types:")
print(zoho_books_customer_payments_raw.dtypes)


print("\nPayment Missing values:")
print(zoho_books_customer_payments_raw.isnull().sum())


print("\nPayment Sample raw records:")
display(zoho_books_customer_payments_raw.head())

Payment Dataset shape:
(20, 12)

Payment Column names:
['PaymentReference', 'SourceOrderReference', 'PaymentDate', 'PaymentMethod', 'PaymentStatus', 'Amount', 'GatewayTransactionID', 'PaymentNotes', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Payment Current pandas data types:
PaymentReference        object
SourceOrderReference    object
PaymentDate             object
PaymentMethod           object
PaymentStatus           object
Amount                   int64
GatewayTransactionID    object
PaymentNotes            object
CreatedOn               object
CreatedByUser           object
ModifiedOn              object
ModifiedByUser          object
dtype: object

Payment Missing values:
PaymentReference        0
SourceOrderReference    0
PaymentDate             0
PaymentMethod           0
PaymentStatus           0
Amount                  0
GatewayTransactionID    0
PaymentNotes            0
CreatedOn               0
CreatedByUser           0
ModifiedOn              0
ModifiedByUser          0
dtype: int64

Payment Sample raw records:

  PaymentReference SourceOrderReference PaymentDate     PaymentMethod PaymentStatus  Amount GatewayTransactionID PaymentNotes   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0           PAY001                SO001  2026-07-05              Visa    Successful    2000               TXN001      Partial  2026-07-05         admin  2026-07-05          admin
1           PAY002                SO001  2026-07-05              Visa    Successful    1198               TXN002    Completed  2026-07-05         admin  2026-07-05          admin
2           PAY003                SO002  2026-07-06       Credit Card    Successful    2199               TXN003         Paid  2026-07-06         admin  2026-07-06          admin
3           PAY004                SO003  2026-07-07  Cash on Delivery    Successful    1399               TXN004         Paid  2026-07-07         admin  2026-07-07          admin
4           PAY005                SO004  2026-07-08              Visa    Successful    4298               TXN005         Paid  2026-07-08         admin  2026-07-08          admin

## 1.4 Data Profiling

Profile the untouched raw Payment dataset using the reusable `data_profiler_v1` tool.

The profiler is used to identify potential data-quality issues, semantic field types, missing values, duplicates, formatting inconsistencies, and other detectable anomalies before any cleaning or transformation is performed.

The Payment dataset will be profiled as a single source dataset before any transformation takes place.

Profiling results are treated as findings for investigation. The profiler does not make business decisions or automatically determine the correct transformation.

In [5]:
# =========================================================
# 1.4 Data Profiling
# =========================================================

import sys
import importlib


# Identify the project root
project_root = Path.cwd().parent


# Add the project root to the Python path if needed
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))


# Import and reload the reusable data profiler
from profiler import data_profiler_v1 as profiler

importlib.reload(profiler)


print("Profiler loaded successfully:")
print(profiler.__file__)


print("\nProfiler configuration:")
print(profiler.DEFAULT_CONFIG)

Profiler loaded successfully:
c:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\profiler\data_profiler_v1.py

Profiler configuration:
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

In [6]:
# Run the complete profiler against the untouched raw Payment dataset

payment_profile_results = profiler.profile_dataset(
    zoho_books_customer_payments_raw
)


print("\nPayment profiling completed successfully.")

print("\nPayment profiler sections:")
print(list(payment_profile_results.keys()))

Payment profiling completed successfully.

Payment profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

## 1.5 Review Profiling Results

Review the complete Payment profiling results before making any transformation decisions.

The automated profiler identifies potential data-quality issues, but the results must be independently reviewed in the context of the Payment dataset and LJ Dev Commerce business requirements.

This review examines:

- Automated profiling findings

- Issues requiring independent analyst review

- Potential business-rule decisions

- Issues that may require transformation

The Payment dataset will be reviewed as a single source dataset before any transformation takes place.

No data is modified during this stage.

In [7]:
# =========================================================
# 1.5 Review Profiling Results
# =========================================================

print("\n" + "=" * 70)
print("PAYMENT PROFILING RESULTS")
print("=" * 70)

for section_name, section_result in payment_profile_results.items():

    print("\n" + "-" * 70)
    print(section_name.upper())
    print("-" * 70)

    print(section_result)

======================================================================
PAYMENT PROFILING RESULTS
======================================================================

----------------------------------------------------------------------
FIELD_TYPES
----------------------------------------------------------------------
PaymentReference         identifier
SourceOrderReference     identifier
PaymentDate                    date
PaymentMethod           categorical
PaymentStatus           categorical
Amount                      numeric
GatewayTransactionID     identifier
PaymentNotes                   text
CreatedOn                      date
CreatedByUser           categorical
ModifiedOn                     date
ModifiedByUser          categorical
Name: DetectedFieldType, dtype: object

----------------------------------------------------------------------
DETECTION_DETAILS
----------------------------------------------------------------------
{'PaymentReference': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SourceOrderReference': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'PaymentDate': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'PaymentMethod': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'PaymentStatus': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'Amount': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'GatewayTransactionID': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'PaymentNotes': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'CreatedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'CreatedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'ModifiedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'ModifiedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}}

----------------------------------------------------------------------
GENERAL
----------------------------------------------------------------------
{'rows': 20, 'columns': 12, 'exact_duplicate_rows': 0, 'column_profile':                      DataType DetectedFieldType  MissingCount  MissingPercent  UniqueCount  DuplicateValueCount
PaymentReference       object        identifier             0             0.0           20                    0
SourceOrderReference   object        identifier             0             0.0           19                    1
PaymentDate            object              date             0             0.0           19                    1
PaymentMethod          object       categorical             0             0.0            4                   16
PaymentStatus          object       categorical             0             0.0            3                   17
Amount                  int64           numeric             0             0.0           16                    4
GatewayTransactionID   object        identifier             0             0.0           20                    0
PaymentNotes           object              text             0             0.0            5                   15
CreatedOn              object              date             0             0.0           19                    1
CreatedByUser          object       categorical             0             0.0            1                   19
ModifiedOn             object              date             0             0.0           19                    1
ModifiedByUser         object       categorical             0             0.0            1                   19}

----------------------------------------------------------------------
TEXT
----------------------------------------------------------------------
{'PaymentNotes': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 4, 'MaximumLength': 16, 'AverageLength': np.float64(6.1)}}

----------------------------------------------------------------------
CATEGORICAL
----------------------------------------------------------------------
{'PaymentMethod': {'UniqueCount': 4, 'MostCommonValue': 'Visa', 'MostCommonCount': 8, 'CategoryDistribution': {'Visa': 8, 'Cash on Delivery': 5, 'Credit Card': 4, 'Mastercard': 3}}, 'PaymentStatus': {'UniqueCount': 3, 'MostCommonValue': 'Successful', 'MostCommonCount': 17, 'CategoryDistribution': {'Successful': 17, 'Pending': 2, 'Failed': 1}}, 'CreatedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 20, 'CategoryDistribution': {'admin': 20}}, 'ModifiedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 20, 'CategoryDistribution': {'admin': 20}}}

----------------------------------------------------------------------
NUMERIC
----------------------------------------------------------------------
{'Amount': {'ValidNumericCount': 20, 'InvalidNumericCount': 0, 'Minimum': np.float64(0.0), 'Maximum': np.float64(4298.0), 'Mean': np.float64(1649.4), 'Median': np.float64(1298.5), 'ZeroCount': 3, 'NegativeCount': 0, 'PositiveCount': 17, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(-3514.5), 'UpperOutlierBoundary': np.float64(7121.5)}}

----------------------------------------------------------------------
DATE
----------------------------------------------------------------------
{'PaymentDate': {'ValidDateCount': 20, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-05 00:00:00'), 'MaximumDate': Timestamp('2026-07-23 00:00:00'), 'FutureDateCount': 0}, 'CreatedOn': {'ValidDateCount': 20, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-05 00:00:00'), 'MaximumDate': Timestamp('2026-07-23 00:00:00'), 'FutureDateCount': 0}, 'ModifiedOn': {'ValidDateCount': 20, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-05 00:00:00'), 'MaximumDate': Timestamp('2026-07-23 00:00:00'), 'FutureDateCount': 0}}

----------------------------------------------------------------------
PATTERNS
----------------------------------------------------------------------
{'email': {}, 'phone': {}, 'identifier': {'PaymentReference': {'UniqueCount': 20, 'DuplicateCount': 0, 'MissingCount': 0}, 'SourceOrderReference': {'UniqueCount': 19, 'DuplicateCount': 1, 'MissingCount': 0}, 'GatewayTransactionID': {'UniqueCount': 20, 'DuplicateCount': 0, 'MissingCount': 0}}}

----------------------------------------------------------------------
ISSUES
----------------------------------------------------------------------
                 Column            IssueType Severity  Count                           Description
0  SourceOrderReference  DuplicateIdentifier     High      1  Repeated identifier values detected.

----------------------------------------------------------------------
CONFIGURATION
----------------------------------------------------------------------
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

## 1.6 Review Profiler Issues

Review the issues identified by the automated profiler for the Payment dataset.

The full profiling output provides a broad assessment of the untouched raw Payment dataset. This step focuses specifically on the detected issues so they can be investigated before any transformation decisions are made.

Profiler findings are treated as indicators for review and do not automatically determine the correct transformation.

The Payment dataset will be reviewed as a single source, and identified issues will be evaluated against the Payment Data Dictionary and LJ Dev Commerce business requirements.

In [8]:
# =========================================================
# 1.6 Review Profiler Issues
# =========================================================

payment_issues = payment_profile_results["issues"]


print("\n" + "=" * 70)
print("PAYMENT PROFILER ISSUES")
print("=" * 70)

display(payment_issues)

======================================================================
PAYMENT PROFILER ISSUES
======================================================================

                 Column            IssueType Severity  Count                           Description
0  SourceOrderReference  DuplicateIdentifier     High      1  Repeated identifier values detected.

## 1.7 Independent Analyst Review

Perform a systematic independent analyst review of the untouched raw Payment dataset.

This section is the notebook-based version of the Pre-ETL Inspection.

The review goes beyond the automated profiler and checks the Payment dataset using independent analyst validation relevant to its business meaning and approved ETL design.

The review covers, where applicable:

- Dataset structure and grain

- Missing and blank values

- Exact duplicate rows

- Primary-key candidates and key uniqueness

- Parent order relationship and payment-to-order consistency

- Whitespace in text fields

- Text consistency

- Payment method and payment status consistency

- Numeric validity and statistical outlier candidates

- Payment amount and payment status business-rule consistency

- Date parsing, datatype, validity, and Created/Modified date consistency

- Source-to-target datatype compatibility considerations

- Payment relationship values

Automated profiler findings and independent analyst findings are kept conceptually separate.

The Payment dataset is reviewed independently before any transformation.

No data is modified in this section.

In [9]:
# =========================================================
# 1.7 Independent Analyst Review
# =========================================================


# =========================================================
# 1. Dataset Structure and Grain
# =========================================================

print("1. DATASET STRUCTURE AND GRAIN")
print("=" * 80)

print(f"Rows: {zoho_books_customer_payments_raw.shape[0]}")
print(f"Columns: {zoho_books_customer_payments_raw.shape[1]}")

print("\nWorking assumption:")
print("One row represents one payment transaction.")


# =========================================================
# 2. Missing Values and Blank Values
# =========================================================

print("\n\n2. MISSING VALUES AND BLANK VALUES")
print("=" * 80)

source_df = zoho_books_customer_payments_raw

missing_values = source_df.isna().sum()

blank_values = pd.Series(
    {
        column: (
            source_df[column]
            .astype("string")
            .str.strip()
            .eq("")
            .sum()
            if source_df[column].dtype == "object"
            else 0
        )
        for column in source_df.columns
    }
)

missing_blank_review = pd.DataFrame({
    "MissingValues": missing_values,
    "BlankValues": blank_values
})

display(missing_blank_review)


# =========================================================
# 3. Exact Duplicate Rows
# =========================================================

print("\n\n3. EXACT DUPLICATE ROWS")
print("=" * 80)

exact_duplicate_count = source_df.duplicated().sum()

print(
    "Payment - Exact duplicate rows:",
    exact_duplicate_count
)

if exact_duplicate_count > 0:

    display(
        source_df[
            source_df.duplicated(keep=False)
        ]
    )


# =========================================================
# 4. Primary Key Candidate and Identifier Uniqueness
# =========================================================

print("\n\n4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS")
print("=" * 80)

identifier_columns = [
    "PaymentReference",
    "SourceOrderReference",
    "GatewayTransactionID"
]

identifier_review = pd.DataFrame(
    {
        "Column": identifier_columns,

        "NullCount": [
            source_df[column].isna().sum()
            for column in identifier_columns
        ],

        "BlankCount": [
            source_df[column]
            .astype("string")
            .str.strip()
            .eq("")
            .sum()
            for column in identifier_columns
        ],

        "DuplicateCount": [
            source_df[column].duplicated().sum()
            for column in identifier_columns
        ],

        "UniqueValues": [
            source_df[column].nunique()
            for column in identifier_columns
        ]
    }
)

display(identifier_review)


# =========================================================
# 5. Payment Transaction Identifier Collision Review
# =========================================================

print("\n\n5. PAYMENT TRANSACTION IDENTIFIER COLLISION REVIEW")
print("=" * 80)

transaction_identifier_review = source_df[
    [
        "PaymentReference",
        "GatewayTransactionID"
    ]
].copy()

duplicate_payment_references = (
    transaction_identifier_review[
        transaction_identifier_review["PaymentReference"]
        .duplicated(keep=False)
    ]
)

duplicate_gateway_transactions = (
    transaction_identifier_review[
        transaction_identifier_review["GatewayTransactionID"]
        .duplicated(keep=False)
    ]
)

print(
    "Duplicate PaymentReference records:",
    len(duplicate_payment_references)
)

print(
    "Duplicate GatewayTransactionID records:",
    len(duplicate_gateway_transactions)
)

if not duplicate_payment_references.empty:

    print("\nDuplicate PaymentReference values:")
    display(duplicate_payment_references)

if not duplicate_gateway_transactions.empty:

    print("\nDuplicate GatewayTransactionID values:")
    display(duplicate_gateway_transactions)


# =========================================================
# 6. Parent Order / Payment Relationship Review
# =========================================================

print("\n\n6. PARENT ORDER / PAYMENT RELATIONSHIP REVIEW")
print("=" * 80)

payment_order_review = source_df[
    [
        "SourceOrderReference",
        "PaymentReference",
        "PaymentStatus",
        "Amount"
    ]
].copy()

print("Distinct parent orders:")
print(source_df["SourceOrderReference"].nunique())

print("Distinct payment references:")
print(source_df["PaymentReference"].nunique())

print("\nOrders containing multiple payment records:")

multiple_payment_orders = (
    source_df
    .groupby("SourceOrderReference")
    .size()
    .reset_index(name="PaymentCount")
)

multiple_payment_orders = multiple_payment_orders[
    multiple_payment_orders["PaymentCount"] > 1
]

display(multiple_payment_orders)


# =========================================================
# 7. Leading and Trailing Whitespace Review
# =========================================================

print("\n\n7. LEADING AND TRAILING WHITESPACE REVIEW")
print("=" * 80)

text_columns = source_df.select_dtypes(
    include="object"
).columns

whitespace_findings = []

for column in text_columns:

    whitespace_mask = (
        source_df[column].astype("string")
        != source_df[column].astype("string").str.strip()
    )

    count = whitespace_mask.sum()

    if count > 0:

        whitespace_records = source_df.loc[
            whitespace_mask,
            ["PaymentReference", column]
        ]

        whitespace_findings.append({
            "Column": column,
            "WhitespaceRecordCount": count
        })

        print(f"\nColumn: {column}")
        display(whitespace_records)

if whitespace_findings:

    print("\nWhitespace findings summary:")
    display(pd.DataFrame(whitespace_findings))

else:

    print("No leading or trailing whitespace found.")


# =========================================================
# 8. Text Consistency Review
# =========================================================

print("\n\n8. TEXT CONSISTENCY REVIEW")
print("=" * 80)

text_consistency_columns = [
    "PaymentMethod",
    "PaymentStatus",
    "PaymentNotes",
    "CreatedByUser",
    "ModifiedByUser"
]

for column in text_consistency_columns:

    print(f"\n{column} values:")

    display(
        source_df[column]
        .value_counts(dropna=False)
        .sort_index()
        .rename("RecordCount")
        .to_frame()
    )


# =========================================================
# 9. Numeric Validity Review
# =========================================================

print("\n\n9. NUMERIC VALIDITY REVIEW")
print("=" * 80)

numeric_columns = [
    "Amount"
]

numeric_summary = source_df[
    numeric_columns
].describe().T

numeric_summary["NegativeCount"] = [
    (source_df[column] < 0).sum()
    for column in numeric_columns
]

numeric_summary["ZeroCount"] = [
    (source_df[column] == 0).sum()
    for column in numeric_columns
]

numeric_summary["PositiveCount"] = [
    (source_df[column] > 0).sum()
    for column in numeric_columns
]

display(numeric_summary)


# =========================================================
# 10. Numeric Outlier Candidate Review
# =========================================================

print("\n\n10. NUMERIC OUTLIER CANDIDATE REVIEW")
print("=" * 80)

outlier_summary = []

for column in numeric_columns:

    q1 = source_df[column].quantile(0.25)
    q3 = source_df[column].quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)

    outlier_mask = (
        (source_df[column] < lower_bound)
        |
        (source_df[column] > upper_bound)
    )

    outlier_count = outlier_mask.sum()

    outlier_summary.append({
        "Column": column,
        "LowerBoundary": lower_bound,
        "UpperBoundary": upper_bound,
        "OutlierCandidateCount": outlier_count
    })

    if outlier_count > 0:

        print(f"\nOutlier candidate(s): {column}")

        display(
            source_df.loc[
                outlier_mask,
                [
                    "PaymentReference",
                    "SourceOrderReference",
                    column
                ]
            ]
        )

print("\nOutlier candidate summary:")
display(pd.DataFrame(outlier_summary))


# =========================================================
# 11. Payment Amount and Status Business Rule Review
# =========================================================

print("\n\n11. PAYMENT AMOUNT AND STATUS BUSINESS RULE REVIEW")
print("=" * 80)

invalid_negative_amount = source_df[
    source_df["Amount"] < 0
]

successful_non_positive = source_df[
    (source_df["PaymentStatus"] == "Successful")
    &
    (source_df["Amount"] <= 0)
]

pending_non_zero = source_df[
    (source_df["PaymentStatus"] == "Pending")
    &
    (source_df["Amount"] != 0)
]

failed_non_zero = source_df[
    (source_df["PaymentStatus"] == "Failed")
    &
    (source_df["Amount"] != 0)
]

print(
    "Records where Amount < 0:",
    len(invalid_negative_amount)
)

print(
    "Successful payments where Amount <= 0:",
    len(successful_non_positive)
)

print(
    "Pending payments where Amount != 0:",
    len(pending_non_zero)
)

print(
    "Failed payments where Amount != 0:",
    len(failed_non_zero)
)

if not invalid_negative_amount.empty:

    print("\nNegative payment amounts:")
    display(invalid_negative_amount)

if not successful_non_positive.empty:

    print("\nSuccessful payments with non-positive amounts:")
    display(successful_non_positive)

if not pending_non_zero.empty:

    print("\nPending payments with non-zero amounts:")
    display(pending_non_zero)

if not failed_non_zero.empty:

    print("\nFailed payments with non-zero amounts:")
    display(failed_non_zero)


# =========================================================
# 12. Date Parsing and Datatype Review
# =========================================================

print("\n\n12. DATE PARSING AND DATATYPE REVIEW")
print("=" * 80)

date_columns = [
    "PaymentDate",
    "CreatedOn",
    "ModifiedOn"
]

date_review = []

for column in date_columns:

    parsed_dates = pd.to_datetime(
        source_df[column],
        errors="coerce"
    )

    date_review.append({
        "Column": column,
        "CurrentSourceDtype": str(
            source_df[column].dtype
        ),
        "InvalidDateCount": parsed_dates.isna().sum(),
        "MinimumDate": parsed_dates.min(),
        "MaximumDate": parsed_dates.max()
    })

display(pd.DataFrame(date_review))


# =========================================================
# 13. PaymentDate / CreatedOn / ModifiedOn Date Logic
# =========================================================

print("\n\n13. PAYMENTDATE / CREATEDON / MODIFIEDON DATE LOGIC REVIEW")
print("=" * 80)

payment_dates = pd.to_datetime(
    source_df["PaymentDate"],
    errors="coerce"
)

created_dates = pd.to_datetime(
    source_df["CreatedOn"],
    errors="coerce"
)

modified_dates = pd.to_datetime(
    source_df["ModifiedOn"],
    errors="coerce"
)

payment_before_created = source_df[
    payment_dates < created_dates
]

modified_before_created = source_df[
    modified_dates < created_dates
]

print(
    "Records where PaymentDate is earlier than CreatedOn: "
    f"{len(payment_before_created)}"
)

print(
    "Records where ModifiedOn is earlier than CreatedOn: "
    f"{len(modified_before_created)}"
)

if not payment_before_created.empty:

    print("\nPaymentDate earlier than CreatedOn:")

    display(
        payment_before_created[
            [
                "PaymentReference",
                "PaymentDate",
                "CreatedOn"
            ]
        ]
    )

if not modified_before_created.empty:

    print("\nModifiedOn earlier than CreatedOn:")

    display(
        modified_before_created[
            [
                "PaymentReference",
                "CreatedOn",
                "ModifiedOn"
            ]
        ]
    )


# =========================================================
# 14. Payment Method / Status / Notes Relationship Review
# =========================================================

print("\n\n14. PAYMENT METHOD / STATUS / NOTES RELATIONSHIP REVIEW")
print("=" * 80)

payment_status_notes_review = source_df[
    [
        "PaymentReference",
        "PaymentMethod",
        "PaymentStatus",
        "Amount",
        "PaymentNotes"
    ]
].copy()

display(payment_status_notes_review)


# =========================================================
# 15. Source Datatype Review
# =========================================================

print("\n\n15. SOURCE DATATYPE REVIEW")
print("=" * 80)

datatype_review = pd.DataFrame({
    "Column": source_df.columns,
    "SourceDtype": [
        str(source_df[column].dtype)
        for column in source_df.columns
    ]
})

display(datatype_review)


# =========================================================
# Independent Analyst Review Complete
# =========================================================

print("\n" + "=" * 80)
print("Independent Analyst Review completed.")
print("No data was modified.")
print("=" * 80)

1. DATASET STRUCTURE AND GRAIN
================================================================================
Rows: 20
Columns: 12

Working assumption:
One row represents one payment transaction.


2. MISSING VALUES AND BLANK VALUES
================================================================================

                      MissingValues  BlankValues
PaymentReference                  0            0
SourceOrderReference              0            0
PaymentDate                       0            0
PaymentMethod                     0            0
PaymentStatus                     0            0
Amount                            0            0
GatewayTransactionID              0            0
PaymentNotes                      0            0
CreatedOn                         0            0
CreatedByUser                     0            0
ModifiedOn                        0            0
ModifiedByUser                    0            0

3. EXACT DUPLICATE ROWS
================================================================================
Payment - Exact duplicate rows: 0


4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS
================================================================================

                 Column  NullCount  BlankCount  DuplicateCount  UniqueValues
0      PaymentReference          0           0               0            20
1  SourceOrderReference          0           0               1            19
2  GatewayTransactionID          0           0               0            20

5. PAYMENT TRANSACTION IDENTIFIER COLLISION REVIEW
================================================================================
Duplicate PaymentReference records: 0
Duplicate GatewayTransactionID records: 0


6. PARENT ORDER / PAYMENT RELATIONSHIP REVIEW
================================================================================
Distinct parent orders:
19
Distinct payment references:
20

Orders containing multiple payment records:

  SourceOrderReference  PaymentCount
0                SO001             2

7. LEADING AND TRAILING WHITESPACE REVIEW
================================================================================
No leading or trailing whitespace found.


8. TEXT CONSISTENCY REVIEW
================================================================================

PaymentMethod values:

                  RecordCount
PaymentMethod
Cash on Delivery            5
Credit Card                 4
Mastercard                  3
Visa                        8

PaymentStatus values:

               RecordCount
PaymentStatus
Failed                   1
Pending                  2
Successful              17

PaymentNotes values:

                  RecordCount
PaymentNotes
Awaiting payment            2
Completed                   1
Paid                       15
Partial                     1
Payment failed              1

CreatedByUser values:

               RecordCount
CreatedByUser
admin                   20

ModifiedByUser values:

                RecordCount
ModifiedByUser
admin                    20

9. NUMERIC VALIDITY REVIEW
================================================================================

        count    mean          std  min    25%     50%     75%     max  NegativeCount  ZeroCount  PositiveCount
Amount   20.0  1649.4  1467.203692  0.0  474.0  1298.5  3133.0  4298.0              0          3             17

10. NUMERIC OUTLIER CANDIDATE REVIEW
================================================================================

Outlier candidate summary:

   Column  LowerBoundary  UpperBoundary  OutlierCandidateCount
0  Amount        -3514.5         7121.5                      0

11. PAYMENT AMOUNT AND STATUS BUSINESS RULE REVIEW
================================================================================
Records where Amount < 0: 0
Successful payments where Amount <= 0: 0
Pending payments where Amount != 0: 0
Failed payments where Amount != 0: 0


12. DATE PARSING AND DATATYPE REVIEW
================================================================================

        Column CurrentSourceDtype  InvalidDateCount MinimumDate MaximumDate
0  PaymentDate             object                 0  2026-07-05  2026-07-23
1    CreatedOn             object                 0  2026-07-05  2026-07-23
2   ModifiedOn             object                 0  2026-07-05  2026-07-23

13. PAYMENTDATE / CREATEDON / MODIFIEDON DATE LOGIC REVIEW
================================================================================
Records where PaymentDate is earlier than CreatedOn: 0
Records where ModifiedOn is earlier than CreatedOn: 0


14. PAYMENT METHOD / STATUS / NOTES RELATIONSHIP REVIEW
================================================================================

   PaymentReference     PaymentMethod PaymentStatus  Amount      PaymentNotes
0            PAY001              Visa    Successful    2000           Partial
1            PAY002              Visa    Successful    1198         Completed
2            PAY003       Credit Card    Successful    2199              Paid
3            PAY004  Cash on Delivery    Successful    1399              Paid
4            PAY005              Visa    Successful    4298              Paid
5            PAY006        Mastercard    Successful    3448              Paid
6            PAY007  Cash on Delivery       Pending       0  Awaiting payment
7            PAY008              Visa    Successful    3078              Paid
8            PAY009       Credit Card    Successful    1599              Paid
9            PAY010              Visa    Successful     399              Paid
10           PAY011       Credit Card        Failed       0    Payment failed
11           PAY012  Cash on Delivery    Successful     499              Paid
12           PAY013              Visa    Successful     699              Paid
13           PAY014        Mastercard    Successful    3298              Paid
14           PAY015  Cash on Delivery    Successful     179              Paid
15           PAY016              Visa    Successful    3598              Paid
16           PAY017              Visa    Successful     699              Paid
17           PAY018       Credit Card    Successful     499              Paid
18           PAY019        Mastercard    Successful    3899              Paid
19           PAY020  Cash on Delivery       Pending       0  Awaiting payment

15. SOURCE DATATYPE REVIEW
================================================================================

                  Column SourceDtype
0       PaymentReference      object
1   SourceOrderReference      object
2            PaymentDate      object
3          PaymentMethod      object
4          PaymentStatus      object
5                 Amount       int64
6   GatewayTransactionID      object
7           PaymentNotes      object
8              CreatedOn      object
9          CreatedByUser      object
10            ModifiedOn      object
11        ModifiedByUser      object

================================================================================
Independent Analyst Review completed.
No data was modified.
================================================================================

## 1.8 Findings and Transformation Decisions

Compare the automated profiler findings, the Independent Analyst Review findings, and the approved Payment data requirements to formally determine the required treatment for each finding.

Each finding must be classified as one of the following:

- Safe deterministic transformation

- Valid value — retain unchanged

- Expected business behavior

- Requires relationship validation later

- Requires business investigation

No transformation is performed in this section.

For Payment, the approved business rules include:

- Each row represents one payment transaction.

- One sales order may contain multiple payment records.

- `PaymentReference` represents the payment-level identifier and must remain unique.

- `GatewayTransactionID` represents the gateway transaction identifier and must remain unique.

- `SourceOrderReference` represents the parent Sales Order relationship and may repeat when an order has multiple payment records.

- Successful payments are preserved for audit.

- Payment records support partial and split payments.

- Payment status must use the standardized payment status values.

- Payment amount must be preserved as the supplied transaction value.

- Zero payment amounts may occur for Pending or Failed payment records and must be evaluated against payment status and notes rather than automatically treated as errors.

- PaymentDate, CreatedOn, and ModifiedOn must be valid dates.

- `ModifiedOn` must not be earlier than `CreatedOn`.

- Payment relationships will be validated against the Sales Order header during the appropriate validation stage.

- The observed PAY008 / SO007 amount discrepancy will be retained as supplied because no authoritative payment allocation evidence is available to support a correction.

The approved decisions from this section will define the transformations applied in Section 2.2.

In [10]:
# =========================================================
# 1.8 Findings and Transformation Decisions
# =========================================================

transformation_decisions = pd.DataFrame([

    {
        "Finding": "PaymentReference uniqueness and completeness",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain PaymentReference unchanged as the payment-level "
            "identifier for Payment lineage and reconciliation"
        ),
        "Reason": (
            "PaymentReference is non-null and unique across all 20 Payment "
            "records, making it the approved payment-level identifier."
        )
    },

    {
        "Finding": "GatewayTransactionID uniqueness and completeness",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain GatewayTransactionID unchanged as the gateway "
            "transaction identifier"
        ),
        "Reason": (
            "GatewayTransactionID is non-null and unique across all 20 "
            "Payment records."
        )
    },

    {
        "Finding": "SourceOrderReference repeated across multiple payment records",
        "AffectedRecords": 1,
        "Decision": "Expected business behavior",
        "ApprovedAction": (
            "Retain SourceOrderReference unchanged and use it to maintain "
            "the Sales Order → Payment parent-child relationship"
        ),
        "Reason": (
            "A sales order may contain multiple payment records, including "
            "partial and split payments. The repeated SO001 reference must "
            "not be treated as a duplicate-payment condition."
        )
    },

    {
        "Finding": "No exact duplicate Payment rows",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain the dataset unchanged with respect to exact duplicates"
        ),
        "Reason": (
            "No exact duplicate rows were identified in the Payment source dataset."
        )
    },

    {
        "Finding": "No missing or blank values",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "No missing-value or blank-value treatment is required"
        ),
        "Reason": (
            "All Payment source fields contain populated values with no "
            "NULL or blank-string findings."
        )
    },

    {
        "Finding": "No leading or trailing whitespace",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "No text trimming is required based on the independent review"
        ),
        "Reason": (
            "No leading or trailing whitespace was identified in the "
            "Payment source dataset."
        )
    },

    {
        "Finding": "PaymentMethod values are consistent",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain PaymentMethod values unchanged"
        ),
        "Reason": (
            "The observed payment methods are consistent and contain the "
            "expected categorical values: Visa, Credit Card, Mastercard, "
            "and Cash on Delivery."
        )
    },

    {
        "Finding": "PaymentStatus values are consistent",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain PaymentStatus values unchanged using the observed "
            "standardized status values"
        ),
        "Reason": (
            "The observed payment statuses are Successful, Pending, and "
            "Failed. No inconsistent status values were identified."
        )
    },

    {
        "Finding": "PaymentNotes values contain no formatting issues",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain PaymentNotes values unchanged"
        ),
        "Reason": (
            "No whitespace, blank strings, or missing-value markers were "
            "identified in PaymentNotes."
        )
    },

    {
        "Finding": "CreatedByUser and ModifiedByUser values are consistent",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain CreatedByUser and ModifiedByUser values unchanged"
        ),
        "Reason": (
            "All observed audit-user values are consistently populated "
            "with admin."
        )
    },

    {
        "Finding": "Payment Amount values are non-negative",
        "AffectedRecords": 20,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain Amount values unchanged; convert only to the target "
            "Decimal-compatible datatype"
        ),
        "Reason": (
            "No negative payment amounts were identified. The supplied "
            "transaction amounts must be preserved as transaction values."
        )
    },

    {
        "Finding": "Zero payment amounts for Pending or Failed payments",
        "AffectedRecords": 3,
        "Decision": "Expected business behavior",
        "ApprovedAction": (
            "Retain zero Amount values unchanged for the applicable "
            "Pending and Failed payment records"
        ),
        "Reason": (
            "PAY007 and PAY020 are Pending and PAY011 is Failed. Their "
            "zero amounts are consistent with their payment status and "
            "must not be automatically changed."
        )
    },

    {
        "Finding": "Successful payment amounts are positive",
        "AffectedRecords": 17,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain successful payment Amount values unchanged"
        ),
        "Reason": (
            "All Successful payment records have positive supplied "
            "transaction amounts."
        )
    },

    {
        "Finding": "Profiler numeric outlier candidates",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Do not automatically modify or remove statistical outlier candidates"
        ),
        "Reason": (
            "The profiler identified no statistical outlier candidates for "
            "Amount. No outlier treatment is required."
        )
    },

    {
        "Finding": "PaymentDate stored as object",
        "AffectedRecords": 20,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": (
            "Convert PaymentDate to datetime during transformation"
        ),
        "Reason": (
            "All PaymentDate values are valid and parseable dates. The "
            "target Payment design requires a Datetime-compatible field."
        )
    },

    {
        "Finding": "CreatedOn stored as object",
        "AffectedRecords": 20,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": (
            "Convert CreatedOn to datetime during transformation"
        ),
        "Reason": (
            "All CreatedOn values are valid and parseable dates. The "
            "target Payment design requires a Datetime-compatible field."
        )
    },

    {
        "Finding": "ModifiedOn stored as object",
        "AffectedRecords": 20,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": (
            "Convert ModifiedOn to datetime during transformation"
        ),
        "Reason": (
            "All ModifiedOn values are valid and parseable dates. The "
            "target Payment design requires a Datetime-compatible field."
        )
    },

    {
        "Finding": "Amount source datatype",
        "AffectedRecords": 20,
        "Decision": "Safe deterministic transformation",
        "ApprovedAction": (
            "Convert Amount to Decimal-compatible values for the "
            "database-ready dataset"
        ),
        "Reason": (
            "Amount is a monetary field and the approved Payment target "
            "data dictionary requires a Decimal-compatible representation."
        )
    },

    {
        "Finding": "PaymentDate / CreatedOn / ModifiedOn date logic",
        "AffectedRecords": 0,
        "Decision": "Valid value — retain unchanged",
        "ApprovedAction": (
            "Retain source audit and payment dates and convert only to "
            "the required datetime datatype"
        ),
        "Reason": (
            "All dates are valid, and no record has PaymentDate earlier "
            "than CreatedOn or ModifiedOn earlier than CreatedOn."
        )
    },

    {
        "Finding": "Payment relationship to Sales Order",
        "AffectedRecords": 20,
        "Decision": "Requires relationship validation later",
        "ApprovedAction": (
            "Retain SourceOrderReference values unchanged and validate "
            "the corresponding Sales Order relationship against "
            "commerce.sales_order"
        ),
        "Reason": (
            "SourceOrderReference represents the Payment → Sales Order "
            "relationship. Foreign-key readiness must be confirmed during "
            "the appropriate relationship validation stage."
        )
    },

    {
        "Finding": "PAY008 / SO007 payment amount discrepancy",
        "AffectedRecords": 1,
        "Decision": "Requires business investigation",
        "ApprovedAction": (
            "Retain PAY008 exactly as supplied. Do not correct, delete, "
            "or create an artificial adjustment. Preserve the exception "
            "for traceability and reconciliation."
        ),
        "Reason": (
            "The Zoho payment amount is AED 3,078 while the corresponding "
            "Shopify order total is AED 3,257, a difference of AED 179. "
            "No authoritative Zoho invoice, payment allocation, or receipt "
            "evidence is available to establish the correct payment allocation."
        )
    }

])


print("Payment Findings and Transformation Decisions")
print("=" * 120)

display(transformation_decisions)


print("\nDecision Summary")
print("=" * 120)

print(
    transformation_decisions["Decision"].value_counts()
)

Payment Findings and Transformation Decisions
========================================================================================================================

                                                          Finding  AffectedRecords                                Decision                                                                                                                                              ApprovedAction                                                                                                                                                                                                                                                    Reason
0                    PaymentReference uniqueness and completeness               20          Valid value — retain unchanged                                                    Retain PaymentReference unchanged as the payment-level identifier for Payment lineage and reconciliation                                                                                                                                   PaymentReference is non-null and unique across all 20 Payment records, making it the approved payment-level identifier.
1                GatewayTransactionID uniqueness and completeness               20          Valid value — retain unchanged                                                                                 Retain GatewayTransactionID unchanged as the gateway transaction identifier                                                                                                                                                                                GatewayTransactionID is non-null and unique across all 20 Payment records.
2   SourceOrderReference repeated across multiple payment records                1              Expected business behavior                                            Retain SourceOrderReference unchanged and use it to maintain the Sales Order → Payment parent-child relationship                                                                              A sales order may contain multiple payment records, including partial and split payments. The repeated SO001 reference must not be treated as a duplicate-payment condition.
3                                 No exact duplicate Payment rows                0          Valid value — retain unchanged                                                                                               Retain the dataset unchanged with respect to exact duplicates                                                                                                                                                                                    No exact duplicate rows were identified in the Payment source dataset.
4                                      No missing or blank values                0          Valid value — retain unchanged                                                                                                       No missing-value or blank-value treatment is required                                                                                                                                                                 All Payment source fields contain populated values with no NULL or blank-string findings.
5                               No leading or trailing whitespace                0          Valid value — retain unchanged                                                                                                No text trimming is required based on the independent review                                                                                                                                                                           No leading or trailing whitespace was identified in the Payment source dataset.
6                             PaymentMethod values are consistent               20          Valid value — retain unchanged                                                                                                                       Retain PaymentMethod values unchanged                                                                                                             The observed payment methods are consistent and contain the expected categorical values: Visa, Credit Card, Mastercard, and Cash on Delivery.
7                             PaymentStatus values are consistent               20          Valid value — retain unchanged                                                                         Retain PaymentStatus values unchanged using the observed standardized status values                                                                                                                                         The observed payment statuses are Successful, Pending, and Failed. No inconsistent status values were identified.
8                PaymentNotes values contain no formatting issues               20          Valid value — retain unchanged                                                                                                                        Retain PaymentNotes values unchanged                                                                                                                                                                   No whitespace, blank strings, or missing-value markers were identified in PaymentNotes.
9          CreatedByUser and ModifiedByUser values are consistent               20          Valid value — retain unchanged                                                                                                    Retain CreatedByUser and ModifiedByUser values unchanged                                                                                                                                                                                     All observed audit-user values are consistently populated with admin.
10                         Payment Amount values are non-negative               20          Valid value — retain unchanged                                                                      Retain Amount values unchanged; convert only to the target Decimal-compatible datatype                                                                                                                                    No negative payment amounts were identified. The supplied transaction amounts must be preserved as transaction values.
11            Zero payment amounts for Pending or Failed payments                3              Expected business behavior                                                                   Retain zero Amount values unchanged for the applicable Pending and Failed payment records                                                                                                    PAY007 and PAY020 are Pending and PAY011 is Failed. Their zero amounts are consistent with their payment status and must not be automatically changed.
12                        Successful payment amounts are positive               17          Valid value — retain unchanged                                                                                                           Retain successful payment Amount values unchanged                                                                                                                                                                                All Successful payment records have positive supplied transaction amounts.
13                            Profiler numeric outlier candidates                0          Valid value — retain unchanged                                                                                        Do not automatically modify or remove statistical outlier candidates                                                                                                                                                   The profiler identified no statistical outlier candidates for Amount. No outlier treatment is required.
14                                   PaymentDate stored as object               20       Safe deterministic transformation                                                                                                       Convert PaymentDate to datetime during transformation                                                                                                                                     All PaymentDate values are valid and parseable dates. The target Payment design requires a Datetime-compatible field.
15                                     CreatedOn stored as object               20       Safe deterministic transformation                                                                                                         Convert CreatedOn to datetime during transformation                                                                                                                                       All CreatedOn values are valid and parseable dates. The target Payment design requires a Datetime-compatible field.
16                                    ModifiedOn stored as object               20       Safe deterministic transformation                                                                                                        Convert ModifiedOn to datetime during transformation                                                                                                                                      All ModifiedOn values are valid and parseable dates. The target Payment design requires a Datetime-compatible field.
17                                         Amount source datatype               20       Safe deterministic transformation                                                                                  Convert Amount to Decimal-compatible values for the database-ready dataset                                                                                                                                  Amount is a monetary field and the approved Payment target data dictionary requires a Decimal-compatible representation.
18                PaymentDate / CreatedOn / ModifiedOn date logic                0          Valid value — retain unchanged                                                                    Retain source audit and payment dates and convert only to the required datetime datatype                                                                                                                                           All dates are valid, and no record has PaymentDate earlier than CreatedOn or ModifiedOn earlier than CreatedOn.
19                            Payment relationship to Sales Order               20  Requires relationship validation later                           Retain SourceOrderReference values unchanged and validate the corresponding Sales Order relationship against commerce.sales_order                                                                                     SourceOrderReference represents the Payment → Sales Order relationship. Foreign-key readiness must be confirmed during the appropriate relationship validation stage.
20                      PAY008 / SO007 payment amount discrepancy                1         Requires business investigation  Retain PAY008 exactly as supplied. Do not correct, delete, or create an artificial adjustment. Preserve the exception for traceability and reconciliation.  The Zoho payment amount is AED 3,078 while the corresponding Shopify order total is AED 3,257, a difference of AED 179. No authoritative Zoho invoice, payment allocation, or receipt evidence is available to establish the correct payment allocation.

Decision Summary
========================================================================================================================
Decision
Valid value — retain unchanged            13
Safe deterministic transformation          4
Expected business behavior                 2
Requires relationship validation later     1
Requires business investigation            1
Name: count, dtype: int64

# =========================================================
# SECTION 2 — DATA TRANSFORMATION
# =========================================================

## 2.1 Create Clean Working Dataset

Create a separate working copy of the raw Payment dataset before applying any approved transformations.

The raw Payment dataset must remain unchanged throughout the ETL process.

All transformations will be applied only to the clean working dataset.

The Payment source dataset will remain as a single working dataset during this step.

In [11]:
# =========================================================
# 2.1 Create Clean Working Dataset
# =========================================================

zoho_books_customer_payments_clean = (
    zoho_books_customer_payments_raw.copy()
)


print("Clean working dataset created successfully.")

print(
    f"\nPayment raw rows:   "
    f"{zoho_books_customer_payments_raw.shape[0]}"
)

print(
    f"Payment clean rows: "
    f"{zoho_books_customer_payments_clean.shape[0]}"
)


print("\nRaw and clean datasets are separate objects:")

print(
    "Payment:",
    zoho_books_customer_payments_raw
    is not zoho_books_customer_payments_clean
)

Clean working dataset created successfully.

Payment raw rows:   20
Payment clean rows: 20

Raw and clean datasets are separate objects:
Payment: True

## 2.2 Apply Approved Transformations

Apply only the transformations approved in Section 1.8 to the clean working Payment dataset.

Approved transformations:

- Convert `PaymentDate` to datetime.

- Convert `CreatedOn` to datetime.

- Convert `ModifiedOn` to datetime.

- Convert `Amount` to Decimal-compatible values.

The datetime and monetary datatype transformations are deterministic and prepare the source values for the approved Payment target structure and downstream database loading.

No other business values will be modified.

The `SourceOrderReference` repeated value will be retained unchanged because it represents an expected parent-order relationship rather than duplicate Payment records.

The zero payment amounts associated with Pending and Failed payment records will be retained unchanged because they are consistent with the observed payment status and notes.

The PAY008 / SO007 payment amount discrepancy will be retained exactly as supplied because no authoritative payment allocation evidence is available to support a correction.

No statistical outlier treatment will be applied because the profiler identified no numeric outlier candidates for `Amount`.

The Payment dataset will remain as a single working dataset during this transformation step.

In [12]:
# =========================================================
# 2.2 Apply Approved Transformations
# =========================================================

# ---------------------------------------------------------
# 1. Convert approved date fields
# ---------------------------------------------------------

zoho_books_customer_payments_clean["PaymentDate"] = pd.to_datetime(
    zoho_books_customer_payments_clean["PaymentDate"],
    errors="raise"
)

zoho_books_customer_payments_clean["CreatedOn"] = pd.to_datetime(
    zoho_books_customer_payments_clean["CreatedOn"],
    errors="raise"
)

zoho_books_customer_payments_clean["ModifiedOn"] = pd.to_datetime(
    zoho_books_customer_payments_clean["ModifiedOn"],
    errors="raise"
)


# ---------------------------------------------------------
# 2. Convert approved monetary fields to Decimal-compatible values
# ---------------------------------------------------------

from decimal import Decimal

zoho_books_customer_payments_clean["Amount"] = (
    zoho_books_customer_payments_clean["Amount"].apply(Decimal)
)


print("Payment approved transformations applied successfully.")

Payment approved transformations applied successfully.

## 3.1 Transformation Validation

Validate that every transformation approved in Section 1.8 was successfully applied to the clean Payment dataset.

This validation checks:

- PaymentDate datetime conversion

- CreatedOn datetime conversion

- ModifiedOn datetime conversion

- Amount Decimal-compatible conversion

- Payment business values remain unchanged

- Payment status and payment amount business-rule consistency remains valid

- SourceOrderReference repeated values remain unchanged

- PAY008 / SO007 retained payment amount remains unchanged

- Profiler findings and approved retention decisions remain unchanged

Only approved transformations and approved source-value retention decisions are validated.

No additional data modifications are performed in this section.

In [13]:
# =========================================================
# 3.1 Transformation Validation
# =========================================================

validation_results = []


# ---------------------------------------------------------
# 1. PaymentDate Datetime Validation
# ---------------------------------------------------------

payment_date_is_datetime = pd.api.types.is_datetime64_any_dtype(
    zoho_books_customer_payments_clean["PaymentDate"]
)

validation_results.append({
    "Validation": "PaymentDate datetime conversion",
    "Expected": "datetime64 datatype",
    "Actual": str(
        zoho_books_customer_payments_clean["PaymentDate"].dtype
    ),
    "Passed": payment_date_is_datetime
})


# ---------------------------------------------------------
# 2. CreatedOn Datetime Validation
# ---------------------------------------------------------

created_on_is_datetime = pd.api.types.is_datetime64_any_dtype(
    zoho_books_customer_payments_clean["CreatedOn"]
)

validation_results.append({
    "Validation": "CreatedOn datetime conversion",
    "Expected": "datetime64 datatype",
    "Actual": str(
        zoho_books_customer_payments_clean["CreatedOn"].dtype
    ),
    "Passed": created_on_is_datetime
})


# ---------------------------------------------------------
# 3. ModifiedOn Datetime Validation
# ---------------------------------------------------------

modified_on_is_datetime = pd.api.types.is_datetime64_any_dtype(
    zoho_books_customer_payments_clean["ModifiedOn"]
)

validation_results.append({
    "Validation": "ModifiedOn datetime conversion",
    "Expected": "datetime64 datatype",
    "Actual": str(
        zoho_books_customer_payments_clean["ModifiedOn"].dtype
    ),
    "Passed": modified_on_is_datetime
})


# ---------------------------------------------------------
# 4. Amount Decimal Validation
# ---------------------------------------------------------

amount_is_decimal = zoho_books_customer_payments_clean[
    "Amount"
].apply(
    lambda value: isinstance(value, Decimal)
).all()

validation_results.append({
    "Validation": "Amount Decimal conversion",
    "Expected": "All values are Decimal-compatible",
    "Actual": (
        "All values are Decimal"
        if amount_is_decimal
        else "One or more values are not Decimal"
    ),
    "Passed": amount_is_decimal
})


# ---------------------------------------------------------
# 5. Payment Business Value Validation
# ---------------------------------------------------------

raw_amounts = (
    zoho_books_customer_payments_raw["Amount"]
    .tolist()
)

clean_amounts = [
    int(value)
    for value in zoho_books_customer_payments_clean["Amount"]
]

amount_values_retained = (
    raw_amounts == clean_amounts
)

raw_statuses = (
    zoho_books_customer_payments_raw["PaymentStatus"]
    .tolist()
)

clean_statuses = (
    zoho_books_customer_payments_clean["PaymentStatus"]
    .tolist()
)

status_values_retained = (
    raw_statuses == clean_statuses
)

raw_order_references = (
    zoho_books_customer_payments_raw[
        "SourceOrderReference"
    ].tolist()
)

clean_order_references = (
    zoho_books_customer_payments_clean[
        "SourceOrderReference"
    ].tolist()
)

order_reference_values_retained = (
    raw_order_references == clean_order_references
)

validation_results.append({
    "Validation": "Payment business values retained",
    "Expected": (
        "Amount, PaymentStatus, and SourceOrderReference "
        "remain unchanged"
    ),
    "Actual": (
        f"Amount unchanged: {amount_values_retained}; "
        f"PaymentStatus unchanged: {status_values_retained}; "
        f"SourceOrderReference unchanged: "
        f"{order_reference_values_retained}"
    ),
    "Passed": (
        amount_values_retained
        and status_values_retained
        and order_reference_values_retained
    )
})


# ---------------------------------------------------------
# 6. Payment Amount and Status Business Rule Validation
# ---------------------------------------------------------

invalid_negative_amount_count = (
    zoho_books_customer_payments_clean["Amount"] < 0
).sum()

successful_non_positive_count = (
    (
        zoho_books_customer_payments_clean["PaymentStatus"]
        == "Successful"
    )
    &
    (
        zoho_books_customer_payments_clean["Amount"]
        <= 0
    )
).sum()

pending_non_zero_count = (
    (
        zoho_books_customer_payments_clean["PaymentStatus"]
        == "Pending"
    )
    &
    (
        zoho_books_customer_payments_clean["Amount"]
        != 0
    )
).sum()

failed_non_zero_count = (
    (
        zoho_books_customer_payments_clean["PaymentStatus"]
        == "Failed"
    )
    &
    (
        zoho_books_customer_payments_clean["Amount"]
        != 0
    )
).sum()

validation_results.append({
    "Validation": "Payment amount and status business rules",
    "Expected": (
        "No negative amounts; Successful payments are positive; "
        "Pending and Failed zero amounts remain valid"
    ),
    "Actual": (
        f"Negative amounts: {invalid_negative_amount_count}; "
        f"Successful <= 0: {successful_non_positive_count}; "
        f"Pending != 0: {pending_non_zero_count}; "
        f"Failed != 0: {failed_non_zero_count}"
    ),
    "Passed": (
        invalid_negative_amount_count == 0
        and successful_non_positive_count == 0
        and pending_non_zero_count == 0
        and failed_non_zero_count == 0
    )
})


# ---------------------------------------------------------
# 7. SourceOrderReference Relationship Value Retention
# ---------------------------------------------------------

source_order_reference_retained = (
    zoho_books_customer_payments_raw[
        "SourceOrderReference"
    ].tolist()
    ==
    zoho_books_customer_payments_clean[
        "SourceOrderReference"
    ].tolist()
)

validation_results.append({
    "Validation": "SourceOrderReference repeated values retained",
    "Expected": (
        "Repeated parent-order references remain unchanged"
    ),
    "Actual": (
        "SourceOrderReference values retained unchanged"
        if source_order_reference_retained
        else "SourceOrderReference values changed"
    ),
    "Passed": source_order_reference_retained
})


# ---------------------------------------------------------
# 8. PAY008 / SO007 Retention Validation
# ---------------------------------------------------------

pay008_raw_amount = (
    zoho_books_customer_payments_raw.loc[
        zoho_books_customer_payments_raw["PaymentReference"]
        == "PAY008",
        "Amount"
    ].iloc[0]
)

pay008_clean_amount = (
    zoho_books_customer_payments_clean.loc[
        zoho_books_customer_payments_clean["PaymentReference"]
        == "PAY008",
        "Amount"
    ].iloc[0]
)

pay008_retained = (
    Decimal(str(pay008_raw_amount))
    == pay008_clean_amount
)

validation_results.append({
    "Validation": "PAY008 / SO007 retained payment amount",
    "Expected": "PAY008 Amount remains AED 3078",
    "Actual": (
        f"Raw: {pay008_raw_amount}; "
        f"Clean: {pay008_clean_amount}"
    ),
    "Passed": pay008_retained
})


# ---------------------------------------------------------
# 9. Profiler Finding Retention Validation
# ---------------------------------------------------------

raw_payment_references = (
    zoho_books_customer_payments_raw[
        "PaymentReference"
    ].tolist()
)

clean_payment_references = (
    zoho_books_customer_payments_clean[
        "PaymentReference"
    ].tolist()
)

payment_records_retained = (
    raw_payment_references
    == clean_payment_references
)

validation_results.append({
    "Validation": "Profiler finding and source record retention",
    "Expected": (
        "All source Payment records remain retained; "
        "no records are removed due to profiler findings"
    ),
    "Actual": (
        "All source Payment records retained"
        if payment_records_retained
        else "Source Payment records changed or removed"
    ),
    "Passed": payment_records_retained
})


# ---------------------------------------------------------
# Transformation Validation Results
# ---------------------------------------------------------

transformation_validation = pd.DataFrame(
    validation_results
)

print("TRANSFORMATION VALIDATION RESULTS")
print("=" * 120)

display(transformation_validation)


# ---------------------------------------------------------
# Overall Result
# ---------------------------------------------------------

overall_validation_passed = (
    transformation_validation["Passed"].all()
)

print(
    "\nOverall Transformation Validation Passed:",
    overall_validation_passed
)

if not overall_validation_passed:
    raise ValueError(
        "Transformation validation failed. Review the results "
        "before proceeding."
    )

TRANSFORMATION VALIDATION RESULTS
========================================================================================================================

                                      Validation                                                                                             Expected                                                                                       Actual  Passed
0                PaymentDate datetime conversion                                                                                  datetime64 datatype                                                                               datetime64[ns]    True
1                  CreatedOn datetime conversion                                                                                  datetime64 datatype                                                                               datetime64[ns]    True
2                 ModifiedOn datetime conversion                                                                                  datetime64 datatype                                                                               datetime64[ns]    True
3                      Amount Decimal conversion                                                                    All values are Decimal-compatible                                                                       All values are Decimal    True
4               Payment business values retained                                     Amount, PaymentStatus, and SourceOrderReference remain unchanged  Amount unchanged: True; PaymentStatus unchanged: True; SourceOrderReference unchanged: True    True
5       Payment amount and status business rules  No negative amounts; Successful payments are positive; Pending and Failed zero amounts remain valid                     Negative amounts: 0; Successful <= 0: 0; Pending != 0: 0; Failed != 0: 0    True
6  SourceOrderReference repeated values retained                                                    Repeated parent-order references remain unchanged                                               SourceOrderReference values retained unchanged    True
7         PAY008 / SO007 retained payment amount                                                                       PAY008 Amount remains AED 3078                                                                       Raw: 3078; Clean: 3078    True
8   Profiler finding and source record retention          All source Payment records remain retained; no records are removed due to profiler findings                                                          All source Payment records retained    True

Overall Transformation Validation Passed: True

## 3.2 Validate Data Preservation

Validate that the approved transformations did not unintentionally alter unaffected Payment data.

The validation compares the raw and cleaned datasets while accounting for the approved transformations:

- PaymentDate datatype conversion

- CreatedOn datatype conversion

- ModifiedOn datatype conversion

- Amount datatype conversion

All other business and audit field values should remain unchanged.

The Payment dataset will be validated as a single source.

In [14]:
# =========================================================
# 3.2 Validate Data Preservation
# =========================================================

# Columns that should remain completely unchanged after
# accounting for approved transformations
unchanged_columns = [
    "PaymentReference",
    "SourceOrderReference",
    "PaymentMethod",
    "PaymentStatus",
    "GatewayTransactionID",
    "PaymentNotes",
    "CreatedByUser",
    "ModifiedByUser"
]


all_columns_match = True


# =========================================================
# Payment
# =========================================================

print("=" * 70)
print("PAYMENT DATA PRESERVATION")
print("=" * 70)

for column in unchanged_columns:

    matches = (
        zoho_books_customer_payments_raw[column]
        .astype(str)
        .reset_index(drop=True)
        ==
        zoho_books_customer_payments_clean[column]
        .astype(str)
        .reset_index(drop=True)
    ).all()

    print(f"{column}: {matches}")

    if not matches:
        all_columns_match = False


# =========================================================
# Final Validation
# =========================================================

print(
    "\nAll unaffected Payment columns preserved:",
    all_columns_match
)

if not all_columns_match:
    raise ValueError(
        "Data preservation validation failed. "
        "An unaffected Payment column was unexpectedly changed."
    )

======================================================================
PAYMENT DATA PRESERVATION
======================================================================
PaymentReference: True
SourceOrderReference: True
PaymentMethod: True
PaymentStatus: True
GatewayTransactionID: True
PaymentNotes: True
CreatedByUser: True
ModifiedByUser: True

All unaffected Payment columns preserved: True

# =========================================================
# SECTION 4 — CLEAN CSV
# =========================================================

## 4.1 Prepare Validated Payment Dataset for Export

Prepare the validated Clean DataFrame for export as the Payment Clean CSV.

The validated Payment Clean DataFrame has completed its transformation and data preservation validation.

The Payment Clean DataFrame must not be modified during export preparation.

The exported dataset must:

- Preserve all validated Payment records.

- Preserve the approved column structure.

- Preserve `PaymentReference` and `GatewayTransactionID`.

- Preserve `SourceOrderReference` and the Sales Order relationship values.

- Preserve all approved business and audit values.

- Preserve the approved datatype transformations.

- Not generate or resequence Payment identifiers.

- Not correct or modify the PAY008 / SO007 business exception.

- Not introduce unexpected columns.

The result will be the validated Payment Clean DataFrame ready for CSV export.

In [15]:
# =========================================================
# 4.1 Export Clean Payment Dataset
# =========================================================

from pathlib import Path

clean_payment_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\09_Zoho_Books\clean\zoho_books_customer_payments_clean.csv"
)

# Create the clean folder if it does not exist
clean_payment_path.parent.mkdir(
    parents=True,
    exist_ok=True
)

# Export clean dataset
zoho_books_customer_payments_clean.to_csv(
    clean_payment_path,
    index=False
)

print("Clean Payment CSV exported successfully.")
print("Path:", clean_payment_path)
print("Rows exported:", len(zoho_books_customer_payments_clean))
print("Columns exported:", len(zoho_books_customer_payments_clean.columns))

Clean Payment CSV exported successfully.
Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\09_Zoho_Books\clean\zoho_books_customer_payments_clean.csv
Rows exported: 20
Columns exported: 12

## 4.2 Verify Exported Clean Payment CSV

Reload the exported clean Payment CSV and verify that it matches the validated clean DataFrame.

This confirms that the persisted clean Payment CSV is the official handoff artifact for the next pipeline stage.

In [17]:
# =========================================================
# 4.2 Verify Exported Clean Payment CSV
# =========================================================

from decimal import Decimal

# Reload the exported clean CSV
zoho_books_customer_payments_clean_csv = pd.read_csv(
    clean_payment_path,
    parse_dates=["PaymentDate", "CreatedOn", "ModifiedOn"]
)


# ---------------------------------------------------------
# Basic Export Validation
# ---------------------------------------------------------

print("Clean CSV rows:", len(zoho_books_customer_payments_clean_csv))
print("Clean DataFrame rows:", len(zoho_books_customer_payments_clean))

print("\nClean CSV columns:", len(zoho_books_customer_payments_clean_csv.columns))
print("Clean DataFrame columns:", len(zoho_books_customer_payments_clean.columns))


# ---------------------------------------------------------
# Row Count Validation
# ---------------------------------------------------------

row_count_match = (
    len(zoho_books_customer_payments_clean_csv)
    == len(zoho_books_customer_payments_clean)
)

print("\nRow count matches:", row_count_match)


# ---------------------------------------------------------
# Column Validation
# ---------------------------------------------------------

columns_match = (
    list(zoho_books_customer_payments_clean_csv.columns)
    == list(zoho_books_customer_payments_clean.columns)
)

print("Column names and order match:", columns_match)


# ---------------------------------------------------------
# Datatype Validation
# ---------------------------------------------------------

print("\nReloaded Clean CSV datatypes:")
print(zoho_books_customer_payments_clean_csv.dtypes)


# ---------------------------------------------------------
# Normalize CSV Monetary Representation for Comparison
# ---------------------------------------------------------

zoho_books_customer_payments_clean_csv_comparison = (
    zoho_books_customer_payments_clean_csv.copy()
)

zoho_books_customer_payments_clean_csv_comparison["Amount"] = (
    zoho_books_customer_payments_clean_csv_comparison["Amount"]
    .apply(Decimal)
)


# ---------------------------------------------------------
# Content Validation
# ---------------------------------------------------------

content_match = (
    zoho_books_customer_payments_clean
    .reset_index(drop=True)
    .equals(
        zoho_books_customer_payments_clean_csv_comparison
        .reset_index(drop=True)
    )
)

print(
    "\nClean DataFrame and exported CSV content match "
    "after datatype normalization:",
    content_match
)


# ---------------------------------------------------------
# Final Validation
# ---------------------------------------------------------

export_validation_passed = (
    row_count_match
    and columns_match
    and content_match
)

print("\n" + "=" * 80)
print(
    "EXPORTED CLEAN CSV VALIDATION PASSED:",
    export_validation_passed
)
print("=" * 80)

if not export_validation_passed:
    raise ValueError(
        "Exported clean CSV validation failed. "
        "Review the results before proceeding."
    )

Clean CSV rows: 20
Clean DataFrame rows: 20

Clean CSV columns: 12
Clean DataFrame columns: 12

Row count matches: True
Column names and order match: True

Reloaded Clean CSV datatypes:
PaymentReference                object
SourceOrderReference            object
PaymentDate             datetime64[ns]
PaymentMethod                   object
PaymentStatus                   object
Amount                           int64
GatewayTransactionID            object
PaymentNotes                    object
CreatedOn               datetime64[ns]
CreatedByUser                   object
ModifiedOn              datetime64[ns]
ModifiedByUser                  object
dtype: object

Clean DataFrame and exported CSV content match after datatype normalization: True

================================================================================
EXPORTED CLEAN CSV VALIDATION PASSED: True
================================================================================

# =========================================================
# SECTION 5 — DATABASE READY
# =========================================================

## 5.1 Define Source → Target Mapping

Define the approved source-to-target column mapping based on the
LJ Dev Commerce Payment Data Dictionary.

The mapping converts the Clean Payment column names
into the standardized PostgreSQL target column names.

No data values are modified during this step.

In [18]:
# =========================================================
# 5.1 Define Source → Target Mapping
# =========================================================

payment_column_mapping = {
    "PaymentReference": "payment_id",
    "SourceOrderReference": "sales_order_id",
    "PaymentDate": "payment_date",
    "PaymentMethod": "payment_method",
    "PaymentStatus": "payment_status",
    "Amount": "payment_amount",
    "GatewayTransactionID": "transaction_reference",
    "PaymentNotes": "notes",
    "CreatedOn": "created_date",
    "CreatedByUser": "created_by",
    "ModifiedOn": "updated_date",
    "ModifiedByUser": "updated_by"
}

print("Payment Source → Target Mapping")
print("=" * 80)

for source_column, target_column in payment_column_mapping.items():
    print(f"{source_column:<25} → {target_column}")

Payment Source → Target Mapping
================================================================================
PaymentReference          → payment_id
SourceOrderReference      → sales_order_id
PaymentDate               → payment_date
PaymentMethod             → payment_method
PaymentStatus             → payment_status
Amount                    → payment_amount
GatewayTransactionID      → transaction_reference
PaymentNotes              → notes
CreatedOn                 → created_date
CreatedByUser             → created_by
ModifiedOn                → updated_date
ModifiedByUser            → updated_by

## 5.2 Create Database-Ready Dataset

Create the Payment Database-Ready dataset from the verified
exported Clean Payment CSV.

The approved source-to-target mapping is then applied to convert the
source column names into the PostgreSQL target structure.

The Clean Payment CSV remains unchanged.

No undocumented business-value transformations are applied during this step.

In [19]:
# =========================================================
# 5.2 Create Database-Ready Dataset
# =========================================================

from decimal import Decimal

# Define the verified exported Clean CSV path
payment_clean_path = (
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data"
    r"\09_Zoho_Books\clean\zoho_books_customer_payments_clean.csv"
)

# Load the verified exported Clean CSV
zoho_books_customer_payments_clean_exported = pd.read_csv(
    payment_clean_path
)

# Convert approved date columns back to datetime
zoho_books_customer_payments_clean_exported["PaymentDate"] = pd.to_datetime(
    zoho_books_customer_payments_clean_exported["PaymentDate"]
)

zoho_books_customer_payments_clean_exported["CreatedOn"] = pd.to_datetime(
    zoho_books_customer_payments_clean_exported["CreatedOn"]
)

zoho_books_customer_payments_clean_exported["ModifiedOn"] = pd.to_datetime(
    zoho_books_customer_payments_clean_exported["ModifiedOn"]
)

# Create the Database-Ready dataset from the exported Clean CSV
payment_db_ready = (
    zoho_books_customer_payments_clean_exported
    .rename(columns=payment_column_mapping)
    .copy()
)

# ---------------------------------------------------------
# Prepare Decimal-Compatible Numeric Fields
# ---------------------------------------------------------

decimal_columns = [
    "payment_amount"
]

for column in decimal_columns:
    payment_db_ready[column] = (
        payment_db_ready[column]
        .apply(Decimal)
    )

print("Payment Database-Ready Dataset Created Successfully.")
print("=" * 80)

print("\nSource: Verified Exported Clean CSV")

print("\nDatabase-Ready Dataset Shape:")
print(payment_db_ready.shape)

print("\nDatabase-Ready Column Names:")
print(payment_db_ready.columns.tolist())

print("\nDatabase-Ready Data Types:")
print(payment_db_ready.dtypes)

print("\nDatabase-Ready Dataset:")
display(payment_db_ready)

Payment Database-Ready Dataset Created Successfully.
================================================================================

Source: Verified Exported Clean CSV

Database-Ready Dataset Shape:
(20, 12)

Database-Ready Column Names:
['payment_id', 'sales_order_id', 'payment_date', 'payment_method', 'payment_status', 'payment_amount', 'transaction_reference', 'notes', 'created_date', 'created_by', 'updated_date', 'updated_by']

Database-Ready Data Types:
payment_id                       object
sales_order_id                   object
payment_date             datetime64[ns]
payment_method                   object
payment_status                   object
payment_amount                   object
transaction_reference            object
notes                            object
created_date             datetime64[ns]
created_by                       object
updated_date             datetime64[ns]
updated_by                       object
dtype: object

Database-Ready Dataset:

   payment_id sales_order_id payment_date    payment_method payment_status payment_amount transaction_reference             notes created_date created_by updated_date updated_by
0      PAY001          SO001   2026-07-05              Visa     Successful           2000                TXN001           Partial   2026-07-05      admin   2026-07-05      admin
1      PAY002          SO001   2026-07-05              Visa     Successful           1198                TXN002         Completed   2026-07-05      admin   2026-07-05      admin
2      PAY003          SO002   2026-07-06       Credit Card     Successful           2199                TXN003              Paid   2026-07-06      admin   2026-07-06      admin
3      PAY004          SO003   2026-07-07  Cash on Delivery     Successful           1399                TXN004              Paid   2026-07-07      admin   2026-07-07      admin
4      PAY005          SO004   2026-07-08              Visa     Successful           4298                TXN005              Paid   2026-07-08      admin   2026-07-08      admin
5      PAY006          SO005   2026-07-09        Mastercard     Successful           3448                TXN006              Paid   2026-07-09      admin   2026-07-09      admin
6      PAY007          SO006   2026-07-10  Cash on Delivery        Pending              0                TXN007  Awaiting payment   2026-07-10      admin   2026-07-10      admin
7      PAY008          SO007   2026-07-11              Visa     Successful           3078                TXN008              Paid   2026-07-11      admin   2026-07-11      admin
8      PAY009          SO008   2026-07-12       Credit Card     Successful           1599                TXN009              Paid   2026-07-12      admin   2026-07-12      admin
9      PAY010          SO009   2026-07-13              Visa     Successful            399                TXN010              Paid   2026-07-13      admin   2026-07-13      admin
10     PAY011          SO010   2026-07-14       Credit Card         Failed              0                TXN011    Payment failed   2026-07-14      admin   2026-07-14      admin
11     PAY012          SO011   2026-07-15  Cash on Delivery     Successful            499                TXN012              Paid   2026-07-15      admin   2026-07-15      admin
12     PAY013          SO012   2026-07-16              Visa     Successful            699                TXN013              Paid   2026-07-16      admin   2026-07-16      admin
13     PAY014          SO013   2026-07-17        Mastercard     Successful           3298                TXN014              Paid   2026-07-17      admin   2026-07-17      admin
14     PAY015          SO014   2026-07-18  Cash on Delivery     Successful            179                TXN015              Paid   2026-07-18      admin   2026-07-18      admin
15     PAY016          SO015   2026-07-19              Visa     Successful           3598                TXN016              Paid   2026-07-19      admin   2026-07-19      admin
16     PAY017          SO016   2026-07-20              Visa     Successful            699                TXN017              Paid   2026-07-20      admin   2026-07-20      admin
17     PAY018          SO017   2026-07-21       Credit Card     Successful            499                TXN018              Paid   2026-07-21      admin   2026-07-21      admin
18     PAY019          SO018   2026-07-22        Mastercard     Successful           3899                TXN019              Paid   2026-07-22      admin   2026-07-22      admin
19     PAY020          SO019   2026-07-23  Cash on Delivery        Pending              0                TXN020  Awaiting payment   2026-07-23      admin   2026-07-23      admin

## 5.3 Database-Ready Validation

Validate the Payment Database-Ready DataFrame before
PostgreSQL loading.

This validation confirms that:

* The row count is preserved from the verified Clean CSV.

* All expected target columns are present.

* Target columns are in the approved order.

* The source-to-target mapping is complete.

* No undocumented source columns were lost.

* Required fields do not contain NULL values.

* The primary key is unique and does not contain NULL values.

* The dataset is prepared for PostgreSQL table verification and loading.

In [20]:
# =========================================================
# 5.3 Database-Ready Validation
# =========================================================

print("Payment Database-Ready Validation")
print("=" * 80)


# ---------------------------------------------------------
# 1. Row Count Validation
# ---------------------------------------------------------

print("\n1. Row Count Validation")

clean_csv_row_count = len(
    zoho_books_customer_payments_clean_exported
)

database_ready_row_count = len(
    payment_db_ready
)

row_count_match = (
    clean_csv_row_count
    == database_ready_row_count
)

print(
    "Verified Clean CSV rows:",
    clean_csv_row_count
)

print(
    "Database-Ready rows:",
    database_ready_row_count
)

print(
    "Row counts match:",
    row_count_match
)


# ---------------------------------------------------------
# 2. Expected Target Column Validation
# ---------------------------------------------------------

print("\n2. Expected Target Column Validation")

expected_target_columns = list(
    payment_column_mapping.values()
)

actual_target_columns = (
    payment_db_ready.columns.tolist()
)

target_columns_match = (
    expected_target_columns
    == actual_target_columns
)

print("Expected target columns:")
print(expected_target_columns)

print("\nActual Database-Ready columns:")
print(actual_target_columns)

print(
    "\nColumns and order match:",
    target_columns_match
)


# ---------------------------------------------------------
# 3. Mapping Completeness Validation
# ---------------------------------------------------------

print("\n3. Mapping Completeness Validation")

source_columns = (
    zoho_books_customer_payments_clean_exported.columns.tolist()
)

mapping_source_columns = list(
    payment_column_mapping.keys()
)

# Payment has no additional unmapped source columns.
expected_unmapped_source_columns = []

mapped_source_columns_present = (
    set(mapping_source_columns).issubset(
        set(source_columns)
    )
)

actual_unmapped_source_columns = (
    sorted(
        set(source_columns)
        - set(mapping_source_columns)
    )
)

unmapped_source_columns_expected = (
    actual_unmapped_source_columns
    == sorted(
        expected_unmapped_source_columns
    )
)

unexpected_mapping_source_columns = (
    sorted(
        set(mapping_source_columns)
        - set(source_columns)
    )
)

mapping_complete = (
    mapped_source_columns_present
    and unmapped_source_columns_expected
    and len(
        unexpected_mapping_source_columns
    ) == 0
)

print(
    "Mapped source columns are present:",
    mapped_source_columns_present
)

print(
    "Expected unmapped source columns:",
    expected_unmapped_source_columns
)

print(
    "Actual unmapped source columns:",
    actual_unmapped_source_columns
)

print(
    "Unmapped source columns are as expected:",
    unmapped_source_columns_expected
)

print(
    "Unexpected mapping source columns:",
    unexpected_mapping_source_columns
)

print(
    "Source-to-target mapping complete:",
    mapping_complete
)


# ---------------------------------------------------------
# 4. Required Field Validation
# ---------------------------------------------------------

print("\n4. Required Field Validation")

required_payment_fields = [
    "payment_id",
    "sales_order_id",
    "payment_date",
    "payment_method",
    "payment_status",
    "payment_amount",
    "transaction_reference",
    "created_date",
    "created_by",
    "updated_date",
    "updated_by"
]

null_counts = (
    payment_db_ready[
        required_payment_fields
    ].isnull().sum()
)

print(null_counts)

required_fields_valid = (
    null_counts.sum() == 0
)

print(
    "\nRows with NULL required values:",
    null_counts.sum()
)

print(
    "Required field validation passed:",
    required_fields_valid
)


# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

print("\n5. Primary Key Validation")

duplicate_primary_keys = (
    payment_db_ready[
        "payment_id"
    ]
    .duplicated()
    .sum()
)

null_primary_keys = (
    payment_db_ready[
        "payment_id"
    ]
    .isnull()
    .sum()
)

primary_key_valid = (
    duplicate_primary_keys == 0
    and null_primary_keys == 0
)

print(
    "Duplicate Primary Keys:",
    duplicate_primary_keys
)

print(
    "NULL Primary Keys:",
    null_primary_keys
)

print(
    "Primary Key validation passed:",
    primary_key_valid
)


# ---------------------------------------------------------
# 6. Overall Database-Ready Validation
# ---------------------------------------------------------

database_ready_validation_passed = (
    row_count_match
    and target_columns_match
    and mapping_complete
    and required_fields_valid
    and primary_key_valid
)

print("\n6. Database-Ready Validation Summary")
print("=" * 80)

print(
    "Database-Ready validation passed:",
    database_ready_validation_passed
)

Payment Database-Ready Validation
================================================================================

1. Row Count Validation
Verified Clean CSV rows: 20
Database-Ready rows: 20
Row counts match: True

2. Expected Target Column Validation
Expected target columns:
['payment_id', 'sales_order_id', 'payment_date', 'payment_method', 'payment_status', 'payment_amount', 'transaction_reference', 'notes', 'created_date', 'created_by', 'updated_date', 'updated_by']

Actual Database-Ready columns:
['payment_id', 'sales_order_id', 'payment_date', 'payment_method', 'payment_status', 'payment_amount', 'transaction_reference', 'notes', 'created_date', 'created_by', 'updated_date', 'updated_by']

Columns and order match: True

3. Mapping Completeness Validation
Mapped source columns are present: True
Expected unmapped source columns: []
Actual unmapped source columns: []
Unmapped source columns are as expected: True
Unexpected mapping source columns: []
Source-to-target mapping complete: True

4. Required Field Validation
payment_id               0
sales_order_id           0
payment_date             0
payment_method           0
payment_status           0
payment_amount           0
transaction_reference    0
created_date             0
created_by               0
updated_date             0
updated_by               0
dtype: int64

Rows with NULL required values: 0
Required field validation passed: True

5. Primary Key Validation
Duplicate Primary Keys: 0
NULL Primary Keys: 0
Primary Key validation passed: True

6. Database-Ready Validation Summary
================================================================================
Database-Ready validation passed: True

# =========================================================
# SECTION 6 — PostgreSQL
# =========================================================

Connect to PostgreSQL and confirm that the Payment ETL notebook is connected to
the correct database and PostgreSQL environment.

No table changes or data loading are performed in this step.

## 6.1 Connect

Establish a PostgreSQL connection for the Payment ETL
process.

Confirm that:

* The PostgreSQL connection is successful.

* The correct database is connected.

* The correct PostgreSQL user is connected.

* The target schema is available.

No records are inserted during this step.

In [21]:
# =========================================================
# 6.1 Connect to PostgreSQL
# =========================================================

import psycopg2
from getpass import getpass


# ---------------------------------------------------------
# PostgreSQL Connection Configuration
# ---------------------------------------------------------

DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "lj_dev_commerce"
DB_USER = "postgres"

DB_PASSWORD = getpass("Enter PostgreSQL password: ")


# ---------------------------------------------------------
# Connect to PostgreSQL
# ---------------------------------------------------------

try:
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD
    )

    cursor = conn.cursor()

    print("PostgreSQL connection successful.")
    print("Database:", DB_NAME)
    print("Host:", DB_HOST)
    print("Port:", DB_PORT)

except Exception as e:
    print("PostgreSQL connection failed.")
    print("Error:", e)

PostgreSQL connection successful.
Database: lj_dev_commerce
Host: localhost
Port: 5432

## 6.2 Prepare / Create Target Table

Check whether the approved Payment PostgreSQL target table
already exists before creating or modifying anything.

Target:

Schema: commerce

Table: payment

The table must not be recreated blindly. Its existence and approved
database design must be confirmed first.

In [22]:
# =========================================================
# 6.2 Prepare / Create Target Table
# =========================================================

target_schema = "commerce"
target_table = "payment"

# Check whether the target table already exists
cursor.execute("""
    SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = %s
          AND table_name = %s
    );
""", (target_schema, target_table))

table_exists = cursor.fetchone()[0]

print("Payment Target Table Check")
print("=" * 80)

print("Schema:", target_schema)
print("Table:", target_table)
print("Table exists:", table_exists)

if table_exists:
    print("\nTarget table already exists.")
    print("The table will not be recreated.")
else:
    print("\nTarget table does not exist.")
    print("The approved database design must be used before creating it.")

Payment Target Table Check
================================================================================
Schema: commerce
Table: payment
Table exists: False

Target table does not exist.
The approved database design must be used before creating it.

## 6.2.1 Create Payment Table

The `commerce.payment` table does not currently exist.

This section creates the Payment PostgreSQL target table based
on the approved LJ Dev Commerce Payment Data Dictionary.

Key design decisions:

- `payment_id` is the Primary Key.

- All required Data Dictionary fields use `NOT NULL`.

- `sales_order_id` is a Foreign Key based on the
  approved Payment database relationship.

- `payment_date`, `created_date`, and `updated_date` use the PostgreSQL
  `TIMESTAMP` datatype.

- `payment_amount` uses the PostgreSQL `DECIMAL` datatype.

In [23]:
# =========================================================
# 6.2.1 Create Payment Table
# =========================================================

create_payment_table_query = """
CREATE TABLE commerce.payment (

    payment_id TEXT PRIMARY KEY,

    sales_order_id TEXT NOT NULL,

    payment_date TIMESTAMP NOT NULL,

    payment_method TEXT NOT NULL,
    payment_status TEXT NOT NULL,

    payment_amount DECIMAL NOT NULL,

    transaction_reference TEXT NOT NULL,

    notes TEXT,

    created_date TIMESTAMP NOT NULL,
    created_by TEXT NOT NULL,

    updated_date TIMESTAMP NOT NULL,
    updated_by TEXT NOT NULL,

    FOREIGN KEY (sales_order_id)
        REFERENCES commerce.sales_order(sales_order_id)

);
"""

try:
    cursor.execute(create_payment_table_query)
    conn.commit()

    print("Payment table created successfully.")
    print("Table: commerce.payment")

except Exception as e:
    conn.rollback()

    print("Payment table creation failed.")
    print("Error:", e)

Payment table created successfully.
Table: commerce.payment

## 6.3 Verify Payment Table Structure

Verify the actual PostgreSQL structure of the
`commerce.payment` table after creation.

Confirm:

- Column names

- Column order

- PostgreSQL data types

- NULL / NOT NULL rules

- Default values

The actual PostgreSQL table structure will be reviewed against the
approved Payment Data Dictionary before records are loaded.

In [24]:
# =========================================================
# 6.3 Verify Payment Table Structure
# =========================================================

verify_payment_table_query = """
SELECT
    ordinal_position,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'commerce'
  AND table_name = 'payment'
ORDER BY ordinal_position;
"""

try:
    cursor.execute(verify_payment_table_query)

    table_structure = cursor.fetchall()

    print("Payment Table Structure")
    print("=" * 80)

    print(
        f"{'Position':<10}"
        f"{'Column Name':<25}"
        f"{'Data Type':<25}"
        f"{'Nullable':<12}"
        f"{'Default'}"
    )

    print("-" * 100)

    for row in table_structure:
        print(
            f"{row[0]:<10}"
            f"{row[1]:<25}"
            f"{row[2]:<25}"
            f"{row[3]:<12}"
            f"{row[4]}"
        )

except Exception as e:
    print("Payment table structure verification failed.")
    print("Error:", e)

Payment Table Structure
================================================================================
Position  Column Name              Data Type                Nullable    Default
----------------------------------------------------------------------------------------------------
1         payment_id               text                     NO          None
2         sales_order_id           text                     NO          None
3         payment_date             timestamp without time zoneNO          None
4         payment_method           text                     NO          None
5         payment_status           text                     NO          None
6         payment_amount           numeric                  NO          None
7         transaction_reference    text                     NO          None
8         notes                    text                     YES         None
9         created_date             timestamp without time zoneNO          None
10        created_by               text                     NO          None
11        updated_date             timestamp without time zoneNO          None
12        updated_by               text                     NO          None

## 6.4 Verify Keys, Relationships & Load Dependencies

Verify the applicable keys, relationships, and load dependencies before
loading Payment records into PostgreSQL.

Confirm:

- `payment_id` is the Primary Key.

- `sales_order_id` references the approved Sales Order parent table.

- Required Sales Order parent records are available before loading Payment
  records.

- The dataset follows the approved project ETL load order.

Only applicable checks are performed for this dataset.

In [25]:
# =========================================================
# 6.4 Verify Keys, Relationships & Load Dependencies
# =========================================================

print("Payment Keys, Relationships & Load Dependency Review")
print("=" * 80)

# ---------------------------------------------------------
# 1. Primary Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'payment'
      AND tc.constraint_type = 'PRIMARY KEY';
""")

primary_keys = cursor.fetchall()

print("\n1. Primary Key")
print(primary_keys)

primary_key_valid = (
    len(primary_keys) == 1
    and primary_keys[0][1] == "payment_id"
)

print("Primary Key validation passed:", primary_key_valid)


# ---------------------------------------------------------
# 2. Foreign Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name,
        ccu.table_schema AS referenced_schema,
        ccu.table_name AS referenced_table,
        ccu.column_name AS referenced_column
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
        ON ccu.constraint_name = tc.constraint_name
        AND ccu.table_schema = tc.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'payment'
      AND tc.constraint_type = 'FOREIGN KEY'
    ORDER BY kcu.column_name;
""")

foreign_keys = cursor.fetchall()

print("\n2. Foreign Keys")
print(foreign_keys)

expected_foreign_key_columns = {
    "sales_order_id"
}

actual_foreign_key_columns = {
    row[1] for row in foreign_keys
}

foreign_keys_valid = (
    actual_foreign_key_columns
    == expected_foreign_key_columns
)

print(
    "Expected Foreign Key columns:",
    expected_foreign_key_columns
)

print(
    "Actual Foreign Key columns:",
    actual_foreign_key_columns
)

print(
    "Foreign Key validation passed:",
    foreign_keys_valid
)


# ---------------------------------------------------------
# 3. Load Dependency Review
# ---------------------------------------------------------

print("\n3. Load Dependency Review")

load_dependency_ready = (
    primary_key_valid
    and foreign_keys_valid
)

print(
    "Primary Key ready:",
    primary_key_valid
)

print(
    "Foreign Key dependencies ready:",
    foreign_keys_valid
)


# ---------------------------------------------------------
# 4. Overall Load Dependency Status
# ---------------------------------------------------------

print("\n4. Overall Load Dependency Status")
print("=" * 80)

print(
    "Payment is ready for data loading:",
    load_dependency_ready
)

Payment Keys, Relationships & Load Dependency Review
================================================================================

1. Primary Key
[('payment_pkey', 'payment_id')]
Primary Key validation passed: True

2. Foreign Keys
[('payment_sales_order_id_fkey', 'sales_order_id', 'commerce', 'sales_order', 'sales_order_id')]
Expected Foreign Key columns: {'sales_order_id'}
Actual Foreign Key columns: {'sales_order_id'}
Foreign Key validation passed: True

3. Load Dependency Review
Primary Key ready: True
Foreign Key dependencies ready: True

4. Overall Load Dependency Status
================================================================================
Payment is ready for data loading: True

## 6.5 Insert Payment Records

Load the validated Payment database-ready dataset into the
verified `commerce.payment` PostgreSQL table.

Before inserting records:

- Confirm the target table is currently empty.

- Confirm the database-ready row count.

- Insert only the validated database-ready records.

- Use an explicit column list matching the approved target structure.

- Commit the transaction only after successful insertion.

No transformations are performed during the database loading step.

In [26]:
# =========================================================
# 6.5 Insert Payment Records
# =========================================================

print("Payment Record Loading")
print("=" * 80)


# ---------------------------------------------------------
# 1. Confirm Target Table Is Empty
# ---------------------------------------------------------

cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.payment;
""")

existing_record_count = cursor.fetchone()[0]

print("\n1. Target Table Record Count")
print("Existing records:", existing_record_count)

target_table_empty = (
    existing_record_count == 0
)

print("Target table is empty:", target_table_empty)


# ---------------------------------------------------------
# 2. Confirm Database-Ready Row Count
# ---------------------------------------------------------

db_ready_row_count = len(
    payment_db_ready
)

print("\n2. Database-Ready Row Count")
print("Database-ready records:", db_ready_row_count)


# ---------------------------------------------------------
# 3. Insert Validated Database-Ready Records
# ---------------------------------------------------------

insert_payment_query = """
INSERT INTO commerce.payment (
    payment_id,
    sales_order_id,
    payment_date,
    payment_method,
    payment_status,
    payment_amount,
    transaction_reference,
    notes,
    created_date,
    created_by,
    updated_date,
    updated_by
)
VALUES (
    %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s
);
"""

try:

    if not target_table_empty:
        raise ValueError(
            "Target table is not empty. "
            "Insertion stopped to prevent accidental duplicate loading."
        )

    records_to_insert = [
        tuple(row)
        for row in payment_db_ready.itertuples(
            index=False,
            name=None
        )
    ]

    if len(records_to_insert) != db_ready_row_count:
        raise ValueError(
            "Database-ready record count changed before insertion."
        )

    cursor.executemany(
        insert_payment_query,
        records_to_insert
    )

    conn.commit()

    print("\n3. Insert Result")
    print(
        "Payment records inserted:",
        len(records_to_insert)
    )
    print("Transaction committed successfully.")

except Exception as e:

    conn.rollback()

    print("\nPayment record insertion failed.")
    print("Transaction rolled back.")
    print("Error:", e)

Payment Record Loading
================================================================================

1. Target Table Record Count
Existing records: 0
Target table is empty: True

2. Database-Ready Row Count
Database-ready records: 20

3. Insert Result
Payment records inserted: 20
Transaction committed successfully.

## 6.6 Validate Payment Row Count

Compare the number of records in the Database-Ready dataset with the
number of records currently stored in the PostgreSQL
`commerce.payment` table.

This confirms that the intended load scope was completed successfully.

No additional integrity checks are performed in this section.

In [27]:
# =========================================================
# 6.6 Validate Payment Row Count
# =========================================================

# Expected row count from the Database-Ready dataset
db_ready_row_count = len(payment_db_ready)


# Actual row count from PostgreSQL
cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.payment;
""")

postgresql_row_count = cursor.fetchone()[0]


# Validation result
row_count_match = (
    db_ready_row_count == postgresql_row_count
)


print("Payment Row Count Validation")
print("=" * 80)

print("\n1. Database-Ready Dataset Row Count")
print("Rows:", db_ready_row_count)

print("\n2. PostgreSQL Table Row Count")
print("Rows:", postgresql_row_count)

print("\n3. Row Count Validation")
print("Row counts match:", row_count_match)

print("\n4. Validation Summary")
print("=" * 80)

if row_count_match:
    print("Payment row count validation passed.")
else:
    print("Payment row count validation failed.")

Payment Row Count Validation
================================================================================

1. Database-Ready Dataset Row Count
Rows: 20

2. PostgreSQL Table Row Count
Rows: 20

3. Row Count Validation
Row counts match: True

4. Validation Summary
================================================================================
Payment row count validation passed.

## 6.7 Retrieve Payment Records

Retrieve the Payment records directly from PostgreSQL to confirm
that the loaded data is stored correctly.

Review:

- Loaded records

- Column values

- Payment amount values

- Payment method and payment status values

- Sales Order and transaction reference values

- Date and timestamp values

- Overall record formatting

This step confirms that records can be successfully retrieved from the
PostgreSQL target table.

In [28]:
# =========================================================
# 6.7 Retrieve Payment Records
# =========================================================

retrieve_payment_query = """
SELECT
    payment_id,
    sales_order_id,
    payment_date,
    payment_method,
    payment_status,
    payment_amount,
    transaction_reference,
    notes,
    created_date,
    created_by,
    updated_date,
    updated_by
FROM commerce.payment
ORDER BY payment_id;
"""

try:
    cursor.execute(retrieve_payment_query)

    payment_records = cursor.fetchall()

    print("Payment Records Retrieved from PostgreSQL")
    print("=" * 80)

    print("Records retrieved:", len(payment_records))

    # Retrieve column names from the query result
    column_names = [
        description[0]
        for description in cursor.description
    ]

    # Create a DataFrame for readable review
    payment_postgresql = pd.DataFrame(
        payment_records,
        columns=column_names
    )

    print("\nRetrieved Payment Records:")
    display(payment_postgresql)

except Exception as e:
    print("Payment record retrieval failed.")
    print("Error:", e)

Payment Records Retrieved from PostgreSQL
================================================================================
Records retrieved: 20

Retrieved Payment Records:

   payment_id sales_order_id payment_date    payment_method payment_status payment_amount transaction_reference             notes created_date created_by updated_date updated_by
0      PAY001          SO001   2026-07-05              Visa     Successful           2000                TXN001           Partial   2026-07-05      admin   2026-07-05      admin
1      PAY002          SO001   2026-07-05              Visa     Successful           1198                TXN002         Completed   2026-07-05      admin   2026-07-05      admin
2      PAY003          SO002   2026-07-06       Credit Card     Successful           2199                TXN003              Paid   2026-07-06      admin   2026-07-06      admin
3      PAY004          SO003   2026-07-07  Cash on Delivery     Successful           1399                TXN004              Paid   2026-07-07      admin   2026-07-07      admin
4      PAY005          SO004   2026-07-08              Visa     Successful           4298                TXN005              Paid   2026-07-08      admin   2026-07-08      admin
5      PAY006          SO005   2026-07-09        Mastercard     Successful           3448                TXN006              Paid   2026-07-09      admin   2026-07-09      admin
6      PAY007          SO006   2026-07-10  Cash on Delivery        Pending              0                TXN007  Awaiting payment   2026-07-10      admin   2026-07-10      admin
7      PAY008          SO007   2026-07-11              Visa     Successful           3078                TXN008              Paid   2026-07-11      admin   2026-07-11      admin
8      PAY009          SO008   2026-07-12       Credit Card     Successful           1599                TXN009              Paid   2026-07-12      admin   2026-07-12      admin
9      PAY010          SO009   2026-07-13              Visa     Successful            399                TXN010              Paid   2026-07-13      admin   2026-07-13      admin
10     PAY011          SO010   2026-07-14       Credit Card         Failed              0                TXN011    Payment failed   2026-07-14      admin   2026-07-14      admin
11     PAY012          SO011   2026-07-15  Cash on Delivery     Successful            499                TXN012              Paid   2026-07-15      admin   2026-07-15      admin
12     PAY013          SO012   2026-07-16              Visa     Successful            699                TXN013              Paid   2026-07-16      admin   2026-07-16      admin
13     PAY014          SO013   2026-07-17        Mastercard     Successful           3298                TXN014              Paid   2026-07-17      admin   2026-07-17      admin
14     PAY015          SO014   2026-07-18  Cash on Delivery     Successful            179                TXN015              Paid   2026-07-18      admin   2026-07-18      admin
15     PAY016          SO015   2026-07-19              Visa     Successful           3598                TXN016              Paid   2026-07-19      admin   2026-07-19      admin
16     PAY017          SO016   2026-07-20              Visa     Successful            699                TXN017              Paid   2026-07-20      admin   2026-07-20      admin
17     PAY018          SO017   2026-07-21       Credit Card     Successful            499                TXN018              Paid   2026-07-21      admin   2026-07-21      admin
18     PAY019          SO018   2026-07-22        Mastercard     Successful           3899                TXN019              Paid   2026-07-22      admin   2026-07-22      admin
19     PAY020          SO019   2026-07-23  Cash on Delivery        Pending              0                TXN020  Awaiting payment   2026-07-23      admin   2026-07-23      admin

## 6.8 Source → Database Reconciliation

Compare the validated Payment Database-Ready dataset with the
records retrieved directly from PostgreSQL.

Validate:

- Row counts

- Column names

- Column order

- Payment IDs

- Record-level values

This confirms that the Database-Ready dataset was loaded into PostgreSQL
without unintended changes.

In [29]:
# =========================================================
# 6.8 Source → Database Reconciliation
# =========================================================

# ---------------------------------------------------------
# 1. Prepare Source Dataset
# ---------------------------------------------------------

payment_source_reconciliation = (
    payment_db_ready.copy()
    .sort_values("payment_id")
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 2. Prepare PostgreSQL Dataset
# ---------------------------------------------------------

payment_postgresql_reconciliation = (
    payment_postgresql.copy()
    .sort_values("payment_id")
    .reset_index(drop=True)
)


print("Payment Source → Database Reconciliation")
print("=" * 80)


# ---------------------------------------------------------
# 3. Row Count Validation
# ---------------------------------------------------------

source_row_count = len(
    payment_source_reconciliation
)

database_row_count = len(
    payment_postgresql_reconciliation
)

row_count_match = (
    source_row_count == database_row_count
)

print("\n1. Row Count Validation")
print("Database-Ready rows:", source_row_count)
print("PostgreSQL rows:", database_row_count)
print("Row counts match:", row_count_match)


# ---------------------------------------------------------
# 4. Column Validation
# ---------------------------------------------------------

source_columns = (
    payment_source_reconciliation.columns.tolist()
)

database_columns = (
    payment_postgresql_reconciliation.columns.tolist()
)

column_match = (
    source_columns == database_columns
)

print("\n2. Column Validation")
print("Columns and order match:", column_match)

if not column_match:
    print("\nDatabase-Ready columns:")
    print(source_columns)

    print("\nPostgreSQL columns:")
    print(database_columns)


# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

source_payment_ids = set(
    payment_source_reconciliation[
        "payment_id"
    ]
)

database_payment_ids = set(
    payment_postgresql_reconciliation[
        "payment_id"
    ]
)

primary_key_match = (
    source_payment_ids
    == database_payment_ids
)

print("\n3. Payment ID Validation")
print(
    "Payment IDs match:",
    primary_key_match
)


# ---------------------------------------------------------
# 6. Record-Level Value Validation
# ---------------------------------------------------------

value_match = (
    payment_source_reconciliation.equals(
        payment_postgresql_reconciliation
    )
)

print("\n4. Record-Level Value Validation")
print("All record values match:", value_match)


# ---------------------------------------------------------
# 7. Reconciliation Summary
# ---------------------------------------------------------

reconciliation_passed = (
    row_count_match
    and column_match
    and primary_key_match
    and value_match
)

print("\n5. Source → Database Reconciliation Summary")
print("=" * 80)

print(
    "Source → Database reconciliation passed:",
    reconciliation_passed
)

Payment Source → Database Reconciliation
================================================================================

1. Row Count Validation
Database-Ready rows: 20
PostgreSQL rows: 20
Row counts match: True

2. Column Validation
Columns and order match: True

3. Payment ID Validation
Payment IDs match: True

4. Record-Level Value Validation
All record values match: True

5. Source → Database Reconciliation Summary
================================================================================
Source → Database reconciliation passed: True

## 6.9 Payment Database Integrity Validation

Perform final integrity checks on the loaded
`commerce.payment` table.

The checks confirm:

- Primary-key uniqueness

- Required-field integrity

- Duplicate record checks

- Payment amount validity

- Payment status and amount integrity

- Audit date consistency

These checks provide the final confirmation that the Payment
table is structurally and business-rule compliant after loading.

In [30]:
# =========================================================
# 6.9 Payment Database Integrity Validation
# =========================================================

integrity_query = """
SELECT
    COUNT(*) AS total_rows,

    COUNT(DISTINCT payment_id) AS distinct_payment_ids,

    COUNT(*) FILTER (
        WHERE payment_id IS NULL
    ) AS null_payment_ids,

    COUNT(*) FILTER (
        WHERE sales_order_id IS NULL
    ) AS null_sales_order_ids,

    COUNT(*) FILTER (
        WHERE payment_date IS NULL
    ) AS null_payment_dates,

    COUNT(*) FILTER (
        WHERE payment_method IS NULL
    ) AS null_payment_methods,

    COUNT(*) FILTER (
        WHERE payment_status IS NULL
    ) AS null_payment_statuses,

    COUNT(*) FILTER (
        WHERE payment_amount IS NULL
    ) AS null_payment_amounts,

    COUNT(*) FILTER (
        WHERE transaction_reference IS NULL
    ) AS null_transaction_references,

    COUNT(*) FILTER (
        WHERE created_date IS NULL
    ) AS null_created_dates,

    COUNT(*) FILTER (
        WHERE created_by IS NULL
    ) AS null_created_by,

    COUNT(*) FILTER (
        WHERE updated_date IS NULL
    ) AS null_updated_dates,

    COUNT(*) FILTER (
        WHERE updated_by IS NULL
    ) AS null_updated_by,

    COUNT(*) FILTER (
        WHERE payment_amount < 0
    ) AS invalid_payment_amounts,

    COUNT(*) FILTER (
        WHERE payment_status = 'Successful'
        AND payment_amount <= 0
    ) AS invalid_successful_payment_amounts,

    COUNT(*) FILTER (
        WHERE payment_status = 'Pending'
        AND payment_amount != 0
    ) AS invalid_pending_payment_amounts,

    COUNT(*) FILTER (
        WHERE payment_status = 'Failed'
        AND payment_amount != 0
    ) AS invalid_failed_payment_amounts,

    COUNT(*) FILTER (
        WHERE updated_date < created_date
    ) AS invalid_audit_date_order

FROM commerce.payment;
"""

try:
    cursor.execute(integrity_query)

    integrity_result = cursor.fetchone()

    print("Payment Database Integrity Validation")
    print("=" * 80)

    print("\n1. Primary Key Integrity")
    print("Total rows:", integrity_result[0])
    print(
        "Distinct payment IDs:",
        integrity_result[1]
    )
    print(
        "NULL payment IDs:",
        integrity_result[2]
    )

    print("\n2. Required Field Integrity")
    print("NULL sales order IDs:", integrity_result[3])
    print("NULL payment dates:", integrity_result[4])
    print("NULL payment methods:", integrity_result[5])
    print("NULL payment statuses:", integrity_result[6])
    print("NULL payment amounts:", integrity_result[7])
    print(
        "NULL transaction references:",
        integrity_result[8]
    )
    print("NULL created dates:", integrity_result[9])
    print("NULL created by:", integrity_result[10])
    print("NULL updated dates:", integrity_result[11])
    print("NULL updated by:", integrity_result[12])

    print("\n3. Payment Value Integrity")
    print(
        "Invalid payment amounts:",
        integrity_result[13]
    )
    print(
        "Invalid Successful payment amounts:",
        integrity_result[14]
    )
    print(
        "Invalid Pending payment amounts:",
        integrity_result[15]
    )
    print(
        "Invalid Failed payment amounts:",
        integrity_result[16]
    )

    print("\n4. Audit Date Integrity")
    print(
        "Updated date earlier than created date:",
        integrity_result[17]
    )

    # -----------------------------------------------------
    # Final Validation Result
    # -----------------------------------------------------

    integrity_passed = (
        integrity_result[0] == integrity_result[1]
        and integrity_result[2] == 0
        and integrity_result[3] == 0
        and integrity_result[4] == 0
        and integrity_result[5] == 0
        and integrity_result[6] == 0
        and integrity_result[7] == 0
        and integrity_result[8] == 0
        and integrity_result[9] == 0
        and integrity_result[10] == 0
        and integrity_result[11] == 0
        and integrity_result[12] == 0
        and integrity_result[13] == 0
        and integrity_result[14] == 0
        and integrity_result[15] == 0
        and integrity_result[16] == 0
        and integrity_result[17] == 0
    )

    print("\n5. Database Integrity Validation Summary")
    print("=" * 80)

    print(
        "Payment database integrity passed:",
        integrity_passed
    )

except Exception as e:
    print(
        "Payment database integrity validation failed."
    )
    print("Error:", e)

Payment Database Integrity Validation
================================================================================

1. Primary Key Integrity
Total rows: 20
Distinct payment IDs: 20
NULL payment IDs: 0

2. Required Field Integrity
NULL sales order IDs: 0
NULL payment dates: 0
NULL payment methods: 0
NULL payment statuses: 0
NULL payment amounts: 0
NULL transaction references: 0
NULL created dates: 0
NULL created by: 0
NULL updated dates: 0
NULL updated by: 0

3. Payment Value Integrity
Invalid payment amounts: 0
Invalid Successful payment amounts: 0
Invalid Pending payment amounts: 0
Invalid Failed payment amounts: 0

4. Audit Date Integrity
Updated date earlier than created date: 0

5. Database Integrity Validation Summary
================================================================================
Payment database integrity passed: True

## 6.10 Close PostgreSQL Connection

Close the PostgreSQL cursor and database connection after all
Payment loading and validation steps are complete.

Confirm that PostgreSQL resources are closed cleanly.

In [31]:
# =========================================================
# 6.10 Close PostgreSQL Connection
# =========================================================

try:
    if cursor is not None and not cursor.closed:
        cursor.close()

    if conn is not None and conn.closed == 0:
        conn.close()

    print("PostgreSQL resources closed successfully.")
    print("Cursor closed:", cursor.closed)
    print("Connection closed:", conn.closed != 0)

except Exception as e:
    print("PostgreSQL resource closure failed.")
    print("Error:", e)

PostgreSQL resources closed successfully.
Cursor closed: True
Connection closed: True