# LJ Dev Commerce - Phase 4

# X. Shipment ETL

# =========================================================
# SECTION 1 — EXTRACT, SET UP, PROFILE, FINDINGS & DECISIONS
# =========================================================

# 1.1 Setup

This section prepares the notebook environment for the Shipment ETL process.

The setup includes:

* Importing the required Python libraries.

* Configuring Pandas display options.

* Preparing the notebook environment for the Shipment ETL workflow.

No dataset is loaded, modified, cleaned, or transformed in this section.

In [1]:
# =========================================================
# 1.1 Setup
# =========================================================

import pandas as pd
import numpy as np

# =========================================================
# Display Configuration
# =========================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)

In [2]:

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

## 1.2 Load and Preserve Shipment Raw Dataset

Load the raw Shipment source file from Courier Systems and preserve it as the original source dataset.

The raw dataset must not be modified during the ETL process. Any profiling, cleaning, transformation, or validation work will use separate DataFrame copies where appropriate.

For this section, the Shipment source dataset will remain as a single raw dataset. It will not be transformed or modified during the loading process.

In [5]:
# =========================================================
# 1.2 Load and Preserve Shipment Raw Dataset
# =========================================================

shipment_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\10_Courier_Systems\courier_shipments.csv"
)

shipment_raw = pd.read_csv(shipment_raw_path)
shipment_raw_original = shipment_raw.copy(deep=True)

print("Shipment raw dataset loaded successfully.")
print("Rows:", len(shipment_raw))
print("Columns:", len(shipment_raw.columns))
print("Path:", shipment_raw_path)

Shipment raw dataset loaded successfully.
Rows: 14
Columns: 13
Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\10_Courier_Systems\courier_shipments.csv

## 1.3 Initial Raw Data Inspection

Perform an initial inspection of the untouched Shipment raw dataset before profiling.

This step establishes the structure, current pandas data types, missing-value counts, and sample records for the Shipment raw dataset.

No transformations are performed at this stage.

In [6]:
# =========================================================
# 1.3 Initial Raw Data Inspection
# =========================================================

print("Shipment Dataset shape:")
print(shipment_raw.shape)


print("\nShipment Column names:")
print(shipment_raw.columns.tolist())


print("\nShipment Current pandas data types:")
print(shipment_raw.dtypes)


print("\nShipment Missing values:")
print(shipment_raw.isnull().sum())


print("\nShipment Sample raw records:")
display(shipment_raw.head())

Shipment Dataset shape:
(14, 13)

Shipment Column names:
['ShipmentReference', 'SourceOrderReference', 'DispatchWarehouseCode', 'DispatchDate', 'Courier', 'TrackingNo', 'TrackingStatus', 'DeliveredDate', 'DeliveryNotes', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Shipment Current pandas data types:
ShipmentReference        object
SourceOrderReference     object
DispatchWarehouseCode    object
DispatchDate             object
Courier                  object
TrackingNo               object
TrackingStatus           object
DeliveredDate            object
DeliveryNotes            object
CreatedOn                object
CreatedByUser            object
ModifiedOn               object
ModifiedByUser           object
dtype: object

Shipment Missing values:
ShipmentReference        0
SourceOrderReference     0
DispatchWarehouseCode    0
DispatchDate             0
Courier                  0
TrackingNo               2
TrackingStatus           0
DeliveredDate            1
DeliveryNotes            0
CreatedOn                0
CreatedByUser            0
ModifiedOn               0
ModifiedByUser           0
dtype: int64

Shipment Sample raw records:

  ShipmentReference SourceOrderReference DispatchWarehouseCode DispatchDate Courier TrackingNo TrackingStatus DeliveredDate DeliveryNotes   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0             SH001                SO001                 WH001   2026-07-06     DHL     TRK001      Delivered    2026-07-07      Complete  2026-07-05         admin  2026-07-07          admin
1             SH002                SO002                 WH001   2026-07-07  Aramex     TRK002      Delivered    2026-07-08      Complete  2026-07-06         admin  2026-07-08          admin
2             SH003                SO003                 WH002   2026-07-08   FedEx     TRK003      Delivered    2026-07-09      Complete  2026-07-07         admin  2026-07-09          admin
3             SH004                SO004                 WH001   2026-07-09     DHL     TRK004      Delivered    2026-07-10      Complete  2026-07-08         admin  2026-07-10          admin
4             SH005                SO005                 WH002   2026-07-10  Aramex     TRK005      Delivered    2026-07-11      Complete  2026-07-09         admin  2026-07-11          admin

## 1.4 Data Profiling

Profile the untouched raw Shipment dataset using the reusable `data_profiler_v1` tool.

The profiler is used to identify potential data-quality issues, semantic field types, missing values, duplicates, formatting inconsistencies, and other detectable anomalies before any cleaning or transformation is performed.

The Shipment dataset will be profiled as a single source dataset before any transformation takes place.

Profiling results are treated as findings for investigation. The profiler does not make business decisions or automatically determine the correct transformation.

In [7]:
# =========================================================
# 1.4 Data Profiling
# =========================================================

import sys
import importlib


# Identify the project root
project_root = Path.cwd().parent


# Add the project root to the Python path if needed
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))


# Import and reload the reusable data profiler
from profiler import data_profiler_v1 as profiler

importlib.reload(profiler)


print("Profiler loaded successfully:")
print(profiler.__file__)


print("\nProfiler configuration:")
print(profiler.DEFAULT_CONFIG)

Profiler loaded successfully:
c:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\profiler\data_profiler_v1.py

Profiler configuration:
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

In [8]:
# Run the complete profiler against the untouched raw Shipment dataset

shipment_profile_results = profiler.profile_dataset(
    shipment_raw
)


print("\nShipment profiling completed successfully.")

print("\nShipment profiler sections:")
print(list(shipment_profile_results.keys()))

Shipment profiling completed successfully.

Shipment profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

## 1.5 Review Profiling Results

Review the complete Shipment profiling results before making any transformation decisions.

The automated profiler identifies potential data-quality issues, but the results must be independently reviewed in the context of the Shipment dataset and LJ Dev Commerce business requirements.

This review examines:

- Automated profiling findings

- Issues requiring independent analyst review

- Potential business-rule decisions

- Issues that may require transformation

The Shipment dataset will be reviewed as a single source dataset before any transformation takes place.

No data is modified during this stage.

In [9]:
# =========================================================
# 1.5 Review Profiling Results
# =========================================================

print("\n" + "=" * 70)
print("SHIPMENT PROFILING RESULTS")
print("=" * 70)

for section_name, section_result in shipment_profile_results.items():
    print("\n" + "-" * 70)
    print(section_name.upper())
    print("-" * 70)
    print(section_result)

======================================================================
SHIPMENT PROFILING RESULTS
======================================================================

----------------------------------------------------------------------
FIELD_TYPES
----------------------------------------------------------------------
ShipmentReference         identifier
SourceOrderReference      identifier
DispatchWarehouseCode     identifier
DispatchDate                    date
Courier                         text
TrackingNo                      text
TrackingStatus           categorical
DeliveredDate                   date
DeliveryNotes                   text
CreatedOn                       date
CreatedByUser            categorical
ModifiedOn                      date
ModifiedByUser           categorical
Name: DetectedFieldType, dtype: object

----------------------------------------------------------------------
DETECTION_DETAILS
----------------------------------------------------------------------
{'ShipmentReference': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'SourceOrderReference': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'DispatchWarehouseCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'DispatchDate': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'Courier': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'TrackingNo': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'TrackingStatus': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'DeliveredDate': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'DeliveryNotes': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'CreatedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'CreatedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}, 'ModifiedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'ModifiedByUser': {'DetectedType': 'categorical', 'Confidence': 'Medium', 'Evidence': 'Low unique-value ratio'}}

----------------------------------------------------------------------
GENERAL
----------------------------------------------------------------------
{'rows': 14, 'columns': 13, 'exact_duplicate_rows': 0, 'column_profile':                       DataType DetectedFieldType  MissingCount  MissingPercent  UniqueCount  DuplicateValueCount
ShipmentReference       object        identifier             0            0.00           14                    0
SourceOrderReference    object        identifier             0            0.00           14                    0
DispatchWarehouseCode   object        identifier             0            0.00            3                   11
DispatchDate            object              date             0            0.00           14                    0
Courier                 object              text             0            0.00            3                   11
TrackingNo              object              text             2           14.29           12                    1
TrackingStatus          object       categorical             0            0.00            2                   12
DeliveredDate           object              date             1            7.14           13                    0
DeliveryNotes           object              text             0            0.00            3                   11
CreatedOn               object              date             0            0.00           14                    0
CreatedByUser           object       categorical             0            0.00            1                   13
ModifiedOn              object              date             0            0.00           13                    1
ModifiedByUser          object       categorical             0            0.00            1                   13}

----------------------------------------------------------------------
TEXT
----------------------------------------------------------------------
{'Courier': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 3, 'MaximumLength': 6, 'AverageLength': np.float64(4.43)}, 'TrackingNo': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 6, 'MaximumLength': 6, 'AverageLength': np.float64(6.0)}, 'DeliveryNotes': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 8, 'MaximumLength': 20, 'AverageLength': np.float64(9.86)}}

----------------------------------------------------------------------
CATEGORICAL
----------------------------------------------------------------------
{'TrackingStatus': {'UniqueCount': 2, 'MostCommonValue': 'Delivered', 'MostCommonCount': 13, 'CategoryDistribution': {'Delivered': 13, ' in transit ': 1}}, 'CreatedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 14, 'CategoryDistribution': {'admin': 14}}, 'ModifiedByUser': {'UniqueCount': 1, 'MostCommonValue': 'admin', 'MostCommonCount': 14, 'CategoryDistribution': {'admin': 14}}}

----------------------------------------------------------------------
NUMERIC
----------------------------------------------------------------------
{}

----------------------------------------------------------------------
DATE
----------------------------------------------------------------------
{'DispatchDate': {'ValidDateCount': 14, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-06 00:00:00'), 'MaximumDate': Timestamp('2026-07-21 00:00:00'), 'FutureDateCount': 0}, 'DeliveredDate': {'ValidDateCount': 13, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-07 00:00:00'), 'MaximumDate': Timestamp('2026-07-22 00:00:00'), 'FutureDateCount': 0}, 'CreatedOn': {'ValidDateCount': 14, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-05 00:00:00'), 'MaximumDate': Timestamp('2026-07-20 00:00:00'), 'FutureDateCount': 0}, 'ModifiedOn': {'ValidDateCount': 14, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-07 00:00:00'), 'MaximumDate': Timestamp('2026-07-22 00:00:00'), 'FutureDateCount': 0}}

----------------------------------------------------------------------
PATTERNS
----------------------------------------------------------------------
{'email': {}, 'phone': {}, 'identifier': {'ShipmentReference': {'UniqueCount': 14, 'DuplicateCount': 0, 'MissingCount': 0}, 'SourceOrderReference': {'UniqueCount': 14, 'DuplicateCount': 0, 'MissingCount': 0}, 'DispatchWarehouseCode': {'UniqueCount': 3, 'DuplicateCount': 11, 'MissingCount': 0}}}

----------------------------------------------------------------------
ISSUES
----------------------------------------------------------------------
                  Column            IssueType Severity  Count                           Description
0  DispatchWarehouseCode  DuplicateIdentifier     High     11  Repeated identifier values detected.
1          DeliveredDate        MissingValues   Medium      1              Missing values detected.
2             TrackingNo        MissingValues   Medium      2              Missing values detected.

----------------------------------------------------------------------
CONFIGURATION
----------------------------------------------------------------------
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

## 1.6 Review Profiler Issues

Review the issues identified by the automated profiler for the Shipment dataset.

The full profiling output provides a broad assessment of the untouched raw Shipment dataset. This step focuses specifically on the detected issues so they can be investigated before any transformation decisions are made.

Profiler findings are treated as indicators for review and do not automatically determine the correct transformation.

The Shipment dataset will be reviewed as a single source, and identified issues will be evaluated against the Shipment Data Dictionary and LJ Dev Commerce business requirements.

In [10]:
# =========================================================
# 1.6 Review Profiler Issues
# =========================================================

shipment_issues=shipment_profile_results["issues"]
print("\n" + "=" * 70)
print("SHIPMENT PROFILER ISSUES")
print("=" * 70)
display(shipment_issues)

======================================================================
SHIPMENT PROFILER ISSUES
======================================================================

                  Column            IssueType Severity  Count                           Description
0  DispatchWarehouseCode  DuplicateIdentifier     High     11  Repeated identifier values detected.
1          DeliveredDate        MissingValues   Medium      1              Missing values detected.
2             TrackingNo        MissingValues   Medium      2              Missing values detected.

## 1.7 Independent Analyst Review

Perform a systematic independent analyst review of the untouched raw Shipment dataset.

This section is the notebook-based version of the Pre-ETL Inspection.

The review goes beyond the automated profiler and checks the Shipment dataset using independent analyst validation relevant to its business meaning and approved ETL design.

The review covers, where applicable:

- Dataset structure and grain

- Missing and blank values

- Exact duplicate rows

- Primary-key candidates and key uniqueness

- Parent order relationship and shipment-to-order consistency

- Whitespace in text fields

- Text consistency

- Shipment method and shipment status consistency

- Numeric validity and statistical outlier candidates

- Shipment amount and shipment status business-rule consistency

- Date parsing, datatype, validity, and Created/Modified date consistency

- Source-to-target datatype compatibility considerations

- Shipment relationship values

Automated profiler findings and independent analyst findings are kept conceptually separate.

The Shipment dataset is reviewed independently before any transformation.

No data is modified in this section.

In [11]:
# =========================================================
# 1.7 Independent Analyst Review
# =========================================================

source_df = shipment_raw

print("1. DATASET STRUCTURE AND GRAIN")
print("=" * 80)
print(f"Rows: {source_df.shape[0]}")
print(f"Columns: {source_df.shape[1]}")
print("Working assumption: One row represents one shipment record.")

print("\n\n2. MISSING VALUES AND BLANK VALUES")
print("=" * 80)
missing_values = source_df.isna().sum()
blank_values = pd.Series({
    column: (source_df[column].astype("string").str.strip().eq("").sum()
             if source_df[column].dtype == "object" else 0)
    for column in source_df.columns
})
display(pd.DataFrame({"MissingValues": missing_values, "BlankValues": blank_values}))

print("\n\n3. EXACT DUPLICATE ROWS")
print("=" * 80)
exact_duplicate_count = source_df.duplicated().sum()
print("Shipment - Exact duplicate rows:", exact_duplicate_count)
if exact_duplicate_count > 0:
    display(source_df[source_df.duplicated(keep=False)])

print("\n\n4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS")
print("=" * 80)
identifier_columns = ["ShipmentReference", "SourceOrderReference", "DispatchWarehouseCode"]
identifier_review = pd.DataFrame({
    "Column": identifier_columns,
    "NullCount": [source_df[c].isna().sum() for c in identifier_columns],
    "BlankCount": [source_df[c].astype("string").str.strip().eq("").sum() for c in identifier_columns],
    "DuplicateCount": [source_df[c].duplicated().sum() for c in identifier_columns],
    "UniqueValues": [source_df[c].nunique(dropna=True) for c in identifier_columns]
})
display(identifier_review)

print("\n\n5. SHIPMENT IDENTIFIER COLLISION REVIEW")
print("=" * 80)
duplicates = source_df[source_df["ShipmentReference"].duplicated(keep=False)]
print("Duplicate ShipmentReference records:", len(duplicates))
if not duplicates.empty:
    display(duplicates)

print("\n\n6. PARENT ORDER / WAREHOUSE RELATIONSHIP REVIEW")
print("=" * 80)
print("Distinct SourceOrderReference values:", source_df["SourceOrderReference"].nunique())
print("Distinct DispatchWarehouseCode values:", source_df["DispatchWarehouseCode"].nunique())
print("\nShipment records by source order:")
display(source_df.groupby("SourceOrderReference").size().reset_index(name="ShipmentCount").sort_values("ShipmentCount", ascending=False))
print("\nShipment records by warehouse:")
display(source_df.groupby("DispatchWarehouseCode").size().reset_index(name="ShipmentCount").sort_values("ShipmentCount", ascending=False))

print("\n\n7. LEADING AND TRAILING WHITESPACE REVIEW")
print("=" * 80)
text_columns = source_df.select_dtypes(include="object").columns
whitespace_findings=[]
for column in text_columns:
    mask=source_df[column].astype("string") != source_df[column].astype("string").str.strip()
    count=mask.sum()
    if count>0:
        whitespace_findings.append({"Column":column,"WhitespaceRecordCount":count})
        display(source_df.loc[mask,["ShipmentReference",column]])
if whitespace_findings:
    display(pd.DataFrame(whitespace_findings))
else:
    print("No leading or trailing whitespace found.")

print("\n\n8. TEXT / STATUS CONSISTENCY REVIEW")
print("=" * 80)
for column in ["Courier","TrackingStatus","DeliveryNotes","CreatedByUser","ModifiedByUser"]:
    print(f"\n{column} values:")
    display(source_df[column].value_counts(dropna=False).sort_index().rename("RecordCount").to_frame())

print("\n\n9. TRACKING NUMBER OPTIONALITY REVIEW")
print("=" * 80)
missing_tracking=source_df[source_df["TrackingNo"].isna()]
print("NULL TrackingNo records:",len(missing_tracking))
if not missing_tracking.empty:
    display(missing_tracking[["ShipmentReference","TrackingNo","DeliveryNotes"]])

print("\n\n10. DATE VALIDITY AND DATATYPE REVIEW")
print("=" * 80)
date_columns=["DispatchDate","DeliveredDate","CreatedOn","ModifiedOn"]
for column in date_columns:
    parsed=pd.to_datetime(source_df[column],errors="coerce")
    invalid=(parsed.isna() & source_df[column].notna()).sum()
    print(f"{column}: pandas dtype={source_df[column].dtype}, invalid populated dates={invalid}")

print("\n\n11. DATE RELATIONSHIP REVIEW")
print("=" * 80)
dispatch=pd.to_datetime(source_df["DispatchDate"],errors="coerce")
delivered=pd.to_datetime(source_df["DeliveredDate"],errors="coerce")
created=pd.to_datetime(source_df["CreatedOn"],errors="coerce")
modified=pd.to_datetime(source_df["ModifiedOn"],errors="coerce")
status=source_df["TrackingStatus"].astype("string").str.strip()
print("Delivered before DispatchDate:",(delivered.notna() & dispatch.notna() & (delivered<dispatch)).sum())
print("CreatedOn after DispatchDate:",(created.notna() & dispatch.notna() & (created>dispatch)).sum())
print("ModifiedOn before CreatedOn:",(modified.notna() & created.notna() & (modified<created)).sum())
print("Delivered shipments without DeliveredDate:",(status.eq("Delivered") & delivered.isna()).sum())
print("Non-delivered shipments with DeliveredDate",((~status.eq("Delivered")) & delivered.notna()).sum())

print("\n\n12. STATUS / DELIVERY-DATE BUSINESS RULE REVIEW")
print("=" * 80)
print("Observed trimmed shipment statuses:", sorted(status.dropna().unique().tolist()))
display(source_df.loc[source_df["ShipmentReference"].eq("SH013"),["ShipmentReference","TrackingStatus","DeliveredDate","DeliveryNotes"]])

print("\n\n13. SOURCE-TO-TARGET DATATYPE PREPARATION REVIEW")
print("=" * 80)
datatype_review=pd.DataFrame([
    ["ShipmentReference",str(source_df["ShipmentReference"].dtype),"Text","Retain"],
    ["SourceOrderReference",str(source_df["SourceOrderReference"].dtype),"Text","Retain"],
    ["DispatchWarehouseCode",str(source_df["DispatchWarehouseCode"].dtype),"Text","Retain"],
    ["DispatchDate",str(source_df["DispatchDate"].dtype),"Datetime","Convert"],
    ["Courier",str(source_df["Courier"].dtype),"Text","Retain"],
    ["TrackingNo",str(source_df["TrackingNo"].dtype),"Text","Preserve NULL"],
    ["TrackingStatus",str(source_df["TrackingStatus"].dtype),"Text","Trim + standardize"],
    ["DeliveredDate",str(source_df["DeliveredDate"].dtype),"Datetime","Convert; preserve NULL"],
    ["DeliveryNotes",str(source_df["DeliveryNotes"].dtype),"Text","Retain"],
    ["CreatedOn",str(source_df["CreatedOn"].dtype),"Datetime","Convert"],
    ["CreatedByUser",str(source_df["CreatedByUser"].dtype),"Text","Retain"],
    ["ModifiedOn",str(source_df["ModifiedOn"].dtype),"Datetime","Convert"],
    ["ModifiedByUser",str(source_df["ModifiedByUser"].dtype),"Text","Retain"]
],columns=["SourceColumn","CurrentPandasDtype","TargetType","Preparation"])
display(datatype_review)

print("\nIndependent analyst review completed.")

1. DATASET STRUCTURE AND GRAIN
================================================================================
Rows: 14
Columns: 13
Working assumption: One row represents one shipment record.


2. MISSING VALUES AND BLANK VALUES
================================================================================

                       MissingValues  BlankValues
ShipmentReference                  0            0
SourceOrderReference               0            0
DispatchWarehouseCode              0            0
DispatchDate                       0            0
Courier                            0            0
TrackingNo                         2            0
TrackingStatus                     0            0
DeliveredDate                      1            0
DeliveryNotes                      0            0
CreatedOn                          0            0
CreatedByUser                      0            0
ModifiedOn                         0            0
ModifiedByUser                     0            0

3. EXACT DUPLICATE ROWS
================================================================================
Shipment - Exact duplicate rows: 0


4. PRIMARY KEY CANDIDATE AND IDENTIFIER UNIQUENESS
================================================================================

                  Column  NullCount  BlankCount  DuplicateCount  UniqueValues
0      ShipmentReference          0           0               0            14
1   SourceOrderReference          0           0               0            14
2  DispatchWarehouseCode          0           0              11             3

5. SHIPMENT IDENTIFIER COLLISION REVIEW
================================================================================
Duplicate ShipmentReference records: 0


6. PARENT ORDER / WAREHOUSE RELATIONSHIP REVIEW
================================================================================
Distinct SourceOrderReference values: 14
Distinct DispatchWarehouseCode values: 3

Shipment records by source order:

   SourceOrderReference  ShipmentCount
0                 SO001              1
1                 SO002              1
2                 SO003              1
3                 SO004              1
4                 SO005              1
5                 SO007              1
6                 SO008              1
7                 SO009              1
8                 SO011              1
9                 SO012              1
10                SO013              1
11                SO014              1
12                SO015              1
13                SO016              1

Shipment records by warehouse:

  DispatchWarehouseCode  ShipmentCount
0                 WH001              9
1                 WH002              3
2                 WH003              2

7. LEADING AND TRAILING WHITESPACE REVIEW
================================================================================

   ShipmentReference TrackingStatus
12             SH013    in transit

           Column  WhitespaceRecordCount
0  TrackingStatus                      1

8. TEXT / STATUS CONSISTENCY REVIEW
================================================================================

Courier values:

         RecordCount
Courier
Aramex             4
DHL                6
FedEx              4

TrackingStatus values:

                RecordCount
TrackingStatus
 in transit               1
Delivered                13

DeliveryNotes values:

                      RecordCount
DeliveryNotes
Complete                       11
In transit                      1
Tracking unavailable            2

CreatedByUser values:

               RecordCount
CreatedByUser
admin                   14

ModifiedByUser values:

                RecordCount
ModifiedByUser
admin                    14

9. TRACKING NUMBER OPTIONALITY REVIEW
================================================================================
NULL TrackingNo records: 2

   ShipmentReference TrackingNo         DeliveryNotes
6              SH007        NaN  Tracking unavailable
11             SH012        NaN  Tracking unavailable

10. DATE VALIDITY AND DATATYPE REVIEW
================================================================================
DispatchDate: pandas dtype=object, invalid populated dates=0
DeliveredDate: pandas dtype=object, invalid populated dates=0
CreatedOn: pandas dtype=object, invalid populated dates=0
ModifiedOn: pandas dtype=object, invalid populated dates=0


11. DATE RELATIONSHIP REVIEW
================================================================================
Delivered before DispatchDate: 0
CreatedOn after DispatchDate: 0
ModifiedOn before CreatedOn: 0
Delivered shipments without DeliveredDate: 0
Non-delivered shipments with DeliveredDate 0


12. STATUS / DELIVERY-DATE BUSINESS RULE REVIEW
================================================================================
Observed trimmed shipment statuses: ['Delivered', 'in transit']

   ShipmentReference TrackingStatus DeliveredDate DeliveryNotes
12             SH013    in transit            NaN    In transit

13. SOURCE-TO-TARGET DATATYPE PREPARATION REVIEW
================================================================================

             SourceColumn CurrentPandasDtype TargetType             Preparation
0       ShipmentReference             object       Text                  Retain
1    SourceOrderReference             object       Text                  Retain
2   DispatchWarehouseCode             object       Text                  Retain
3            DispatchDate             object   Datetime                 Convert
4                 Courier             object       Text                  Retain
5              TrackingNo             object       Text           Preserve NULL
6          TrackingStatus             object       Text      Trim + standardize
7           DeliveredDate             object   Datetime  Convert; preserve NULL
8           DeliveryNotes             object       Text                  Retain
9               CreatedOn             object   Datetime                 Convert
10          CreatedByUser             object       Text                  Retain
11             ModifiedOn             object   Datetime                 Convert
12         ModifiedByUser             object       Text                  Retain

Independent analyst review completed.

## 1.8 Findings and Transformation Decisions

Compare the automated profiler findings, Independent Analyst Review findings, current Shipment Data Dictionary, Source → Target Mapping, Relationship Map, and the approved Final Pre-ETL Decision.

Approved decisions:

- Keep all 14 shipment records.
- Preserve ShipmentReference as shipment_id.
- Preserve SourceOrderReference and DispatchWarehouseCode.
- Preserve legitimate NULL TrackingNo values for SH007 and SH012.
- Trim whitespace from TrackingStatus and standardize SH013 to `In Transit`.
- Convert DispatchDate, DeliveredDate, CreatedOn, and ModifiedOn to datetime.
- Preserve SH013 DeliveredDate as NULL.
- `delivery_date` is Optional.
- Delivered shipments must have a delivery date.
- In Transit shipments may have a NULL delivery date.
- No records are deleted.

In [12]:
# =========================================================
# 1.8 Findings and Transformation Decisions
# =========================================================

transformation_decisions = pd.DataFrame([
    ["ShipmentReference uniqueness",14,"Valid value — retain unchanged","Use as shipment_id","Approved shipment identifier."],
    ["No exact duplicate rows",0,"Valid value — retain unchanged","Keep all 14 records","No duplicate rows were identified."],
    ["TrackingNo NULL for SH007 and SH012",2,"Expected business behavior","Preserve NULLs","tracking_number is Optional."],
    ["SH013 TrackingStatus = ' in transit'",1,"Safe deterministic transformation","Trim and standardize to 'In Transit'","Approved final decision."],
    ["SH013 DeliveredDate = NULL",1,"Approved business rule","Preserve NULL","SH013 is In Transit; no delivery date may be invented."],
    ["DispatchDate object dtype",14,"Safe deterministic transformation","Convert to datetime","Target shipment_date is Datetime."],
    ["DeliveredDate object dtype",13,"Safe deterministic transformation","Convert to datetime; preserve NULL","Target delivery_date is Optional Datetime."],
    ["CreatedOn object dtype",14,"Safe deterministic transformation","Convert to datetime","Target created_date is Datetime."],
    ["ModifiedOn object dtype",14,"Safe deterministic transformation","Convert to datetime","Target updated_date is Datetime."],
    ["Date relationships valid",0,"Valid value — retain unchanged","Preserve values after datatype conversion","No invalid date ordering found."],
    ["Shipment → Sales Order relationship",14,"Requires relationship validation later","Validate against commerce.sales_order","sales_order_id is an FK."],
    ["Shipment → Warehouse relationship",14,"Requires relationship validation later","Validate against commerce.warehouse","warehouse_id is an FK."]
],columns=["Finding","AffectedRecords","Decision","ApprovedAction","Reason"])

display(transformation_decisions)
print("Shipment transformation decisions recorded. Status: READY FOR TRANSFORMATION")

                                 Finding  AffectedRecords                                Decision                             ApprovedAction                                                  Reason
0           ShipmentReference uniqueness               14          Valid value — retain unchanged                         Use as shipment_id                           Approved shipment identifier.
1                No exact duplicate rows                0          Valid value — retain unchanged                        Keep all 14 records                      No duplicate rows were identified.
2    TrackingNo NULL for SH007 and SH012                2              Expected business behavior                             Preserve NULLs                            tracking_number is Optional.
3   SH013 TrackingStatus = ' in transit'                1       Safe deterministic transformation       Trim and standardize to 'In Transit'                                Approved final decision.
4             SH013 DeliveredDate = NULL                1                  Approved business rule                              Preserve NULL  SH013 is In Transit; no delivery date may be invented.
5              DispatchDate object dtype               14       Safe deterministic transformation                        Convert to datetime                       Target shipment_date is Datetime.
6             DeliveredDate object dtype               13       Safe deterministic transformation         Convert to datetime; preserve NULL              Target delivery_date is Optional Datetime.
7                 CreatedOn object dtype               14       Safe deterministic transformation                        Convert to datetime                        Target created_date is Datetime.
8                ModifiedOn object dtype               14       Safe deterministic transformation                        Convert to datetime                        Target updated_date is Datetime.
9               Date relationships valid                0          Valid value — retain unchanged  Preserve values after datatype conversion                         No invalid date ordering found.
10   Shipment → Sales Order relationship               14  Requires relationship validation later      Validate against commerce.sales_order                                sales_order_id is an FK.
11     Shipment → Warehouse relationship               14  Requires relationship validation later        Validate against commerce.warehouse                                  warehouse_id is an FK.

Shipment transformation decisions recorded. Status: READY FOR TRANSFORMATION

# =========================================================
# SECTION 2 — DATA TRANSFORMATION
# =========================================================

## 2.1 Create Clean Working Dataset

Create a separate working copy of the raw Shipment dataset before applying any approved transformations.

The raw Shipment dataset must remain unchanged throughout the ETL process.

All transformations will be applied only to the clean working dataset.

The Shipment source dataset will remain as a single working dataset during this step.

In [13]:
# =========================================================
# 2.1 Create Clean Working Dataset
# =========================================================

shipment_clean=shipment_raw.copy()

print("Clean working dataset created successfully.")
print("Shipment raw rows:",shipment_raw.shape[0])
print("Shipment clean rows:",shipment_clean.shape[0])
print("Raw and clean datasets are separate objects:",shipment_raw is not shipment_clean)

Clean working dataset created successfully.
Shipment raw rows: 14
Shipment clean rows: 14
Raw and clean datasets are separate objects: True

## 2.2 Apply Approved Transformations

Apply only the transformations approved in Section 1.8 to the clean working Shipment dataset.

Approved transformations:

- Trim leading/trailing whitespace from `TrackingStatus`.
- Standardize SH013 `TrackingStatus` to `In Transit`.
- Convert `DispatchDate`, `DeliveredDate`, `CreatedOn`, and `ModifiedOn` to datetime.
- Preserve legitimate NULL `TrackingNo` values.
- Preserve SH013 `DeliveredDate` as NULL.

No other business values are modified.

In [14]:
# =========================================================
# 2.2 Apply Approved Transformations
# =========================================================

shipment_clean["TrackingStatus"] = shipment_clean["TrackingStatus"].astype("string").str.strip()
shipment_clean["TrackingStatus"] = shipment_clean["TrackingStatus"].replace({"in transit":"In Transit"})

for column in ["DispatchDate","DeliveredDate","CreatedOn","ModifiedOn"]:
    shipment_clean[column] = pd.to_datetime(shipment_clean[column], errors="raise")

# TrackingNo NULL values are intentionally preserved.

print("Approved Shipment transformations applied.")

Approved Shipment transformations applied.

## 3.1 Transformation Validation

Validate every approved Shipment transformation from Section 1.8.

Checks include status standardization, datetime conversion, preservation of legitimate TrackingNo NULLs, preservation of SH013 delivery-date NULL, and approved shipment business rules.

In [15]:
# =========================================================
# 3.1 Transformation Validation
# =========================================================

allowed_statuses={"Delivered","In Transit"}
status_valid=set(shipment_clean["TrackingStatus"].dropna().unique()) <= allowed_statuses
sh013=shipment_clean.loc[shipment_clean["ShipmentReference"].eq("SH013")]
sh013_status_valid=(len(sh013)==1 and sh013.iloc[0]["TrackingStatus"]=="In Transit")
sh013_delivery_null=(len(sh013)==1 and pd.isna(sh013.iloc[0]["DeliveredDate"]))
datetime_valid=all(pd.api.types.is_datetime64_any_dtype(shipment_clean[c]) for c in ["DispatchDate","DeliveredDate","CreatedOn","ModifiedOn"])
tracking_null_ids=set(shipment_clean.loc[shipment_clean["TrackingNo"].isna(),"ShipmentReference"])
tracking_nulls_valid=(tracking_null_ids=={"SH007","SH012"})

print("Shipment Transformation Validation")
print("Status values valid:",status_valid)
print("SH013 standardized to In Transit:",sh013_status_valid)
print("Datetime fields valid:",datetime_valid)
print("SH013 DeliveredDate remains NULL:",sh013_delivery_null)
print("Tracking NULLs preserved:",tracking_nulls_valid)
transformation_validation_passed=all([status_valid,sh013_status_valid,datetime_valid,sh013_delivery_null,tracking_nulls_valid])
print("Overall transformation validation passed:",transformation_validation_passed)

Shipment Transformation Validation
Status values valid: True
SH013 standardized to In Transit: True
Datetime fields valid: True
SH013 DeliveredDate remains NULL: True
Tracking NULLs preserved: True
Overall transformation validation passed: True

## 3.2 Validate Data Preservation

Validate that the approved Shipment transformations did not unintentionally alter unaffected source data.

The raw and clean datasets are compared while accounting for the approved status and datatype transformations.

In [16]:
# =========================================================
# 3.2 Validate Data Preservation
# =========================================================

preserved_columns=["ShipmentReference","SourceOrderReference","DispatchWarehouseCode","Courier","TrackingNo","DeliveryNotes","CreatedByUser","ModifiedByUser"]
row_count_preserved=len(shipment_clean)==len(shipment_raw)
column_structure_preserved=shipment_clean.columns.tolist()==shipment_raw.columns.tolist()
preservation_results={c: shipment_clean[c].astype("string").equals(shipment_raw[c].astype("string")) for c in preserved_columns}
preserved_values_valid=all(preservation_results.values())
shipment_ids_preserved=shipment_clean["ShipmentReference"].tolist()==shipment_raw["ShipmentReference"].tolist()
data_preservation_passed=all([row_count_preserved,column_structure_preserved,preserved_values_valid,shipment_ids_preserved])

display(pd.Series(preservation_results,name="Preserved"))
print("Row count preserved:",row_count_preserved)
print("Column structure preserved:",column_structure_preserved)
print("Shipment IDs preserved:",shipment_ids_preserved)
print("Unchanged values preserved:",preserved_values_valid)
print("Overall data preservation validation passed:",data_preservation_passed)

ShipmentReference        True
SourceOrderReference     True
DispatchWarehouseCode    True
Courier                  True
TrackingNo               True
DeliveryNotes            True
CreatedByUser            True
ModifiedByUser           True
Name: Preserved, dtype: bool

Row count preserved: True
Column structure preserved: True
Shipment IDs preserved: True
Unchanged values preserved: True
Overall data preservation validation passed: True

# =========================================================
# SECTION 4 — CLEAN CSV
# =========================================================

In [18]:
# =========================================================
# 4.1 Export Clean Shipment Dataset
# =========================================================

shipment_clean_dir = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\10_Courier_Systems\clean"
)

shipment_clean_dir.mkdir(parents=True, exist_ok=True)

shipment_clean_path = shipment_clean_dir / "courier_shipments_clean.csv"

shipment_clean.to_csv(
    shipment_clean_path,
    index=False
)

print("Clean Shipment CSV exported successfully.")
print("Path:", shipment_clean_path)
print("Rows:", len(shipment_clean))
print("Columns:", len(shipment_clean.columns))

Clean Shipment CSV exported successfully.
Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\10_Courier_Systems\clean\courier_shipments_clean.csv
Rows: 14
Columns: 13

## 4.2 Verify Exported Clean Shipment CSV

Reload the exported clean Shipment CSV and verify that it matches the validated clean Shipment DataFrame.

The Clean CSV is the official handoff artifact for the Database-Ready stage.

In [19]:
# =========================================================
# 4.2 Verify Exported Clean Shipment CSV
# =========================================================

shipment_clean_csv=pd.read_csv(shipment_clean_path)
row_count_match=len(shipment_clean_csv)==len(shipment_clean)
column_structure_match=shipment_clean_csv.columns.tolist()==shipment_clean.columns.tolist()
print("Shipment Clean CSV read-back successful.")
print("Rows:",len(shipment_clean_csv))
print("Columns:",len(shipment_clean_csv.columns))
print("Row count matches:",row_count_match)
print("Column structure matches:",column_structure_match)
display(shipment_clean_csv.head())

Shipment Clean CSV read-back successful.
Rows: 14
Columns: 13
Row count matches: True
Column structure matches: True

  ShipmentReference SourceOrderReference DispatchWarehouseCode DispatchDate Courier TrackingNo TrackingStatus DeliveredDate DeliveryNotes   CreatedOn CreatedByUser  ModifiedOn ModifiedByUser
0             SH001                SO001                 WH001   2026-07-06     DHL     TRK001      Delivered    2026-07-07      Complete  2026-07-05         admin  2026-07-07          admin
1             SH002                SO002                 WH001   2026-07-07  Aramex     TRK002      Delivered    2026-07-08      Complete  2026-07-06         admin  2026-07-08          admin
2             SH003                SO003                 WH002   2026-07-08   FedEx     TRK003      Delivered    2026-07-09      Complete  2026-07-07         admin  2026-07-09          admin
3             SH004                SO004                 WH001   2026-07-09     DHL     TRK004      Delivered    2026-07-10      Complete  2026-07-08         admin  2026-07-10          admin
4             SH005                SO005                 WH002   2026-07-10  Aramex     TRK005      Delivered    2026-07-11      Complete  2026-07-09         admin  2026-07-11          admin

# =========================================================
# SECTION 5 — DATABASE READY
# =========================================================

In [20]:
# =========================================================
# 5.1 Define Source → Target Mapping
# =========================================================

shipment_mapping=pd.DataFrame([
    ["ShipmentReference","shipment_id","TEXT","Required","PK",""],
    ["SourceOrderReference","sales_order_id","TEXT","Required","FK","commerce.sales_order.sales_order_id"],
    ["DispatchWarehouseCode","warehouse_id","TEXT","Required","FK","commerce.warehouse.warehouse_id"],
    ["DispatchDate","shipment_date","TIMESTAMP","Required","",""],
    ["Courier","courier_name","TEXT","Required","",""],
    ["TrackingNo","tracking_number","TEXT","Optional","",""],
    ["TrackingStatus","shipment_status","TEXT","Required","","Delivered / In Transit"],
    ["DeliveredDate","delivery_date","TIMESTAMP","Optional","",""],
    ["DeliveryNotes","notes","TEXT","Optional","",""],
    ["CreatedOn","created_date","TIMESTAMP","Required","",""],
    ["CreatedByUser","created_by","TEXT","Required","",""],
    ["ModifiedOn","updated_date","TIMESTAMP","Required","",""],
    ["ModifiedByUser","updated_by","TEXT","Required","",""]
],columns=["Source Column","Target Column","Target Datatype","Required","Key Role","Reference / Rule"])
display(shipment_mapping)

            Source Column    Target Column Target Datatype  Required Key Role                     Reference / Rule
0       ShipmentReference      shipment_id            TEXT  Required       PK
1    SourceOrderReference   sales_order_id            TEXT  Required       FK  commerce.sales_order.sales_order_id
2   DispatchWarehouseCode     warehouse_id            TEXT  Required       FK      commerce.warehouse.warehouse_id
3            DispatchDate    shipment_date       TIMESTAMP  Required
4                 Courier     courier_name            TEXT  Required
5              TrackingNo  tracking_number            TEXT  Optional
6          TrackingStatus  shipment_status            TEXT  Required                        Delivered / In Transit
7           DeliveredDate    delivery_date       TIMESTAMP  Optional
8           DeliveryNotes            notes            TEXT  Optional
9               CreatedOn     created_date       TIMESTAMP  Required
10          CreatedByUser       created_by            TEXT  Required
11             ModifiedOn     updated_date       TIMESTAMP  Required
12         ModifiedByUser       updated_by            TEXT  Required

## 5.2 Create Database-Ready Dataset

Create the Shipment Database-Ready dataset from the verified exported Clean Shipment CSV.

Apply the approved source-to-target mapping, target column order, datatypes, nullability, and database-specific requirements.

In [21]:
# =========================================================
# 5.2 Create Database-Ready Shipment Dataset FROM EXPORTED CSV
# =========================================================

shipment_db_source=pd.read_csv(shipment_clean_path,parse_dates=["DispatchDate","DeliveredDate","CreatedOn","ModifiedOn"])
shipment_db_ready=shipment_db_source.rename(columns={
    "ShipmentReference":"shipment_id","SourceOrderReference":"sales_order_id","DispatchWarehouseCode":"warehouse_id",
    "DispatchDate":"shipment_date","Courier":"courier_name","TrackingNo":"tracking_number","TrackingStatus":"shipment_status",
    "DeliveredDate":"delivery_date","DeliveryNotes":"notes","CreatedOn":"created_date","CreatedByUser":"created_by",
    "ModifiedOn":"updated_date","ModifiedByUser":"updated_by"
})[["shipment_id","sales_order_id","warehouse_id","shipment_date","courier_name","tracking_number","shipment_status","delivery_date","notes","created_date","created_by","updated_date","updated_by"]].copy()

print("Shipment Database-Ready dataset created from exported Clean CSV.")
print("Rows:",len(shipment_db_ready))
print("Columns:",len(shipment_db_ready.columns))
display(shipment_db_ready.head())

Shipment Database-Ready dataset created from exported Clean CSV.
Rows: 14
Columns: 13

  shipment_id sales_order_id warehouse_id shipment_date courier_name tracking_number shipment_status delivery_date     notes created_date created_by updated_date updated_by
0       SH001          SO001        WH001    2026-07-06          DHL          TRK001       Delivered    2026-07-07  Complete   2026-07-05      admin   2026-07-07      admin
1       SH002          SO002        WH001    2026-07-07       Aramex          TRK002       Delivered    2026-07-08  Complete   2026-07-06      admin   2026-07-08      admin
2       SH003          SO003        WH002    2026-07-08        FedEx          TRK003       Delivered    2026-07-09  Complete   2026-07-07      admin   2026-07-09      admin
3       SH004          SO004        WH001    2026-07-09          DHL          TRK004       Delivered    2026-07-10  Complete   2026-07-08      admin   2026-07-10      admin
4       SH005          SO005        WH002    2026-07-10       Aramex          TRK005       Delivered    2026-07-11  Complete   2026-07-09      admin   2026-07-11      admin

## 5.3 Database-Ready Validation

Validate the Shipment Database-Ready DataFrame before PostgreSQL loading.

Confirm row count, target columns/order, target-compatible datatypes, required fields, nullable optional fields, primary-key uniqueness, foreign-key readiness, mapping completeness, and the conditional delivery-date business rule.

In [22]:
# =========================================================
# 5.3 Database-Ready Validation
# =========================================================

expected_target_columns=["shipment_id","sales_order_id","warehouse_id","shipment_date","courier_name","tracking_number","shipment_status","delivery_date","notes","created_date","created_by","updated_date","updated_by"]
target_columns_match=shipment_db_ready.columns.tolist()==expected_target_columns
row_count_match=len(shipment_db_ready)==len(shipment_clean_csv)
required_fields=["shipment_id","sales_order_id","warehouse_id","shipment_date","courier_name","shipment_status","created_date","created_by","updated_date","updated_by"]
required_null_counts=shipment_db_ready[required_fields].isnull().sum()
required_fields_valid=required_null_counts.sum()==0
duplicate_primary_keys=shipment_db_ready["shipment_id"].duplicated().sum()
null_primary_keys=shipment_db_ready["shipment_id"].isnull().sum()
primary_key_valid=(duplicate_primary_keys==0 and null_primary_keys==0)
datetime_fields=["shipment_date","delivery_date","created_date","updated_date"]
datetime_fields_valid=all(pd.api.types.is_datetime64_any_dtype(shipment_db_ready[c]) for c in datetime_fields)
allowed_statuses={"Delivered","In Transit"}
status_values_valid=set(shipment_db_ready["shipment_status"].dropna().unique()) <= allowed_statuses
delivered_requires_date=shipment_db_ready.loc[shipment_db_ready["shipment_status"].eq("Delivered"),"delivery_date"].notna().all()
mapping_complete=set(shipment_mapping["Source Column"])==set(shipment_clean_csv.columns)

display(required_null_counts)
print("Target columns match:",target_columns_match)
print("Row count match:",row_count_match)
print("Required fields valid:",required_fields_valid)
print("Primary key valid:",primary_key_valid)
print("Datetime fields valid:",datetime_fields_valid)
print("Status values valid:",status_values_valid)
print("Delivered shipments have delivery dates:",delivered_requires_date)
print("Mapping complete:",mapping_complete)
database_ready_validation_passed=all([target_columns_match,row_count_match,required_fields_valid,primary_key_valid,datetime_fields_valid,status_values_valid,delivered_requires_date,mapping_complete])
print("Shipment Database-Ready validation passed:",database_ready_validation_passed)

shipment_id        0
sales_order_id     0
warehouse_id       0
shipment_date      0
courier_name       0
shipment_status    0
created_date       0
created_by         0
updated_date       0
updated_by         0
dtype: int64

Target columns match: True
Row count match: True
Required fields valid: True
Primary key valid: True
Datetime fields valid: True
Status values valid: True
Delivered shipments have delivery dates: True
Mapping complete: True
Shipment Database-Ready validation passed: True

# =========================================================
# SECTION 6 — PostgreSQL
# =========================================================

## 6.1 Connect

Establish a PostgreSQL connection for the Shipment ETL process.

Confirm the connection, database, user, and target schema before loading records.

In [23]:
# =========================================================
# 6.1 Connect to PostgreSQL
# =========================================================

import psycopg2
from getpass import getpass


# ---------------------------------------------------------
# PostgreSQL Connection Configuration
# ---------------------------------------------------------

DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "lj_dev_commerce"
DB_USER = "postgres"

DB_PASSWORD = getpass("Enter PostgreSQL password: ")


# ---------------------------------------------------------
# Connect to PostgreSQL
# ---------------------------------------------------------

try:
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD
    )

    cursor = conn.cursor()

    print("PostgreSQL connection successful.")
    print("Database:", DB_NAME)
    print("Host:", DB_HOST)
    print("Port:", DB_PORT)

except Exception as e:
    print("PostgreSQL connection failed.")
    print("Error:", e)

PostgreSQL connection successful.
Database: lj_dev_commerce
Host: localhost
Port: 5432

## 6.2 Prepare / Create Target Table

Check whether the approved PostgreSQL target table already exists before creating or modifying anything.

Target:

Schema: `commerce`

Table: `shipment`

The table must not be recreated blindly.

In [24]:
# =========================================================
# 6.2 Prepare / Create Target Table
# =========================================================

target_schema = "commerce"
target_table = "shipment"

# Check whether the target table already exists
cursor.execute("""
    SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = %s
          AND table_name = %s
    );
""", (target_schema, target_table))

table_exists = cursor.fetchone()[0]

print("Shipment Target Table Check")
print("=" * 80)

print("Schema:", target_schema)
print("Table:", target_table)
print("Table exists:", table_exists)

if table_exists:
    print("\nTarget table already exists.")
    print("The table will not be recreated.")
else:
    print("\nTarget table does not exist.")
    print("The approved database design must be used before creating it.")

Shipment Target Table Check
================================================================================
Schema: commerce
Table: shipment
Table exists: False

Target table does not exist.
The approved database design must be used before creating it.

## 6.2.1 Create Shipment Table

Create `commerce.shipment` only when the target table does not already exist.

The table follows the current Shipment Data Dictionary. `delivery_date` and `tracking_number` are nullable; required fields use `NOT NULL`; `shipment_id` is the Primary Key; `sales_order_id` and `warehouse_id` are Foreign Keys.

In [25]:
# =========================================================
# 6.2.1 Create Shipment Table
# =========================================================

if not table_exists:
    create_shipment_table_query="""
    CREATE TABLE commerce.shipment (
        shipment_id TEXT PRIMARY KEY,
        sales_order_id TEXT NOT NULL,
        warehouse_id TEXT NOT NULL,
        shipment_date TIMESTAMP NOT NULL,
        courier_name TEXT NOT NULL,
        tracking_number TEXT,
        shipment_status TEXT NOT NULL,
        delivery_date TIMESTAMP,
        notes TEXT,
        created_date TIMESTAMP NOT NULL,
        created_by TEXT NOT NULL,
        updated_date TIMESTAMP NOT NULL,
        updated_by TEXT NOT NULL,
        FOREIGN KEY (sales_order_id) REFERENCES commerce.sales_order(sales_order_id),
        FOREIGN KEY (warehouse_id) REFERENCES commerce.warehouse(warehouse_id)
    );
    """
    try:
        cursor.execute(create_shipment_table_query)
        conn.commit()
        print("Shipment table created successfully.")
    except Exception as e:
        conn.rollback()
        print("Shipment table creation failed.")
        print("Error:",e)
else:
    print("Shipment table already exists. Creation skipped.")

Shipment table created successfully.

## 6.3 Verify Shipment Table Structure

Verify the actual PostgreSQL structure of `commerce.shipment` against the approved Shipment Data Dictionary, including column order, datatypes, and NULL / NOT NULL rules.

In [26]:
# =========================================================
# 6.3 Verify Shipment Table Structure
# =========================================================

verify_shipment_table_query = """
SELECT
    ordinal_position,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'commerce'
  AND table_name = 'shipment'
ORDER BY ordinal_position;
"""

try:
    cursor.execute(verify_shipment_table_query)

    table_structure = cursor.fetchall()

    print("Shipment Table Structure")
    print("=" * 80)

    print(
        f"{'Position':<10}"
        f"{'Column Name':<25}"
        f"{'Data Type':<25}"
        f"{'Nullable':<12}"
        f"{'Default'}"
    )

    print("-" * 100)

    for row in table_structure:
        print(
            f"{row[0]:<10}"
            f"{row[1]:<25}"
            f"{row[2]:<25}"
            f"{row[3]:<12}"
            f"{row[4]}"
        )

except Exception as e:
    print("Shipment table structure verification failed.")
    print("Error:", e)

Shipment Table Structure
================================================================================
Position  Column Name              Data Type                Nullable    Default
----------------------------------------------------------------------------------------------------
1         shipment_id              text                     NO          None
2         sales_order_id           text                     NO          None
3         warehouse_id             text                     NO          None
4         shipment_date            timestamp without time zoneNO          None
5         courier_name             text                     NO          None
6         tracking_number          text                     YES         None
7         shipment_status          text                     NO          None
8         delivery_date            timestamp without time zoneYES         None
9         notes                    text                     YES         None
10        created_date             timestamp without time zoneNO          None
11        created_by               text                     NO          None
12        updated_date             timestamp without time zoneNO          None
13        updated_by               text                     NO          None

## 6.4 Verify Keys, Relationships & Load Dependencies

Verify the Shipment Primary Key, both approved Foreign Keys, referenced parent records, and load-order readiness before loading.

Relationships:
- `sales_order_id` → `commerce.sales_order.sales_order_id`
- `warehouse_id` → `commerce.warehouse.warehouse_id`

In [27]:
# =========================================================
# 6.4 Verify Keys, Relationships & Load Dependencies
# =========================================================

print("Shipment Keys, Relationships & Load Dependency Review")
print("="*80)

cursor.execute("""
SELECT tc.constraint_name,kcu.column_name
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
 ON tc.constraint_name=kcu.constraint_name AND tc.table_schema=kcu.table_schema
WHERE tc.table_schema='commerce' AND tc.table_name='shipment' AND tc.constraint_type='PRIMARY KEY';
""")
primary_keys=cursor.fetchall()
primary_key_valid=(len(primary_keys)==1 and primary_keys[0][1]=="shipment_id")
print("Primary Key:",primary_keys)
print("Primary Key validation passed:",primary_key_valid)

cursor.execute("""
SELECT tc.constraint_name,kcu.column_name,ccu.table_schema,ccu.table_name,ccu.column_name
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
 ON tc.constraint_name=kcu.constraint_name AND tc.table_schema=kcu.table_schema
JOIN information_schema.constraint_column_usage AS ccu
 ON ccu.constraint_name=tc.constraint_name AND ccu.table_schema=tc.table_schema
WHERE tc.table_schema='commerce' AND tc.table_name='shipment' AND tc.constraint_type='FOREIGN KEY'
ORDER BY kcu.column_name;
""")
foreign_keys=cursor.fetchall()
expected_foreign_keys={("sales_order_id","sales_order","sales_order_id"),("warehouse_id","warehouse","warehouse_id")}
actual_foreign_keys={(r[1],r[3],r[4]) for r in foreign_keys}
foreign_keys_valid=actual_foreign_keys==expected_foreign_keys
print("Foreign Keys:",foreign_keys)
print("Foreign Key validation passed:",foreign_keys_valid)

sales_order_ids=shipment_db_ready["sales_order_id"].dropna().unique().tolist()
warehouse_ids=shipment_db_ready["warehouse_id"].dropna().unique().tolist()

placeholders=",".join(["%s"]*len(sales_order_ids))
cursor.execute(f"SELECT sales_order_id FROM commerce.sales_order WHERE sales_order_id IN ({placeholders});",sales_order_ids)
existing_sales_order_ids={r[0] for r in cursor.fetchall()}
missing_sales_order_ids=set(sales_order_ids)-existing_sales_order_ids
sales_order_dependency_valid=len(missing_sales_order_ids)==0

placeholders=",".join(["%s"]*len(warehouse_ids))
cursor.execute(f"SELECT warehouse_id FROM commerce.warehouse WHERE warehouse_id IN ({placeholders});",warehouse_ids)
existing_warehouse_ids={r[0] for r in cursor.fetchall()}
missing_warehouse_ids=set(warehouse_ids)-existing_warehouse_ids
warehouse_dependency_valid=len(missing_warehouse_ids)==0

print("Missing Sales Order IDs:",missing_sales_order_ids)
print("Sales Order dependency ready:",sales_order_dependency_valid)
print("Missing Warehouse IDs:",missing_warehouse_ids)
print("Warehouse dependency ready:",warehouse_dependency_valid)

load_dependency_ready=all([primary_key_valid,foreign_keys_valid,sales_order_dependency_valid,warehouse_dependency_valid])
print("Shipment is ready for data loading:",load_dependency_ready)

Shipment Keys, Relationships & Load Dependency Review
================================================================================
Primary Key: [('shipment_pkey', 'shipment_id')]
Primary Key validation passed: True
Foreign Keys: [('shipment_sales_order_id_fkey', 'sales_order_id', 'commerce', 'sales_order', 'sales_order_id'), ('shipment_warehouse_id_fkey', 'warehouse_id', 'commerce', 'warehouse', 'warehouse_id')]
Foreign Key validation passed: True
Missing Sales Order IDs: set()
Sales Order dependency ready: True
Missing Warehouse IDs: set()
Warehouse dependency ready: True
Shipment is ready for data loading: True

## 6.5 Insert Shipment Records

Load the validated Shipment Database-Ready dataset into the verified `commerce.shipment` PostgreSQL table.

Before inserting, confirm the target table is empty, confirm the database-ready row count, insert only validated records, use the approved target column list, and commit only after successful insertion.

In [29]:
# =========================================================
# 6.5 Insert Shipment Records
# =========================================================

print("Shipment Record Loading")
print("="*80)

cursor.execute("SELECT COUNT(*) FROM commerce.shipment;")
existing_record_count=cursor.fetchone()[0]
target_table_empty=existing_record_count==0
db_ready_row_count=len(shipment_db_ready)

print("Existing records:",existing_record_count)
print("Target table is empty:",target_table_empty)
print("Database-ready records:",db_ready_row_count)

insert_shipment_query="""
INSERT INTO commerce.shipment (
    shipment_id,sales_order_id,warehouse_id,shipment_date,courier_name,
    tracking_number,shipment_status,delivery_date,notes,created_date,
    created_by,updated_date,updated_by
)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);
"""

try:
    if not target_table_empty:
        raise ValueError("Target table is not empty. Insertion stopped to prevent accidental duplicate loading.")

    records_to_insert=[]
    
    for row in shipment_db_ready.itertuples(index=False,name=None):
        cleaned_row=tuple(
            None if pd.isna(value) else value
            for value in row
        )
        records_to_insert.append(cleaned_row)

    if len(records_to_insert)!=db_ready_row_count:
        raise ValueError("Database-ready record count changed before insertion.")

    cursor.executemany(insert_shipment_query,records_to_insert)
    conn.commit()

    print("Shipment records inserted:",len(records_to_insert))
    print("Transaction committed successfully.")

except Exception as e:
    conn.rollback()
    print("Shipment record insertion failed.")
    print("Transaction rolled back.")
    print("Error:",e)

Shipment Record Loading
================================================================================
Existing records: 0
Target table is empty: True
Database-ready records: 14
Shipment records inserted: 14
Transaction committed successfully.

## 6.6 Validate Shipment Row Count

Compare the Database-Ready Shipment row count with the number of records currently stored in `commerce.shipment`.

In [30]:
# =========================================================
# 6.6 Validate Shipment Row Count
# =========================================================

# Expected row count from the Database-Ready dataset
db_ready_row_count = len(shipment_db_ready)


# Actual row count from PostgreSQL
cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.shipment;
""")

postgresql_row_count = cursor.fetchone()[0]


# Validation result
row_count_match = (
    db_ready_row_count == postgresql_row_count
)


print("Shipment Row Count Validation")
print("=" * 80)

print("\n1. Database-Ready Dataset Row Count")
print("Rows:", db_ready_row_count)

print("\n2. PostgreSQL Table Row Count")
print("Rows:", postgresql_row_count)

print("\n3. Row Count Validation")
print("Row counts match:", row_count_match)

print("\n4. Validation Summary")
print("=" * 80)

if row_count_match:
    print("Shipment row count validation passed.")
else:
    print("Shipment row count validation failed.")

Shipment Row Count Validation
================================================================================

1. Database-Ready Dataset Row Count
Rows: 14

2. PostgreSQL Table Row Count
Rows: 14

3. Row Count Validation
Row counts match: True

4. Validation Summary
================================================================================
Shipment row count validation passed.

## 6.7 Retrieve Shipment Records

Retrieve Shipment records directly from PostgreSQL and review IDs, relationships, status, tracking values, dates, NULL handling, and overall record formatting.

In [31]:
# =========================================================
# 6.7 Retrieve Shipment Records
# =========================================================

retrieve_shipment_query="""
SELECT
    shipment_id,sales_order_id,warehouse_id,shipment_date,courier_name,
    tracking_number,shipment_status,delivery_date,notes,created_date,
    created_by,updated_date,updated_by
FROM commerce.shipment
ORDER BY shipment_id;
"""

try:
    cursor.execute(retrieve_shipment_query)
    shipment_records=cursor.fetchall()
    column_names=[description[0] for description in cursor.description]
    shipment_postgresql=pd.DataFrame(shipment_records,columns=column_names)
    for column in ["shipment_date","delivery_date","created_date","updated_date"]:
        shipment_postgresql[column]=pd.to_datetime(shipment_postgresql[column],errors="coerce")
    print("Shipment Records Retrieved from PostgreSQL")
    print("Records retrieved:",len(shipment_records))
    display(shipment_postgresql)
except Exception as e:
    print("Shipment record retrieval failed.")
    print("Error:",e)

Shipment Records Retrieved from PostgreSQL
Records retrieved: 14

   shipment_id sales_order_id warehouse_id shipment_date courier_name tracking_number shipment_status delivery_date                 notes created_date created_by updated_date updated_by
0        SH001          SO001        WH001    2026-07-06          DHL          TRK001       Delivered    2026-07-07              Complete   2026-07-05      admin   2026-07-07      admin
1        SH002          SO002        WH001    2026-07-07       Aramex          TRK002       Delivered    2026-07-08              Complete   2026-07-06      admin   2026-07-08      admin
2        SH003          SO003        WH002    2026-07-08        FedEx          TRK003       Delivered    2026-07-09              Complete   2026-07-07      admin   2026-07-09      admin
3        SH004          SO004        WH001    2026-07-09          DHL          TRK004       Delivered    2026-07-10              Complete   2026-07-08      admin   2026-07-10      admin
4        SH005          SO005        WH002    2026-07-10       Aramex          TRK005       Delivered    2026-07-11              Complete   2026-07-09      admin   2026-07-11      admin
5        SH006          SO007        WH001    2026-07-12          DHL          TRK006       Delivered    2026-07-13              Complete   2026-07-11      admin   2026-07-13      admin
6        SH007          SO008        WH001    2026-07-13        FedEx            None       Delivered    2026-07-14  Tracking unavailable   2026-07-12      admin   2026-07-14      admin
7        SH008          SO009        WH003    2026-07-14       Aramex          TRK008       Delivered    2026-07-15              Complete   2026-07-13      admin   2026-07-15      admin
8        SH009          SO011        WH002    2026-07-16          DHL          TRK009       Delivered    2026-07-17              Complete   2026-07-15      admin   2026-07-17      admin
9        SH010          SO012        WH001    2026-07-17        FedEx          TRK010       Delivered    2026-07-18              Complete   2026-07-16      admin   2026-07-18      admin
10       SH011          SO013        WH001    2026-07-18          DHL          TRK011       Delivered    2026-07-19              Complete   2026-07-17      admin   2026-07-19      admin
11       SH012          SO014        WH003    2026-07-19       Aramex            None       Delivered    2026-07-20  Tracking unavailable   2026-07-18      admin   2026-07-20      admin
12       SH013          SO015        WH001    2026-07-20          DHL          TRK013      In Transit           NaT            In transit   2026-07-19      admin   2026-07-20      admin
13       SH014          SO016        WH001    2026-07-21        FedEx          TRK014       Delivered    2026-07-22              Complete   2026-07-20      admin   2026-07-22      admin

## 6.8 Source → Database Reconciliation

Compare the validated Shipment Database-Ready dataset with the records retrieved directly from PostgreSQL.

Validate row counts, column names/order, shipment IDs, and record-level values.

In [32]:
# =========================================================
# 6.8 Source → Database Reconciliation
# =========================================================

shipment_source_reconciliation=shipment_db_ready.copy().sort_values("shipment_id").reset_index(drop=True)
shipment_postgresql_reconciliation=shipment_postgresql.copy().sort_values("shipment_id").reset_index(drop=True)

for column in ["shipment_date","delivery_date","created_date","updated_date"]:
    shipment_source_reconciliation[column]=pd.to_datetime(shipment_source_reconciliation[column],errors="coerce")
    shipment_postgresql_reconciliation[column]=pd.to_datetime(shipment_postgresql_reconciliation[column],errors="coerce")

source_row_count=len(shipment_source_reconciliation)
database_row_count=len(shipment_postgresql_reconciliation)
row_count_match=source_row_count==database_row_count
source_columns=shipment_source_reconciliation.columns.tolist()
database_columns=shipment_postgresql_reconciliation.columns.tolist()
column_match=source_columns==database_columns
source_shipment_ids=set(shipment_source_reconciliation["shipment_id"])
database_shipment_ids=set(shipment_postgresql_reconciliation["shipment_id"])
primary_key_match=source_shipment_ids==database_shipment_ids
value_match=shipment_source_reconciliation.equals(shipment_postgresql_reconciliation)
reconciliation_passed=all([row_count_match,column_match,primary_key_match,value_match])

print("Shipment Source → Database Reconciliation")
print("Row counts match:",row_count_match)
print("Columns and order match:",column_match)
print("Shipment IDs match:",primary_key_match)
print("All record values match:",value_match)
print("Source → Database reconciliation passed:",reconciliation_passed)

Shipment Source → Database Reconciliation
Row counts match: True
Columns and order match: True
Shipment IDs match: True
All record values match: True
Source → Database reconciliation passed: True

## 6.9 Shipment Database Integrity Validation

Perform final integrity checks on `commerce.shipment`, including primary-key uniqueness, required fields, foreign-key relationships, approved status values, Delivered → delivery-date requirement, In Transit → nullable delivery-date behavior, and audit/date consistency.

In [33]:
# =========================================================
# 6.9 Shipment Database Integrity Validation
# =========================================================

integrity_query="""
SELECT
 COUNT(*) AS total_rows,
 COUNT(DISTINCT shipment_id) AS distinct_shipment_ids,
 COUNT(*) FILTER (WHERE shipment_id IS NULL) AS null_shipment_ids,
 COUNT(*) FILTER (WHERE sales_order_id IS NULL) AS null_sales_order_ids,
 COUNT(*) FILTER (WHERE warehouse_id IS NULL) AS null_warehouse_ids,
 COUNT(*) FILTER (WHERE shipment_date IS NULL) AS null_shipment_dates,
 COUNT(*) FILTER (WHERE courier_name IS NULL) AS null_courier_names,
 COUNT(*) FILTER (WHERE shipment_status IS NULL) AS null_shipment_statuses,
 COUNT(*) FILTER (WHERE created_date IS NULL) AS null_created_dates,
 COUNT(*) FILTER (WHERE created_by IS NULL) AS null_created_by,
 COUNT(*) FILTER (WHERE updated_date IS NULL) AS null_updated_dates,
 COUNT(*) FILTER (WHERE updated_by IS NULL) AS null_updated_by,
 COUNT(*) FILTER (WHERE shipment_status NOT IN ('Delivered','In Transit')) AS invalid_statuses,
 COUNT(*) FILTER (WHERE shipment_status='Delivered' AND delivery_date IS NULL) AS delivered_without_delivery_date,
 COUNT(*) FILTER (WHERE shipment_status='In Transit' AND delivery_date IS NOT NULL) AS in_transit_with_delivery_date,
 COUNT(*) FILTER (WHERE updated_date < created_date) AS invalid_audit_date_order,
 COUNT(*) FILTER (WHERE delivery_date IS NOT NULL AND delivery_date < shipment_date) AS delivery_before_shipment
FROM commerce.shipment;
"""

try:
    cursor.execute(integrity_query)
    r=cursor.fetchone()
    print("Shipment Database Integrity Validation")
    print("="*80)
    labels=["Total rows","Distinct shipment IDs","NULL shipment IDs","NULL sales order IDs","NULL warehouse IDs","NULL shipment dates","NULL courier names","NULL shipment statuses","NULL created dates","NULL created by","NULL updated dates","NULL updated by","Invalid statuses","Delivered without delivery date","In Transit with delivery date","Updated before created","Delivery before shipment"]
    for label,value in zip(labels,r): print(f"{label}: {value}")
    integrity_passed=(r[0]==r[1] and all(v==0 for v in r[2:]))
    print("\nShipment database integrity passed:",integrity_passed)
except Exception as e:
    print("Shipment database integrity validation failed.")
    print("Error:",e)

Shipment Database Integrity Validation
================================================================================
Total rows: 14
Distinct shipment IDs: 14
NULL shipment IDs: 0
NULL sales order IDs: 0
NULL warehouse IDs: 0
NULL shipment dates: 0
NULL courier names: 0
NULL shipment statuses: 0
NULL created dates: 0
NULL created by: 0
NULL updated dates: 0
NULL updated by: 0
Invalid statuses: 0
Delivered without delivery date: 0
In Transit with delivery date: 0
Updated before created: 0
Delivery before shipment: 0

Shipment database integrity passed: True

## 6.10 Close PostgreSQL Connection

Close the PostgreSQL cursor and database connection after all Shipment loading and validation steps are complete.

Confirm that PostgreSQL resources are closed cleanly.

In [34]:
# =========================================================
# 6.10 Close PostgreSQL Connection
# =========================================================

try:
    if cursor is not None and not cursor.closed:
        cursor.close()

    if conn is not None and conn.closed == 0:
        conn.close()

    print("PostgreSQL resources closed successfully.")
    print("Cursor closed:", cursor.closed)
    print("Connection closed:", conn.closed != 0)

except Exception as e:
    print("PostgreSQL resource closure failed.")
    print("Error:", e)

PostgreSQL resources closed successfully.
Cursor closed: True
Connection closed: True