# LJ Dev Commerce - Phase 4

# V. Marketing Campaign ETL

# =========================================================
# 01. Extract
# =========================================================

## 1.1 Setup

This section imports the required Python libraries and defines the
project paths used throughout the Marketing Campaign ETL pipeline.

The raw dataset will be preserved and used as the source for the
dataset inspection, profiling, transformation, validation, and
downstream ETL stages.

In [1]:
import pandas as pd

In [2]:
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

## 1.2 Load and Preserve Marketing Campaign Raw Dataset

This section loads the Marketing Campaign source dataset and creates
an independent copy of the original raw data.

The original raw dataset will remain preserved and unchanged throughout
the ETL process. All inspections, profiling, transformations, and
validations will be performed using appropriate working copies.

This ensures that the original source data remains available for
data preservation checks and later reconciliation.

In [3]:
# =========================================================
# 1.2 Load and Preserve Marketing Campaign Raw Dataset
# =========================================================

# Define the raw Marketing Campaign dataset path
marketing_campaign_master_raw_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\05_Marketing\marketing_campaign_master.csv"
)

# Load the raw source dataset
marketing_campaign_master_raw = pd.read_csv(
    marketing_campaign_master_raw_path
)

# Preserve the original raw dataset
marketing_campaign_master_raw_original = (
    marketing_campaign_master_raw.copy(deep=True)
)

print("Marketing Campaign raw dataset loaded successfully.")
print("Rows:", marketing_campaign_master_raw.shape[0])
print("Columns:", marketing_campaign_master_raw.shape[1])

print("\nColumn names:")
print(marketing_campaign_master_raw.columns.tolist())

print(
    "\nRaw dataset preserved:",
    marketing_campaign_master_raw.equals(
        marketing_campaign_master_raw_original
    )
)

display(marketing_campaign_master_raw)

Marketing Campaign raw dataset loaded successfully.
Rows: 4
Columns: 12

Column names:
['CampaignCode', 'CampaignName', 'CampaignType', 'StartDate', 'EndDate', 'DiscountPct', 'Description', 'ActiveFlag', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Raw dataset preserved: True

,CampaignCode,CampaignName,CampaignType,StartDate,EndDate,DiscountPct,Description,ActiveFlag,CreatedOn,CreatedByUser,ModifiedOn,ModifiedByUser
0,CAM001,Summer Tech Sale,Seasonal,2026-07-01,2026-07-31,10,Summer electronics promotion,True,2026-06-20,marketing_admin,2026-07-15,marketing_admin
1,CAM002,Back to School,Seasonal,2026-07-15,2026-08-31,15,Student device promotion,True,2026-07-01,marketing_admin,2026-07-15,marketing_admin
2,CAM003,Weekend Flash Sale,Flash Sale,2026-07-10,2026-07-12,20,Limited weekend discount,False,2026-07-05,marketing_admin,2026-07-13,marketing_admin
3,CAM004,New Customer Offer,Acquisition,2026-07-01,2026-09-30,5,New customer discount,True,2026-06-25,marketing_admin,2026-07-15,marketing_admin

## 1.3 Initial Inspection

This section performs an initial inspection of the Marketing Campaign
raw dataset.

The inspection reviews the dataset structure, column names, data types,
sample records, and basic descriptive information before detailed
profiling is performed.

No transformations are applied in this section.

In [5]:
# =========================================================
# 1.3 Initial Inspection
# =========================================================

print("Marketing Campaign Raw Dataset - Initial Inspection")
print("=" * 80)

# ---------------------------------------------------------
# 1. Dataset Shape
# ---------------------------------------------------------

print("\n1. Dataset Shape")
print("Rows:", marketing_campaign_master_raw.shape[0])
print("Columns:", marketing_campaign_master_raw.shape[1])

# ---------------------------------------------------------
# 2. Column Names
# ---------------------------------------------------------

print("\n2. Column Names")
print(marketing_campaign_master_raw.columns.tolist())

# ---------------------------------------------------------
# 3. Current Pandas Data Types
# ---------------------------------------------------------

print("\n3. Current Pandas Data Types")
print(marketing_campaign_master_raw.dtypes)

# ---------------------------------------------------------
# 4. Missing Values
# ---------------------------------------------------------

print("\n4. Missing Values")
print(marketing_campaign_master_raw.isnull().sum())

# ---------------------------------------------------------
# 5. Dataset Information
# ---------------------------------------------------------

print("\n5. Dataset Information")
marketing_campaign_master_raw.info()

# ---------------------------------------------------------
# 6. First Five Records
# ---------------------------------------------------------

print("\n6. First Five Records")
display(marketing_campaign_master_raw.head())

# ---------------------------------------------------------
# 7. Last Five Records
# ---------------------------------------------------------

print("\n7. Last Five Records")
display(marketing_campaign_master_raw.tail())

# ---------------------------------------------------------
# 8. Descriptive Statistics
# ---------------------------------------------------------

print("\n8. Descriptive Statistics")
display(marketing_campaign_master_raw.describe(include="all").T)

# ---------------------------------------------------------
# 9. Full Raw Dataset
# ---------------------------------------------------------

print("\n9. Full Raw Marketing Campaign Dataset")
display(marketing_campaign_master_raw)

Marketing Campaign Raw Dataset - Initial Inspection
================================================================================

1. Dataset Shape
Rows: 4
Columns: 12

2. Column Names
['CampaignCode', 'CampaignName', 'CampaignType', 'StartDate', 'EndDate', 'DiscountPct', 'Description', 'ActiveFlag', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

3. Current Pandas Data Types
CampaignCode      object
CampaignName      object
CampaignType      object
StartDate         object
EndDate           object
DiscountPct        int64
Description       object
ActiveFlag          bool
CreatedOn         object
CreatedByUser     object
ModifiedOn        object
ModifiedByUser    object
dtype: object

4. Missing Values
CampaignCode      0
CampaignName      0
CampaignType      0
StartDate         0
EndDate           0
DiscountPct       0
Description       0
ActiveFlag        0
CreatedOn         0
CreatedByUser     0
ModifiedOn        0
ModifiedByUser    0
dtype: int64

5. Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CampaignCode    4 non-null      object
 1   CampaignName    4 non-null      object
 2   CampaignType    4 non-null      object
 3   StartDate       4 non-null      object
 4   EndDate         4 non-null      object
 5   DiscountPct     4 non-null      int64
 6   Description     4 non-null      object
 7   ActiveFlag      4 non-null      bool
 8   CreatedOn       4 non-null      object
 9   CreatedByUser   4 non-null      object
 10  ModifiedOn      4 non-null      object
 11  ModifiedByUser  4 non-null      object
dtypes: bool(1), int64(1), object(10)
memory usage: 488.0+ bytes

6. First Five Records

,CampaignCode,CampaignName,CampaignType,StartDate,EndDate,DiscountPct,Description,ActiveFlag,CreatedOn,CreatedByUser,ModifiedOn,ModifiedByUser
0,CAM001,Summer Tech Sale,Seasonal,2026-07-01,2026-07-31,10,Summer electronics promotion,True,2026-06-20,marketing_admin,2026-07-15,marketing_admin
1,CAM002,Back to School,Seasonal,2026-07-15,2026-08-31,15,Student device promotion,True,2026-07-01,marketing_admin,2026-07-15,marketing_admin
2,CAM003,Weekend Flash Sale,Flash Sale,2026-07-10,2026-07-12,20,Limited weekend discount,False,2026-07-05,marketing_admin,2026-07-13,marketing_admin
3,CAM004,New Customer Offer,Acquisition,2026-07-01,2026-09-30,5,New customer discount,True,2026-06-25,marketing_admin,2026-07-15,marketing_admin

7. Last Five Records

,CampaignCode,CampaignName,CampaignType,StartDate,EndDate,DiscountPct,Description,ActiveFlag,CreatedOn,CreatedByUser,ModifiedOn,ModifiedByUser
0,CAM001,Summer Tech Sale,Seasonal,2026-07-01,2026-07-31,10,Summer electronics promotion,True,2026-06-20,marketing_admin,2026-07-15,marketing_admin
1,CAM002,Back to School,Seasonal,2026-07-15,2026-08-31,15,Student device promotion,True,2026-07-01,marketing_admin,2026-07-15,marketing_admin
2,CAM003,Weekend Flash Sale,Flash Sale,2026-07-10,2026-07-12,20,Limited weekend discount,False,2026-07-05,marketing_admin,2026-07-13,marketing_admin
3,CAM004,New Customer Offer,Acquisition,2026-07-01,2026-09-30,5,New customer discount,True,2026-06-25,marketing_admin,2026-07-15,marketing_admin

8. Descriptive Statistics

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
CampaignCode,4,4,CAM001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CampaignName,4,4,Summer Tech Sale,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CampaignType,4,3,Seasonal,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StartDate,4,3,2026-07-01,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EndDate,4,4,2026-07-31,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DiscountPct,4.0,NaN,NaN,NaN,12.5,6.454972,5.0,8.75,12.5,16.25,20.0
Description,4,4,Summer electronics promotion,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ActiveFlag,4,2,True,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CreatedOn,4,4,2026-06-20,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CreatedByUser,4,1,marketing_admin,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ModifiedOn,4,2,2026-07-15,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ModifiedByUser,4,1,marketing_admin,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

9. Full Raw Marketing Campaign Dataset

,CampaignCode,CampaignName,CampaignType,StartDate,EndDate,DiscountPct,Description,ActiveFlag,CreatedOn,CreatedByUser,ModifiedOn,ModifiedByUser
0,CAM001,Summer Tech Sale,Seasonal,2026-07-01,2026-07-31,10,Summer electronics promotion,True,2026-06-20,marketing_admin,2026-07-15,marketing_admin
1,CAM002,Back to School,Seasonal,2026-07-15,2026-08-31,15,Student device promotion,True,2026-07-01,marketing_admin,2026-07-15,marketing_admin
2,CAM003,Weekend Flash Sale,Flash Sale,2026-07-10,2026-07-12,20,Limited weekend discount,False,2026-07-05,marketing_admin,2026-07-13,marketing_admin
3,CAM004,New Customer Offer,Acquisition,2026-07-01,2026-09-30,5,New customer discount,True,2026-06-25,marketing_admin,2026-07-15,marketing_admin

## 1.4 Data Profiling

Profile the untouched raw Marketing Campaign dataset using the reusable
`data_profiler_v1` tool.

The profiler is used to identify potential data-quality issues, semantic
field types, missing values, duplicates, formatting inconsistencies, and
other detectable anomalies before any cleaning or transformation is
performed.

Profiling results are treated as findings for investigation. The profiler
does not make business decisions or automatically determine the correct
transformation.

In [6]:
# =========================================================
# 1.4 Data Profiling
# =========================================================

import sys
import importlib

# Identify the project root
project_root = Path.cwd().parent

# Add the project root to the Python path if needed
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# Import and reload the reusable data profiler
from profiler import data_profiler_v1 as profiler

importlib.reload(profiler)

print("Profiler loaded successfully:")
print(profiler.__file__)

print("\nProfiler configuration:")
print(profiler.DEFAULT_CONFIG)

Profiler loaded successfully:
c:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\profiler\data_profiler_v1.py

Profiler configuration:
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

In [7]:
# Run the complete profiler against the untouched raw Marketing Campaign dataset

profile_results = profiler.profile_dataset(marketing_campaign_master_raw)

print("\nMarketing Campaign profiling completed successfully.")
print("\nProfiler sections:")
print(list(profile_results.keys()))

Marketing Campaign profiling completed successfully.

Profiler sections:
['field_types', 'detection_details', 'general', 'text', 'categorical', 'numeric', 'date', 'patterns', 'issues', 'configuration']

## 1.5 Review Profiling Results

Review the complete Marketing Campaign profiling results before making
any transformation decisions.

The automated profiler identifies potential data-quality issues, but the
results must be independently reviewed in the context of the Marketing
Campaign dataset and LJ Dev Commerce business requirements.

This review examines:

* Automated profiling findings
* Issues requiring independent analyst review
* Potential business-rule decisions
* Issues that may require transformation

No data is modified during this stage.

In [8]:
# =========================================================
# 1.5 Review Profiling Results
# =========================================================

for section_name, section_result in profile_results.items():
    
    print("\n" + "=" * 70)
    print(section_name.upper())
    print("=" * 70)
    
    print(section_result)

======================================================================
FIELD_TYPES
======================================================================
CampaignCode      identifier
CampaignName            text
CampaignType            text
StartDate               date
EndDate                 date
DiscountPct          numeric
Description             text
ActiveFlag           boolean
CreatedOn               date
CreatedByUser           text
ModifiedOn              date
ModifiedByUser          text
Name: DetectedFieldType, dtype: object

======================================================================
DETECTION_DETAILS
======================================================================
{'CampaignCode': {'DetectedType': 'identifier', 'Confidence': 'Medium', 'Evidence': 'Column name suggests identifier semantics'}, 'CampaignName': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'CampaignType': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'StartDate': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'EndDate': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'DiscountPct': {'DetectedType': 'numeric', 'Confidence': 'High', 'Evidence': 'Native numeric dtype'}, 'Description': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'ActiveFlag': {'DetectedType': 'boolean', 'Confidence': 'High', 'Evidence': 'Native boolean dtype'}, 'CreatedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'CreatedByUser': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}, 'ModifiedOn': {'DetectedType': 'date', 'Confidence': 'High', 'Evidence': '100% of values match recognized date representations'}, 'ModifiedByUser': {'DetectedType': 'text', 'Confidence': 'Low', 'Evidence': 'No stronger semantic pattern detected'}}

======================================================================
GENERAL
======================================================================
{'rows': 4, 'columns': 12, 'exact_duplicate_rows': 0, 'column_profile':                DataType DetectedFieldType  MissingCount  MissingPercent  \
CampaignCode     object        identifier             0             0.0
CampaignName     object              text             0             0.0
CampaignType     object              text             0             0.0
StartDate        object              date             0             0.0
EndDate          object              date             0             0.0
DiscountPct       int64           numeric             0             0.0
Description      object              text             0             0.0
ActiveFlag         bool           boolean             0             0.0
CreatedOn        object              date             0             0.0
CreatedByUser    object              text             0             0.0
ModifiedOn       object              date             0             0.0
ModifiedByUser   object              text             0             0.0

                UniqueCount  DuplicateValueCount
CampaignCode              4                    0
CampaignName              4                    0
CampaignType              3                    1
StartDate                 3                    1
EndDate                   4                    0
DiscountPct               4                    0
Description               4                    0
ActiveFlag                2                    2
CreatedOn                 4                    0
CreatedByUser             1                    3
ModifiedOn                2                    2
ModifiedByUser            1                    3  }

======================================================================
TEXT
======================================================================
{'CampaignName': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 14, 'MaximumLength': 18, 'AverageLength': np.float64(16.5)}, 'CampaignType': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 8, 'MaximumLength': 11, 'AverageLength': np.float64(9.25)}, 'Description': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 21, 'MaximumLength': 28, 'AverageLength': np.float64(24.25)}, 'CreatedByUser': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 15, 'MaximumLength': 15, 'AverageLength': np.float64(15.0)}, 'ModifiedByUser': {'WhitespaceCount': 0, 'BlankCount': 0, 'PotentialMissingMarkerCount': 0, 'PotentialMissingMarkers': [], 'MinimumLength': 15, 'MaximumLength': 15, 'AverageLength': np.float64(15.0)}}

======================================================================
CATEGORICAL
======================================================================
{'ActiveFlag': {'UniqueCount': 2, 'MostCommonValue': np.True_, 'MostCommonCount': 3, 'CategoryDistribution': {True: 3, False: 1}}}

======================================================================
NUMERIC
======================================================================
{'DiscountPct': {'ValidNumericCount': 4, 'InvalidNumericCount': 0, 'Minimum': np.float64(5.0), 'Maximum': np.float64(20.0), 'Mean': np.float64(12.5), 'Median': np.float64(12.5), 'ZeroCount': 0, 'NegativeCount': 0, 'PositiveCount': 4, 'RecognizedRepresentations': ['Integer'], 'CurrencyIndicators': [], 'PercentageCount': 0, 'AccountingCount': 0, 'OutlierCandidateCount': 0, 'LowerOutlierBoundary': np.float64(-2.5), 'UpperOutlierBoundary': np.float64(27.5)}}

======================================================================
DATE
======================================================================
{'StartDate': {'ValidDateCount': 4, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-01 00:00:00'), 'MaximumDate': Timestamp('2026-07-15 00:00:00'), 'FutureDateCount': 0}, 'EndDate': {'ValidDateCount': 4, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-12 00:00:00'), 'MaximumDate': Timestamp('2026-09-30 00:00:00'), 'FutureDateCount': 1}, 'CreatedOn': {'ValidDateCount': 4, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-06-20 00:00:00'), 'MaximumDate': Timestamp('2026-07-05 00:00:00'), 'FutureDateCount': 0}, 'ModifiedOn': {'ValidDateCount': 4, 'InvalidDateCount': 0, 'AmbiguousDateCount': 0, 'RecognizedFormats': ['ISO'], 'MixedFormat': False, 'MinimumDate': Timestamp('2026-07-13 00:00:00'), 'MaximumDate': Timestamp('2026-07-15 00:00:00'), 'FutureDateCount': 0}}

======================================================================
PATTERNS
======================================================================
{'email': {}, 'phone': {}, 'identifier': {'CampaignCode': {'UniqueCount': 4, 'DuplicateCount': 0, 'MissingCount': 0}}}

======================================================================
ISSUES
======================================================================
    Column   IssueType Severity  Count                            Description
0  EndDate  FutureDate   Medium      1  Dates later than today were detected.

======================================================================
CONFIGURATION
======================================================================
{'date_detection_threshold': 0.8, 'numeric_detection_threshold': 0.8, 'email_detection_threshold': 0.8, 'phone_detection_threshold': 0.8, 'categorical_unique_ratio': 0.2, 'outlier_iqr_multiplier': 1.5, 'required_columns': [], 'unique_columns': [], 'non_negative_columns': []}

## 1.6 Review Profiler Issues

Review each issue identified by the automated profiler and determine
whether it represents a genuine data-quality problem.

Profiler findings are treated as indicators for investigation and do not
automatically require data cleaning or transformation.

Each issue must be reviewed using:

* The actual dataset values
* Business context
* The Marketing Campaign Data Dictionary
* Independent analyst review

Only confirmed data-quality issues will be approved for transformation.

In [9]:
# =========================================================
# 1.6 Review Profiler Issues
# =========================================================

profiler_issues = profile_results["issues"]

print("Marketing Campaign Profiler Issues")
print("=" * 80)

if profiler_issues.empty:
    print("\nNo issues were identified by the automated profiler.")
else:
    print("\nProfiler issues identified:")
    display(profiler_issues)

Marketing Campaign Profiler Issues
================================================================================

Profiler issues identified:

    Column   IssueType Severity  Count                            Description
0  EndDate  FutureDate   Medium      1  Dates later than today were detected.

## 1.7 Independent Analyst Review

Perform an independent Pre-ETL-style review of the Marketing Campaign
raw dataset inside the ETL notebook.

This review independently examines the actual dataset values and does
not rely solely on automated profiler findings.

The review covers:

* Dataset structure and grain
* Every source column and its actual values
* Missing values and duplicate records
* Identifier integrity
* Text quality and whitespace
* Categorical consistency
* Numeric validity and reasonableness
* Date values and date relationships
* Boolean values
* Audit field consistency
* Business-rule validation

The purpose is to identify confirmed data-quality issues, distinguish
valid business scenarios from genuine problems, and determine what
requires cleaning, transformation, or an analyst/business decision.

No transformations are applied in this section.

In [11]:
# =========================================================
# 1.7 Independent Analyst Review
# =========================================================

print("Marketing Campaign - Independent Analyst Review")
print("=" * 80)

# ---------------------------------------------------------
# 1. Dataset Overview and Grain
# ---------------------------------------------------------

print("\n1. Dataset Overview and Grain")
print("Expected grain: One marketing campaign per row")
print("Rows:", marketing_campaign_master_raw.shape[0])
print("Columns:", marketing_campaign_master_raw.shape[1])

# ---------------------------------------------------------
# 2. Complete Raw Dataset Review
# ---------------------------------------------------------

print("\n2. Complete Raw Dataset Review")
display(marketing_campaign_master_raw)

# ---------------------------------------------------------
# 3. Missing and Blank Value Review
# ---------------------------------------------------------

print("\n3. Missing and Blank Value Review")

missing_values = marketing_campaign_master_raw.isnull().sum()

blank_values = pd.Series(
    {
        column: (
            marketing_campaign_master_raw[column]
            .astype("string")
            .str.strip()
            .eq("")
            .sum()
            if marketing_campaign_master_raw[column].dtype == "object"
            else 0
        )
        for column in marketing_campaign_master_raw.columns
    }
)

missing_blank_review = pd.DataFrame({
    "MissingValues": missing_values,
    "BlankValues": blank_values
})

display(missing_blank_review)

# ---------------------------------------------------------
# 4. Exact Duplicate Record Review
# ---------------------------------------------------------

print("\n4. Exact Duplicate Record Review")

duplicate_rows = marketing_campaign_master_raw[
    marketing_campaign_master_raw.duplicated(keep=False)
]

print("Exact duplicate rows:", duplicate_rows.shape[0])

if duplicate_rows.empty:
    print("No exact duplicate records found.")
else:
    display(duplicate_rows)

# ---------------------------------------------------------
# 5. CampaignCode Identifier Review
# ---------------------------------------------------------

print("\n5. CampaignCode Identifier Review")

print(
    "Missing CampaignCode values:",
    marketing_campaign_master_raw["CampaignCode"].isnull().sum()
)

print(
    "Duplicate CampaignCode values:",
    marketing_campaign_master_raw["CampaignCode"].duplicated().sum()
)

print("CampaignCode values:")
display(
    marketing_campaign_master_raw[
        ["CampaignCode", "CampaignName"]
    ]
)

# ---------------------------------------------------------
# 6. Campaign Text Field Review
# ---------------------------------------------------------

print("\n6. Campaign Text Field Review")

text_columns = [
    "CampaignName",
    "CampaignType",
    "Description",
    "CreatedByUser",
    "ModifiedByUser"
]

for column in text_columns:

    print(f"\n{column}")

    print(
        "Unique values:",
        marketing_campaign_master_raw[column].nunique()
    )

    column_as_string = (
        marketing_campaign_master_raw[column]
        .astype("string")
    )

    print(
        "Whitespace issues:",
        (
            column_as_string
            != column_as_string.str.strip()
        ).sum()
    )

    print(
        "Blank values:",
        column_as_string.str.strip().eq("").sum()
    )

    print("Actual values:")
    print(marketing_campaign_master_raw[column].tolist())

# ---------------------------------------------------------
# 7. Campaign Type Review
# ---------------------------------------------------------

print("\n7. Campaign Type Review")

print("CampaignType values and frequency:")
print(
    marketing_campaign_master_raw["CampaignType"]
    .value_counts(dropna=False)
)

# ---------------------------------------------------------
# 8. Discount Percentage Review
# ---------------------------------------------------------

print("\n8. Discount Percentage Review")

print("DiscountPct values:")
print(
    marketing_campaign_master_raw["DiscountPct"].tolist()
)

print(
    "\nMinimum:",
    marketing_campaign_master_raw["DiscountPct"].min()
)

print(
    "Maximum:",
    marketing_campaign_master_raw["DiscountPct"].max()
)

print(
    "Negative values:",
    (
        marketing_campaign_master_raw["DiscountPct"] < 0
    ).sum()
)

print(
    "Values above 100:",
    (
        marketing_campaign_master_raw["DiscountPct"] > 100
    ).sum()
)

# ---------------------------------------------------------
# 9. ActiveFlag Boolean Review
# ---------------------------------------------------------

print("\n9. ActiveFlag Boolean Review")

print("ActiveFlag values and frequency:")
print(
    marketing_campaign_master_raw["ActiveFlag"]
    .value_counts(dropna=False)
)

print("\nActual ActiveFlag values:")
print(
    marketing_campaign_master_raw["ActiveFlag"].tolist()
)

# ---------------------------------------------------------
# 10. Date Value Review
# ---------------------------------------------------------

print("\n10. Date Value Review")

date_columns = [
    "StartDate",
    "EndDate",
    "CreatedOn",
    "ModifiedOn"
]

for column in date_columns:

    print(f"\n{column}")

    print("Actual values:")
    print(
        marketing_campaign_master_raw[column].tolist()
    )

    converted_dates = pd.to_datetime(
        marketing_campaign_master_raw[column],
        errors="coerce"
    )

    print(
        "Invalid dates:",
        converted_dates.isnull().sum()
    )

    print(
        "Minimum date:",
        converted_dates.min()
    )

    print(
        "Maximum date:",
        converted_dates.max()
    )

# ---------------------------------------------------------
# 11. Date Business Logic Review
# ---------------------------------------------------------

print("\n11. Date Business Logic Review")

start_date = pd.to_datetime(
    marketing_campaign_master_raw["StartDate"],
    errors="coerce"
)

end_date = pd.to_datetime(
    marketing_campaign_master_raw["EndDate"],
    errors="coerce"
)

created_date = pd.to_datetime(
    marketing_campaign_master_raw["CreatedOn"],
    errors="coerce"
)

modified_date = pd.to_datetime(
    marketing_campaign_master_raw["ModifiedOn"],
    errors="coerce"
)

print(
    "EndDate before StartDate:",
    (end_date < start_date).sum()
)

print(
    "ModifiedOn before CreatedOn:",
    (modified_date < created_date).sum()
)

print(
    "CreatedOn after StartDate:",
    (created_date > start_date).sum()
)

print("\nCampaign Date Relationships:")

display(
    marketing_campaign_master_raw[
        [
            "CampaignCode",
            "CampaignName",
            "StartDate",
            "EndDate",
            "ActiveFlag",
            "CreatedOn",
            "ModifiedOn"
        ]
    ]
)

# ---------------------------------------------------------
# 12. Future Date Review
# ---------------------------------------------------------

print("\n12. Future Date Review")

today = pd.Timestamp.today().normalize()

for column, converted_dates in {
    "StartDate": start_date,
    "EndDate": end_date,
    "CreatedOn": created_date,
    "ModifiedOn": modified_date
}.items():

    future_count = (
        converted_dates > today
    ).sum()

    print(
        f"{column} future dates: {future_count}"
    )

# ---------------------------------------------------------
# 13. Audit Field Review
# ---------------------------------------------------------

print("\n13. Audit Field Review")

print("\nCreatedByUser values:")
print(
    marketing_campaign_master_raw["CreatedByUser"]
    .value_counts(dropna=False)
)

print("\nModifiedByUser values:")
print(
    marketing_campaign_master_raw["ModifiedByUser"]
    .value_counts(dropna=False)
)

# ---------------------------------------------------------
# 14. Independent Review Complete
# ---------------------------------------------------------

print("\n14. Independent Analyst Review Complete")
print("=" * 80)

print(
    "All major Marketing Campaign data areas were independently reviewed."
)

print(
    "No transformations were applied to the raw dataset."
)

Marketing Campaign - Independent Analyst Review
================================================================================

1. Dataset Overview and Grain
Expected grain: One marketing campaign per row
Rows: 4
Columns: 12

2. Complete Raw Dataset Review

,CampaignCode,CampaignName,CampaignType,StartDate,EndDate,DiscountPct,Description,ActiveFlag,CreatedOn,CreatedByUser,ModifiedOn,ModifiedByUser
0,CAM001,Summer Tech Sale,Seasonal,2026-07-01,2026-07-31,10,Summer electronics promotion,True,2026-06-20,marketing_admin,2026-07-15,marketing_admin
1,CAM002,Back to School,Seasonal,2026-07-15,2026-08-31,15,Student device promotion,True,2026-07-01,marketing_admin,2026-07-15,marketing_admin
2,CAM003,Weekend Flash Sale,Flash Sale,2026-07-10,2026-07-12,20,Limited weekend discount,False,2026-07-05,marketing_admin,2026-07-13,marketing_admin
3,CAM004,New Customer Offer,Acquisition,2026-07-01,2026-09-30,5,New customer discount,True,2026-06-25,marketing_admin,2026-07-15,marketing_admin

3. Missing Value Review
CampaignCode      0
CampaignName      0
CampaignType      0
StartDate         0
EndDate           0
DiscountPct       0
Description       0
ActiveFlag        0
CreatedOn         0
CreatedByUser     0
ModifiedOn        0
ModifiedByUser    0
dtype: int64

4. Exact Duplicate Record Review
Exact duplicate rows: 0
No exact duplicate records found.

5. CampaignCode Identifier Review
Missing CampaignCode values: 0
Duplicate CampaignCode values: 0
CampaignCode values:

  CampaignCode        CampaignName
0       CAM001    Summer Tech Sale
1       CAM002      Back to School
2       CAM003  Weekend Flash Sale
3       CAM004  New Customer Offer

6. Campaign Text Field Review

CampaignName
Unique values: 4
Whitespace issues: 0
Blank values: 0
Actual values:
['Summer Tech Sale', 'Back to School', 'Weekend Flash Sale', 'New Customer Offer']

CampaignType
Unique values: 3
Whitespace issues: 0
Blank values: 0
Actual values:
['Seasonal', 'Seasonal', 'Flash Sale', 'Acquisition']

Description
Unique values: 4
Whitespace issues: 0
Blank values: 0
Actual values:
['Summer electronics promotion', 'Student device promotion', 'Limited weekend discount', 'New customer discount']

CreatedByUser
Unique values: 1
Whitespace issues: 0
Blank values: 0
Actual values:
['marketing_admin', 'marketing_admin', 'marketing_admin', 'marketing_admin']

ModifiedByUser
Unique values: 1
Whitespace issues: 0
Blank values: 0
Actual values:
['marketing_admin', 'marketing_admin', 'marketing_admin', 'marketing_admin']

7. Campaign Type Review
CampaignType values and frequency:
CampaignType
Seasonal       2
Flash Sale     1
Acquisition    1
Name: count, dtype: int64

8. Discount Percentage Review
DiscountPct values:
[10, 15, 20, 5]

Minimum: 5
Maximum: 20
Negative values: 0
Values above 100: 0

9. ActiveFlag Boolean Review
ActiveFlag values and frequency:
ActiveFlag
True     3
False    1
Name: count, dtype: int64

Actual ActiveFlag values:
[True, True, False, True]

10. Date Value Review

StartDate
Actual values:
['2026-07-01', '2026-07-15', '2026-07-10', '2026-07-01']
Invalid dates: 0
Minimum date: 2026-07-01 00:00:00
Maximum date: 2026-07-15 00:00:00

EndDate
Actual values:
['2026-07-31', '2026-08-31', '2026-07-12', '2026-09-30']
Invalid dates: 0
Minimum date: 2026-07-12 00:00:00
Maximum date: 2026-09-30 00:00:00

CreatedOn
Actual values:
['2026-06-20', '2026-07-01', '2026-07-05', '2026-06-25']
Invalid dates: 0
Minimum date: 2026-06-20 00:00:00
Maximum date: 2026-07-05 00:00:00

ModifiedOn
Actual values:
['2026-07-15', '2026-07-15', '2026-07-13', '2026-07-15']
Invalid dates: 0
Minimum date: 2026-07-13 00:00:00
Maximum date: 2026-07-15 00:00:00

11. Date Business Logic Review
EndDate before StartDate: 0
ModifiedOn before CreatedOn: 0
CreatedOn after StartDate: 0

Campaign Date Relationships:

,CampaignCode,CampaignName,StartDate,EndDate,ActiveFlag,CreatedOn,ModifiedOn
0,CAM001,Summer Tech Sale,2026-07-01,2026-07-31,True,2026-06-20,2026-07-15
1,CAM002,Back to School,2026-07-15,2026-08-31,True,2026-07-01,2026-07-15
2,CAM003,Weekend Flash Sale,2026-07-10,2026-07-12,False,2026-07-05,2026-07-13
3,CAM004,New Customer Offer,2026-07-01,2026-09-30,True,2026-06-25,2026-07-15

12. Future Date Review
StartDate future dates: 0
EndDate future dates: 1
CreatedOn future dates: 0
ModifiedOn future dates: 0

13. Audit Field Review

CreatedByUser values:
CreatedByUser
marketing_admin    4
Name: count, dtype: int64

ModifiedByUser values:
ModifiedByUser
marketing_admin    4
Name: count, dtype: int64

14. Independent Analyst Review Complete
================================================================================
All major Marketing Campaign data areas were independently reviewed.
No transformations were applied to the raw dataset.

## 1.8 Findings and Transformation Decisions

This section consolidates the findings from:

* Automated data profiling
* Profiler issue review
* Independent analyst review
* Marketing Campaign Data Dictionary requirements

Each finding is classified to determine whether it requires:

* Data cleaning
* Data transformation
* A business or analyst decision
* No action

Confirmed findings for the Marketing Campaign dataset:

* No missing values were identified.
* No exact duplicate records were identified.
* `CampaignCode` is complete and unique.
* No text whitespace or blank-value issues were identified.
* `CampaignType` values do not require cleaning.
* `DiscountPct` values are valid and within a reasonable percentage range.
* `ActiveFlag` contains valid Boolean values.
* All date values are valid and use a consistent ISO format.
* One future `EndDate` was identified but represents a valid business scenario
  and does not require correction.
* Audit field values are consistent and do not require cleaning.

No source-data cleaning is required.

The dataset will proceed to the Transform stage, where required
source-to-target mappings and database-ready datatype transformations
will be applied without changing valid business values.

In [12]:
# =========================================================
# 1.8 Findings and Transformation Decisions
# =========================================================

findings_summary = pd.DataFrame(
    [
        {
            "Area": "Missing Values",
            "Finding": "No missing values identified",
            "Decision": "No action required"
        },
        {
            "Area": "Duplicate Records",
            "Finding": "No exact duplicate records identified",
            "Decision": "No action required"
        },
        {
            "Area": "CampaignCode",
            "Finding": "Complete and unique",
            "Decision": "Preserve as campaign identifier"
        },
        {
            "Area": "Text Quality",
            "Finding": "No whitespace or blank-value issues identified",
            "Decision": "No cleaning required"
        },
        {
            "Area": "CampaignType",
            "Finding": "Values reviewed and no inconsistency identified",
            "Decision": "No cleaning required"
        },
        {
            "Area": "DiscountPct",
            "Finding": "Valid numeric values from 5 to 20",
            "Decision": "No cleaning required"
        },
        {
            "Area": "ActiveFlag",
            "Finding": "Valid Boolean values",
            "Decision": "Preserve Boolean values"
        },
        {
            "Area": "Date Values",
            "Finding": "All dates are valid and consistently formatted",
            "Decision": "Convert to database-ready datetime types during transformation"
        },
        {
            "Area": "Future EndDate",
            "Finding": "One future campaign end date identified",
            "Decision": "Valid business scenario - preserve unchanged"
        },
        {
            "Area": "Audit Fields",
            "Finding": "Consistent CreatedByUser and ModifiedByUser values",
            "Decision": "No cleaning required"
        }
    ]
)

print("Marketing Campaign Findings and Transformation Decisions")
print("=" * 80)

display(findings_summary)

print("\nSummary")
print("Source-data cleaning required: No")
print("Business values requiring correction: No")
print("Database-ready datatype transformations required: Yes")
print("Source-to-target mapping required: Yes")

Marketing Campaign Findings and Transformation Decisions
================================================================================

,Area,Finding,Decision
0,Missing Values,No missing values identified,No action required
1,Duplicate Records,No exact duplicate records identified,No action required
2,CampaignCode,Complete and unique,Preserve as campaign identifier
3,Text Quality,No whitespace or blank-value issues identified,No cleaning required
4,CampaignType,Values reviewed and no inconsistency identified,No cleaning required
5,DiscountPct,Valid numeric values from 5 to 20,No cleaning required
6,ActiveFlag,Valid Boolean values,Preserve Boolean values
7,Date Values,All dates are valid and consistently formatted,Convert to database-ready datetime types durin...
8,Future EndDate,One future campaign end date identified,Valid business scenario - preserve unchanged
9,Audit Fields,Consistent CreatedByUser and ModifiedByUser va...,No cleaning required

Summary
Source-data cleaning required: No
Business values requiring correction: No
Database-ready datatype transformations required: Yes
Source-to-target mapping required: Yes

# =========================================================
# 2. Transform
# =========================================================

Apply only the transformations approved during the Extract & Analyze
stage.

The Marketing Campaign review confirmed that no source-data cleaning is
required.

The Transform stage will therefore focus on the approved datatype
preparation required to make the dataset ready for validation and the
next pipeline stages.

The raw dataset will remain unchanged throughout this process.

## 2.1 Create Marketing Campaign Working Dataset

Create an independent working copy of the preserved raw Marketing
Campaign dataset.

All approved transformations in the Transform stage will be applied
to this working dataset.

The original raw dataset and preserved raw copy will remain unchanged.

In [13]:
# =========================================================
# 2.1 Create Marketing Campaign Working Dataset
# =========================================================

# Create an independent working dataset for transformation
marketing_campaign_master_clean = (
    marketing_campaign_master_raw.copy(deep=True)
)

print("Marketing Campaign working dataset created successfully.")

print("\nWorking dataset shape:")
print(marketing_campaign_master_clean.shape)

print("\nRaw dataset remains unchanged:",
      marketing_campaign_master_raw.equals(
          marketing_campaign_master_raw_original
      ))

print("\nWorking dataset created independently:",
      marketing_campaign_master_clean is not marketing_campaign_master_raw)

Marketing Campaign working dataset created successfully.

Working dataset shape:
(4, 12)

Raw dataset remains unchanged: True

Working dataset created independently: True

## 2.2 Apply Approved Transformations

Apply only the transformations approved in Section 1.8.

The independent review confirmed that no source-data cleaning is
required.

The approved transformation is datatype preparation for the date
columns:

* `StartDate`
* `EndDate`
* `CreatedOn`
* `ModifiedOn`

These columns are currently stored as pandas `object` datatype and will
be converted to pandas `datetime` datatype.

All valid business values will be preserved.

In [14]:
# =========================================================
# 2.2 Apply Approved Transformations
# =========================================================

# Define the approved date columns for datatype conversion
date_columns = [
    "StartDate",
    "EndDate",
    "CreatedOn",
    "ModifiedOn"
]

# Convert approved date columns to datetime
for column in date_columns:
    marketing_campaign_master_clean[column] = pd.to_datetime(
        marketing_campaign_master_clean[column],
        errors="raise"
    )

print("Approved transformations applied successfully.")

print("\nUpdated pandas data types:")
print(marketing_campaign_master_clean.dtypes)

Approved transformations applied successfully.

Updated pandas data types:
CampaignCode              object
CampaignName              object
CampaignType              object
StartDate         datetime64[ns]
EndDate           datetime64[ns]
DiscountPct                int64
Description               object
ActiveFlag                  bool
CreatedOn         datetime64[ns]
CreatedByUser             object
ModifiedOn        datetime64[ns]
ModifiedByUser            object
dtype: object

# =========================================================
# 3. Validate
# =========================================================

Validate the approved transformations applied to the Marketing Campaign
Clean DataFrame.

Validation confirms that:

* The required date columns were successfully converted to datetime.
* No invalid dates were introduced during transformation.
* The approved transformations produced the expected result.

No additional transformations are applied in this stage.

## 3.1 Transformation Validation

Validate the approved datatype transformations applied to the Marketing
Campaign Clean DataFrame.

The validation confirms that:

* All required date columns use the pandas datetime datatype.
* No invalid or missing dates were introduced during conversion.
* The transformed date values remain valid.

In [15]:
# =========================================================
# 3.1 Transformation Validation
# =========================================================

print("Marketing Campaign Transformation Validation")
print("=" * 80)

# ---------------------------------------------------------
# 1. Date Datatype Validation
# ---------------------------------------------------------

print("\n1. Date Datatype Validation")

date_datatype_results = {}

for column in date_columns:
    
    is_datetime = pd.api.types.is_datetime64_any_dtype(
        marketing_campaign_master_clean[column]
    )
    
    date_datatype_results[column] = is_datetime
    
    print(
        f"{column:<15} Datetime: {is_datetime}"
    )

# ---------------------------------------------------------
# 2. Invalid Date Validation
# ---------------------------------------------------------

print("\n2. Invalid Date Validation")

for column in date_columns:
    
    invalid_count = (
        marketing_campaign_master_clean[column]
        .isnull()
        .sum()
    )
    
    print(
        f"{column:<15} Invalid/Missing Dates: {invalid_count}"
    )

# ---------------------------------------------------------
# 3. Overall Transformation Result
# ---------------------------------------------------------

all_date_columns_valid = all(date_datatype_results.values())

print("\n3. Transformation Validation Summary")
print("=" * 80)

print("All required date columns are datetime:",
      all_date_columns_valid)

print(
    "Transformation validation passed:",
    all_date_columns_valid
)

Marketing Campaign Transformation Validation
================================================================================

1. Date Datatype Validation
StartDate       Datetime: True
EndDate         Datetime: True
CreatedOn       Datetime: True
ModifiedOn      Datetime: True

2. Invalid Date Validation
StartDate       Invalid/Missing Dates: 0
EndDate         Invalid/Missing Dates: 0
CreatedOn       Invalid/Missing Dates: 0
ModifiedOn      Invalid/Missing Dates: 0

3. Transformation Validation Summary
================================================================================
All required date columns are datetime: True
Transformation validation passed: True

## 3.2 Data Preservation Validation

Validate that the approved date datatype transformations did not
unintentionally modify the Marketing Campaign dataset.

This validation confirms that:

* Row count remains unchanged.
* Column count remains unchanged.
* Column names remain unchanged.
* Non-date column values remain unchanged.
* Date values remain unchanged after datatype conversion.

Only the approved pandas datatypes should have changed.

In [16]:
# =========================================================
# 3.2 Data Preservation Validation
# =========================================================

print("Marketing Campaign Data Preservation Validation")
print("=" * 80)

# ---------------------------------------------------------
# 1. Row Count Validation
# ---------------------------------------------------------

print("\n1. Row Count Validation")

raw_row_count = marketing_campaign_master_raw.shape[0]
clean_row_count = marketing_campaign_master_clean.shape[0]

print("Raw dataset rows:", raw_row_count)
print("Clean dataset rows:", clean_row_count)
print("Row counts match:", raw_row_count == clean_row_count)

# ---------------------------------------------------------
# 2. Column Structure Validation
# ---------------------------------------------------------

print("\n2. Column Structure Validation")

raw_columns = marketing_campaign_master_raw.columns.tolist()
clean_columns = marketing_campaign_master_clean.columns.tolist()

print("Column counts match:",
      len(raw_columns) == len(clean_columns))

print("Column names and order match:",
      raw_columns == clean_columns)

# ---------------------------------------------------------
# 3. Non-Date Value Preservation
# ---------------------------------------------------------

print("\n3. Non-Date Value Preservation")

non_date_columns = [
    column
    for column in marketing_campaign_master_raw.columns
    if column not in date_columns
]

non_date_values_match = (
    marketing_campaign_master_raw[non_date_columns]
    .equals(marketing_campaign_master_clean[non_date_columns])
)

print("Non-date values unchanged:",
      non_date_values_match)

# ---------------------------------------------------------
# 4. Date Value Preservation
# ---------------------------------------------------------

print("\n4. Date Value Preservation")

date_values_match = True

for column in date_columns:

    raw_dates = pd.to_datetime(
        marketing_campaign_master_raw[column],
        errors="raise"
    )

    clean_dates = marketing_campaign_master_clean[column]

    values_match = raw_dates.equals(clean_dates)

    print(f"{column:<15} Values unchanged: {values_match}")

    if not values_match:
        date_values_match = False

# ---------------------------------------------------------
# 5. Overall Preservation Validation
# ---------------------------------------------------------

all_preservation_checks_passed = (
    raw_row_count == clean_row_count
    and raw_columns == clean_columns
    and non_date_values_match
    and date_values_match
)

print("\n5. Data Preservation Validation Summary")
print("=" * 80)

print(
    "All data preservation checks passed:",
    all_preservation_checks_passed
)

Marketing Campaign Data Preservation Validation
================================================================================

1. Row Count Validation
Raw dataset rows: 4
Clean dataset rows: 4
Row counts match: True

2. Column Structure Validation
Column counts match: True
Column names and order match: True

3. Non-Date Value Preservation
Non-date values unchanged: True

4. Date Value Preservation
StartDate       Values unchanged: True
EndDate         Values unchanged: True
CreatedOn       Values unchanged: True
ModifiedOn      Values unchanged: True

5. Data Preservation Validation Summary
================================================================================
All data preservation checks passed: True

# =========================================================
# 4. Clean CSV
# =========================================================

Export the validated Marketing Campaign Clean DataFrame as a Clean CSV.

The Clean CSV preserves the approved cleaned and transformed source
structure and serves as the validated intermediate dataset before
database-ready source-to-target mapping.

No additional transformations are applied during this stage.

## 4.1 Export Clean CSV

Export the validated Marketing Campaign Clean DataFrame to the
standardized Clean CSV location.

The exported file represents the approved Clean CSV version of the
Marketing Campaign dataset.

In [18]:
# =========================================================
# 4.1 Export Clean Marketing Campaign Dataset
# =========================================================

from pathlib import Path

clean_marketing_campaign_path = Path(
    r"C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce"
    r"\data\05_Marketing\clean\marketing_campaign_master_clean.csv"
)

# Create the clean folder if it does not exist
clean_marketing_campaign_path.parent.mkdir(
    parents=True,
    exist_ok=True
)

# Export clean dataset
marketing_campaign_master_clean.to_csv(
    clean_marketing_campaign_path,
    index=False
)

print("Clean Marketing Campaign CSV exported successfully.")
print("Path:", clean_marketing_campaign_path)
print("Rows exported:", len(marketing_campaign_master_clean))
print("Columns exported:", len(marketing_campaign_master_clean.columns))

Clean Marketing Campaign CSV exported successfully.
Path: C:\JEP\DATA ANALYST PORTFOLIO\Lj_Dev_Commerce\data\05_Marketing\clean\marketing_campaign_master_clean.csv
Rows exported: 4
Columns exported: 12

## 4.2 Validate Clean CSV Export

Validate the exported Marketing Campaign Clean CSV by reloading the file
and comparing its structure and row count with the validated Clean
DataFrame.

This confirms that the Clean CSV was exported successfully and can be
used as the approved intermediate dataset for the next ETL stage.

In [19]:
# =========================================================
# 4.2 Validate Clean CSV Export
# =========================================================

# Reload the exported Clean CSV
marketing_campaign_master_clean_exported = pd.read_csv(
    clean_marketing_campaign_path
)

print("Marketing Campaign Clean CSV Export Validation")
print("=" * 80)

# ---------------------------------------------------------
# 1. Row Count Validation
# ---------------------------------------------------------

print("\n1. Row Count Validation")

print("Clean DataFrame rows:",
      len(marketing_campaign_master_clean))

print("Exported Clean CSV rows:",
      len(marketing_campaign_master_clean_exported))

print(
    "Row counts match:",
    len(marketing_campaign_master_clean)
    == len(marketing_campaign_master_clean_exported)
)

# ---------------------------------------------------------
# 2. Column Validation
# ---------------------------------------------------------

print("\n2. Column Validation")

print("Clean DataFrame columns:")
print(marketing_campaign_master_clean.columns.tolist())

print("\nExported Clean CSV columns:")
print(marketing_campaign_master_clean_exported.columns.tolist())

print(
    "\nColumns and order match:",
    marketing_campaign_master_clean.columns.tolist()
    == marketing_campaign_master_clean_exported.columns.tolist()
)

# ---------------------------------------------------------
# 3. Export Validation Summary
# ---------------------------------------------------------

row_count_match = (
    len(marketing_campaign_master_clean)
    == len(marketing_campaign_master_clean_exported)
)

column_match = (
    marketing_campaign_master_clean.columns.tolist()
    == marketing_campaign_master_clean_exported.columns.tolist()
)

print("\n3. Clean CSV Export Validation Summary")
print("=" * 80)

print(
    "Clean CSV export validation passed:",
    row_count_match and column_match
)

Marketing Campaign Clean CSV Export Validation
================================================================================

1. Row Count Validation
Clean DataFrame rows: 4
Exported Clean CSV rows: 4
Row counts match: True

2. Column Validation
Clean DataFrame columns:
['CampaignCode', 'CampaignName', 'CampaignType', 'StartDate', 'EndDate', 'DiscountPct', 'Description', 'ActiveFlag', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Exported Clean CSV columns:
['CampaignCode', 'CampaignName', 'CampaignType', 'StartDate', 'EndDate', 'DiscountPct', 'Description', 'ActiveFlag', 'CreatedOn', 'CreatedByUser', 'ModifiedOn', 'ModifiedByUser']

Columns and order match: True

3. Clean CSV Export Validation Summary
================================================================================
Clean CSV export validation passed: True

# =========================================================
# 5. Database Ready
# =========================================================

Prepare the validated Marketing Campaign Clean CSV for the PostgreSQL
target structure.

This stage applies the approved source-to-target mapping based on the
LJ Dev Commerce Marketing Campaign Data Dictionary and prepares the
dataset for database loading.

The Clean CSV remains unchanged.

## 5.1 Define Source → Target Mapping

Define the approved source-to-target column mapping based on the
LJ Dev Commerce Marketing Campaign Data Dictionary.

The mapping converts the source column names into the standardized
PostgreSQL target column names.

No data values are modified during this step.

In [21]:
# =========================================================
# 5.1 Define Source → Target Mapping
# =========================================================

marketing_campaign_column_mapping = {
    "CampaignCode": "campaign_id",
    "CampaignName": "campaign_name",
    "CampaignType": "campaign_type",
    "StartDate": "start_date",
    "EndDate": "end_date",
    "DiscountPct": "discount_percentage",
    "Description": "campaign_description",
    "ActiveFlag": "is_active",
    "CreatedOn": "created_date",
    "CreatedByUser": "created_by",
    "ModifiedOn": "updated_date",
    "ModifiedByUser": "updated_by"
}

print("Marketing Campaign Source → Target Mapping")
print("=" * 80)

for source_column, target_column in marketing_campaign_column_mapping.items():
    print(f"{source_column:<20} → {target_column}")

Marketing Campaign Source → Target Mapping
================================================================================
CampaignCode         → campaign_id
CampaignName         → campaign_name
CampaignType         → campaign_type
StartDate            → start_date
EndDate              → end_date
DiscountPct          → discount_percentage
Description          → campaign_description
ActiveFlag           → is_active
CreatedOn            → created_date
CreatedByUser        → created_by
ModifiedOn           → updated_date
ModifiedByUser       → updated_by

## 5.2 Create Database-Ready Dataset

Create the Marketing Campaign Database-Ready dataset from the verified
exported Clean CSV.

The approved source-to-target mapping is then applied to convert the
source column names into the PostgreSQL target structure.

The Clean CSV remains unchanged.

No undocumented business-value transformations are applied during this
step.

In [22]:
# =========================================================
# 5.2 Create Database-Ready Dataset
# =========================================================

# Load the verified exported Clean CSV
marketing_campaign_master_clean_exported = pd.read_csv(
    clean_marketing_campaign_path
)

# Create the Database-Ready dataset from the exported Clean CSV
marketing_campaign_master_db_ready = (
    marketing_campaign_master_clean_exported
    .rename(columns=marketing_campaign_column_mapping)
    .copy()
)

# ---------------------------------------------------------
# Prepare target-compatible datatypes
# ---------------------------------------------------------

database_ready_date_columns = [
    "start_date",
    "end_date",
    "created_date",
    "updated_date"
]

for column in database_ready_date_columns:
    marketing_campaign_master_db_ready[column] = pd.to_datetime(
        marketing_campaign_master_db_ready[column],
        errors="raise"
    )

marketing_campaign_master_db_ready[
    "discount_percentage"
] = pd.to_numeric(
    marketing_campaign_master_db_ready[
        "discount_percentage"
    ],
    errors="raise"
)

marketing_campaign_master_db_ready[
    "is_active"
] = marketing_campaign_master_db_ready[
    "is_active"
].astype(bool)

print(
    "Marketing Campaign Database-Ready Dataset Created Successfully."
)

print("=" * 80)

print("\nSource: Verified Exported Clean CSV")

print("\nDatabase-Ready Dataset Shape:")
print(marketing_campaign_master_db_ready.shape)

print("\nDatabase-Ready Column Names:")
print(
    marketing_campaign_master_db_ready.columns.tolist()
)

print("\nDatabase-Ready Data Types:")
print(marketing_campaign_master_db_ready.dtypes)

print("\nDatabase-Ready Dataset:")
display(marketing_campaign_master_db_ready)

Marketing Campaign Database-Ready Dataset Created Successfully.
================================================================================

Source: Verified Exported Clean CSV

Database-Ready Dataset Shape:
(4, 12)

Database-Ready Column Names:
['campaign_id', 'campaign_name', 'campaign_type', 'start_date', 'end_date', 'discount_percentage', 'campaign_description', 'is_active', 'created_date', 'created_by', 'updated_date', 'updated_by']

Database-Ready Dataset:

,campaign_id,campaign_name,campaign_type,start_date,end_date,discount_percentage,campaign_description,is_active,created_date,created_by,updated_date,updated_by
0,CAM001,Summer Tech Sale,Seasonal,2026-07-01,2026-07-31,10,Summer electronics promotion,True,2026-06-20,marketing_admin,2026-07-15,marketing_admin
1,CAM002,Back to School,Seasonal,2026-07-15,2026-08-31,15,Student device promotion,True,2026-07-01,marketing_admin,2026-07-15,marketing_admin
2,CAM003,Weekend Flash Sale,Flash Sale,2026-07-10,2026-07-12,20,Limited weekend discount,False,2026-07-05,marketing_admin,2026-07-13,marketing_admin
3,CAM004,New Customer Offer,Acquisition,2026-07-01,2026-09-30,5,New customer discount,True,2026-06-25,marketing_admin,2026-07-15,marketing_admin

## 5.3 Database-Ready Validation

Validate the Marketing Campaign Database-Ready DataFrame before
PostgreSQL loading.

This validation confirms that:

* The row count is preserved from the verified Clean CSV.
* All expected target columns are present.
* Target columns are in the approved order.
* The source-to-target mapping is complete.
* No undocumented source columns were lost.
* Required fields do not contain NULL values.
* The primary key is unique and does not contain NULL values.
* The dataset is prepared for PostgreSQL table verification and loading.

In [23]:
# =========================================================
# 5.3 Database-Ready Validation
# =========================================================

print("Marketing Campaign Database-Ready Validation")
print("=" * 80)

# ---------------------------------------------------------
# 1. Row Count Validation
# ---------------------------------------------------------

print("\n1. Row Count Validation")

clean_csv_row_count = len(
    marketing_campaign_master_clean_exported
)

database_ready_row_count = len(
    marketing_campaign_master_db_ready
)

row_count_match = (
    clean_csv_row_count == database_ready_row_count
)

print("Verified Clean CSV rows:", clean_csv_row_count)
print("Database-Ready rows:", database_ready_row_count)
print("Row counts match:", row_count_match)

# ---------------------------------------------------------
# 2. Expected Target Column Validation
# ---------------------------------------------------------

print("\n2. Expected Target Column Validation")

expected_target_columns = list(
    marketing_campaign_column_mapping.values()
)

actual_target_columns = (
    marketing_campaign_master_db_ready.columns.tolist()
)

target_columns_match = (
    expected_target_columns == actual_target_columns
)

print("Expected target columns:")
print(expected_target_columns)

print("\nActual Database-Ready columns:")
print(actual_target_columns)

print(
    "\nColumns and order match:",
    target_columns_match
)

# ---------------------------------------------------------
# 3. Mapping Completeness Validation
# ---------------------------------------------------------

print("\n3. Mapping Completeness Validation")

source_columns = (
    marketing_campaign_master_clean_exported.columns.tolist()
)

mapping_source_columns = list(
    marketing_campaign_column_mapping.keys()
)

mapping_complete = (
    source_columns == mapping_source_columns
)

print(
    "Source columns match mapping definition:",
    mapping_complete
)

print(
    "Source columns not mapped:",
    sorted(
        set(source_columns)
        - set(mapping_source_columns)
    )
)

print(
    "Unexpected mapping source columns:",
    sorted(
        set(mapping_source_columns)
        - set(source_columns)
    )
)

# ---------------------------------------------------------
# 4. Required Field Validation
# ---------------------------------------------------------

print("\n4. Required Field Validation")

required_target_columns = [
    "campaign_id",
    "campaign_name",
    "campaign_type",
    "start_date",
    "end_date",
    "discount_percentage",
    "is_active",
    "created_date",
    "created_by",
    "updated_date",
    "updated_by"
]

required_null_counts = (
    marketing_campaign_master_db_ready[
        required_target_columns
    ]
    .isnull()
    .sum()
)

required_fields_valid = (
    required_null_counts.sum() == 0
)

print("NULL counts for required fields:")
display(required_null_counts.to_frame("NullCount"))

print(
    "Required field validation passed:",
    required_fields_valid
)

print(
    "Optional campaign_description NULL count:",
    marketing_campaign_master_db_ready[
        "campaign_description"
    ].isnull().sum()
)

# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

print("\n5. Primary Key Validation")

duplicate_primary_keys = (
    marketing_campaign_master_db_ready["campaign_id"]
    .duplicated()
    .sum()
)

null_primary_keys = (
    marketing_campaign_master_db_ready["campaign_id"]
    .isnull()
    .sum()
)

primary_key_valid = (
    duplicate_primary_keys == 0
    and null_primary_keys == 0
)

print(
    "Duplicate Primary Keys:",
    duplicate_primary_keys
)

print(
    "NULL Primary Keys:",
    null_primary_keys
)

print(
    "Primary Key validation passed:",
    primary_key_valid
)

# ---------------------------------------------------------
# 6. Target-Compatible Datatype Validation
# ---------------------------------------------------------

print("\n6. Target-Compatible Datatype Validation")

target_datetime_columns = [
    "start_date",
    "end_date",
    "created_date",
    "updated_date"
]

target_numeric_columns = [
    "discount_percentage"
]

target_boolean_columns = [
    "is_active"
]

datetime_types_valid = all(
    pd.api.types.is_datetime64_any_dtype(
        marketing_campaign_master_db_ready[column]
    )
    for column in target_datetime_columns
)

numeric_types_valid = all(
    pd.api.types.is_numeric_dtype(
        marketing_campaign_master_db_ready[column]
    )
    for column in target_numeric_columns
)

boolean_types_valid = all(
    pd.api.types.is_bool_dtype(
        marketing_campaign_master_db_ready[column]
    )
    for column in target_boolean_columns
)

target_datatypes_valid = (
    datetime_types_valid
    and numeric_types_valid
    and boolean_types_valid
)

print(
    "Datetime columns valid:",
    datetime_types_valid
)

print(
    "Numeric columns valid:",
    numeric_types_valid
)

print(
    "Boolean columns valid:",
    boolean_types_valid
)

print(
    "Target-compatible datatypes valid:",
    target_datatypes_valid
)

# ---------------------------------------------------------
# 7. Overall Database-Ready Validation
# ---------------------------------------------------------

database_ready_validation_passed = (
    row_count_match
    and target_columns_match
    and mapping_complete
    and required_fields_valid
    and primary_key_valid
    and target_datatypes_valid
)

print("\n7. Database-Ready Validation Summary")
print("=" * 80)

print(
    "Database-Ready validation passed:",
    database_ready_validation_passed
)

Marketing Campaign Database-Ready Validation
================================================================================

1. Row Count Validation
Verified Clean CSV rows: 4
Database-Ready rows: 4
Row counts match: True

2. Expected Target Column Validation
Expected target columns:
['campaign_id', 'campaign_name', 'campaign_type', 'start_date', 'end_date', 'discount_percentage', 'campaign_description', 'is_active', 'created_date', 'created_by', 'updated_date', 'updated_by']

Actual Database-Ready columns:
['campaign_id', 'campaign_name', 'campaign_type', 'start_date', 'end_date', 'discount_percentage', 'campaign_description', 'is_active', 'created_date', 'created_by', 'updated_date', 'updated_by']

Columns and order match: True

3. Mapping Completeness Validation
Source columns match mapping definition: True
Source columns not mapped: []
Unexpected mapping source columns: []

4. Required Field Validation
campaign_id             0
campaign_name           0
campaign_type           0
start_date              0
end_date                0
discount_percentage     0
campaign_description    0
is_active               0
created_date            0
created_by              0
updated_date            0
updated_by              0
dtype: int64

Rows with NULL required values: 0
Required field validation passed: True

5. Primary Key Validation
Duplicate Primary Keys: 0
NULL Primary Keys: 0
Primary Key validation passed: True

6. Database-Ready Validation Summary
================================================================================
Database-Ready validation passed: True

# =========================================================
# 6. PostgreSQL
# =========================================================

Connect to PostgreSQL and confirm that the ETL notebook is connected to
the correct database and PostgreSQL environment.

No table changes or data loading are performed in this step.

## 6.1 Connect

Establish a PostgreSQL connection for the Marketing Campaign ETL
process.

Confirm that:

* The PostgreSQL connection is successful.
* The correct database is connected.
* The correct PostgreSQL user is connected.
* The target schema is available.

No records are inserted during this step.

In [25]:
# =========================================================
# 6.1 Connect to PostgreSQL
# =========================================================

import psycopg2
from getpass import getpass


# ---------------------------------------------------------
# PostgreSQL Connection Configuration
# ---------------------------------------------------------

DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "lj_dev_commerce"
DB_USER = "postgres"

DB_PASSWORD = getpass("Enter PostgreSQL password: ")

conn = None
cursor = None


# ---------------------------------------------------------
# Connect to PostgreSQL
# ---------------------------------------------------------

try:
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD
    )

    cursor = conn.cursor()

    print("PostgreSQL connection successful.")
    print("Database:", DB_NAME)
    print("Host:", DB_HOST)
    print("Port:", DB_PORT)
    print("User:", DB_USER)

    # Verify target schema availability
    cursor.execute("""
        SELECT EXISTS (
            SELECT 1
            FROM information_schema.schemata
            WHERE schema_name = 'commerce'
        );
    """)

    commerce_schema_exists = cursor.fetchone()[0]

    print(
        "commerce schema exists:",
        commerce_schema_exists
    )

    if not commerce_schema_exists:
        raise RuntimeError(
            "Required PostgreSQL schema 'commerce' does not exist."
        )

except Exception as e:
    print("PostgreSQL connection or schema verification failed.")
    print("Error:", e)
    raise

PostgreSQL connection successful.
Database: lj_dev_commerce
Host: localhost
Port: 5432

## 6.2 Prepare / Create Target Table

Check whether the approved Marketing Campaign PostgreSQL target table
already exists before creating or modifying anything.

Target:

Schema: commerce
Table: marketing_campaign

The table must not be recreated blindly. Its existence and approved
database design must be confirmed first.

In [26]:
# =========================================================
# 6.2 Prepare / Create Target Table
# =========================================================

target_schema = "commerce"
target_table = "marketing_campaign"

# Check whether the target table already exists
cursor.execute("""
    SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = %s
          AND table_name = %s
    );
""", (target_schema, target_table))

table_exists = cursor.fetchone()[0]

print("Marketing Campaign Target Table Check")
print("=" * 80)

print("Schema:", target_schema)
print("Table:", target_table)
print("Table exists:", table_exists)

if table_exists:
    print("\nTarget table already exists.")
    print("The table will not be recreated.")
else:
    print("\nTarget table does not exist.")
    print("The approved database design must be used before creating it.")

Marketing Campaign Target Table Check
================================================================================
Schema: commerce
Table: marketing_campaign
Table exists: False

Target table does not exist.
The approved database design must be used before creating it.

## 6.2.1 Create Marketing Campaign Table

The `commerce.marketing_campaign` table does not currently exist.

This section creates the Marketing Campaign PostgreSQL target table based
on the approved LJ Dev Commerce Marketing Campaign Data Dictionary.

Key design decisions:

- `campaign_id` is the Primary Key.

- All required Data Dictionary fields use `NOT NULL`.

- `campaign_description` is optional and therefore allows `NULL`.

- `is_active` uses the PostgreSQL `BOOLEAN` datatype.

- `start_date`, `end_date`, `created_date`, and `updated_date`
  use the PostgreSQL `TIMESTAMP` datatype.

- `discount_percentage` uses the PostgreSQL `DECIMAL` datatype.

- Marketing Campaign does not contain foreign keys at this stage.

In [27]:
# =========================================================
# 6.2.1 Create Marketing Campaign Table
# =========================================================

create_marketing_campaign_table_query = """
CREATE TABLE commerce.marketing_campaign (

    campaign_id TEXT PRIMARY KEY,

    campaign_name TEXT NOT NULL,
    campaign_type TEXT NOT NULL,

    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,

    discount_percentage DECIMAL NOT NULL,

    campaign_description TEXT,

    is_active BOOLEAN NOT NULL,

    created_date TIMESTAMP NOT NULL,
    created_by TEXT NOT NULL,

    updated_date TIMESTAMP NOT NULL,
    updated_by TEXT NOT NULL

);
"""

if table_exists:

    print(
        "Marketing Campaign table already exists."
    )

    print(
        "Table creation skipped to prevent unintended recreation."
    )

else:

    try:

        cursor.execute(
            create_marketing_campaign_table_query
        )

        conn.commit()

        print(
            "Marketing Campaign table created successfully."
        )

        print(
            "Table: commerce.marketing_campaign"
        )

    except Exception as e:

        conn.rollback()

        print(
            "Marketing Campaign table creation failed."
        )

        print("Error:", e)

        raise

Marketing Campaign table created successfully.
Table: commerce.marketing_campaign

## 6.3 Verify Marketing Campaign Table Structure

Verify the actual PostgreSQL structure of the
`commerce.marketing_campaign` table after creation.

Confirm:

- Column names
- Column order
- PostgreSQL data types
- NULL / NOT NULL rules
- Default values

The actual PostgreSQL table structure will be reviewed against the
approved Marketing Campaign Data Dictionary before records are loaded.

In [28]:
# =========================================================
# 6.3 Verify Marketing Campaign Table Structure
# =========================================================

verify_marketing_campaign_table_query = """
SELECT
    ordinal_position,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'commerce'
  AND table_name = 'marketing_campaign'
ORDER BY ordinal_position;
"""

try:
    cursor.execute(
        verify_marketing_campaign_table_query
    )

    table_structure = cursor.fetchall()

    print("Marketing Campaign Table Structure")
    print("=" * 80)

    print(
        f"{'Position':<10}"
        f"{'Column Name':<25}"
        f"{'Data Type':<25}"
        f"{'Nullable':<12}"
        f"{'Default'}"
    )

    print("-" * 100)

    for row in table_structure:
        print(
            f"{row[0]:<10}"
            f"{row[1]:<25}"
            f"{row[2]:<25}"
            f"{row[3]:<12}"
            f"{row[4]}"
        )

    expected_table_columns = [
        (
            "campaign_id",
            "text",
            "NO"
        ),
        (
            "campaign_name",
            "text",
            "NO"
        ),
        (
            "campaign_type",
            "text",
            "NO"
        ),
        (
            "start_date",
            "timestamp without time zone",
            "NO"
        ),
        (
            "end_date",
            "timestamp without time zone",
            "NO"
        ),
        (
            "discount_percentage",
            "numeric",
            "NO"
        ),
        (
            "campaign_description",
            "text",
            "YES"
        ),
        (
            "is_active",
            "boolean",
            "NO"
        ),
        (
            "created_date",
            "timestamp without time zone",
            "NO"
        ),
        (
            "created_by",
            "text",
            "NO"
        ),
        (
            "updated_date",
            "timestamp without time zone",
            "NO"
        ),
        (
            "updated_by",
            "text",
            "NO"
        )
    ]

    actual_table_columns = [
        (
            row[1],
            row[2],
            row[3]
        )
        for row in table_structure
    ]

    table_structure_match = (
        actual_table_columns
        == expected_table_columns
    )

    print("\nExpected structure matches actual structure:",
          table_structure_match)

    if not table_structure_match:
        raise RuntimeError(
            "The existing commerce.marketing_campaign table "
            "does not match the approved target structure."
        )

except Exception as e:
    print(
        "Marketing Campaign table structure verification failed."
    )

    print("Error:", e)

    raise

Marketing Campaign Table Structure
================================================================================
Position  Column Name              Data Type                Nullable    Default
----------------------------------------------------------------------------------------------------
1         campaign_id              text                     NO          None
2         campaign_name            text                     NO          None
3         campaign_type            text                     NO          None
4         start_date               timestamp without time zoneNO          None
5         end_date                 timestamp without time zoneNO          None
6         discount_percentage      numeric                  NO          None
7         campaign_description     text                     YES         None
8         is_active                boolean                  NO          None
9         created_date             timestamp without time zoneNO          None
10        created_by               text                     NO          None
11        updated_date             timestamp without time zoneNO          None
12        updated_by               text                     NO          None

## 6.4 Verify Keys, Relationships & Load Dependencies

Verify the applicable keys, relationships, and load dependencies before
loading Marketing Campaign records into PostgreSQL.

Confirm:

- `campaign_id` is the Primary Key.
- The target table has no unexpected foreign key dependencies.
- No parent/master table is required before loading Marketing Campaign.
- The dataset follows the approved project ETL load order.

Only applicable checks are performed for this dataset.

In [30]:
# =========================================================
# 6.4 Verify Keys, Relationships & Load Dependencies
# =========================================================

print("Marketing Campaign Keys, Relationships & Load Dependency Review")
print("=" * 80)

# ---------------------------------------------------------
# 1. Primary Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'marketing_campaign'
      AND tc.constraint_type = 'PRIMARY KEY';
""")

primary_keys = cursor.fetchall()

print("\n1. Primary Key")
print(primary_keys)

primary_key_valid = (
    len(primary_keys) == 1
    and primary_keys[0][1] == "campaign_id"
)

print("Primary Key validation passed:", primary_key_valid)


# ---------------------------------------------------------
# 2. Foreign Key Verification
# ---------------------------------------------------------

cursor.execute("""
    SELECT
        tc.constraint_name,
        kcu.column_name,
        ccu.table_schema AS referenced_schema,
        ccu.table_name AS referenced_table,
        ccu.column_name AS referenced_column
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
        ON ccu.constraint_name = tc.constraint_name
        AND ccu.table_schema = tc.table_schema
    WHERE tc.table_schema = 'commerce'
      AND tc.table_name = 'marketing_campaign'
      AND tc.constraint_type = 'FOREIGN KEY';
""")

foreign_keys = cursor.fetchall()

print("\n2. Foreign Keys")
print(foreign_keys)

no_foreign_key_dependency = len(foreign_keys) == 0

print(
    "No foreign key dependency:",
    no_foreign_key_dependency
)


# ---------------------------------------------------------
# 3. Load Dependency Decision
# ---------------------------------------------------------

print("\n3. Load Dependency Review")

load_dependency_ready = (
    primary_key_valid
    and no_foreign_key_dependency
)

print("Primary Key ready:", primary_key_valid)
print("Foreign Key dependencies ready:",
      no_foreign_key_dependency)

print("\n4. Overall Load Dependency Status")
print("=" * 80)

print("Marketing Campaign is ready for data loading:",
      load_dependency_ready)

Marketing Campaign Keys, Relationships & Load Dependency Review
================================================================================

1. Primary Key
[('marketing_campaign_pkey', 'campaign_id')]
Primary Key validation passed: True

2. Foreign Keys
[]
No foreign key dependency: True

3. Load Dependency Review
Primary Key ready: True
Foreign Key dependencies ready: True

4. Overall Load Dependency Status
================================================================================
Marketing Campaign is ready for data loading: True

## 6.5 Insert Marketing Campaign Records

Load the validated Marketing Campaign database-ready dataset into the
verified `commerce.marketing_campaign` PostgreSQL table.

Before inserting records:

- Confirm the target table is currently empty.
- Confirm the database-ready row count.
- Insert only the validated database-ready records.
- Use an explicit column list matching the approved target structure.
- Commit the transaction only after successful insertion.

No transformations are performed during the database loading step.

In [31]:
# =========================================================
# 6.5 Insert Marketing Campaign Records
# =========================================================

# ---------------------------------------------------------
# 1. Check Current Target Table Row Count
# ---------------------------------------------------------

cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.marketing_campaign;
""")

existing_row_count = cursor.fetchone()[0]

print("Marketing Campaign Database Load")
print("=" * 80)

print("\n1. Current Target Table Status")
print("Existing rows:", existing_row_count)


# ---------------------------------------------------------
# 2. Confirm Database-Ready Dataset
# ---------------------------------------------------------

source_row_count = len(
    marketing_campaign_master_db_ready
)

print("\n2. Database-Ready Dataset")
print("Rows ready for loading:", source_row_count)

if not database_ready_validation_passed:
    raise RuntimeError(
        "Database-Ready validation has not passed. "
        "Marketing Campaign records will not be inserted."
    )


# ---------------------------------------------------------
# 3. Prevent Accidental Duplicate Load
# ---------------------------------------------------------

if existing_row_count > 0:

    print("\n3. Duplicate Load Protection")
    print(
        "Target table already contains records."
    )

    print(
        "No records were inserted."
    )

else:

    # -----------------------------------------------------
    # 4. Prepare Records for PostgreSQL
    # -----------------------------------------------------

    records_to_insert = [
        tuple(row)
        for row in marketing_campaign_master_db_ready[
            [
                "campaign_id",
                "campaign_name",
                "campaign_type",
                "start_date",
                "end_date",
                "discount_percentage",
                "campaign_description",
                "is_active",
                "created_date",
                "created_by",
                "updated_date",
                "updated_by"
            ]
        ].itertuples(
            index=False,
            name=None
        )
    ]

    # -----------------------------------------------------
    # 5. Insert Records
    # -----------------------------------------------------

    insert_marketing_campaign_query = """
    INSERT INTO commerce.marketing_campaign (
        campaign_id,
        campaign_name,
        campaign_type,
        start_date,
        end_date,
        discount_percentage,
        campaign_description,
        is_active,
        created_date,
        created_by,
        updated_date,
        updated_by
    )
    VALUES (
        %s, %s, %s, %s, %s, %s,
        %s, %s, %s, %s, %s, %s
    );
    """

    try:

        cursor.executemany(
            insert_marketing_campaign_query,
            records_to_insert
        )

        conn.commit()

        print("\n3. Insert Result")
        print(
            "Marketing Campaign records inserted successfully."
        )

        print(
            "Rows inserted:",
            len(records_to_insert)
        )

    except Exception as e:

        conn.rollback()

        print("\n3. Insert Result")
        print(
            "Marketing Campaign record insertion failed."
        )

        print("Error:", e)

        raise

Marketing Campaign Database Load
================================================================================

1. Current Target Table Status
Existing rows: 0

2. Database-Ready Dataset
Rows ready for loading: 4

3. Insert Result
Marketing Campaign records inserted successfully.
Rows inserted: 4

## 6.6 Validate Marketing Campaign Row Count

Compare the number of records in the Database-Ready dataset with the
number of records currently stored in the PostgreSQL
`commerce.marketing_campaign` table.

This confirms that the intended load scope was completed successfully.

No additional integrity checks are performed in this section.

In [32]:
# =========================================================
# 6.6 Validate Marketing Campaign Row Count
# =========================================================

# Expected row count from the Database-Ready dataset
db_ready_row_count = len(marketing_campaign_master_db_ready)


# Actual row count from PostgreSQL
cursor.execute("""
    SELECT COUNT(*)
    FROM commerce.marketing_campaign;
""")

postgresql_row_count = cursor.fetchone()[0]


# Validation result
row_count_match = (
    db_ready_row_count == postgresql_row_count
)


print("Marketing Campaign Row Count Validation")
print("=" * 80)

print("\n1. Database-Ready Dataset Row Count")
print("Rows:", db_ready_row_count)

print("\n2. PostgreSQL Table Row Count")
print("Rows:", postgresql_row_count)

print("\n3. Row Count Validation")
print("Row counts match:", row_count_match)

print("\n4. Validation Summary")
print("=" * 80)

if row_count_match:
    print("Marketing Campaign row count validation passed.")
else:
    print("Marketing Campaign row count validation failed.")

Marketing Campaign Row Count Validation
================================================================================

1. Database-Ready Dataset Row Count
Rows: 4

2. PostgreSQL Table Row Count
Rows: 4

3. Row Count Validation
Row counts match: True

4. Validation Summary
================================================================================
Marketing Campaign row count validation passed.

## 6.7 Retrieve Marketing Campaign Records

Retrieve the Marketing Campaign records directly from PostgreSQL to confirm
that the loaded data is stored correctly.

Review:

- Loaded records
- Column values
- Date values
- Discount percentage values
- Boolean values
- Overall record formatting

This step confirms that records can be successfully retrieved from the
PostgreSQL target table.

In [33]:
# =========================================================
# 6.7 Retrieve Marketing Campaign Records
# =========================================================

retrieve_marketing_campaign_query = """
SELECT
    campaign_id,
    campaign_name,
    campaign_type,
    start_date,
    end_date,
    discount_percentage,
    campaign_description,
    is_active,
    created_date,
    created_by,
    updated_date,
    updated_by
FROM commerce.marketing_campaign
ORDER BY campaign_id;
"""

try:
    cursor.execute(retrieve_marketing_campaign_query)

    marketing_campaign_records = cursor.fetchall()

    print("Marketing Campaign Records Retrieved from PostgreSQL")
    print("=" * 80)

    print("Records retrieved:", len(marketing_campaign_records))

    # Retrieve column names from the query result
    column_names = [
        description[0]
        for description in cursor.description
    ]

    # Create a DataFrame for readable review
    marketing_campaign_postgresql = pd.DataFrame(
        marketing_campaign_records,
        columns=column_names
    )

    print("\nRetrieved Marketing Campaign Records:")
    display(marketing_campaign_postgresql)

except Exception as e:
    print("Marketing Campaign record retrieval failed.")
    print("Error:", e)

Marketing Campaign Records Retrieved from PostgreSQL
================================================================================
Records retrieved: 4

Retrieved Marketing Campaign Records:

,campaign_id,campaign_name,campaign_type,start_date,end_date,discount_percentage,campaign_description,is_active,created_date,created_by,updated_date,updated_by
0,CAM001,Summer Tech Sale,Seasonal,2026-07-01,2026-07-31,10,Summer electronics promotion,True,2026-06-20,marketing_admin,2026-07-15,marketing_admin
1,CAM002,Back to School,Seasonal,2026-07-15,2026-08-31,15,Student device promotion,True,2026-07-01,marketing_admin,2026-07-15,marketing_admin
2,CAM003,Weekend Flash Sale,Flash Sale,2026-07-10,2026-07-12,20,Limited weekend discount,False,2026-07-05,marketing_admin,2026-07-13,marketing_admin
3,CAM004,New Customer Offer,Acquisition,2026-07-01,2026-09-30,5,New customer discount,True,2026-06-25,marketing_admin,2026-07-15,marketing_admin

## 6.8 Source → Database Reconciliation

Compare the validated Marketing Campaign Database-Ready dataset with the
records retrieved directly from PostgreSQL.

Validate:

- Row counts
- Column names
- Column order
- Campaign IDs
- Record-level values

This confirms that the Database-Ready dataset was loaded into PostgreSQL
without unintended changes.

In [34]:
# =========================================================
# 6.8 Source → Database Reconciliation
# =========================================================

# ---------------------------------------------------------
# 1. Prepare Source Dataset
# ---------------------------------------------------------

marketing_campaign_source_reconciliation = (
    marketing_campaign_master_db_ready.copy()
    .sort_values("campaign_id")
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 2. Prepare PostgreSQL Dataset
# ---------------------------------------------------------

marketing_campaign_postgresql_reconciliation = (
    marketing_campaign_postgresql.copy()
    .sort_values("campaign_id")
    .reset_index(drop=True)
)

# Normalize PostgreSQL-returned datatypes to the
# Database-Ready target datatypes before value comparison
reconciliation_date_columns = [
    "start_date",
    "end_date",
    "created_date",
    "updated_date"
]

for column in reconciliation_date_columns:

    marketing_campaign_postgresql_reconciliation[column] = (
        pd.to_datetime(
            marketing_campaign_postgresql_reconciliation[column],
            errors="raise"
        )
    )

marketing_campaign_postgresql_reconciliation[
    "discount_percentage"
] = pd.to_numeric(
    marketing_campaign_postgresql_reconciliation[
        "discount_percentage"
    ],
    errors="raise"
)


print("Marketing Campaign Source → Database Reconciliation")
print("=" * 80)


# ---------------------------------------------------------
# 3. Row Count Validation
# ---------------------------------------------------------

source_row_count = len(
    marketing_campaign_source_reconciliation
)

database_row_count = len(
    marketing_campaign_postgresql_reconciliation
)

row_count_match = (
    source_row_count == database_row_count
)

print("\n1. Row Count Validation")
print("Database-Ready rows:", source_row_count)
print("PostgreSQL rows:", database_row_count)
print("Row counts match:", row_count_match)


# ---------------------------------------------------------
# 4. Column Validation
# ---------------------------------------------------------

source_columns = (
    marketing_campaign_source_reconciliation.columns.tolist()
)

database_columns = (
    marketing_campaign_postgresql_reconciliation.columns.tolist()
)

column_match = (
    source_columns == database_columns
)

print("\n2. Column Validation")
print("Columns and order match:", column_match)

if not column_match:

    print("\nDatabase-Ready columns:")
    print(source_columns)

    print("\nPostgreSQL columns:")
    print(database_columns)


# ---------------------------------------------------------
# 5. Primary Key Validation
# ---------------------------------------------------------

source_campaign_ids = set(
    marketing_campaign_source_reconciliation[
        "campaign_id"
    ]
)

database_campaign_ids = set(
    marketing_campaign_postgresql_reconciliation[
        "campaign_id"
    ]
)

primary_key_match = (
    source_campaign_ids == database_campaign_ids
)

print("\n3. Campaign ID Validation")
print(
    "Campaign IDs match:",
    primary_key_match
)


# ---------------------------------------------------------
# 6. Record-Level Value Validation
# ---------------------------------------------------------

value_match = (
    marketing_campaign_source_reconciliation.equals(
        marketing_campaign_postgresql_reconciliation
    )
)

print("\n4. Record-Level Value Validation")
print(
    "All record values match:",
    value_match
)


# ---------------------------------------------------------
# 7. Reconciliation Summary
# ---------------------------------------------------------

reconciliation_passed = (
    row_count_match
    and column_match
    and primary_key_match
    and value_match
)

print("\n5. Source → Database Reconciliation Summary")
print("=" * 80)

print(
    "Source → Database reconciliation passed:",
    reconciliation_passed
)

Marketing Campaign Source → Database Reconciliation
================================================================================

1. Row Count Validation
Database-Ready rows: 4
PostgreSQL rows: 4
Row counts match: True

2. Column Validation
Columns and order match: True

3. Campaign ID Validation
Campaign IDs match: True

4. Record-Level Value Validation
All record values match: False

5. Source → Database Reconciliation Summary
================================================================================
Source → Database reconciliation passed: False

## 6.9 Marketing Campaign Database Integrity Validation

Perform final integrity checks on the loaded
`commerce.marketing_campaign` table.

The checks confirm:

- Primary-key uniqueness
- Required-field integrity
- Duplicate record checks
- Boolean validity
- Campaign date consistency
- Audit date consistency

These checks provide the final confirmation that the Marketing Campaign
table is structurally and business-rule compliant after loading.

In [35]:
# =========================================================
# 6.9 Marketing Campaign Database Integrity Validation
# =========================================================

integrity_query = """
SELECT
    COUNT(*) AS total_rows,

    COUNT(DISTINCT campaign_id) AS distinct_campaign_ids,

    COUNT(*) FILTER (
        WHERE campaign_id IS NULL
    ) AS null_campaign_ids,

    COUNT(*) FILTER (
        WHERE campaign_name IS NULL
    ) AS null_campaign_names,

    COUNT(*) FILTER (
        WHERE campaign_type IS NULL
    ) AS null_campaign_types,

    COUNT(*) FILTER (
        WHERE start_date IS NULL
    ) AS null_start_dates,

    COUNT(*) FILTER (
        WHERE end_date IS NULL
    ) AS null_end_dates,

    COUNT(*) FILTER (
        WHERE discount_percentage IS NULL
    ) AS null_discount_percentages,

    COUNT(*) FILTER (
        WHERE is_active IS NULL
    ) AS null_active_flags,

    COUNT(*) FILTER (
        WHERE created_date IS NULL
    ) AS null_created_dates,

    COUNT(*) FILTER (
        WHERE created_by IS NULL
    ) AS null_created_by,

    COUNT(*) FILTER (
        WHERE updated_date IS NULL
    ) AS null_updated_dates,

    COUNT(*) FILTER (
        WHERE updated_by IS NULL
    ) AS null_updated_by,

    COUNT(*) FILTER (
        WHERE start_date > end_date
    ) AS invalid_campaign_date_order,

    COUNT(*) FILTER (
        WHERE updated_date < created_date
    ) AS invalid_audit_date_order

FROM commerce.marketing_campaign;
"""

try:

    cursor.execute(integrity_query)

    integrity_result = cursor.fetchone()

    print("Marketing Campaign Database Integrity Validation")
    print("=" * 80)

    print("\n1. Primary Key Integrity")
    print("Total rows:", integrity_result[0])
    print("Distinct campaign IDs:", integrity_result[1])
    print("NULL campaign IDs:", integrity_result[2])

    print("\n2. Required Field Integrity")
    print("NULL campaign names:", integrity_result[3])
    print("NULL campaign types:", integrity_result[4])
    print("NULL start dates:", integrity_result[5])
    print("NULL end dates:", integrity_result[6])
    print("NULL discount percentages:", integrity_result[7])
    print("NULL active flags:", integrity_result[8])
    print("NULL created dates:", integrity_result[9])
    print("NULL created by:", integrity_result[10])
    print("NULL updated dates:", integrity_result[11])
    print("NULL updated by:", integrity_result[12])

    print("\n3. Campaign Date Integrity")
    print(
        "Start date later than end date:",
        integrity_result[13]
    )

    print("\n4. Audit Date Integrity")
    print(
        "Updated date earlier than created date:",
        integrity_result[14]
    )

    # -----------------------------------------------------
    # 5. Exact Duplicate Record Check
    # -----------------------------------------------------

    cursor.execute("""
        SELECT COUNT(*)
        FROM (
            SELECT
                campaign_id,
                campaign_name,
                campaign_type,
                start_date,
                end_date,
                discount_percentage,
                campaign_description,
                is_active,
                created_date,
                created_by,
                updated_date,
                updated_by
            FROM commerce.marketing_campaign
            GROUP BY
                campaign_id,
                campaign_name,
                campaign_type,
                start_date,
                end_date,
                discount_percentage,
                campaign_description,
                is_active,
                created_date,
                created_by,
                updated_date,
                updated_by
            HAVING COUNT(*) > 1
        ) AS duplicate_groups;
    """)

    duplicate_record_groups = cursor.fetchone()[0]

    print("\n5. Exact Duplicate Record Check")
    print(
        "Duplicate record groups:",
        duplicate_record_groups
    )

    # -----------------------------------------------------
    # 6. Boolean Validity
    # -----------------------------------------------------

    cursor.execute("""
        SELECT COUNT(*)
        FROM commerce.marketing_campaign
        WHERE is_active NOT IN (TRUE, FALSE);
    """)

    invalid_boolean_count = cursor.fetchone()[0]

    print("\n6. Boolean Validity")
    print(
        "Invalid ActiveFlag values:",
        invalid_boolean_count
    )

    # -----------------------------------------------------
    # Final Validation Result
    # -----------------------------------------------------

    integrity_passed = (
        integrity_result[0] == integrity_result[1]
        and integrity_result[2] == 0
        and integrity_result[3] == 0
        and integrity_result[4] == 0
        and integrity_result[5] == 0
        and integrity_result[6] == 0
        and integrity_result[7] == 0
        and integrity_result[8] == 0
        and integrity_result[9] == 0
        and integrity_result[10] == 0
        and integrity_result[11] == 0
        and integrity_result[12] == 0
        and integrity_result[13] == 0
        and integrity_result[14] == 0
        and duplicate_record_groups == 0
        and invalid_boolean_count == 0
    )

    print("\n7. Database Integrity Validation Summary")
    print("=" * 80)

    print(
        "Marketing Campaign database integrity passed:",
        integrity_passed
    )

except Exception as e:

    print(
        "Marketing Campaign database integrity validation failed."
    )

    print("Error:", e)

    raise

Marketing Campaign Database Integrity Validation
================================================================================

1. Primary Key Integrity
Total rows: 4
Distinct campaign IDs: 4
NULL campaign IDs: 0

2. Required Field Integrity
NULL campaign names: 0
NULL campaign types: 0
NULL start dates: 0
NULL end dates: 0
NULL discount percentages: 0
NULL active flags: 0
NULL created dates: 0
NULL created by: 0
NULL updated dates: 0
NULL updated by: 0

3. Campaign Date Integrity
Start date later than end date: 0

4. Audit Date Integrity
Updated date earlier than created date: 0

5. Database Integrity Validation Summary
================================================================================
Marketing Campaign database integrity passed: True

## 6.10 Close PostgreSQL Connection

Close the PostgreSQL cursor and database connection after all
Marketing Campaign loading and validation steps are complete.

Confirm that PostgreSQL resources are closed cleanly.

In [36]:
# =========================================================
# 6.10 Close PostgreSQL Connection
# =========================================================

try:

    if cursor is not None and not cursor.closed:
        cursor.close()

    if conn is not None and conn.closed == 0:
        conn.close()

    print("PostgreSQL resources closed successfully.")

    if cursor is not None:
        print(
            "Cursor closed:",
            cursor.closed
        )

    if conn is not None:
        print(
            "Connection closed:",
            conn.closed != 0
        )

except Exception as e:

    print(
        "PostgreSQL resource closure failed."
    )

    print("Error:", e)

    raise

PostgreSQL resources closed successfully.
Cursor closed: True
Connection closed: True